### ISSUE TITLE
support the response=raw|document parameter on processes

### ISSUE THREAD

**Issue by pvgenuchten** [geopython/pygeoapi#1004]
https://docs.ogc.org/is/18-062r2/18-062r2.html#toc32 indicates the use of a request parameter response=raw|document (raw is default), which seems not implemented on pygeoapi yet.

This is usefull for response content different then json, such as imagery, xml, pbf.

If response=raw (default) the actual content is send to the client, with an option response=document the content is embedded in a json wrapper (current behaviour).

**Comment by tomkralidis** [comment]
Turns out this is a problem with the [pygeometa plugin](https://geopython.github.io/pygeometa/pygeoapi-plugin) itself.  Fixing in pygeometa proper.  Closing.

**Comment by pvgenuchten** [comment]
Good find, good to know we support the response parameter
