### ISSUE TITLE
Add a CSW backend for OGC API Records

### ISSUE THREAD

**Issue by maxcollombin** [geopython/pygeoapi#1029]
**Is your feature request related to a problem? Please describe.**
Would it be possible to add a Catalogue Service for the Web (CSW) backend for publishing OGC API Records? This could allow publishing collections from existing CSW services and avoid creating TinyDB configuration files.

**Describe the solution you'd like**
be able to publish an OGC API Records collection by referencing a CSW service as provider (e.g. [https://www.geocat.ch/geonetwork/srv/fre/csw?service=CSW&version=2.0.2&request=GetCapabilities](https://www.geocat.ch/geonetwork/srv/fre/csw?service=CSW&version=2.0.2&request=GetCapabilities))

**Describe alternatives you've considered**
None

**Comment by doublebyte1** [comment]
@maxcollombin you mean creating a facade, [like the one for WFS](https://docs.pygeoapi.io/en/0.10.1/data-publishing/ogcapi-features.html#ogr)?

**Comment by doublebyte1** [comment]
@tomkralidis @PascalLike what do you think?

**Comment by maxcollombin** [comment]
@doublebyte1 yes, indeed!
Does that make sense to you?

**Comment by tomkralidis** [comment]
I think this is a great idea!  The devil in this detail is the metadata model/queryables. As a first step, we could start with a facade to implement CSW 2 (or 3) with Dublin Core as the model.  This is identical to the approach we took in QGIS MetaSearch.  We can consider more complex models (i.e. ISO 19115) once we have a baseline.

**Comment by tomkralidis** [comment]
Aside: depending on the underlying CSW implementation (pycsw, GeoNetwork OpenSource, etc.), you may also consider upgrading them if your organization is managing them directly.

**Comment by PascalLike** [comment]
> Aside: depending on the underlying CSW implementation (pycsw, GeoNetwork OpenSource, etc.), you may also consider upgrading them if your organization is managing them directly.

Right! For example, in the most recent versions of GeoNetwork, there should already be support for OARec.

**Comment by tomkralidis** [comment]
Initial implementation now in master branch.
