### ISSUE TITLE
Update tiles to the approved specification

### ISSUE THREAD

**Issue by francbartoli** [geopython/pygeoapi#1046]
**Description**

Related to #699 

- [x] The TileJSON should also be changed to be an alternate representation of a particular tileset, as opposed to a described by / separate metadata resource
 - [x] Also the tileMatrixSetURI should use the TMS register , e.g. http://www.opengis.net/def/tilematrixset/OGC/1.0/WebMercatorQuad
 - [x] The tileMatrixSet key is for a full TMS description, the id should use id

**Steps to Reproduce**

See also [this diagram](https://files.gitter.im/60634f5b6da0373984789488/UyKK/TileSet.png) with the approved [spec](https://docs.ogc.org/is/20-057/20-057.html)

Open the tiles about the lake collection in the [demo instance](https://demo.pygeoapi.io/master/collections/lakes/tiles)

Expected behavior
The closest implementation might be found [here](https://maps.ecere.com/ogcapi/collections/Daraa/tiles?f=json)

Screenshots/Tracebacks

Environment

OS:
Python version:
pygeoapi version:
Additional context

**Comment by PascalLike** [comment]
../collections/{colllectionId}/tiles/{tileMatrixSetId}/metadata seems no longer part of the specification.
It seems that metadata should be moved to ../collections/{colllectionId}/tiles/{tileMatrixSetId}?f=json 

It's expected to contain [TileSetMetadata](https://docs.ogc.org/is/17-083r4/17-083r4.html#toc20)

[pygeoapi old metadata endpoint](https://demo.pygeoapi.io/master/collections/lakes/tiles/WorldCRS84Quad/metadata?f=json) :heavy_check_mark: 
[pygeoapi current metadata endpoint](https://demo.pygeoapi.io/master/collections/lakes/tiles/WorldCRS84Quad?f=json) :exclamation: 
[Example from specs](https://docs.ogc.org/is/17-083r4/17-083r4.html#example-encodings-for-tilesetmetadata-informative)
[Example from another implementation](https://maps.ecere.com/ogcapi/collections/Daraa/tiles/CDBGlobalGrid?f=json)

@doublebyte1 @francbartoli

**Comment by doublebyte1** [comment]
@francbartoli @PascalLike I guess this is solved now.
