### ISSUE TITLE
add Mastodon account

### ISSUE THREAD

**Issue by tomkralidis** [geopython/pygeoapi#1056]
- [x] setup Mastodon project account (@tomkralidis)
- [x] setup integration for crossposting with [Twitter handle](https://twitter.com/pygeoapi) (@tomkralidis @justb4 @francbartoli @kalxas et. al.)
- [x] advertise on website community page (@tomkralidis)

cc @doublebyte1

**Comment by tomkralidis** [comment]
I have submitted for `@pygeoapi@noc.social`, and am waiting on approval.

**Comment by francbartoli** [comment]
closing as everything was completed

**Comment by tomkralidis** [comment]
Reopening: https://noc.social/@pygeoapi is currently tied to my personal email address (Mastodon is tied to email, unlike twitter which is tied to usernames), so we need a neutral email address so that all the PSC can post.

**Comment by francbartoli** [comment]
Sorry Tom, I was aware that

**Comment by tomkralidis** [comment]
Mastodon email now configured to pygeoapi@gmail.com.  Login information has been shared with the PSC. [Technical Infrastructure](https://github.com/geopython/pygeoapi/wiki/Technical-Infrastructure) updated.

It would be valuable to automatically post pygeoapi Twitter messages to the pygeoapi Mastodon if possible (cc @justb4 @kalxas @francbartoli @jorgejesus @pvgenuchten)
