### ISSUE TITLE
Missing # in the plugins code example

### ISSUE THREAD

**Issue by frafra** [geopython/pygeoapi#1062]
Hi,
I would like to submit a trivial PR to fix a doc typo by myself, but I am unable to locate the documentation of this project.

I found a missing `#` here:
[class MyCoolVectorDataProvider(BaseProvider):](https://docs.pygeoapi.io/en/stable/plugins.html#python-code)

```python
        # optionally specify the output filename pygeoapi can use as part
        of the response (HTTP Content-Disposition header)
```

**Comment by tomkralidis** [comment]
Thanks @frafra !
