### ISSUE TITLE
Show all the columns from the web interface

### ISSUE THREAD

**Issue by frafra** [geopython/pygeoapi#1073]
**Is your feature request related to a problem? Please describe.**
The web interface shows just some of the available columns for the items.

**Describe the solution you'd like**
All the columns should be shown.

**Describe alternatives you've considered**
None.

**Additional context**
Dropping the `< 5` condition from `items/index.html` and adding `overflow-x: scroll` as style for the right table seems a good solution to me.

**Comment by frafra** [comment]
It depends on #772.

**Comment by webb-ben** [comment]
@frafra Can you confirm this works for you?
