### ISSUE TITLE
Any working example of /collections/{collectionId}/locations (as similar to /items?)

### ISSUE THREAD

**Issue by esumit** [geopython/pygeoapi#1084]
**Describe the solution you'd like**
Request to have a working example of /collections/{collectionId}/locations (as similar to /items?)

**Comment by francbartoli** [comment]
Does `.../locations` come from a particular OGC API specification?

**Comment by esumit** [comment]
Yes, its from EDR spec : refer here : https://app.swaggerhub.com/apis/OGC/ogcapi-edr-1-example-1/1.0.1#/Collection%20data%20queries/ListCollectionDataLocations
