### ISSUE TITLE
Working example of /collections/{collectionId}/position 

### ISSUE THREAD

**Issue by esumit** [geopython/pygeoapi#1085]
**Describe the solution you'd like**
Working example of /collections/{collectionId}/position

**Comment by francbartoli** [comment]
@esumit can you please describe what the issue is and provide more context about it? What OGC API specification are you referring to? Is this a duplicate of #1086?

**Comment by esumit** [comment]
@francbartoli Its not a duplicate of #1086 , as #1086 referring to area API of OGC EDR spec, but this is referring to position API of OGC EDR.
