### ISSUE TITLE
Working example of /collections/{collectionId}/area

### ISSUE THREAD

**Issue by esumit** [geopython/pygeoapi#1086]
**Describe the solution you'd like**
Working example of /collections/{collectionId}/area

**Comment by francbartoli** [comment]
@esumit can you please describe what the issue is and provide more context about it? What OGC API specification are you referring to?

**Comment by esumit** [comment]
@francbartoli I am referring to OGC EDR specifications, and the issue is when I see the pygeoapi then it has given the example on items with html template as well. 

But with https://app.swaggerhub.com/apis/OGC/ogcapi-edr-1-example-1/1.0.1#/Instance%20data%20queries/GetInstanceDataForArea there is no example on pygeoapi.

 In one of my work I would like to implement the Area case as well, so thought to ask if pygeoapi has any plan to add Area's example the similar one available for items .

**Comment by francbartoli** [comment]
@esumit Is it still not clear to me if you are referring to the example of a response `'200'` in the openapi document for that endpoint, can you please confirm?
If it's the case I kindly ask you to change the title and the description of the issue accordingly. Also, it's probably a good idea to collapse the issues about the lack of examples for EDR's endpoints in the `pygeoapi-openapi.yml` file into just one single issue

**Comment by esumit** [comment]
Sure I will do !
