### ISSUE TITLE
pass OGC CITE tests

### ISSUE THREAD

**Issue by tomkralidis** [geopython/pygeoapi#109]
OGC has released [testing for OGC API - Features](http://cite.opengeospatial.org/te2/about/wfs30/3.0/site/) in beta mode.  Services can be tested directly from the [CITE beta facility](http://cite.opengeospatial.org/te2/) or a local [Docker setup](https://hub.docker.com/r/ogccite/ets-wfs30).  More information can be found in the [recent CITE announcement from OGC](http://lists.opengeospatial.org/pipermail/cite-forum/2019-April/001764.html).

**Comment by tomkralidis** [comment]
We now pass all CITE tests for OGC API - Features (no skips or failures).

**Comment by justb4** [comment]
Good work! May add to presentation.

**Comment by tomkralidis** [comment]
Added to presentation and website homepage.
