### ISSUE TITLE
implement file paths

### ISSUE THREAD

**Issue by jorgejesus** [geopython/pygeoapi#11]
Base provider class uses `self.url`  to indicate where the provider is locate, this is problematic when we have for example spatialite that is a file.

Current we used `file://` with asbolute paths. Need to create a specific file attriubte in the base class and support relative paths
e.g
`self.file = "./data/" `

**Comment by tomkralidis** [comment]
I've changed the config so that we use what's intuitive to the provider.  `self.url` is now `self.data` of the dataset object (along with `self.id_field` and `self.provider`.  So for GeoJSON/CSV, `self.data` is a filepath, whereas for Elasticsearch, `self.data` is the URL.
