### ISSUE TITLE
Get Docker build + push working again in GH Workflow

### ISSUE THREAD

**Issue by justb4** [geopython/pygeoapi#1110]
**Description**
Docker build + push seems stuck, canceled after 6 hours by GH, no logs

**Steps to Reproduce**
* commit/push any change to master branch on pygeoapi GH repo
* under Actions see Docker build, i.e. [containers.yml](https://github.com/geopython/pygeoapi/blob/master/.github/workflows/containers.yml) GH Action taking forever

**Expected behavior**
Ok, build can take long but not that long.

**Screenshots/Tracebacks**
The current version of [containers.yml](https://github.com/geopython/pygeoapi/blob/master/.github/workflows/containers.yml) still builds the Docker Image twice, maybe even more if also ARM versions are built.

**Environment**
 - OS: GH Workflow, Ubuntu Latest (maybe we should pin)
 - Python version: any
 - pygeoapi version: latest as from jan 18, 2023

**Additional context**
This happened after #1093 was merged. This made many changes to the Dockerfile, but not to [containers.yml](https://github.com/geopython/pygeoapi/blob/master/.github/workflows/containers.yml) . Also #1105 is in progress but will take some more time. In the meantime at least the Docker Image should be built/pushed, e.g. to run on https://demo.pygeoapi.io/master.

**Comment by tomkralidis** [comment]
Is this still an issue?

**Comment by justb4** [comment]
No will close, was most probably hickup in GH Workflow backend as the Docker build suddenly, from an unrelated push started working again.
