### ISSUE TITLE
Make Unit tests passing in Docker Container

### ISSUE THREAD

**Issue by justb4** [geopython/pygeoapi#1111]
**Description**
Failing Unit tests in Docker Container 

**Steps to Reproduce**
* docker run -p 5000:80 --rm --name pygeoapi geopython/pygeoapi:latest test 
* observe failed tests

**Expected behavior**
All tests passing.

**Screenshots/Tracebacks**
See test output:
[test.txt](https://github.com/geopython/pygeoapi/files/10457130/test.txt)

**Environment**
 - OS: Ubuntu Jammy as in Docker Image
 - Python version: 3.10
 - pygeoapi version: latest on jan 19, 2023

**Additional context**
Actually there are only 3 main failure-causes, most can be explained:

* several tests in [test_api.py](https://github.com/geopython/pygeoapi/blob/master/tests/test_api.py)
Many tests IMO should not be here! Like tests for Postgresql CQL,Coverage, EDR. They should be in their Provider (PG) or Service-specific testfile.  `test_api.py` should perform generic API tests, not specific, and relies on unavailable local servers.

* WFS tests: still the wrong GeoSolutions URL is in, thought we fixed that ages ago...
* `test_async_hello_world_process_parallel` fails, cannot explain

**Comment by justb4** [comment]
Think the Utah WFS has strange behaviour:
This works:
https://demo.deegree.org/utah-workspace/services/wfs?SERVICE=WFS&REQUEST=GetCapabilities

But
https://demo.deegree.org/utah-workspace/services/wfs?SERVICE=WFS&REQUEST=DescribeFeatureType
This fails

<?xml version='1.0' encoding='UTF-8'?>
--
  | <ows:ExceptionReport xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/ows/1.1 http://schemas.opengis.net/ows/1.1.0/owsExceptionReport.xsd" version="2.0.0">
  | <ows:Exception exceptionCode="OperationNotSupported" locator="request">
  | <ows:ExceptionText>Request type 'DescribeFeatureType' is not supported.</ows:ExceptionText>
  | </ows:Exception>
  | </ows:ExceptionReport>

**Comment by justb4** [comment]
Seeing other output via:
https://demo.deegree.org/utah-workspace/console/client/index.xhtml choosing any DescribeFeatureType :

```
<ows:ExceptionReport xsi:schemaLocation="http://www.opengis.net/ows http://schemas.opengis.net/ows/1.0.0/owsExceptionReport.xsd" version="1.0.0" xmlns:ows="http://www.opengis.net/ows" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <ows:Exception exceptionCode="InvalidRequest">
        <ows:ExceptionText>Cannot dispatch XML request with namespace 'http://www.opengis.net/wfs/2.0' -- currently, multiple services for this namespace are active. Please add the service id to the URL to choose one of the services.</ows:ExceptionText>
    </ows:Exception>
</ows:ExceptionReport>
```

**Comment by tomkralidis** [comment]
Is this still an issue?

**Comment by justb4** [comment]
Yes, tests failing for different reasons. And test_api.py contains PostgreSQL tests that be moved to dedicated test file. This is bitting me also outside Docker env now.

**Comment by tomkralidis** [comment]
@totycro sure, feel free to issue a PR.
