### ISSUE TITLE
No module named 'pygeoapi.django_pygeoapi'

### ISSUE THREAD

**Issue by elnazazmi** [geopython/pygeoapi#1115]
**Description**

No module named 'pygeoapi.django_pygeoapi'

**Steps to Reproduce**

Running the example django project from the repository ends with this error and couldn't find any docs how to install pygeoapi.django_pygeoapi.

**Environment**
 - OS: Ubuntu
 - Python version: 3.10.9
 - pygeoapi version: 0.13.0
 - django version: 3.2.16

**Comment by MarcusStrobl** [comment]
I had the same problem when following the instructions. When you import in your `urls.py` `pygeoapi.django_` instead of `pygeoapi.django_pygeoapi` it works.

**Comment by tomkralidis** [comment]
Fixed via #1114
