### ISSUE TITLE
links array missing from process list response

### ISSUE THREAD

**Issue by ghobona** [geopython/pygeoapi#1117]
**Description**

The links array is missing from the process list response.

**Steps to Reproduce**

Visit https://demo.pygeoapi.io/master/processes?f=json

**Expected behavior**

There should a links array at the same level as the processes field.

![Screenshot 2023-01-25 at 20 09 27](https://user-images.githubusercontent.com/18121038/214678583-1c6b46c4-c683-4548-9848-3483a8387b50.png)

**Screenshots/Tracebacks**

**Comment by tomkralidis** [comment]
Fixed in #1120
