### ISSUE TITLE
setup demo server

### ISSUE THREAD

**Issue by tomkralidis** [geopython/pygeoapi#112]
Currently a modest pygeoapi demo operates at http://geo.kralidis.ca/pygeoapi.  Setup a proper demo area per below:

- [x] setup demo at https://demo.pygeoapi.io
- [x] ensure demo is auto-updated
- [x] link demo server from https://pygeoapi.io/

**Comment by justb4** [comment]
Can work on this: can be similar/almost copy from GeoHealthCheck demo VM setup.

Proposed Plan:

* Ubuntu small VM from [Hetzner Cloud](https://www.hetzner.com/cloud)
* [demo.pygeoapi.io GH repo](https://github.com/geopython/demo.pygeoapi.io) to store overall config/setup (except credentials)
* Ansible playbook for initial provisioning/hardening/security
* Docker (compose) based deployment
* proxy with HTTPS via [Traefik](https://traefik.io/)
* DockerHub hook via [micro-dockerhub-hook](https://github.com/maccyber/micro-dockerhub-hook)
* depends on/work with  #114 for pygeoapi Docker Images

**Comment by justb4** [comment]
Basic demo server now running using [local Dockerfile](https://github.com/geopython/demo.pygeoapi.io/blob/master/services/pygeoapi/Dockerfile) with `gunicorn` and `eventlet`.

[geoapi config](https://github.com/geopython/demo.pygeoapi.io/blob/master/services/pygeoapi/local.config.yml) is Volume-mapped with docker-compose.

TODO:

* use official pygeoapi Docker Images from DockerHub
* configure [DockerHub hook ](https://github.com/geopython/demo.pygeoapi.io/tree/master/services/dockerhub)for automatic updates
* more data sources : EL, GPKG and SQLite, need extra packages in Dockerfile

**Comment by thijsbrentjens** [comment]
To start: kudos for all the work done! The demo server is really nice. Is it possible to enable CORS on the demo server?

**Comment by justb4** [comment]
Good one, opened issue #129 . Temp fix on demo server via Traefik headers, can you try?

**Comment by justb4** [comment]
@thijsbrentjes CORS headers fixed via #129 and #130 , runs also on demo server. Can you test?

**Comment by thijsbrentjens** [comment]
Great, CORS works

**Comment by justb4** [comment]
@tomkralidis we only need to link from  https://pygeoapi.io/ and this issue is done? Something you can do?

**Comment by tomkralidis** [comment]
Done.  Thanks @justb4 !
