### ISSUE TITLE
update for SQLAlchemy 2 support

### ISSUE THREAD

**Issue by tomkralidis** [geopython/pygeoapi#1123]
**Description**
The PostgreSQL provider as well as CQL support use SQLAlchemy, which has been recently upgraded to 2.0.

**Steps to Reproduce**
See series of [CI errors](https://github.com/geopython/pygeoapi/actions/runs/4053598702/jobs/6974409553#step:15:967)

**Expected behavior**

**Screenshots/Tracebacks**

**Environment**
 - OS: all
 - Python version: 3.7
 - pygeoapi version: master

**Additional context**
cc @KoalaGeo @kalxas

**Comment by krishnaglodha** [comment]
Can I work on it ?

**Comment by KoalaGeo** [comment]
@ximenesuk @volcan01010 for next sprint?
