### ISSUE TITLE
Support OGC API - Features - Part 2: Coordinate Reference Systems by Reference

### ISSUE THREAD

**Issue by justb4** [geopython/pygeoapi#1128]
**Is your feature request related to a problem? Please describe.**
At the moment, pygeoapi only returns features as GeoJSON, which has a default WGS84 coordinate reference system.
This implies that we will implement support for bbox, bbox-crs and crs.
The OGC standard [OGC API - Features - Part 2: Coordinate Reference Systems by Reference](https://docs.opengeospatial.org/is/18-058r1/18-058r1.html) describes a modular extension for that support.
(No support for JSON-FG is needed yet, which is still under development (and not part of the standard mentioned here).

**Describe the solution you'd like**
Support the facilities in pygeoapi as outlined in the above OGC standard, "Coordinate Reference Systems by Reference".

For pygeoapi queries, this means that users can specify a bounding box in a chosen projection with their request. For pygeoapi responses, this means that feature geometries will be returned in the requested CRS, where the CRS definition is set using the HTTP response header "Content-Crs". Supported CRSs can be configured and will be returned in the (Collection) metadata.
The layered architecture of pygeoapi and the already-included PROJ library required for projection transformations will make these adjustments reasonably straightforward.

We will also study existing pygeoapi developments (branches) for this Standard and the same facilities as already used in other pygeoapi API Services. Any suggestions or collaborations welcome!

**Describe alternatives you've considered**
This issue is about adhering to all facilities specified in the standard. There are really no alternatives.

**Additional context**
The context for the planned development   the Geonovum Tender invitation: [Aligning OGC-API-Features tooling with OGC-standards, the Dutch API Design Rules and INSPIRE](https://www.geonovum.nl/themas/invitation-to-tender), for which a consortium of `pygeoapi` core developers were selected to make the pygeoapi enhancements. The details of the requirements in the Tender can be found [in this PDF document](https://www.geonovum.nl/documents/invitation-to-tender-ogc-api-features-tooling-adjustment-inspirev20pdf).
The enhancement (CRS-support) as specified in this issue is one of three enhancements planned. The others will get separate pygeoapi issues assigned.

**Comment by justb4** [comment]
It appears there are two versions of the "Part 2" standard
https://docs.ogc.org/is/18-058/18-058.html (from Geonovum Tender) and
https://docs.opengeospatial.org/is/18-058r1/18-058r1.html

Diff seems only "editorial" though, comparing through
https://www.copyscape.com/compare.php

Version 18-058r1 van 2022-05-11 is listed on https://www.ogc.org/standards/ so that is the "official one".

**Comment by tomkralidis** [comment]
Great work here!!!
