### ISSUE TITLE
refactor sqlite and geopackage code

### ISSUE THREAD

**Issue by jorgejesus** [geopython/pygeoapi#113]
Both SQLite and geopackage  data provider plugin contains repeated code. This should be refactor into a single class or base structure

**Comment by bitner** [comment]
Is there any reason to have these as separate providers rather than through the OGR provider?

**Comment by jorgejesus** [comment]
Wanted also to dump the code, but then consulted with @justb4  and:

- The separate providers are more efficient that the OGC provider
- Pagination support
- OGC has support for BBOX and the natives still need implementation
