### ISSUE TITLE
pygeoapi not recognising the limit query parameter on the /processes path

### ISSUE THREAD

**Issue by ghobona** [geopython/pygeoapi#1130]
**Description**

The response to the following request should only list 1 process, as constrained in the limit query parameter. However, pygeoapi appears to not recognise the limit parameter.

https://demo.pygeoapi.io/master/processes?limit=1 

**Steps to Reproduce**

Call https://demo.pygeoapi.io/master/processes?limit=1 

**Expected behavior**

The number of processes listed should not exceed the number specified by the limit parameter.

See Abstract Test A.12 of [OGC 18-062r2](https://docs.ogc.org/is/18-062r2/18-062r2.html).

**Screenshots/Tracebacks**

![Screenshot 2023-02-03 at 16 52 42](https://user-images.githubusercontent.com/18121038/216660949-c1b29d36-acf0-4af3-8410-d3b5a02ea377.png)

**Additional context**

![Screenshot 2023-02-03 at 16 51 41](https://user-images.githubusercontent.com/18121038/216661006-f5093811-1cb4-4cad-82c5-b1dcf49ef87d.png)

**Comment by tomkralidis** [comment]
@ghobona this should be fixed in master branch (thanks @webb-ben).
