### ISSUE TITLE
AWS container deployment > Serverless Framework version?

### ISSUE THREAD

**Issue by jdwh** [geopython/pygeoapi#1132]
**Description**
Now in Feb 2023, I've pulled down the source code and installed dependencies.  Going through instructions to deploy serverless container (can't use zappa or the first outlined method for serverless because the default build exceeds the 250MB limit), and running into various issues.  Thinking maybe the versions of software I have installed aren't compatible with the config files?

Locally I have Python 3.9 and Serverless environment: win32, node 18.14.0, framework 3.27.0 (local), plugin 6.2.3, SDK 4.3.2

**Does anyone know what versions of Node/Serverless were used at the time when the instructions found under [aws-lambda](https://github.com/geopython/pygeoapi/blob/a15f9f2b52cb9f40c93490d6ea8beb029fa3744b/aws-lambda/README.md) where written?**

**Steps to Reproduce**
Steps to reproduce the behavior: follow the instructions in the readme.md

**Expected behavior**
Successful deployment to AWS

**Screenshots/Tracebacks**
N/A

**Environment**
 - OS: Windows
 - Python version: 3.9
 - pygeoapi version: 0.14.0
 - node 18.14.0, 
 - serverless framework 3.27.0

**Additional context**
N/A

**Comment by francbartoli** [comment]
Hi @jdwh,

I have a bunch of pygeoapi instances running in AWS lambda. They are wrapped in a [mangum](https://mangum.io/) handler (I'm using the starlette interface by the way) and the lambda deployment is done via docker images which overcome the size limit. I have the impression that those scripts are pretty much old and so the serverless framework too.

Hope this helps

**Comment by RJHCarto** [comment]
Hi @francbartoli, I'm also running into the same issue as above. Do you have any guidance/documentation on how to build pygeoapi out using mangum as suggested and deploy to lambda?

**Comment by jdwh** [comment]
This seems to be cleared now
