### ISSUE TITLE
Support for features with an "empty geometry"

### ISSUE THREAD

**Issue by MTachon** [geopython/pygeoapi#1139]
**Is your feature request related to a problem? Please describe.**
I am currently experimenting with OGC API - Features and trying to set up services that publish data from a PostGIS database (I have switched from the Postgresql provider to the OGR provider as the OGR provider had some features not yet available with the Postgresql provider). 

I get errors when I have records from a table which geometry is set to NULL. The errors occur when pygeoapi performs some operations on the features' geometry (e.g. CRS transformation, format rendering...) before serving them to the end-user. This may happen for all providers using database, without Not-NULL constraint for their geometry column, as data source.

I am wondering whether pygeoapi should be able to filter out all features with an empty geometry, or if it is the responsibility of the administrator setting up the service to make sure that all records have a non-empty geometry? One may want to publish data from a database with only read-only rights. In that case, giving pygeoapi the possibility to filter out features without geometry would remove the need for creating a new database and populating it with filtered data from the original database.

**Describe the solution you'd like**
pygeoapi should check for empty/non-empty geometries when publishing data, and filter out features without geometry.

**Describe alternatives you've considered**
pygeoapi does not check for empty/non-empty geometries. It is the responsibility of the service administrator to have a clean dataset.

**Comment by MTachon** [comment]
Reading again the [OGC API - Features - Part 1: Core](https://docs.ogc.org/is/17-069r4/17-069r4.html) and the definition of what a [Feature](https://docs.ogc.org/is/17-069r4/17-069r4.html#_feature) is, the authors refer to the [Spatial Things, Features and Geometry](https://www.w3.org/TR/sdw-bp/#spatial-things-features-and-geometry) paragraph of the [W3C/OGC Spatial Data on the Web Best Practice](https://docs.ogc.org/is/17-069r4/17-069r4.html#SDWBP) document. If I understand correctly, they distinguish a *feature*, which *"may even lack any concrete location information"*, from a *spatial thing*, which has a *"spatial extent (i.e. size, shape, or position)"*.

In addition, by the end of the [Overview](https://docs.ogc.org/is/17-069r4/17-069r4.html#core-overview) paragraph, one can read *"...The bbox parameter matches all features in the collection that are not associated with a location, too. The datetime parameter matches all features in the collection that are not associated with a time stamp or interval, too..."*

If my understanding is now correct, the features from a collection may not have a defined geometry? In which case pygeoapi shoud **not ignore** features without geometries, but provide better support for them (e.g. not throwing errors when the end-user wants to transform the data, with potentially undefined location, when querying features) instead.

**Comment by alpha-beta-soup** [comment]
Null geometries are weird, but perhaps one way to think about them is that a Thing may have once had a geometry (i.e. a delcared location, extent, volume, etc.), and then lack it without going out of existence for some reason. The best example I can think of is something which has been misplaced. It's wrong to retain a non-null geometry, but it's also reasonable to think that it still exists, so it could have its geometry updated to be empty, while remaining in a collection of Spatial Things.

**Comment by ksonda** [comment]
Another common case are features with an unknown geometry.

Eg a catalog of features for which a comprehensive list is available but for which some items do not have their spatial extent yet digitized.

**Comment by ksonda** [comment]
Note we have dealt with this for the gpkg provider here. https://github.com/geopython/pygeoapi/pull/1136

**Comment by MTachon** [comment]
Exactly. I stumbled upon that problem when working with building features from a PostGIS database. Each building may have a footprint geometry (polygon), and a *position point*, which looks like a centroid for the footprint polygon. Some buildings do not have a footprint geometry as their construction is not yet complete. However, they already have a record in the database, filled with information coming from the cadaster. Buildings under a certain size may not have a *position point*...

For such heterogeneous databases (despite the fact that it may not be that common), a support for features without geometry would be nice. It should indeed be done on the provider level, as done for the gpkg provider in https://github.com/geopython/pygeoapi/pull/1136 . 

Have you tested with the *bbox* parameter, whether features with `NULL` geometry are returned, as in: *"...The bbox parameter matches all features in the collection that are not associated with a location, too."* ? Unsure about what the *Intersect* SQL function returns against empty geometries (**WHERE** SQL clause generated in the `__get_where_clauses` method of the `SQLiteGPKGProvider`). I have mostly experimented with the OGR and Postgres providers until now, I work on supporting empty geometries for these if that is of interest.
