### ISSUE TITLE
revise Docker images status and DockerHub

### ISSUE THREAD

**Issue by jorgejesus** [geopython/pygeoapi#114]
Revise the current docker images for updates, check if they are funcional and status on Dockerhub

**Comment by justb4** [comment]
Ok will first move the Docker stuff under https://github.com/geopython/demo.pygeoapi.io/tree/master/services/pygeoapi to https://github.com/geopython/pygeoapi/tree/master/docker/simple 

That [Dockerfile](https://github.com/geopython/demo.pygeoapi.io/blob/master/services/pygeoapi/Dockerfile) now works for all Providers, including `OGR`, `SQLite/SpatialLite` and `ES`.

And then configure `autobuild` on DockerHub.

**Comment by justb4** [comment]
Think we're done, pls re-open if not.
