### ISSUE TITLE
HTML Table layout problem with many-column features

### ISSUE THREAD

**Issue by justb4** [geopython/pygeoapi#115]
In some cases where a Feature has many attributes (columns), the HTML Table display within the [items.html template](https://github.com/geopython/pygeoapi/blob/master/pygeoapi/templates/items.html#L29) gets "too compact". See image below (feature 'RD Point' has around 20 attributes/columns):

![image](https://user-images.githubusercontent.com/582630/57615492-2180e280-757c-11e9-9d81-264737fb783e.png)

How to solve? Ideas:

* limit number of columns displayed?
* ["horizontal layout" ](https://minicss.org/v2/table#horizontal-tables) as supported by mini.css ?
* explicitly define columns in dataset config?

**Comment by tomkralidis** [comment]
Another option could be to not display a table, and when a user clicks on a point, then show a table of just that feature's properties, displayed similarly to a single feature HTML page.

**Comment by justb4** [comment]
Well not displaying a table would affect non-Point geometries (see e.g. `Great Lakes` Dataset) as these can (currently) not be clicked in Map.

**Comment by pvgenuchten** [comment]
A table is usefull here imho. 
- It helps people people to identify there is a list of items on the page, giving insight in the attributes without clicking in the map
- It helps machines (search engines) to identify there is a list of items on the page

As a start, we could limit the list to the first 8 columns?

If at some point we add more semantics to pygeoapi, for example indicate which field is id/name/description, we can select certain fields to display in list mode, or allow user to indicate which fields to show in list mode.

**Comment by tomkralidis** [comment]
+1

**Comment by justb4** [comment]
Think we're done here. Thanks @pvgenuchten and @tomkralidis . Closing, pls re-open if still work needed.
