### ISSUE TITLE
Elasticsearch docker example broken

### ISSUE THREAD

**Issue by PascalLike** [geopython/pygeoapi#1161]
**Description**
I found a minor issue on the elastic search docker example. On the script to push the index into Elasticseach I'm getting:

```
Elasticsearch seems to be working - Adding ne_110m_populated_places_simple.geojson to ES
Traceback (most recent call last):
  File "/load_es_data.py", line 92, in <module>
    es.options(request_timeout=90).indices.create(
AttributeError: 'Elasticsearch' object has no attribute 'options'
```

The script to push data seems still valid. Indeed, this seems to be some problem with elasticsearch python library installed in the docker image:

 https://github.com/geopython/pygeoapi/blob/master/docker/examples/elastic/ES/Dockerfile#L56

Probably it appeared after Elasticsearch upgrade to 8.4.0. Not sure if the library version should go 1:1 with the Elasticsearch version, the documentation says [maybe better](https://github.com/elastic/elasticsearch-py#compatibility), and I noticed that upgrading to 8.4.0 fixes the issue: so I'm going to submit the fix in a PR.

**Steps to Reproduce**
Pull latest master branch code and run the elasticsearch composition [here](https://github.com/geopython/pygeoapi/tree/master/docker/examples/elastic)

**Expected behavior**
Having pygeoapi elsticsearch setup working out of the box

**Comment by doublebyte1** [comment]
With these changes, we are completely on ES8. We no longer need to activate the compatibility mode, on the docker-compose file](https://github.com/geopython/pygeoapi/blob/master/docker/examples/elastic/docker-compose.yml#L66):

```
    environment:
      ELASTIC_CLIENT_APIVERSIONING: 1
```
