### ISSUE TITLE
INSPIRE OAPIF bulk download link (enclosure)

### ISSUE THREAD

**Issue by GeoSander** [geopython/pygeoapi#1169]
**Is your feature request related to a problem? Please describe.**
`pygeoapi`'s predefined example collections currently lack a couple of [INSPIRE metadata elements](https://github.com/INSPIRE-MIF/gp-ogc-api-features/blob/master/spec/oapif-inspire-download.md#metadata-elements-of-the-data-set) and a [bulk download link](https://github.com/INSPIRE-MIF/gp-ogc-api-features/blob/master/spec/oapif-inspire-download.md#84-requirements-class-inspire-bulk-download-), causing it to not fully pass the [INSPIRE validator](https://inspire.ec.europa.eu/validator/test-selection/index.html).

These include:
- [x] The response of the `GET /collections` operation requires a link to the license of the dataset in the `links` property (`rel` = license) and a link to the metadata record for the dataset. This link shall have `rel` link parameter `describedby` and `type` link parameter `application/xml`.
- [x] The response of the `GET /collections` operation should include at least one link where `rel` = `enclosure` that allows requesting a representation of the entire _dataset_ **OR** the response of each `GET /collections/{collectionId}` operation should include at least one `enclosure` link that allows requesting a representation of the entire _feature collection_.

**Describe the solution you'd like**
The upper two links can already be configured if needed and will simply work out of the box. We will configure a demo collection that meets these INSPIRE link requirements. Note that we will add the `license` link to each feature collection as recommended [here](https://docs.opengeospatial.org/is/17-069r3/17-069r3.html#rec_core_fc-md-license) under 10.C. The same applies to each `describedby` link as recommended [here](https://docs.opengeospatial.org/is/17-069r3/17-069r3.html#rec_core_fc-md-descriptions) under 9.C. There is currently no support in pygeoapi for adding these links to the `collections` response (as recommended under 9.A and 10.A). It also wouldn't make much sense looking at how pygeoapi is typically being used, where different licenses and schemas often apply for each feature collection.

Any configured bulk download link(s) (`rel` = `enclosure`) will require some code that actually issue an HTTP HEAD request to the path given in the `href` parameter of that link if no `length` parameter was configured (content size in bytes). If the HEAD request returns a 200 and the `Content-Length` header is bigger than 0, the `length` and `type` (from `Content-Type` if not configured or different) parameters will be set and the download link will be included in the collection item `links` section.

We will add the bulk download link to each `GET /collections/{collectionId}` operation.

**Describe alternatives you've considered**
There are no alternatives.

**Additional context**
This issue is part of 3 planned developments related to the Geonovum Tender invitation ["Aligning OGC-API-Features tooling with OGC-standards, the Dutch API Design Rules and INSPIRE"](https://www.geonovum.nl/themas/invitation-to-tender), for which a consortium of `pygeoapi` core developers were selected to make some enhancements. The details of the requirements in the Tender can be found [in this PDF document](https://www.geonovum.nl/documents/invitation-to-tender-ogc-api-features-tooling-adjustment-inspirev20pdf).

Related issues:
- #1128
- #1134

**Comment by justb4** [comment]
Can this one be closed as #1173 has been merged and INSPIRE CITE tests ok?

**Comment by GeoSander** [comment]
Yes, you're right! 👍
