### ISSUE TITLE
CQL-TEXT does not work with the NOCASE keyword for case (in)sensitive searches

### ISSUE THREAD

**Issue by webb-ben** [geopython/pygeoapi#1172]
**Description**
As per [CQL predicates](https://portal.ogc.org/files/96288#simple-cql_comparison-predicates), the CQL comparisons should default `nocase: true`. Instead, this is ignored, and specifying `NOCASE` produces an error. The only way I am able to get case insensitive searches with cql-text are with `ILIKE`. 

**Steps to Reproduce**
Use NOCASE parameter: https://reference.geoconnex.us/collections/states/items?filter=name%20LIKE%20%27NEW%%27%20NOCASE%20true

**Expected behavior**
[name LIKE new](https://reference.geoconnex.us/collections/states/items?filter=name%20LIKE%20%27new%%27) is the same as
[name LIKE New](https://reference.geoconnex.us/collections/states/items?filter=name%20LIKE%20%27New%%27) is the same as
[name ILIKE new](https://reference.geoconnex.us/collections/states/items?filter=name%20ILIKE%20%27new%%27) is the same as
[name LIKE new NOCASE true](https://reference.geoconnex.us/collections/states/items?filter=name%20LIKE%20%27new%%27%20NOCASE%20true)

**Screenshots/Tracebacks**
![image](https://user-images.githubusercontent.com/40066515/225056972-7457163f-1ecc-49b7-a8a7-3a4b1d0a202f.png)

**Environment**
 - OS: MacOS Ventura/Mac M1
 - Python version: docker/3.10
 - pygeoapi version: latest/0.15.0

**Additional context**
I have not tested this with CQL-JSON or Elasticsearch.

**Comment by francbartoli** [comment]
This is confirmed with demo:

```shell
http "https://demo.pygeoapi.io/master/collections/lakes/items?f=json&filter=name LIKE '%baika%' NOCASE true"
HTTP/1.1 400 Bad Request
Access-Control-Allow-Origin: *
Content-Crs: <http://www.opengis.net/def/crs/OGC/1.3/CRS84>
Content-Language: en-US
Content-Length: 108
Content-Type: application/json
Date: Wed, 23 Aug 2023 15:33:13 GMT
Server: gunicorn
X-Powered-By: pygeoapi 0.16.dev0

{
    "code": "InvalidParameterValue",
    "description": "Bad CQL string : name LIKE '%BAika%' NOCASE true"
}
```
Neither `ILIKE` is working for me:
```shell
http "https://demo.pygeoapi.io/master/collections/lakes/items?f=json&filter=name ILIKE '%baika%' NOCASE true"
HTTP/1.1 400 Bad Request
Access-Control-Allow-Origin: *
Content-Crs: <http://www.opengis.net/def/crs/OGC/1.3/CRS84>
Content-Language: en-US
Content-Length: 109
Content-Type: application/json
Date: Wed, 23 Aug 2023 15:40:42 GMT
Server: gunicorn
X-Powered-By: pygeoapi 0.16.dev0

{
    "code": "InvalidParameterValue",
    "description": "Bad CQL string : name ILIKE '%BAika%' NOCASE true"
}
```

**Comment by webb-ben** [comment]
@francbartoli The mention of `ILIKE` should be taken separate from the CQL vocabulary for `NOCASE`. The CQL term `NOCASE` does not work. Because of hose the CQL is processed, the SQL term `ILIKE` allows for nocase-like CQL queries.
```
curl -I -X GET "https://demo.pygeoapi.io/master/collections/lakes/items?f=json&filter=name%20ILIKE%20%27%baika%%27"
HTTP/2 200 
access-control-allow-origin: *
content-crs: <http://www.opengis.net/def/crs/OGC/1.3/CRS84>
content-language: en-US
content-type: application/json
date: Wed, 23 Aug 2023 18:51:23 GMT
server: gunicorn
x-powered-by: pygeoapi 0.16.dev0
content-length: 39637
```

**Comment by francbartoli** [comment]
@webb-ben after several tests, I found out that:

1.  We are atm using the ecql parser `pygeofilter.parsers.ecql.parse` despite it is available `pygeofilter.parsers.cql2_text.parse`. @constantinius I'm wondering if it makes sense the switch to the latter in pygeoapi
2. `pygeofilter.parsers.ecql.parse` is supporting case sensitive by default with `LIKE` and case insensitive with `ILIKE`
```python
(Pdb) cqltext = "name LIKE '%baika%'"
(Pdb) print(pygeofilter.parsers.ecql.parse(cqltext))
Like(lhs=ATTRIBUTE name, pattern='%baika%', nocase=False, wildcard='%', singlechar='.', escapechar='\\', not_=False)
(Pdb) cqltext = "name ILIKE '%baika%'"
(Pdb) print(pygeofilter.parsers.ecql.parse(cqltext))
Like(lhs=ATTRIBUTE name, pattern='%baika%', nocase=True, wildcard='%', singlechar='.', escapechar='\\', not_=False)
```
3. However `pygeofilter.parsers.cql2_text.parse` doesn't support `NOCASE`
```python
(Pdb) cqltext = "name LIKE '%baika%' NOCASE true"
(Pdb) print(pygeofilter.parsers.cql2_text.parse(cqltext))
*** lark.exceptions.UnexpectedToken: Unexpected token Token('__ANON_4', 'NOCASE') at line 1, column 21.
Expected one of: 
        * $END
        * AND
        * OR
Previous tokens: [Token('SINGLE_QUOTED', "'%baika%'")]
```

**Comment by webb-ben** [comment]
@francbartoli Any update on this? Believe this remains unresolved.

**Comment by francbartoli** [comment]
deferring to @ricardogsilva who managed to fix some bugs on the `ecql` parser
