### ISSUE TITLE
Upgrade CI main.yml from Ubuntu 20.04 to 22.04 LTS (Jammy) and possibly Python version

### ISSUE THREAD

**Issue by justb4** [geopython/pygeoapi#1176]
**Is your feature request related to a problem? Please describe.**
Yes: 

* 22.04 has been out for some time and is supported within GH Workflows
* the pygeoapi Dockerfile thus Image is based on 22.04 (Jammy) 
* in 22.04 the standard `python3-` APT packages can be used
* several strange failures in Unit tests due to version issues among GDAL, Proj, `pyproj`, GDAL Python bindings
* these run fine using the Docker image (though see some other tests failing EDR and rasterio and OGR WFS with GeoSolutions WFS)

In general I think that the CI (can also be called using the Docker Image) should be reproducable. 
Running  tests in Docker Image: `docker run --rm  geopython/pygeoapi:latest test`
In theory we then need to fix tests and dependencies once.

**Describe the solution you'd like**
Upgrade `main.yml` to use Ubuntu 22.04 LTS. Maybe also upgrade Python (?) 3.7 to 3.8?
Docker Image uses even `Python 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] on linux`...

**Describe alternatives you've considered**
No real alternatives.

**Additional context**
Not applicable.

**Comment by ricardogsilva** [comment]
:+1:  from me, especially on the Python version upgrade.

I'd like to be able to use newer Python features available from 3.8 onwards.

Also, [Python 3.7 is reaching end of life soon](https://devguide.python.org/versions/), so it would make sense to keep on a supported version

**Comment by tomkralidis** [comment]
I'm +1 on adding newer versions to CI.

Having said this, as a project with a significant install base and deployment footprint, pygeoapi needs to be cautious on removing support for older versions.  3.7 is still widely used in the wild, so we need to support 3.7 for awhile yet to ensure sustainability for our community.

**Comment by kalxas** [comment]
I also support moving to 22.04 for CI
I would prefer not to remove 3.7 until it is actually EOL, but moving to a more recent Python version as a default is something we should do.

**Comment by justb4** [comment]
Agree with @kalxas . We can determine which Python versions we include "in the matrix" in `main.yml` , hopefully also 3.7 on Ubuntu 22.04,  though it may make the duration of the CI somewhat longer.

**Comment by MTachon** [comment]
Also supporting moving to Ubuntu 22.04 for CI.

I would also like to use new features available in higher Python versions. But upgrading the python version, or enabling to pin higher python versions in `main.yml` would result in not catching new features/syntax in pygeoapi's code base that were not yet available in python 3.7. This would allow contributors to push changes to pygeoapi which may throw errors for users that install pygeoapi in their python 3.7 environment. As long as we want to support python 3.7, there is not much to do about it.
