### ISSUE TITLE
WMS: Exception - Collection not found

### ISSUE THREAD

**Issue by frafra** [geopython/pygeoapi#1177]
**Description**

> Maps
> Datasets can be made available as dynamic maps:
> http://localhost:5000/collections/mapserver_world_map/map

Visiting the link shows `Exception - Collection not found`

**Steps to Reproduce**
Start pygeoapi and open the link.

**Expected behavior**
A map should be shown?

**Environment**
 - OS: Debian (within a container)
 - Python version: 3.11
 - pygeoapi version: 0.13.0

**Additional context**
I never published any raster. I do not know if that could be an issue linked to a missing dependency, but I see no error hinting at that.

**Comment by tomkralidis** [comment]
Can you provide a sample provider configuration?  The WMSFacade is designed to connect to external WMS services (not pure data per se).
