### ISSUE TITLE
Provide a more prominent place in the docs for plugin integration options

### ISSUE THREAD

**Issue by ricardogsilva** [geopython/pygeoapi#1192]
The current docs on plugins mention integration with pygeoapi in a somewhat unexpected location, as this topic is mentioned as a subsection under the **Custom pygeoapi vector data provider** section, as can be seen here:

https://docs.pygeoapi.io/en/latest/plugins.html#connecting-to-pygeoapi

IMO it would be nicer if this information would be:

- Placed either in a top level section or in the overview of the plugin page
- The current plugin integration text presents two options: either 1) modify pygeoapi core code or 2) implement a standalone plugin. Since this second option is recommended as the better one, it seems this should likely be renumbered to option 1)

I'm willing to provide a PR with these changes, if they are deemed relevant by the maintainers

**Comment by francbartoli** [comment]
+1 @ricardogsilva
