### ISSUE TITLE
Use a pydantic model to define the schema of processes

### ISSUE THREAD

**Issue by ricardogsilva** [geopython/pygeoapi#1199]
**Is your feature request related to a problem? Please describe.**
The various schemas for working with processes are defined in the OAPI - Processes spec but pygeoapi has a loose implementation, which makes it a bit painful to implement custom processes and managers. 

**Describe the solution you'd like**
It would be nice if pygeoapi would provide some pydantic models to work with process-related entities (process, inputs, etc). Something similar already seems to be implemented under `pygeoapi.models`.

**Describe alternatives you've considered**
I guess the alternative is to keep the current implementation, which seems to work too, albeit in a less structured way.

**Additional context**
I think I have already implemented most of the relevant models in my ongoing work with using prefect as a process manager, as shown here (still full of WIP everywhere):

https://github.com/ricardogsilva/pygeoapi-prefect/blob/main/src/pygeoapi_prefect/schemas.py

This is to say that I would be willing to produce a PR with these changes, if the maintainers find it a good idea.

**Comment by francbartoli** [comment]
Hi @ricardogsilva, are you considering to make a pull request to support process manager under `pygeoapi.models`? I'm +1 with this approach
