### ISSUE TITLE
Implement gunicorn integrated into pygeoapi

### ISSUE THREAD

**Issue by jorgejesus** [geopython/pygeoapi#121]
Check and try to implement `gunicorn` server from the `pygeoapi` command line.

**Comment by tomkralidis** [comment]
Sample gunicorn invocation:

`gunicorn --bind 10.132.16.251:5000 pygeoapi.flask_app:APP --access-logfile=-`

**Comment by tomkralidis** [comment]
Suggest we keep this up to the user so as to run themselves (docs?), as well as an async mode like:

`gunicorn --bind 10.132.16.251:5000 pygeoapi.flask_app:APP --access-logfile=- `

@francbartoli thoughts on an async equivalent of gunicorn example?

**Comment by francbartoli** [comment]
There is [uvicorn](https://www.uvicorn.org/):

```python
import uvicorn

async def app(scope, receive, send):
    ...

if __name__ == "__main__":
    uvicorn.run("example:app", host="127.0.0.1", port=5000, log_level="info")
```

However, it can still be run with `gunicorn`:

`gunicorn example:app -w 4 -k uvicorn.workers.UvicornWorker`
