### ISSUE TITLE
Improve documentation of the MongoDB provider

### ISSUE THREAD

**Issue by doublebyte1** [geopython/pygeoapi#1210]
The documentation of the MongoDB provider is very minimal. It may not be sufficient for someone to set it up.

It would be nice to improve this section by providing any information that is needed, in order to use the provider. In particular, it would be useful to know how to import a GeoJSON into MongoDB, the correct way (e.g.: using mongoarray).

Other improvements:
- Check which versions of mongo are supported (and which are not)
- Add a one sentence description of MongoDB (see [OGR example](https://docs.pygeoapi.io/en/stable/data-publishing/ogcapi-features.html#ogr)).

This [docker-composition](https://github.com/geopython/pygeoapi/tree/master/docker/examples/mongo) can be used for testing.

**Comment by krishnaglodha** [comment]
I'll work on it
