### ISSUE TITLE
Update to MongoDB 6x on docker examples

### ISSUE THREAD

**Issue by doublebyte1** [geopython/pygeoapi#1211]
[MongoDB v6 was released almost a year ago](https://www.mongodb.com/docs/upcoming/release-notes/6.0/#std-label-release-notes-6.0).  However, the [docker example of mongo on pygeoapi is still on version 5.03](https://github.com/geopython/pygeoapi/blob/master/docker/examples/mongo/docker-compose.yml#L56).

It would be nice to test if all the functionality works with the mongo 6.0, or even [6.0.5](https://hub.docker.com/layers/library/mongo/6.0.5/images/sha256-83801634df07132cff11fab970dd54182ebcd39428b1a6bdef02d35ca8328a71?context=explore). If that is the case, we could update the [docker-compose example](https://github.com/geopython/pygeoapi/blob/master/docker/examples/mongo/docker-compose.yml).

**Comment by doublebyte1** [comment]
> Hi @doublebyte1, may I know the area to test the functionality with new mongo 6.0 version? Is it to make sure the mongo example https://github.com/geopython/pygeoapi/tree/master/docker/examples/mongo working fine?

@tungbq That's precisely it 👍🏽

**Comment by tungbq** [comment]
May I pick up this task?

**Comment by doublebyte1** [comment]
Hi @tungbq ! you sure can 😄 Are you planning to participate in the [Open Software and Open Standards Code Sprint](https://developer.ogc.org/sprints/20/)?

**Comment by tungbq** [comment]
Hello everyone, unfortunately I have some personal stuffs to be focus so unable to work on this task at this time.
Please feel free to pick up it. Thanks.
