### ISSUE TITLE
Add ability to serve non-spatial tables from PostGres

### ISSUE THREAD

**Issue by KoalaGeo** [geopython/pygeoapi#1219]
**Is your feature request related to a problem? Please describe.**
We'd like to be able to share non-spatial data held in postgres using the OGCAPI-Features standard  

**Describe the solution you'd like**
Add the ability to publish postgres tables which do not have a geometry using pygeoapi 

**Describe alternatives you've considered**
LDProxy offers this function. https://postgrest.org/en/stable/ but doesn't use OGCAPI standards

**Additional context**
See working at https://baugrund-daten.baw.de/geoval/collections/process/items/561698 & https://baugrund-daten.baw.de/geovalr/collections/boundaryconditioncode/items/Test_ParticleSizeDistribution_BC_DIN_18123%3A1996-11

![image](https://user-images.githubusercontent.com/33657876/232442750-b4b6f1ee-73cc-4aab-adc3-a504fd2cf49e.png)

**Comment by volcan01010** [comment]
This enhancement may require wider front-end changes.  Should it be a request to serve non-spatial tables more generally e.g. from GeoPackage as well?
