### ISSUE TITLE
landing_page.html does not contain a "if" conditional in the id="collections" section

### ISSUE THREAD

**Issue by IngenieroGeomatico** [geopython/pygeoapi#1224]
**Description**
In this section: https://github.com/geopython/pygeoapi/blob/crs-features-ogc-adr/pygeoapi/templates/landing_page.html#L46 is missing the if conditional "{% if data['collection'] %} .....{% endif %}"

Steps to Reproduce
1./ clone the repository
2./ create a config.yml without collections (without ogcapi-feature)

Expected behavior
a service without collection section. I have detected this when creating an installation only with ogc-api-processes. I don't need the Collections section and it results with an empty link.

Screenshots/Tracebacks
it is created with an empty section

**Environment**
 - OS: Rocky Linux 8.7 (Green Obsidian)
 - Python version: same as ubuntu:focal docker image
 - pygeoapi version: 0.13.dev0

**Additional context**

**Comment by doublebyte1** [comment]
thank you @IngenieroGeomatico could you provide a config file that exemplifies this? i.e.: only with ogc api - processes

**Comment by doublebyte1** [comment]
file:///home/joana/Pictures/Screenshots/Screenshot%20from%202023-04-24%2014-37-33.png

**Comment by IngenieroGeomatico** [comment]
Yes! It is totally right!

For example, our server for only features looks:

<img width="829" alt="image" src="https://user-images.githubusercontent.com/84268457/234178296-93f02c80-7cee-4bd5-bc2b-57b676fa4969.png">

and our server only for processes looks:

<img width="791" alt="image" src="https://user-images.githubusercontent.com/84268457/234178390-e1029a4b-cb18-4a77-a54b-72eb88f9ba5c.png">
