### ISSUE TITLE
 support OGC-API Map Tiles

### ISSUE THREAD

**Issue by tomkralidis** [geopython/pygeoapi#123]
cc @bitner

https://github.com/opengeospatial/OGC-API-Map-Tiles

**Comment by ghelle-fhh** [comment]
Any update on the status of this?

**Comment by tomkralidis** [comment]
This was asked at FOSS4G 2019 during the [pygeoapi presentation](https://media.ccc.de/v/bucharest-32-next-generation-ogc-web-services-with-pygeoapi).  Some initial thoughts/possibilities:

- we do not want to reinvent the wheel with rendering maps/tiles (MapServer, Mapnik, MapProxy, etc.), so investigation is needed on options and use cases
- we need to support a Python based mapping backend.  Examples include MapServer ([Python mapscript](https://pypi.org/project/mapscript/)), [Mapnik](https://github.com/mapnik/python-mapnik/blob/master/demo/python/rundemo.py). Others?
- the idea of pygeoapi acting as an OGC API proxy to existing WMS/WMTS instances should also be considered
- consideration is needed on how much independent configuration is needed (outside of pygeoapi) as part of implementation.  We want to minimize this if possible.  For example, if we go with Python mapscript as an option, then do we need mapfiles alongside pygeoapi configuration?  Or can we use the pygeoapi config to define inline in mapscript on the fly?  Can we use [mappyfile](https://mappyfile.readthedocs.io/en/latest/)? Performance?

**Comment by tomkralidis** [comment]
Note the forthcoming [OGC API - Tiles sprint](https://www.ogc.org/ogcevents/ogc-api-tiles-code-sprint-virtual-event) on 23-24 April 2020 will be a good opportunity to sprint on this issue and test with others.

**Comment by francbartoli** [comment]
@tomkralidis If I remember well previous discussion other possibilities might be:

- [mapproxy](https://github.com/mapproxy/mapproxy)
- [raw x/y/z from minio/s3?](https://github.com/minio/minio)
- [tileserver-gl](https://github.com/maptiler/tileserver-gl)
- dynamic mvt rendering from PostGIS

**Comment by tomkralidis** [comment]
Implemented by @francbartoli (awesome work Francesco !) in #419 .

**Comment by landryb** [comment]
as far as i understand it, #419 only added support for map tiles in mvt format, which only implements vector tiles support - as this ticket discussed other issues/usecases (proxying wms servers, mapfiles, etc..) the scope seems broader.. should another issue supporting 'OGC API maps' (not *tiles*) be created for this usecase ?

**Comment by francbartoli** [comment]
@landryb yes, this PR has added the support to OGC API - Tiles and at the moment there is only one backend provider `MVT` for vector tiles in pygeoapi. More providers for Tiles could be added.

Regarding OGC API - Maps, it is safer if you definitively open another issue for that.
