### ISSUE TITLE
Install failure: entry_points() got an unexpected keyword argument 'group'

### ISSUE THREAD

**Issue by isedwards** [geopython/pygeoapi#1241]
**Description**

Our install from pygeoapi master is failing after yesterday's ["custom cli commands"](https://github.com/geopython/pygeoapi/commit/e06ff73e57a3f31395ecfbd704eabd09c4677deb) update. At the moment we're just working around the problem by pinning to the previous commit "[Unpin click and Jinja2](https://github.com/geopython/pygeoapi/commit/997a83530e1c1f614287b20d516ca6f87dd9d2bd)" from May 3 which is working fine.

Let us know if you need us to investigate and/or provide more details on our environment.

**Screenshots/Tracebacks**
```
Traceback (most recent call last):
   File "/usr/local/bin/pygeoapi", line 5, in <module>
     from pygeoapi import cli
   File "/usr/local/lib/python3.8/dist-packages/pygeoapi/__init__.py", line 71, in <module>
     def plugins():
   File "/usr/local/lib/python3.8/dist-packages/pygeoapi/__init__.py", line 53, in decorator
     for entry_point in entry_points(group="pygeoapi"):
 TypeError: entry_points() got an unexpected keyword argument 'group'
```

**Comment by tomkralidis** [comment]
@ricardogsilva can you take a look please?

**Comment by ricardogsilva** [comment]
This seems to be related to the version of `importlib_metadata` installed on the system and is mentioned in the docs (if only I had read them thoroughly when I prepared the PR):

https://docs.python.org/3/library/importlib.metadata.html#entry-points


The comment on this sphinx bug report offers a workaround:

https://github.com/sphinx-doc/sphinx/issues/10479#issuecomment-1322265382

I see there is also a backport project that brings compatibility to older Python versions:

https://pypi.org/project/backports.entry-points-selectable/

This second option seems cleaner, so I'll prepare a PR with it very soon

**Comment by tomkralidis** [comment]
Thanks @ricardogsilva. Is `backports.entry-points-selectable/` available on Ubuntu/Debian?  cc @kalxas

**Comment by ricardogsilva** [comment]
> Thanks @ricardogsilva. Is `backports.entry-points-selectable` available on Ubuntu/Debian? cc @kalxas

Hmm, I don't think so.

So with that in mind I can prepare a PR that implements a workaround similar to the one described in the mentioned sphinx bug report comment.

**Comment by kalxas** [comment]
This package is not available in Debian/Ubuntu.

**Comment by tomkralidis** [comment]
@isedwards fixed in master. Can you test?

**Comment by isedwards** [comment]
Thank you @ricardogsilva - our build is now working again with master

**Comment by tomkralidis** [comment]
Thanks all!
