### ISSUE TITLE
CRS Support for OGC API EDR pygeoapi Provider

### ISSUE THREAD

**Issue by sjordan29** [geopython/pygeoapi#1244]
**Is your feature request related to a problem? Please describe.**
I am working with @dblodgett-usgs to configure the pygeoapi EDR provider to work with zarr files with projected coordinate systems. The current implementation appears to require lat/lon coordinates. You can kind of work around this limitation by defining `x_field` and `y_field` as the projected coordinates in the config file instead. You can then query the data with projected coordinates. However, this does not seem user-friendly or in line with the OGC API EDR standard.

An example dataset to serve with EDR provider and projected coordinates:
``` python
import xarray as xr
import s3fs

def s3open(path, storage_options):    
    fs = s3fs.S3FileSystem(**storage_options)
    return s3fs.S3Map(path, s3=fs)

storage_options = {'anon': True, 'requester_pays': False, 'client_kwargs': {'endpoint_url': 'https://renc.osn.xsede.org'}}
ds = xr.open_zarr(s3open('s3://rsignellbucket2/hytest/conus404/conus404_hourly_202302.zarr', storage_options))

```
This dataset has `lat` & `lon` values, but the xarray `.sel()` method only works on `x` and `y` coordinates. 

**Describe the solution you'd like**
For data with projected coordinate systems, I would like users to query with coords in WGS84 and have the EDR provider transform the coordinates in that query to the appropriate CRS. I anticipate this could leverage some of the work done in PR #1174 for feature providers, with `storageCRS` in the configuration file, or work done for coverages (e.g., [rasterio_](https://github.com/geopython/pygeoapi/blob/master/pygeoapi/provider/rasterio_.py) provider).

**Comment by dblodgett-usgs** [comment]
Is this done to some degree in the Coverages provider?
