### ISSUE TITLE
Coverages. Serve several images from a single coverage using tileindex/VRT

### ISSUE THREAD

**Issue by CeciliaPH** [geopython/pygeoapi#1251]
We want to publish a DEM in an unique coverage. Nowadays, our data consists of 4.000 images. In the WCS we published this with a VRT, or a tileindex (shp) containing the bbox of every image and its location.

Following the documentation we are able to publish one image - one coverage/collection, but this is not an feasible way to publish our information. We would like to combine many images in a single coverage. Therefore, the user access the data from a single URL/collection and then the user is able to access an image without having to know in advance the location.

At the documentation we read that it is possible to use RasterIO and GDAL drivers... We probed a lot of combinations but still had not got a clue on how to use VRT to show the raster data, as it download the VRT file itself.   

We are not sure if this is an issue or just a configuration issue on how to configure the .yml

Does anyone have any experience about how to display multiple images in a single coverage?
Any workaround?

**Comment by MTachon** [comment]
Hi @CeciliaPH , I have opened PR https://github.com/geopython/pygeoapi/pull/1324, which explains why you are facing these problems, and intends to implement a feature giving more flexibility to pygeoapi's administrators, which would solve these problems. In the meantime, I would recommend that you have a look at [OGC API - Tiles](https://ogcapi.ogc.org/tiles/), even though there is no support for coverage tiles yet.

**Comment by CeciliaPH** [comment]
Hi @MTachon,
Thanks for the PR. We will keep an eye on it! It would be helpful not only for our DTM but for other coverages.

**Comment by MTachon** [comment]
Hi @CeciliaPH ,
I have worked with PR https://github.com/geopython/pygeoapi/pull/1324, and tested with a VRT file that indexes multiple (over two thousands) GTiff files. Using the VRT file as data source for the service, and specifying `GTiff` as the export format in the query (`f=GTiff`) worked fine for me :) The PR is pretty much ready for review, but is not integrated in the official pygeoapi repository right now. I did not get any feedback yet. But you are welcome to check out the branch https://github.com/MTachon/pygeoapi/tree/ogcapi-cov-support-output-formats and do some testing yourself. I have added some documentation that illustrates how to configure such service, but let me know if you need some help.
