### ISSUE TITLE
A test data file can't be read with GDAL 3.4.1 (ubuntu jammy version)

### ISSUE THREAD

**Issue by totycro** [geopython/pygeoapi#1253]
**Description**
When reading this file in the pygeoapi docker container (gdal 3.4.1 as available in ubuntu jammy), the `right` value in the bounding box is wrong:
```python
>>> rasterio.open('tests/data/CMC_glb_TMP_TGL_2_latlon.15x.15_2020081000_P000.grib2').bounds
BoundingBox(left=179.925, bottom=-90.075, right=539.9250000000001, top=90.075)
```

This is not a rasterio issue because it can be reproduced with gdalinfo:
```
$ docker run -v `pwd`:/mnt osgeo/gdal:alpine-small-3.4.1  gdalinfo /mnt/tests/data/CMC_glb_TMP_TGL_2_latlon.15x.15_2020081000_P000.grib2
...
Upper Right (     539.925,      90.075) (Invalid angle, 90d 4'30.00"N)
...
```
It does not occur in other gdal versions such as 3.3.0 or 3.6.1 (you can change the version of the docker image above to verify).

This leads to this test failure (underlying cause is `Input shapes do not overlap raster` error by rasterio mask):
```
FAILED tests/test_api.py::test_get_collection_coverage - assert <HTTPStatus.INTERNAL_SERVER_ERROR: 500> == <HTTPStatus.OK: 200>
```

I'm not sure if we can really do anything about it if it's really a gdal issue, but i at least want to document it because we'll keep stumbling over it when we use ubuntu LTS. CI is not affected because it still uses gdal 3.0.4.

**Expected behavior**
The `right` value of the bbox should be valid.

**Environment**
 - Current pygeoapi docker image or any environment with gdal 3.4.1

**Comment by kalxas** [comment]
We have recently upgraded the docker image to use latest GDAL 3.8.4 and tests seem to be fixed.

**Comment by totycro** [comment]
Then probably something was fixed in GDAL, so i'll close this
