### ISSUE TITLE
Proxy for Publishing maps to OGC API - Maps - WMSFacade

### ISSUE THREAD

**Issue by CeciliaPH** [geopython/pygeoapi#1261]
**Is your feature request related to a problem? Please describe.**
When publishing OGCAPI-Maps with WMSFacade the normal procedure is to connect to other external URL. In some production environments a proxy must be used.

**Describe the solution you'd like**
It would be great if you could configure the proxy URL, in case you need it in the same yml. It would be the same case as Features using WFS source.

**Describe alternatives you've considered**
When publishing vector data to OGC API - Features through an URL there is a way to indicate the proxy
[https://docs.pygeoapi.io/en/stable/data-publishing/ogcapi-features.html?highlight=proxy](https://docs.pygeoapi.io/en/stable/data-publishing/ogcapi-features.html?highlight=proxy)
         gdal_ogr_options:
            GDAL_CACHEMAX: 64
            GDAL_HTTP_PROXY: (optional proxy)
            GDAL_PROXY_AUTH: (optional auth for remote WFS)

**Additional context**
Thank you!

**Comment by tomkralidis** [comment]
@CeciliaPH thanks for the report.  Are you able to set the HTTP or HTTPS proxy as environment variables? i.e.:

```bash
export HTTPS_PROXY=<url>
```

or

```bash
export HTTP_PROXY=<url>
```

...and then restart pygeoapi and try again?

**Comment by CeciliaPH** [comment]
Dear Tom,

Thanks a lot for your comment. It helped us to find a solution.
Luckily it was a trivial bug. We are running docker and we should indicate the proxy url at the docker yml instead of environment variables or pygeoapi yml (like in wfs – features).

I leave our configuration here just in case it helps someone else.


version: '3.5'
services:
  tomcat:
    image: XXXXXXXXX:latest
    restart: always

    ports:
      - XXXX:80
      
    security_opt:
      - seccomp:unconfined
      
    environment:
      - HTTP_PROXY=http://XXXXXXXXX
      - HTTPS_PROXY=http://XXXXXXXXX
      - http_proxy=http://XXXXXXXXX
      - https_proxy=http://XXXXXXXXX
