### ISSUE TITLE
OGC API - Tiles issues (2023-06 Code Sprint)

### ISSUE THREAD

**Issue by jerstlouis** [geopython/pygeoapi#1262]
**Description**
Summarizing issues encountered with pygeoapi deployments during [2023-06 OGC API sprint](https://developer.ogc.org/sprints/21/).

**Steps to Reproduce**
Access collection description resources at:
- https://emotional.byteroad.net/collections/hex350_grid_cardio_1920?f=json
- https://demo.pygeoapi.io/master/collections/lakes?f=json

**Expected behavior**
1. The "rel" link for linking to tilesets from the collection (for collection tiles) or from the landing page (for dataset tiles) should be:
- http://www.opengis.net/def/rel/ogc/1.0/tilesets-vector for vector tiles
- http://www.opengis.net/def/rel/ogc/1.0/tilesets-coverage for coverage tiles
- http://www.opengis.net/def/rel/ogc/1.0/tilesets-map for map tiles

See [5.2 Link Relations](https://docs.ogc.org/is/20-057/20-057.html#toc18) and Requirement 13 in [11.3 Geospatial data resources](https://docs.ogc.org/is/20-057/20-057.html#toc46).

2. The "tileMatrixSetURI" property used in [tileset metadata](https://emotional.byteroad.net/collections/hex350_grid_cardio_1920/tiles?f=json) is incorrect. The correct URI for _WorldCRS84Quad_ is http://www.opengis.net/def/tilematrixset/OGC/1.0/WorldCRS84Quad .

3. A link with rel: http://www.opengis.net/def/rel/ogc/1.0/tiling-scheme should also be included here pointing to a 2DTMS 2.0 JSON definition e.g., https://raw.githubusercontent.com/opengeospatial/2D-Tile-Matrix-Set/master/registry/json/WorldCRS84Quad.json ( or https://schemas.opengis.net/tms/2.0/json/examples/tilematrixset/WorldCRS84Quad.json if you really want to use schemas.opengis.net , but these are _examples_, the 2DTMS register is the normative entry. See related naming authority issue https://github.com/opengeospatial/NamingAuthority/issues/198 that currently prevents linking to the definition server directly ). Ideal solution would be to host the tile matrix set definition on the local server at `/tileMatrixSets` as per _Recommendation 6_.

4. The tileset link returns a _500 Internal Server Error_:
https://emotional.byteroad.net/collections/hex350_grid_cardio_1920/tiles/WorldCRS84Quad?f=json

cc @doublebyte1 @ghobona @tomkralidis

**Comment by tomkralidis** [comment]
Thanks @jerstlouis; PR in #1264

**Comment by doublebyte1** [comment]
Thank you @jerstlouis ; another PR in https://github.com/geopython/pygeoapi/issues/1470

**Comment by doublebyte1** [comment]
@jerstlouis I am marking this as complete now, as all the issues have been solved. Thanks again for pointing this out!
