### ISSUE TITLE
Vector Tiles Issues

### ISSUE THREAD

**Issue by doublebyte1** [geopython/pygeoapi#1286]
**Description**
I am going to summarize here some issues related to the publication of vector tiles, using OGC API - Tiles.
1 - ElasticSearch Tiles does not provide tile metadata. As a workaround we are using TilesMetadataFormat.NONE, but this is causing some issues because the tileset links are not resolving to anything.
2 - Even, when we have tilemetadata, the tileset links are missing links with self and alternate representation of the datasets, like we have [here](http://localhost:5000/collections/lakes/tiles/WorldCRS84Quad?f=json).

**Steps to Reproduce**
1. Access [this](https://emotional.byteroad.net/collections/hex350_grid_cardio_1920/tiles?f=json) page and try to resolve any of the tilesetlinks. An internal server error will be thrown.
2. Access [this](https://demo.pygeoapi.io/master/collections/lakes/tiles?f=json) page. From there, navigate to [one](https://demo.pygeoapi.io/master/collections/lakes/tiles/WorldCRS84Quad?f=json) of the tilesetlinks.

**Expected behavior**
1. We should see the tileset representation.
2. We should see the links for the different representations of this resource.

**Environment**
 - OS: Ubuntu 22.04.2 LTS
 - Python version: 3.7.5
 - pygeoapi version: 0.16.dev0 (master build on 24/07/23

**Additional context**
It is possible to test this issues using `gdal/ogr`. 
1. `./ogrinfo --config API TILES --config CPL_DEBUG ON "OGCAPI:https://demo.pygeoapi.io/master/collections/lakes"`
2. `ogrinfo --config API TILES --config CPL_DEBUG ON "OGCAPI:https://emotional.byteroad.net/collections/hex350_grid_cardio_1920"
`
Here we get the right response:`
./ogrinfo --config API TILES --config CPL_DEBUG ON "OGCAPI:https://maps.gnosis.earth/ogcapi/collections/Daraa:AgricultureSrf"`

`GDAL version: GDAL 3.8.0dev-360a9aea02, released 2023/06/24 (debug build)

Also, see this issue: https://github.com/OSGeo/gdal/issues/7970#issuecomment-1605687527

**Comment by doublebyte1** [comment]
I think one option to solve issue #1, could be to attempt to always attempt to generate tilesetmetadata with default values, even when we don't have a tilejson file (or other) from the provider.

**Comment by doublebyte1** [comment]
@PascalLike I think that if we want the "default" response to be OGC 2D Tile Matrix Set and Tileset metadata JSON encoding, it should look like this: https://maps.gnosis.earth/ogcapi/tileMatrixSets/WorldCRS84Quad?f=json
Instead, it is looking more like tilejson: https://demo.pygeoapi.io/master/collections/lakes/tiles/WorldCRS84Quad?f=json
Or are we always trying to generate tilejson?

**Comment by PascalLike** [comment]
> @PascalLike I think that if we want the "default" response to be OGC 2D Tile Matrix Set and Tileset metadata JSON encoding, it should look like this: https://maps.gnosis.earth/ogcapi/tileMatrixSets/WorldCRS84Quad?f=json Instead, it is looking more like tilejson: https://demo.pygeoapi.io/master/collections/lakes/tiles/WorldCRS84Quad?f=json Or are we always trying to generate tilejson?

You're right! It's configured to return tilesjson https://github.com/geopython/demo.pygeoapi.io/blob/master/services/pygeoapi_master/local.config.yml#L154C23-L154C23

We have to configure it to return the desired format.

**Comment by francbartoli** [comment]
Hey @doublebyte1 and @PascalLike, should we keep this open or can it be considered closed by #1288?

**Comment by doublebyte1** [comment]
@francbartoli @PascalLike you can close this issue. I will create a separate issue to add OGC 2D Tile Matrix Set and Tileset metadata JSON encoding as the default metadata encoding (instead of TileJSON).
