### ISSUE TITLE
Man page

### ISSUE THREAD

**Issue by xamanu** [geopython/pygeoapi#1301]
**Is your feature request related to a problem? Please describe.**

When installing `pygeoapi` in the context of an Operating Systems it is recommended to provide a man page with a program.

**Describe the solution you'd like**

Include a [man page](http://www.ibiblio.org/pub/Linux/docs/HOWTO/Man-Page) into the code base.

**Describe alternatives you've considered**

Generate the man page somehow from `click`.

**Additional context**

This would beneficial the official packaging for Debian (and derivatives).

**Comment by tomkralidis** [comment]
@xamanu thanks for opening the issue.  We can add `python3-click-man` to `debian/control` (in `Build-Depends`) and then run (in `debian/rules`?) the following command:

```bash
click-man --target /usr/share/man/man1 pygeoapi  # will only ever output ".1" files
```

Would this work or this is another preferred workflow (i.e. `debian/files`, etc.)?

**Comment by xamanu** [comment]
Thanks @tomkralidis, I think this is a good suggestion. Will do that. In case there is anything to do on the upstream side. I can still re/open the topic.
