### ISSUE TITLE
OPTIONS operations are not advertised

### ISSUE THREAD

**Issue by drnextgis** [geopython/pygeoapi#1305]
`options` operations (HTTP methods) are not advertised via the OpenAPI definition though the server supports them:
```
$ http OPTIONS https://demo.pygeoapi.io/master/collections/lakes/items/1         
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Allow: HEAD, GET
Content-Language: en-US
Content-Length: 0
Content-Type: application/json
Date: Mon, 03 Jul 2023 07:05:08 GMT
Server: gunicorn
X-Powered-By: pygeoapi 0.16.dev0
```

**Comment by tomkralidis** [comment]
Is this a requirement?  I don't see anything in the various OGC API standards, nor in resulting server implementations?

**Comment by drnextgis** [comment]
According to the [spec](https://docs.ogc.org/DRAFTS/20-002.html#_overview_3):
> The server SHALL support the HTTP OPTIONS operation at the each resource endpoint.

Why not to expose it explicitly through the OpenAPI definition?

**Comment by drnextgis** [comment]
Thank you Tom! This is exactly the solution I expected :+1:
