### ISSUE TITLE
Forks of master branch fail GitHub Actions

### ISSUE THREAD

**Issue by webb-ben** [geopython/pygeoapi#1320]
**Description**
A fork of geopython/pygeoapi:master that is wanting to keep up date fails GitHub Actions because the the geopython Docker image is hard-coded into container.yml.

Some solutions could be:

- A solution for organizations that have the same organization name in GitHub and Dockerhub - which is atleast true for geopython and internetofwater, changing [L67-69](https://github.com/internetofwater/pygeoapi/actions/runs/5512958119/workflow#L67-L69) would be the same behavior as already implemented for the geopython/pygeoapi repository while allowing downstream forks to fit in (more) seamlessly. 
```
          images: |
            ${{ github.repository }}
            ghcr.io/${{ github.repository }}
```
- The even friendlier downstream change, which is probably overkill could be allowing the DOCKER_REPOSITORY in [L18](https://github.com/internetofwater/pygeoapi/actions/runs/5512958119/workflow#L18) to be a repository variable / secret.
```
DOCKER_REPOSITORY: ${{ vars.DOCKER_REPOSITORY || github.repository }}
```

**Steps to Reproduce**
Create a fork of pygeoapi in a repository where GitHub actions are enabled. 
Monitor build status

**Expected behavior**
Ability to publish pygeoapi docker images without needing to make changes to containers.yml

**Screenshots/Tracebacks**
[Failed Action](https://github.com/internetofwater/pygeoapi/actions/runs/5511810860/workflow)
[Modified File Action](https://github.com/internetofwater/pygeoapi/actions/runs/5512958119/workflow)

**Environment**
 - OS:
 - Python version:
 - pygeoapi version:

**Additional context**

**Comment by ricardogsilva** [comment]
@webb-ben Is this still relevant?

looking at the current workflow:

https://github.com/geopython/pygeoapi/blob/f092cf548ebbe405e030a6247a81ac5b6d276e28/.github/workflows/containers.yml#L71-L80

and according to the [docs of the docker/build-push-action github action](https://github.com/marketplace/actions/build-and-push-docker-images#git-context) it seems to me that the repo details are not hardcoded in the workflow.

**Comment by webb-ben** [comment]
Yes it is. The docker image will always publish as:
https://github.com/geopython/pygeoapi/blob/f092cf548ebbe405e030a6247a81ac5b6d276e28/.github/workflows/containers.yml#L15

The solutions offered in the issue still work to resolve it

**Comment by francescoingv** [comment]
@ricardogsilva
I also have the issue on pygeoapi/.github/workflows/containers.yml (line 39 - 40) when I commit to my local repository.

I have a DockerHub account,
but I don't know where to set my credentials (`secrets.DOCKER_USERNAME` and `secrets.DOCKER_PASSWORD`)
(i.e. in what file, placed where, with what format)

Should I also change line 15 (`DOCKER_REPOSITORY: geopython/pygeoapi`)
to something like: `francescomartinelliingv/pygeoapi` ?

Please advice.

**Comment by francescoingv** [comment]
@ricardogsilva 
as of today,
possibly the reported error changed a little, but when pulling a commit on a branch of a fork of geopython/pygeoapi:master
I still get an email with the message `Publish Docker image: Some jobs were not successful`.

If usefull this is the link I am redirected to:
https://github.com/francescoingv/pygeoapi/actions/runs/9958179840

Thank you.

**Comment by webb-ben** [comment]
@francescoingv you will need to set this in the [settings tab of your fork](https://github.com/francescoingv/pygeoapi/settings/secrets/actions)
<img width="1350" alt="image" src="https://github.com/user-attachments/assets/0b95d936-581c-400c-8901-fa65cd554bb5">

**Comment by francescoingv** [comment]
Thank you @webb-ben ,
I will check it: but would it be possible to avoid the docker part?

**Comment by francescoingv** [comment]
> @francescoingv you will need to set this in the [settings tab of your fork](https://github.com/francescoingv/pygeoapi/settings/secrets/actions) <img alt="image" width="1350" src="https://private-user-images.githubusercontent.com/40066515/349205337-0b95d936-581c-400c-8901-fa65cd554bb5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0MDIyOTksIm5iZiI6MTcyMTQwMTk5OSwicGF0aCI6Ii80MDA2NjUxNS8zNDkyMDUzMzctMGI5NWQ5MzYtNTgxYy00MDBjLTg5MDEtZmE2NWNkNTU0YmI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDE1MTMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwOTA0MDg5NmE0NjJiMzQyZmU1MjYzM2NmODE0YWNmZTBjODE3ZGY5ODdjNmM1NTM3OGUyNmUzZjQ1YzljZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rxitylzUItd1fmq4odgDVJK9hdrdF6WfETwFGUHAd-g">

@webb-ben I set the 2 secrets in my settings,
however I still get an error.
https://github.com/francescoingv/pygeoapi/actions/workflows/containers.yml
It worked a couple of times and then now it is failing again.

Could you please help to understand what I am still missing or doing wrong?

Thank you

**Comment by webb-ben** [comment]
@francescoingv There are three secrets you need to set to get the container build to work:

```
DOCKER_REPOSITORY
DOCKER_USERNAME
DOCKER_PASSWORD
```

From the linked action history it appears some of these are not set
<img width="580" alt="image" src="https://github.com/user-attachments/assets/df4563df-27de-43cb-b9ca-aaf53b945c2a">

**Comment by francescoingv** [comment]
@webb-ben thank you.
In your screenshot I only saw DOCKER_USERNAME (I set it to my docker account name)
and DOCKER_TOKEN (I set it to the token I got from docker, but I understand this was useless).

Now you reported I also have to set DOCKER_PASSWORD (I immagine to my docker accont password)
and DOCKER_REPOSITORY, but I have no idea what value to associate to this variable:.

Could you please help with this last variable (DOCKER_REPOSITORY)?

Thank you.

**Comment by webb-ben** [comment]
@francescoingv DOCKER_REPOSITORY is going to represent the docker image you want to publish under. For instance I could choose between publishing on my [personal pygeoapi image](https://hub.docker.com/r/webbben/pygeoapi/) or my [organizational pygeoapi image](https://hub.docker.com/r/internetofwater/pygeoapi/).

If you are developing for personal use it should be `francescoinno/pygeoapi` (i.e. `DOCKER_USERNAME/pygeoapi`)

**Comment by francescoingv** [comment]
Dear @webb-ben,
now I have set the Action-Secrets above (`DOCKER_REPOSITORY, DOCKER_USERNAME, DOCKER_PASSWORD`)
but I still get the following error:
```
Run docker/login-action@v2.1.0
  with:
    username: ***
    password: ***
    ecr: auto
    logout: true
  env:
    DOCKER_REPOSITORY: ***
Logging into Docker Hub...
Error: Error response from daemon: Get "https://registry-1.docker.io/v2/": unauthorized: incorrect username or password
```

I double checked the settings are correct:
**DOCKER_USERNAME = FrancescoMartinelliIngv**
**DOCKER_REPOSITORY = francescomartinelliingv/pygeoapi**
(but I also tried **DOCKER_REPOSITORY = pygeoapi** )
and **DOCKER_PASSWORD** is correct.

Could you please advice?
Thank you.

**Comment by webb-ben** [comment]
It is not an issue with the `DOCKER_REPOSITORY`, the issue you are seeing is just about not being able to authenticate with dockerhub. It is your username or password that must be the issue. 

Are you using your literal Dockerhub password? I have only tested this using [Dockerhub PATs](https://docs.docker.com/security/for-developers/access-tokens/).
