### ISSUE TITLE
Missing `dataType` attribute in response of tile request 

### ISSUE THREAD

**Issue by codehub-rony** [geopython/pygeoapi#1326]
**Description**
I'm trying to import [pygeoapi demo data](https://demo.pygeoapi.io/stable/collections/lakes/tiles/WebMercatorQuad) in OpenLayers as a [OGVectorTile](https://openlayers.org/en/latest/apidoc/module-ol_source_OGCVectorTile-OGCVectorTile.html). 

When the source is loaded, I get an error `Error: Expected tileset data type to be "map" or "vector"`

I checked the code in OpenLayers and it expects the [tilejson](https://demo.pygeoapi.io/stable/collections/lakes/tiles/WebMercatorQuad&f=json) to have a `dataType` attribute.  This attribute is missing in the response.

Not sure if this is an OpenLayers issue, or something for pygeoapi. However, from what I can see in the [OGC API Tile specification](https://developer.ogc.org/api/tiles/index.html#tag/Vector-Tiles/operation/.collection.vector.getTileSet), the `dataType` attribute is required.

**Steps to Reproduce**
Working code example; https://codesandbox.io/s/ogc-vector-tiles-forked-6f4tq3?file=/main.js

**Expected behavior**
The json to contain an attribute `dataType` with in this case the value `vector`

**Screenshots/Tracebacks**
Screenshot of [specification](https://developer.ogc.org/api/tiles/index.html#tag/Vector-Tiles/operation/.collection.vector.getTileSetsList) showing a valid result for `/collections/{collectionId}/tiles/{tileMatrixSetId}`

![capture](https://github.com/geopython/pygeoapi/assets/10270049/a4903e2f-bbc0-4ddc-b688-6df0e8ca5b1a)

**Environment**
 - OS: 
 - Python version: 
 - pygeoapi version: 0.15 according to the footer of the demo site

**Additional context**

**Comment by totycro** [comment]
I've looked into this, it shouldn't be hard to fix.

The data is read from here, so the first step of the fix would be to add all required attributes, including `dataType`, here:
https://github.com/geopython/pygeoapi/blob/master/tests/data/tiles/ne_110m_lakes/metadata.json

The response of this endpoint corresponds to this pydantic model, so we'd also need to add `dataType` here:
https://github.com/geopython/pygeoapi/blob/c7c07855e5cfa95b88d6d0d11f5c23111e38da95/pygeoapi/models/provider/mvt.py#L42

However what seems odd to me is that other keys don't correspond at all to this standard, there are keys such as `bounds` and `center`, and the aforementioned standard, it should be `boundingBox` and `centerPoint`. Also other required attributes such as `crs` and `links` are missing.

There is however this TileJSON standard, which the endpoint seems to correspond to:
https://github.com/mapbox/tilejson-spec/tree/master/3.0.0

Also OpenLayers seems to support this. Can you try to load the data specifying this source instead?
https://openlayers.org/en/latest/apidoc/module-ol_source_TileJSON-TileJSON.html

**Comment by doublebyte1** [comment]
@codehub-rony @totycro I think this was already solved:
https://github.com/geopython/pygeoapi/blob/e131cbf8daf0c7c8deb757970c15445ae2b4c829/pygeoapi/models/provider/base.py#L847
You can check the response here:
https://demo.pygeoapi.io/stable/collections/lakes/tiles/WebMercatorQuad/metadata?f=json
