### ISSUE TITLE
configure which field to use as label (by lang)

### ISSUE THREAD

**Issue by pvgenuchten** [geopython/pygeoapi#133]
It is interesting to know which of the feature properties can be used as label (for a given language). This label can be shown on the feature-popup when hovering (in stead of id). Also it can act as the feature page title (and schema.org/name).

![image](https://user-images.githubusercontent.com/299829/58213573-01c38a00-7cf3-11e9-9a1f-9c531af3c450.png)

Inside dataset configuration I suggest to add a title-property configuration, which can have multiple values per language (in case the dataset contains properties per language)
```
title_property:
   en: "title"
   fr: "titre"
```

**Comment by pvgenuchten** [comment]
Same on crumbs path and page title <head><title/> would be good to list the item title (in below case: "De Slokop"), in stead of repeating the dataset name

![image](https://user-images.githubusercontent.com/299829/70116153-27e2c300-1662-11ea-9c80-7212d20527af.png)

**Comment by jorgejesus** [comment]
@pvgenuchten  I would first consider decouple this from language request, and have a ticket to properly check how languages could be implemented on all the code base structure. Something like:

```
languages: ["en","fr","nl","pt"]
```
And then for the dataset maybe implement standard language, and optional ?? 

```
lakes:
        type: collection
        lang: nl
```
Then we could have other system/code/implementation to deal with language translation. Mainly different templates based on language?

Then you could do:

```
title_property: NAAM
```
And on the template:

https://github.com/geopython/pygeoapi/blob/917f1c0a959ca9962ceedfcca04a08b9e1298418/pygeoapi/templates/item.html#L13

The on the api level fiddle with `id` 

https://github.com/geopython/pygeoapi/blob/917f1c0a959ca9962ceedfcca04a08b9e1298418/pygeoapi/api.py#L932

and/or with the template that returns the item page items

**Comment by pvgenuchten** [comment]
Let's first set up the title_property element, and later improve to allow the element in multiple languages, for example by:

```YAML
title_property: Name
```

vs 

```YAML
title_property:
   en_us: name-en
   nl_nl: name-nl
   fr_ca: name-fr
```

or if the record is a json document, allow hierarchical

```YAML
title_property:
   en_us: name["en"]
   nl_nl: name["nl"]
   fr_ca: name["fr"]
```
