### ISSUE TITLE
"Install in 5 minutes" instructions stops with error: A GDAL API version must be specified.

### ISSUE THREAD

**Issue by pa5cal** [geopython/pygeoapi#1331]
**Description**
Following the ["Install in 5 minutes"](https://pygeoapi.io/) instructions literally doesn't result in a working installation. There's a missing dependency GDAL API version.

**Steps to Reproduce**
```
python -m venv pygeoapi
cd pygeoapi
Scripts\activate.bat
git clone https://github.com/geopython/pygeoapi.git
cd pygeoapi
pip3 install -r requirements.txt
```

**Expected behavior**
This should install pygeoapi without errors.

**Screenshots/Tracebacks**
````
 C:\Users\.......:
  INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.
  ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.
````

**Environment**
 - OS: Windows Server 2019 Standard
 - Python version: Python 3.7.4 
 - pygeoapi version: Latest

**Additional context**
The mentioned README does not contain any further information how to create the required extra option.

**Comment by doublebyte1** [comment]
@pa5cal thank you for reporting this. Does the issue still persist in the latest version?

**Comment by pa5cal** [comment]
@doublebyte1 thank you for asking. I am now using pygeoapi via Docker, as the installation and usage worked smoothly without any further difficulties.
