### ISSUE TITLE
OGC API MAPS and COVERAGES serving on-the-fly band math based on raster path stored in Postgres (tileindex approach)

### ISSUE THREAD

**Issue by MathewNWSH** [geopython/pygeoapi#1340]
**Is your feature request related to a problem? Please describe.**
As a user of WMS and WCS, I would like to have a tool for on-the-fly band math based on OGC APISs and data stored in a similar way to Mapserver's TileIndex.

**Describe the solution you'd like**
I am looking for something like the following:

Request:
```
http://localhost:5000/collections/Seintinel2Postgres/map?querry=((B8-B4)/(B8+B4))?f=png
```
Where B8 and B4 represent columns that store paths to Sentinel2 raster data on S3. When requesting data based on the TileIndex utility, Mapserver would get the rows with intersecting geometries and compute the query as a visualization.

It would also be great to be able to create custom compositions using requests, such as:
```
http://localhost:5000/collections/Seintinel2Postgres/map?channel_order=B3,B2,B1?f=png
```
**Describe alternatives you've considered**
Right now, I am using gdal VRT files, which somewhat meets my needs, but still requires me to create a separate file for each raster. This is not completely on-the-fly

Thanks,
Marc

**Comment by CeciliaPH** [comment]
I found this related issue for Maps.

https://github.com/geopython/pygeoapi/issues/1930
