### ISSUE TITLE
Serve OGCAPI-Tiles from .pmtiles file

### ISSUE THREAD

**Issue by KoalaGeo** [geopython/pygeoapi#1358]
**Is your feature request related to a problem? Please describe.**
The ability to use .pmtiles (https://github.com/protomaps/PMTiles) to serve ogcapi-tiles 

**Describe the solution you'd like**
Add pmtiles as a providor format. 

**Additional context**
Aligned with MVT layers - https://protomaps.com/docs/pmtiles
See specs - https://github.com/protomaps/PMTiles/blob/main/spec/v3/spec.md

**Comment by francbartoli** [comment]
Hi @KoalaGeo, this looks very nice and a great addition! However, I see the support in python https://github.com/protomaps/PMTiles/tree/main/python is still experimental. Are you planning to work on this? Can we use this experimental package right now if you have tested it?

**Comment by KoalaGeo** [comment]
Hi @francbartoli, 

Sorry, not tried the python yet, been experiementing using them directly and via [Martin](https://maplibre.org/martin/). 

However thought it was a good one to add to the list!

**Comment by doublebyte1** [comment]
Support to Martin was added with this PR: https://github.com/geopython/pygeoapi/pull/1552

I will close this issue for now, but feel free to reopen it if the support to Martin does not address it.
