### ISSUE TITLE
Participate in the Hacktoberfest 🚀

### ISSUE THREAD

**Issue by doublebyte1** [geopython/pygeoapi#1359]
_Hacktoberfest is a month-long celebration of open source projects, their maintainers, and the entire community of contributors. Each October, open source maintainers give new contributors extra attention as they guide developers through their first pull requests on GitHub._

I propose that pygeoapi joins the Hacktoberfest this year, welcoming new developers to the project. We can do that by taking these actions:

- Add the "Hacktoberfest" topic to the repository, so that it is listed [here](Hacktoberfest).
- Labelling issues with the Hacktoberfest label. I suggest easy issues, [like the ones with the "good first issue" label.](https://github.com/geopython/pygeoapi/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22)
- Keep an eye on PR with the "Hacktoberfest" label this month. If they are spam, we can label them with the "spam" label.
- Spreading the word about pygeoapi joining the hacktoberfest.

More information:
https://hacktoberfest.com/participation/
https://discord.gg/hacktoberfest

**Comment by tomkralidis** [comment]
Good idea @doublebyte1!

- repository update with 'Hacktoberfest' topic
- added issue label 'Hacktoberfest'
- communications:
   - https://noc.social/@pygeoapi/111165887391177285
   - https://twitter.com/pygeoapi/status/1708851077578145822

Let me know if I missed anything.  Thanks again :)

**Comment by doublebyte1** [comment]
@tomkralidis I already added a couple of issues here:
https://github.com/geopython/pygeoapi/issues?q=is%3Aopen+is%3Aissue+label%3AHacktoberfest

I'll add more later! :-)

**Comment by doublebyte1** [comment]
<img width="1440" alt="Screenshot 2023-10-04 at 10 35 18" src="https://github.com/geopython/pygeoapi/assets/1038897/455840ff-01a9-4bf6-9554-a09f1d4565eb">

**Comment by ravindu9802** [comment]
Hey, @doublebyte1 , I want to work on this. Can you assign this to me?

**Comment by doublebyte1** [comment]
@ravindu9802 can you describe exactly what you want to work in?
