### ISSUE TITLE
Upgrade minimum Python version to 3.8

### ISSUE THREAD

**Issue by ricardogsilva** [geopython/pygeoapi#1360]
This is related to the discussion in #1176

Now that we are [three months past Python 3.7's EOL](https://endoflife.date/python), is probably a good time to drop it from pygeoapi's CI and move our minimum Python version up to Python 3.8. which seems to be the most conservative version to keep support for nowadays.

My main motivation for this is I'd like to do some work related to validation of pygeoapi input/output with the corresponding OGC schemas, using jsonschema validation - including adding support for linked schema files (_i.e._ those `$ref` properties that show up all over the OGC schemas). 
There seems to be a nice [referencing](https://github.com/python-jsonschema/referencing) package made by the folks of python-jsonschema and I'm keen to study how to integrate this into pygeoapi. This third-party package unfortunately only supports Python 3.8+.

**Comment by francbartoli** [comment]
+1, also for security reason it's useful to move

**Comment by doublebyte1** [comment]
@ricardogsilva  I think we may need to adjust the code with the upgrade.  I noticed that for instance the unit tests don't work with python 3.8.

**Comment by ricardogsilva** [comment]
@doublebyte1 I'm looking into failed unit tests to try and get them in shape for bumping Python version to 3.8

**Comment by ricardogsilva** [comment]
With the recent merge of #1399 this is completed
