### ISSUE TITLE
Update elastic version on elastic docker example README file

### ISSUE THREAD

**Issue by doublebyte1** [geopython/pygeoapi#1361]
**Description**
The [elastic README file](https://github.com/geopython/pygeoapi/commit/c31e173effcd4b72049e0b139f30b710d324c455#diff-446dcefdeb4bfcac30f275eafb84c90a1dd8a7c9778070f7403825628b4c0c6dR10) mentions elastic vv5.6.8,  which is out of sync with the actual [Dockerfile](https://github.com/geopython/pygeoapi/blob/master/docker/examples/elastic/ES/Dockerfile#L34).
Also, elastic is currently not running on CentosOS 7.

**Expected behavior**
The README should contain the elastic version declared on the [Dockerfile](https://github.com/geopython/pygeoapi/blob/master/docker/examples/elastic/ES/Dockerfile#L34) and the OS version of the image. To check the OS version, you can follow these steps:

- Start the [docker-composition](https://github.com/geopython/pygeoapi/blob/master/docker/examples/elastic/docker-compose.yml)
- Enter the elastic container with: `docker exec -it elastic bash`
- Check the OS version with: `cat /etc/os-release`

To fix this issue, [update the elastic versions and OS description on the README file](https://github.com/geopython/pygeoapi/blob/master/docker/examples/elastic/README.md?plain=1#L10) to the correct values.

**Comment by Yasir761** [comment]
@doublebyte1 , can you please assign it to me?

**Comment by doublebyte1** [comment]
@Yasir761 someone else has made a PR https://github.com/geopython/pygeoapi/pull/1369 ! Are you still working on this?

**Comment by Yasir761** [comment]
> @Yasir761 someone else has made a PR #1369 ! Are you still working on this?

Yes I was doing but now someone else made PR?

**Comment by doublebyte1** [comment]
@Yasir761 I am sorry about that. I think they probably did not see that you were assigned to it
