### ISSUE TITLE
Close the elastic ports on the elastic docker example

### ISSUE THREAD

**Issue by doublebyte1** [geopython/pygeoapi#1363]
**Is your feature request related to a problem? Please describe.**
The elastic example is [publishing the elastic container ports on the host](https://github.com/geopython/pygeoapi/blob/master/docker/examples/elastic/docker-compose.yml#L62). If run in production, this could open a vulnerability as the elastic server is unprotected. 

**Describe the solution you'd like**
In reality, we do not need to publish these ports, as the [pygeoapi container is accessing the elastic container directly](https://github.com/geopython/pygeoapi/blob/master/docker/examples/elastic/pygeoapi/docker.config.yml#L151). Therefore, we can just not publish these ports in the docker-compose file and everything will work as expected. For debugging purposes, maybe we can just leave that code there, but commented out, and perhaps add a warning that if someone uses it in production they will need to protect elastic.

**Comment by krishnaglodha** [comment]
I'll work on it

**Comment by melencholicmice** [comment]
Hello , is the issue still open ? if it is  I would look into it.

**Comment by doublebyte1** [comment]
@melencholicmice yes, it is! Thank you for your interest 👍🏽

**Comment by doublebyte1** [comment]
> Hello , is the issue still open ? if it is I would look into it.

I think that a PR already solved this issue. 
https://github.com/geopython/pygeoapi/pull/1382

@melencholicmice Sorry about that!

**Comment by melencholicmice** [comment]
@doublebyte1  I understand, I'm Intrested  in contributing  to the project  so is there any other issues I can look into ?
