### ISSUE TITLE
Upgrade Mongo version to 7 on Docker Examples

### ISSUE THREAD

**Issue by doublebyte1** [geopython/pygeoapi#1371]
The example docker-composition for using the Mongo backend provider, uses [Mongo v6](https://github.com/geopython/pygeoapi/blob/master/docker/examples/mongo/README.md?plain=1#L10).  Mongo 7 was [released in August](https://www.mongodb.com/docs/manual/release-notes/7.0/) and there is a [Docker image for v7.0.2 on Docker Hub](https://hub.docker.com/layers/library/mongo/7.0.2/images/sha256-05bb0d03427adc9f27eb93b02dd501e4f852f3ff46144bfd42a227721c496e1f?context=explore).

The idea would be to upgrade the mongo version docker-compose to the latest tag available (at this time 7.2). This would involve the following tasks: 
- [ ] Update the version number on docker compose
- [ ] Test manually that everything works as expected: check the [queryables](http://localhost:5000/collections/ne_110m_populated_places_simple/queryables) and [items](http://localhost:5000/collections/ne_110m_populated_places_simple/items)  endpoints.
- [ ] Run the [mongo unit tests](https://github.com/geopython/pygeoapi/blob/master/.github/workflows/main.yml#L142).
- [ ] After everything works, [update the README to reflect the correct version number and OS](https://github.com/geopython/pygeoapi/blob/master/docker/examples/mongo/README.md?plain=1#L10).

**Additional context**
https://docs.pygeoapi.io/en/latest/data-publishing/ogcapi-features.html#mongodb

**Comment by carlospatinos** [comment]
Can I work on this please?

**Comment by carlospatinos** [comment]
Hello there, I am not familiar with this app from before so what I am trying to do is as follows:

1. start up the application
2. run tests

I have this in mind to have an starting point to make sure all is working before applying changes in docker and testing again. 

I followed the https://docs.pygeoapi.io/en/latest/installation.html and then run the app and then execute pytest (i had to install that first)

I am getting a bunch of errors and warnings on the test without any changes so wondering if I am missing some setup step
I am getting these:
1 skipped, 16 warnings, 40 errors in 5.24s 
Any guidance is welcome

**Comment by doublebyte1** [comment]
@carlospatinos thank you for working on this issue! 

You don't need to run the server, if you are playing with the docker examples. The docker-compose already includes a [pygeoapi container](https://github.com/geopython/pygeoapi/blob/master/docker/examples/mongo/docker-compose.yml#L33), built from an image.

What you would need to do is run the [docker-compose file](https://github.com/geopython/pygeoapi/blob/master/docker/examples/mongo/docker-compose.yml), and check the everything works by accesing the [web UI of pygeoapi](https://docs.pygeoapi.io/en/stable/tour.html#landing-page).

[If you type 'pytest', you will be running the entire test suite](https://docs.pygeoapi.io/en/stable/development.html?highlight=pytest#testing), which would be relevant if you were changing something in pygeoapi. In this case you want to run just the specific tests that are related to mongo, because we want to make sure that pygeoapi still works well with the upgraded mongo version.

I have put a link on the description of the issue with the test that you need to run. You also need to [load sample data, before running the test](https://github.com/geopython/pygeoapi/blob/master/.github/workflows/main.yml#L125). 

Let me know if this helps!

**Comment by carlospatinos** [comment]
I followed your instructions and results are as follow:

1. By updating this mongo version to 7.0.2  and docker containers start 
2. Load data script seems to be working
3. UI is working (and showing data)
4. But there are some errors while executing the mongo test as follows

![errors](https://github.com/geopython/pygeoapi/assets/7103780/0b601fc3-c122-4199-bdd3-ab4d58cae0aa)

I tried reverting the change to mongo 6...  i see similar issues so maybe something i am missing.
I installed all the different requirements and even had to install bson as I was getting 
ModuleNotFoundError: No module named 'bson'

I can try to troubleshoot why thats happening but wanted to get your opinion as you may spot something obvious 

Thanks

**Comment by doublebyte1** [comment]
@carlospatinos did you load the data, before running the tests?

https://github.com/geopython/pygeoapi/blob/master/.github/workflows/main.yml#L125

**Comment by doublebyte1** [comment]
@carlospatinos which python version are you running?

**Comment by carlospatinos** [comment]
Found the problem, it was a dependency that was not being installed properly

**Comment by carlospatinos** [comment]
@doublebyte1 please let me know if anything is missing :)

**Comment by carlospatinos** [comment]
PR in place https://github.com/geopython/pygeoapi/pull/1378
