### ISSUE TITLE
README file is out of sync with the data in sensorthings example

### ISSUE THREAD

**Issue by doublebyte1** [geopython/pygeoapi#1374]
**Description**
The [README file describes three configuration files](https://github.com/doublebyte1/pygeoapi/blob/master/docker/examples/sensorthings/README.md#sensorthings-build-options). The links to the configuration files are all broken.

Two configuration files are presented and referenced in [docker-compose](https://github.com/doublebyte1/pygeoapi/blob/master/docker/examples/sensorthings/docker-compose.yml#L38), but they are not described in the README file: [brgm.config.yml](https://github.com/doublebyte1/pygeoapi/blob/master/docker/examples/sensorthings/brgm.config.yml) and [usgs.config.yml](https://github.com/doublebyte1/pygeoapi/blob/master/docker/examples/sensorthings/usgs.config.yml) 

**Steps to Reproduce**
Try to follow the README to run the examples.

**Expected behavior**
The README should describe the configuration files that are in the folder. The name, link and description of these files should be updated.

**Environment**
 - OS: Ubuntu 22.04.3 LTS
 - Python version: 3.7.8
 - pygeoapi version: 0.16.dev0

**Additional context**
[STA standard](https://github.com/opengeospatial/sensorthings)

**Comment by shivathapaa** [comment]
Hi @doublebyte1,

I've identified the links to be updated in the README. I'm somewhat confused about what type of descriptions should be added for these configuration files. Could you please provide guidance on the specific descriptions or information that should be included in the README? Please consider assigning this issue to me for resolution.

Thank you for your assistance.

**Comment by doublebyte1** [comment]
Hi @shivathapaa ! Thank you for working on this issue.

The idea of the description [would be just to put a sentence, like what is currently in the README](https://github.com/doublebyte1/pygeoapi/blob/master/docker/examples/sensorthings/README.md?plain=1#L13):  "server serving the BRGM water quality endpoint". This would help users to understand what the example is about.

As for what the example is about, unfortunately I know as much as you do, but what I would do if I was going to write the description would be to research a bit more. One strategy could be to run the [docker-composition](https://github.com/doublebyte1/pygeoapi/blob/master/docker/examples/sensorthings/docker-compose.yml) and check the web ui of the server to see what the data is about (you should try this for both configuration files). Another strategy, could be to look at the actual configuration file and see if there are links there that can take us to metadata (for instance: https://github.com/doublebyte1/pygeoapi/blob/master/docker/examples/sensorthings/brgm.config.yml#L116C1-L116C1 or https://github.com/doublebyte1/pygeoapi/blob/master/docker/examples/sensorthings/brgm.config.yml#L116C1-L116C1).

Hope this helps!
