### ISSUE TITLE
Logfile rotation

### ISSUE THREAD

**Issue by xkosubek** [geopython/pygeoapi#1389]
Hello,

it would be nice to have a logfile rotation, because the logs could grow fast.

In the Python logger it is possible to rotate logs size or time based.

http://docs.python.org/3/library/logging.handlers.html#rotatingfilehandler
http://docs.python.org/3/library/logging.handlers.html#timedrotatingfilehandler

My suggestion would be, to make it configurable in the config file.
```
logging:
    level: ERROR
    #logfile: /tmp/pygeoapi.log
    #rotate_mode: off # [off|time|size]
    #rotate_when: midnight # [s|m|h|d|w0-w6|midnight]
    #rotate_interval: 0
    #rotate_max_bytes: 20
    #rotate_backup_count
```

If this is ok for you, you can assign this issue to me and i will implement it.

Regards,
Andreas

**Comment by xlangerama** [comment]
Notes from the Codesprint: 

rotate_mode has either time or size or is none. 

If none then behave as default for legacy support. 

If Parameters are set have a rotation object and then dump everything under the rotate object. 

Check for the rotation style and then support the logic. 

pygeoapi/log.py

Document under configuration.rst and under logging section.
-> log rotation subsection.
