### ISSUE TITLE
Configurable DEFAULT_CRS

### ISSUE THREAD

**Issue by xkosubek** [geopython/pygeoapi#1393]
It would be nice, when the default output CRS could be configured like the storage_crs. I know, this is against the specification of the OGC Feature API. But for now at least the Oracle and the OGR Provider allowing a provider specific configuration of a target_crs. But since the new parameter in the provider query function call, crs_transform_spec, it cames to the following inconsistency:

Given:
Default Provider configuration storage_crs = EPSG:31287
Oracle Provider configuration target_crs = EPSG:31287

When:
Query without crs parameter => Output in EPSG:31287 <=Already against Spec

When:
BBox Query without bbox-crs parameter => Transformation call from OGC:WGS84 to EPSG:31287
To this time i can not difference between a query with bbox-crs parameter set to OGC:WGS84 (bbox is submitted in WGS84)
and a query without bbox-crs (bbox is submitted in EPSG:31287, what i would aspect when i set target_crs to it). To use the service complete in EPSG:31287, i have to set the query parameter bbox-crs ...

In my opinion, this is a inconsistency. Either i would delete the target_crs parameter (at least in the oracle provider) and force the usage of the query parameters crs and bbox-crs or have the possibility to complete change the default crs.

What is your opinion about that?

**Comment by totycro** [comment]
In my opinion, there is a valid use case where you always want the output in a certain CRS, especially if all the clients are under your control. However this is not the general case, so it makes sense that the spec requires a specific default CRS, which effectively means that any `target_crs` setting other than WGS84 a spec violation.

So the way forward here could be to actually remove the `target_crs` setting and set up the clients in a way that they always request this CRS.
