### ISSUE TITLE
break Dockerfile up into smaller instructions and optimize for using the docker cache when building

### ISSUE THREAD

**Issue by ricardogsilva** [geopython/pygeoapi#1406]
The current pygeoapi `Dockerfile` consists basically of an `add` instruction and then a  big `run` instruction. This is not very efficient, as it does not allow leveraging the docker cache when re-building. The docker docs have a nice overview of how to optimize image builds taking the docker caching mechanism into mind:

https://docs.docker.com/build/cache/

For pygeoapi's docker image:

- `add`ing the pygeoapi directory before performing other actions means that anytime the pygeoapi source changes the docker cache is busted and the image needs to be rebuilt from scratch - this means that if I change the code, the new image must re-install all of the system dependencies, even if they did not change. If, for example, this instruction would come after having installed system dependencies, then that step could potentially reuse the docker cache and thus building the image would be a lot faster. 

- Putting most operations inside a big `run` block does not allow using the docker cache, as docker cannot know what can be cached and what cannot

- `adding` everything in a single step is also not very efficient - we can `add` the requirements files first, then install those and then `add` the actual pygeoapi source code - this way, if the contents of the requirements files don't change, docker will be able to cache the installation of these requirements and speed up the image building process 

**Is your feature request related to a problem? Please describe.**
I'm rebuilding the pygeoapi docker image and getting bored because it takes sooo long to be done :sweat:

**Comment by totycro** [comment]
There is already a PR which includes this: https://github.com/geopython/pygeoapi/pull/1252

I've been using the Dockerfile from that PR locally because currently the build time is really long.
