### ISSUE TITLE
Dynamic configuration update (for dynamic service registration)

### ISSUE THREAD

**Issue by geotom** [geopython/pygeoapi#1417]
# Dynamic configuration (without server restart)

I would love to work with pyGeoAPI as a dynamic service registry. This means a hot reloading of the service configuration file to allow registration and unregistration of services. This could also benefit other services of pyGeoAPI and allow for dynamic setups where pyGeoAPI works as outbound interface with a custom internal orchestrator tool which supports to register / unregister services.

I do not think we need an internal API for this. It would be enough to be able to alter the configuration by custom code and call a configuration reload on pyGeoAPI. Right now, I have to manipulate the configuration and restart the full pyGeoAPI.

Thanks for considering this (if it is not already possible)

**Comment by geotom** [comment]
That sounds really great @tomkralidis! UI part for me is less important, but the ability to update parts of the configuration dynamically and the server dynamically responding to the updates would be a killer feature. Thanks for hinting the issue tickets

**Comment by tomkralidis** [comment]
That is an option however it is gunicorn specific (note: you can don this now by updating the gunicorn startup). Perhaps a watcher in pygeoapi proper would be the most generic approach.

**Comment by tomkralidis** [comment]
Yes, see #1443.
