### ISSUE TITLE
Make better use of screen real estate in Collections HTML page

### ISSUE THREAD

**Issue by justb4** [geopython/pygeoapi#142]
The `Collections` HTML page is sort of squeezed-in, not using available browser-screen optimally. Best to show this with a picture, for example when opening
https://demo.pygeoapi.io/master/collections?f=html
we see:

![image](https://user-images.githubusercontent.com/582630/58421450-41da9200-8090-11e9-8315-b1f68827adab.png)

I.e.

* vertically: a scroll-bar which IMO is not required
* horizontally: the table could be broader 

Seen on Google Chrome and Safari Mac OSX.

**Comment by justb4** [comment]
I can take this one up, PR upcoming. Below after some CSS and other mods:

![image](https://user-images.githubusercontent.com/582630/58707775-220bdc80-83b6-11e9-8577-5737ebb11777.png)

* excess text removed
* no vertical scrollbar table
* keep footer positioned at bottom

**Comment by justb4** [comment]
Should be fixed.

**Comment by tomkralidis** [comment]
The fixed footer results in some pages' content not being fully visible.  Example: https://demo.pygeoapi.io/master

However pages like https://demo.pygeoapi.io/stable/collections?f=html now render much better.

Can we not have the fixed footer?  Pull request for review in #158

**Comment by justb4** [comment]
Think this issue is fixed and can be closed, also it is more about formatting than content as in #361.
