### ISSUE TITLE
`parameter-names` need to change to `parameter_names` in EDR implementation 

### ISSUE THREAD

**Issue by krishnaglodha** [geopython/pygeoapi#1433]
**Description**
According to the OGC API - EDR Document https://docs.ogc.org/is/19-086r6/19-086r6.html#_b6db449c-4ca7-4117-9bf4-241984cef569 the name of the `key` that represents all parameters should be `parameter_names`. 

I also confirmed it by checking https://labs.metoffice.gov.uk/edr/collections/global_pop_density and https://ogcie.iblsoft.com/edr/collections/GFS_between-depth

**Comment by tomkralidis** [comment]
Thanks @krishnaglodha; addressed in #1431
