### ISSUE TITLE
Connection PyGeoAPI STAC from QGIS?

### ISSUE THREAD

**Issue by bertt** [geopython/pygeoapi#1434]
Hi,

I'm trying to get a connection in QGIS to STAC from PyGeoAPI but the message 'Connection is not a valid STAC API' is returned:

![image](https://github.com/geopython/pygeoapi/assets/538812/bba3368f-f365-499a-8757-555f0f7a959c)

I'm running latest PygeoAPI docker image with some STAC information, I can retrieve the catalog using http://localhost:5000/stac/stac-demo/catalog.json . Also tried without the catalog.json but same message.

So the question is: How can I make a STAC connection in QGIS to PyGeoapi? Or is this not supported?

**Comment by allixender** [comment]
I have the same experience, and found that e.g. conformance classes or collections under the stac endpoint are not shown like in other stac implementations. But it should be without the "catalog.json" because it's a STAC API endpoint.

**Comment by allixender** [comment]
Mentioning the original improvements as well: https://github.com/geopython/pygeoapi/issues/221
