### ISSUE TITLE
expose shapely functions as sample process

### ISSUE THREAD

**Issue by tomkralidis** [geopython/pygeoapi#1439]
As suggested by Sumit Sen at GISE OGC Stack Winter School 2023, given [Shapely](https://shapely.readthedocs.io) is a core pygeoapi dependency, it would be value to have `pygeoapi.process.shapely_functions.py` to expose various geometric processing functionality.  Candidates could be:

- measurement (length, area, etc.)
- predicates
- set operations
- constructive ops

(there could be others).

All functions should be able to accept either WKT or a GeoJSON geometry object and output same.

**Comment by krishnaglodha** [comment]
Can I work on it ?

**Comment by tomkralidis** [comment]
Sure!

**Comment by tomkralidis** [comment]
Update: it looks like we have 2 open PRs in support of this issue:
- #1481 
- #1565 

Can you let me know if you are actively working on these PRs?  We should also consider coordinating this work further into a single PR.

**Comment by jeafreezy** [comment]
Hi @tomkralidis , yes I am working on mine. I will be pushing the final docs this weekend.

**Comment by jeafreezy** [comment]
I've pushed the docs. The PR is npw open for review @tomkralidis.🙏🏿

**Comment by tomkralidis** [comment]
Initial implementation added in #1565.  Thanks!
