### ISSUE TITLE
move all examples into separate GitHub repository

### ISSUE THREAD

**Issue by tomkralidis** [geopython/pygeoapi#1456]
Currently, we have a growing number of deployment examples in the codebase:

- `aws-lambda`
- `docker/examples`
- `examples`

I'd like to move the above into a new repository called `pygeoapi-examples`.  This keeps the codebase "core", and having a specific repository for examples will give more flexibility moving forward.

I will implement the above once we have 3 +1s here.

**Comment by francbartoli** [comment]
+1, I would clarify the overall use for this new repository though

**Comment by webb-ben** [comment]
+1
I find the docker examples to be the easiest place to develop and test pygeoapi docker images. Plus one to this so long as the examples are better documented than they currently are, and I would love to get a docker compose file in the current docker folder.

**Comment by kalxas** [comment]
+1

**Comment by doublebyte1** [comment]
+1 to have these things outside the code base.

I think it would be helpful to reference to it from the documentation, as these examples are more expressive than the code snippets.

**Comment by pvgenuchten** [comment]
+1, but keep a basic Docker deployment

**Comment by tomkralidis** [comment]
Associated PRs:
- #1464 
- https://github.com/geopython/pygeoapi-examples/pull/1
