### ISSUE TITLE
Refactor Tiles Metadata UI to support multiple formats

### ISSUE THREAD

**Issue by doublebyte1** [geopython/pygeoapi#1458]
**Is your feature request related to a problem? Please describe.**
The tiles Metadata UI only supports one format at a time (the one that was selected on the configuration file).

On this example, TileJSON was selected. 

![Screenshot from 2023-12-27 12-13-49](https://github.com/geopython/pygeoapi/assets/1038897/5e1060e9-b60b-445a-832c-1d33824e4e07)

![Screenshot from 2023-12-27 12-14-01](https://github.com/geopython/pygeoapi/assets/1038897/9137f6a3-7e8e-4e39-9c11-77dd3df89c79)

The "default" metadata format (OGC TMS) is not consistently supported by the UI. The option to display metadata does not appear in the tiles resource page: http://localhost:5000/collections/lakes/tiles

![Screenshot from 2023-12-27 12-33-19](https://github.com/geopython/pygeoapi/assets/1038897/9f24f6ae-75e2-4d10-8045-d831af575ae3)

And by accessing the url directly (http://localhost:5000/collections/lakes/tiles/WorldCRS84Quad/metadata), we see a UI page that is not consistent with the OGC 2D TMS format (see "tileJSON" reference):

![Screenshot from 2023-12-27 12-34-33](https://github.com/geopython/pygeoapi/assets/1038897/cdb31b84-1ff6-4e73-b9b7-951867aafadb)

**Describe the solution you'd like**
With [this](https://github.com/geopython/pygeoapi/issues/1457) refactoring, we would be able to support multiple formats:

- https://demo.pygeoapi.io/master/collections/lakes/tiles/WorldCRS84Quad/metadata?f=json -> OGC 2D TMS (default for machines)
- https://demo.pygeoapi.io/master/collections/lakes/tiles/WorldCRS84Quad/metadata?f=tilejson -> TileJSON
- https://demo.pygeoapi.io/master/collections/lakes/tiles/WorldCRS84Quad/metadata?f=html -> HTML (default for browsers)

The HTML page should be agnostic of the format. Similar to this implementation:
https://maps.gnosis.earth/ogcapi/collections/blueMarble/map/tiles/WorldCRS84Quad?f=tilejson
https://maps.gnosis.earth/ogcapi/collections/blueMarble/map/tiles/WorldCRS84Quad?f=json
https://maps.gnosis.earth/ogcapi/collections/blueMarble/map/tiles/WorldCRS84Quad?f=html

**Describe alternatives you've considered**
Leaving it, as it is.

**Comment by simonseyock** [comment]
While working on the WMTSProvider I stumbled over this problems as well.

I added some variables to the template:

https://github.com/geopython/pygeoapi/pull/1473/files#diff-f3ee4caa7dc224a51caf333d89b130fe02ff0351a77dfdd11c06d0a4b56e6732R2803-R2811

and reworked the map viewer a little bit:

https://github.com/geopython/pygeoapi/pull/1473/files#diff-a33f7def52ad3a6af980fe603069ad9add9fc080d131b966551b592241dbf432L42-R67

Maybe this helps, cheers!
