### ISSUE TITLE
ModuleNotFoundError: No module named 'jsonpatch'

### ISSUE THREAD

**Issue by krishnaglodha** [geopython/pygeoapi#1469]
**Description**
I'm trying to execute `Install in 5 minutes` on https://pygeoapi.io/ , and getting above mentioned error. 

**Steps to Reproduce**
```
python3 -m venv pygeoapi
cd pygeoapi
. bin/activate
git clone https://github.com/geopython/pygeoapi.git
cd pygeoapi
pip3 install -r requirements.txt
python3 setup.py install
cp pygeoapi-config.yml example-config.yml
vi example-config.yml  # edit as required
export PYGEOAPI_CONFIG=example-config.yml
export PYGEOAPI_OPENAPI=example-openapi.yml
pygeoapi openapi generate $PYGEOAPI_CONFIG --output-file $PYGEOAPI_OPENAPI
pygeoapi serve

```
**Screenshots/Tracebacks**
<img width="570" alt="Screenshot 2024-01-03 at 9 53 12 PM" src="https://github.com/geopython/pygeoapi/assets/47075664/a916c462-e161-4476-8a3f-9d3a658ca5b1">

**Environment**
 - OS: Mac OS
 - Python version: 3.11
 - pygeoapi version: latest

**Comment by krishnaglodha** [comment]
Should we mention it on the [admin page ](https://docs.pygeoapi.io/en/latest/admin-api.html) that to run is successfully, user should also execute `pip install -r requirements-admin.txt`

**Comment by doublebyte1** [comment]
@krishnaglodha well spotted! 👍🏽  Do you want to do a PR to add that line to the docs?

https://github.com/geopython/pygeoapi/blob/d66e790df18ddcaa984984c2cb6a25c97c21bdee/docs/source/installation.rst?plain=1#L29

**Comment by krishnaglodha** [comment]
Will do

Thanks & Regards,
Krishna G. Lodha
Founder
office email - ***@***.***
personal email - ***@***.***

**Comment by krishnaglodha** [comment]
I propose to have this on the doc page of admin, because we are not sure that everyone will be using admin function, thus, let people know about this only on admin doc page ?

**Comment by ricardogsilva** [comment]
@krishnaglodha 

If that would be the case, then the packages specified on `requirements-admin.txt` ought to be optional, which does not seem to be the case currently, which I guess is a bug? 

The admin is being turned on conditionally, depending on the pygeoapi config. However, the import of `jsonpatch` happens regardless.

**Comment by ricardogsilva** [comment]
I guess a decision needs to be taken on whether:

- The admin is part of the default pygeoapi experience, in which case I guess there is no need for a separate `requirements-admin.txt` file and the admin dependencies become regular pygeoapi dependencies - no need to modify the installation docs in this case.

- The admin is indeed optional, in which case the docs need to be adjusted and the code needs to include some guards that ensure the admin dependencies are not imported unconditionally

@tomkralidis @webb-ben , what would be your thoughts on this?

**Comment by doublebyte1** [comment]
> 
> The admin is being turned on conditionally, depending on the pygeoapi config. However, the import of `jsonpatch` happens regardless.

@ricardogsilva indeed that does not seem correct. 

I am in favour of the second option (admin as optional). I can think of use cases where people don't need an admin UI and just want a simple, lightweight, API.

**Comment by tomkralidis** [comment]
PR in #1485
