### ISSUE TITLE
Add Docker build and possibly Docker Image test to Travis build

### ISSUE THREAD

**Issue by justb4** [geopython/pygeoapi#148]
After a push to `master` the Travis build may succeed but the then triggered Docker build on DockerHub may fail.

Add a Docker build to [Travis YAML](https://github.com/geopython/pygeoapi/blob/master/.travis.yml) build (Travis supports Docker as a `service`) and possibly even test the Docker Image as it contains test config+data. This could be effected via:

`docker run -it geopython/pygeoapi test` (on the  Docker Image built within Travis off course..)

**Comment by tomkralidis** [comment]
@justb4 status on this one? I think we are building and running Docker in Travis?

**Comment by justb4** [comment]
Closing: now have GH Workflow Docker build/push and new issue #1003
