### ISSUE TITLE
Enable CQL filtering to accept filter geometries in any CRS

### ISSUE THREAD

**Issue by ricardogsilva** [geopython/pygeoapi#1488]
pygeoapi currently offers CQL filtering for some backends. However, when supplying a geometry as part of the CQL filter, one needs to ensure it uses the same CRS as the corresponding collection.

It would be great if pygeoapi would be able to accept geometries in whatever CRS and would then convert them to the appropriate CRS, as needed by the collection provider.

As an example, I have a feature collection which is stored in a PostGIS DB and has a storage CRS of `EPSG:3004`. I would like to
perform a request for retrieving those collection items which are located whithin 100 m of some reference point. This translates to the following request:

```sh
curl 'http://localhost:5000/collections/beni_confiscati/items?\
    filter=DWITHIN(geometry,SRID=3004;POINT(2313683.65%204641312.29),100,meters)'
```

As illustrated above, in order for my request to work, I currently need to pass in a point defined in EWKT with the storage CRS (_i.e._ `SRID=3004;POINT(2313683.65,4641312.29)` - this is not always convenient.

I would like to be able to perform a request with a filter where my `POINT` would simply be defined using the `OGC:CRS84` CRS implicitly and then pygeoapi would convert that to whatever CRS the feature collection is stored in - Something like this:

```sh
curl 'http://localhost:5000/collections/beni_confiscati/items?\
    filter=DWITHIN(geometry,POINT(12.512829%2041.896698),100,meters)'
``` 

I would also like to be able to keep specifying a custom CRS and being able to also have pygeoapi automatically convert input geometries (if needed) in order to be able to query the collection. For example, these would be nice to have:

```sh
# supplying the same CRS as the one being used internally - no conversion of coordinates needed
curl 'http://localhost:5000/collections/beni_confiscati/items?\
    filter=DWITHIN(geometry,SRID=3004;POINT(2313683.65%204641312.29),100,meters)'

# supplying another CRS
curl 'http://localhost:5000/collections/beni_confiscati/items?\
    filter=DWITHIN(geometry,SRID=3857;POINT(1392921%205145517),100,meters)' 
```

**Comment by walkermatt** [comment]
Note: Support for specifying the CRS of geometries in CQL filters by using EWKT isn't current supported in pygeoapi (as of 09cb2c07bd35cbc87fe9bd77c9049b94f930f9a8).

Parsing of CQL geometry values is handled by [geopython/pygeofilter](https://github.com/geopython/pygeofilter); @ricardogsilva has recently had a [PR merged which improves geometry parsing to add support for a CRS](https://github.com/geopython/pygeofilter/pull/88) :tada:.

To take advantage of this enhancement uninstall pygeofilter from you're pygeoapi virtual environment, clone the pygeofilter repo and install it as an editable package:

```shell
pip unistall pygeofilter

git clone https://github.com/geopython/pygeofilter.git
cd pygeofilter
pip install -e .
```
