### ISSUE TITLE
Address requirement 5 of OGC API - Tiles Core Requirements

### ISSUE THREAD

**Issue by doublebyte1** [geopython/pygeoapi#1499]
**Description**
[Requirement 5](https://docs.ogc.org/is/20-057/20-057.html#toc27) of the Core Requirements of OGC API - Tiles, states that:

`A successful execution of the tile operation with content SHALL be reported as a response with an HTTP status code 200.
`
Instead, pygeoapi is returning 202.

**Steps to Reproduce**
```
curl -I 'https://demo.pygeoapi.io/master/collections/lakes/tiles/WorldCRS84Quad/2/0/1?f=mvt'
HTTP/2 202 

```

**Expected behavior**
The server should return 200, for a successful response:

```
curl -I 'https://demo.pygeoapi.io/master/collections/lakes/tiles/WorldCRS84Quad/2/0/1?f=mvt'
HTTP/2 200

**Comment by francbartoli** [comment]
Closed by #1500
