### ISSUE TITLE
Adoption of Architectural Decision Record (ADR) methodology as best practice

### ISSUE THREAD

**Issue by francbartoli** [geopython/pygeoapi#1537]
**Is your feature request related to a problem? Please describe.**
As the pygeoapi project evolves and scales, it becomes increasingly important to establish clear documentation and communication channels regarding architectural decisions. Currently, the pygeoapi project lacks a standardized method for documenting architectural decisions. This lowers the ability of contributors, maintainers, and stakeholders to understand the reasoning behind certain design choices and may lead to misunderstandings or inefficiencies during the development process.  This issue proposes the adoption of [Architectural Decision Records (ADRs)](https://github.com/adr/adr.github.io) as a best practice within the pygeoapi project.
It serves as a starting point for discussing the feasibility and implications of adopting ADRs within the pygeoapi project. Feedback and contributions from the community are welcomed and encouraged to help shape the proposed implementation plan and ensure its successful adoption.

**Describe the solution you'd like**
One approach gaining traction in the software development community is the use of Architectural Decision Records (ADRs). ADRs provide a structured way to capture important architectural decisions, their contexts, and the rationale behind them, thereby promoting transparency and aiding in future decision-making processes. They will be available as a markdown files under the documentation folder and eventually made published and searchable as web pages. An ADR may or may not be linked to a pull request but when there is a particular focus/impact on the design of the pygeoapi architecture then it can be required (if missing) as part of the review process to converge toward an architectural change with a documented and clear consensus/rejection.
By adopting ADRs as a best practice, the pygeoapi project can enhance its architectural governance processes, foster collaboration among contributors, and ultimately deliver more robust and maintainable software solutions.

Implementation Plan:
To adopt ADRs as a best practice within the pygeoapi project, the following steps are proposed:

- **Education and Awareness**: Raise awareness among contributors, maintainers, and stakeholders about the benefits of ADRs and the proposed adoption process.
- **Establishment of Guidelines**: Define clear guidelines for creating, maintaining, and organizing ADRs within the project repository.
- **Integration with Development Workflow**: Integrate the creation and review of ADRs into the project's development workflow to ensure that important architectural decisions are documented in a timely manner.
- **Documentation**: Update the project's documentation to include information on ADRs, their purpose, and how they should be used within the context of the pygeoapi project.
- **Community Engagement**: Encourage community participation in the creation and review of ADRs to ensure that a diverse range of perspectives is considered in the decision-making process.

**Describe alternatives you've considered**
Keep the architectural decisions fragmented and hidden in the discussions of the issues/PRs themself.

**Additional context**
By formally documenting key architectural decisions, we aim to achieve the following benefits:

- **Transparency**: ADRs provide transparency into the thought process behind architectural decisions, allowing contributors and stakeholders to understand the rationale and implications of various design choices.
- **Consistency**: A standardized format for documenting architectural decisions promotes consistency across the project, making it easier for new contributors to understand the project's architecture and guiding future decision-making processes.
- **Knowledge Sharing**: ADRs serve as a valuable knowledge-sharing tool, capturing the collective wisdom and experience of the project's contributors and enabling knowledge transfer across team members.
- **Risk Mitigation**: Documenting architectural decisions helps mitigate the risk of future misunderstandings or disputes by providing a clear record of the rationale behind each decision.

**Comment by francbartoli** [comment]
I will start with my +1

**Comment by tomkralidis** [comment]
Thanks @francbartoli.  As discussed, this can be put forth as an [RFC](https://pygeoapi.io/development/rfc) on the pygeoapi website and then sent to the mailing list for PSC vote.
