### ISSUE TITLE
Adding Shapely Buffer Functionality in API Process

### ISSUE THREAD

**Issue by Prajwalita** [geopython/pygeoapi#1540]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by francbartoli** [comment]
Hello @Prajwalita, is this a feature request? From the title would look like you are looking for an implementation of a user-defined process which might be developed as an external and pluggable plugin of a pygeoapi process

**Comment by Prajwalita** [comment]
expose shapely functions and GDAL functions as sample processes

**Comment by francbartoli** [comment]
Sorry @Prajwalita, what's kind of an improvement is going to be a number of samples more than just only one? For the sake of having an example in the code base I do believe just one shapely/GDAL function is quite enough

**Comment by francbartoli** [comment]
Also, I would encourage to change the title to `Replacing HelloWorld sample process with a shapely/GDAL function` or something like that for more clarity

**Comment by tomkralidis** [comment]
Closing as per https://github.com/geopython/pygeoapi/pull/1541#issuecomment-2035996444, so work needs to follow in the pygeoapi-examples repository.

**Comment by aufdenkampe** [comment]
@sjordan29, these functions could be useful as we move forward on fleshing out EDR.
