### ISSUE TITLE
Upgrade test suite to Python 3.9

### ISSUE THREAD

**Issue by huard** [geopython/pygeoapi#1543]
**Is your feature request related to a problem? Please describe.**

The CI runs on 3.8, but numpy and xarray have dropped support for 3.8 last year (see https://docs.xarray.dev/en/stable/whats-new.html#v2023-02-0-feb-7-2023). This is not causing any problem right now for me, but I suspect changes in upstream libraries could go undetected. 

**Describe the solution you'd like**
Update the python version running the CI to 3.9.

**Comment by ricardogsilva** [comment]
In the spirit of [pygeoapi RFC2](https://pygeoapi.io/development/rfc/2/), it seems to me that the idea is to ensure dependencies are aligned with whatever is available in the current ubuntu LTS version - which at the time of writing is version 22.04.

In light of this, it seems to me that we actually ought to move to Python 3.10, which is the default version on ubuntu 22.04.

**Comment by tomkralidis** [comment]
Thanks for the report.  Associated PR in #1586.
