### ISSUE TITLE
Incorrect behaviour for Tile Providers, using OpenLayers Client

### ISSUE THREAD

**Issue by doublebyte1** [geopython/pygeoapi#1546]
**Description**
The `OGCVectorTile` class of OpenLayers does not display correctly the vector tiles layers from pygeoapi.

<img width="1440" alt="Screenshot 2024-02-23 at 18 50 06" src="https://github.com/geopython/pygeoapi/assets/1038897/0fe871c9-1650-4112-adbc-64a0a9711da9">

<img width="1440" alt="Screenshot 2024-02-23 at 18 50 11" src="https://github.com/geopython/pygeoapi/assets/1038897/7f736a9f-a217-4774-b6c6-4031c48316e1">

**Steps to Reproduce**

- Setup this [fork](https://github.com/doublebyte1/openlayers/tree/orderedAxes) of OpenLayers (see [this](https://github.com/openlayers/openlayers/issues/15521) issue for more details on why using this fork).
- Enable any of the pygeoapi layers, rendered using WGS84 (`MVT-elastic` or `MVT-tippecanoe` providers):

Vector tile layers:
https://emotional.byteroad.net/collections/hex350_grid_cardio_1920/tiles/WorldCRS84Quad
https://demo.pygeoapi.io/master/collections/lakes/tiles/WorldCRS84Quad

**Expected behavior**

<img width="1440" alt="Screenshot 2024-02-23 at 18 50 44" src="https://github.com/geopython/pygeoapi/assets/1038897/855c8260-cc3f-4992-b8dd-cd79eade8548">

**Comment by francbartoli** [comment]
@doublebyte1 is this a bug in pygeoapi? Do you know why leaflet displays the tiles properly?

**Comment by doublebyte1** [comment]
@francbartoli leaflet displays the tiles correctly, but it does not parse the tilematrixset. It just looks at the url template and displays it using a WebMercatorQuad tiling scheme (see example bellow).

`var pbfURL='http://localhost/collections/lakes-geographic/tiles/WebMercatorQuad/{z}/{x}/{y}?f=mvt';

 var pbfLayer=L.vectorGrid.protobuf(pbfURL,mapVectorTileOptions).on('click',function(e) {
     console.log(e.layer);
     L.DomEvent.stop(e);
 }).addTo(map); `

![leaflet-elastic-mvt](https://github.com/geopython/pygeoapi/assets/1038897/1a9db51c-38d7-4404-b5e7-14b7f816373c)

**Comment by doublebyte1** [comment]
It seems that both elasticsearch and tippecanoe are using a WebMercatorQuad tiling scheme. However, openlayers is still not able to display the tiles correctly (maybe it is assuming a certain tile size of the MVT file?)

![openlayers-mercator](https://github.com/geopython/pygeoapi/assets/1038897/4ba7a91a-957c-404a-83a9-5d474c910c19)

**Comment by doublebyte1** [comment]
@francbartoli I am going to close this issue, as it is not related to pygeoapi and maybe open another one on the openlayers repository.

**Comment by jerstlouis** [comment]
@doublebyte1 

> a certain tile size of the MVT file

a certain **grid** size
