### ISSUE TITLE
Remove the need of a tiling scheme parameter from configuration options for OGC API - Tiles

### ISSUE THREAD

**Issue by doublebyte1** [geopython/pygeoapi#1559]
**Description**
OGC API - Tiles offers a configuration parameter to describe the tiling scheme of the tiles provider.

https://github.com/geopython/demo.pygeoapi.io/blob/ce0a200e715a3422f2b229574e1f0c4ff7c1ab92/services/pygeoapi_master/local.config.yml#L149-165

There are a couple of issues with these approach:

- It may give the impression that the user can choose the tiling scheme, which is not the case. They can only choose from what the provider offers.
- Some providers only offer one specific tiling scheme and the user may not know what that it is. We can put that knowledge in the provider class, without having to rely on a user parameter.
- Currently, there is no mechanism to allow serving two tiling schemes, for a given collection (although that is shown in some examples).

**Steps to Reproduce**

- Configure a tile collection to use the two supported tiling schemes (WebMercatorQuad, WorldCRS84Quad). Try to obtain the tiles in the two different tiling schemes.
- Configure a tile collection with MVT-elastic provider to use the WorldCRS84Quad. Try to obtain tiles using WorldCRS84Quad.

**Expected behavior**

- MVT-elastic provider: there should not be any tiling scheme as parameter. MVT-elastic tiles are served using WebMercatorQuad and that should be on pygeoapi documentation.
- MVT-tippecanoe provider: there should not be any tiling scheme as parameter. pygeoapi should look for subfolders with the name of the tiling schemes and publish them. This should also be documented.
- MVT-proxy provider: as this provider is more generic, this case we would need the tiling-schemes configuration option.

**Comment by PascalLike** [comment]
I agree with the solution, it does not make much sense to have a parameter if there is no really a choice to make. From a user's point of view, we describe these providers with different examples in the documentation, so personally, I see no problem if the configuration is different from one provider to another.

**Comment by doublebyte1** [comment]
- [ ] Set MVT-elastic to always use WebMercatorQuad
- [ ] Double-check if MVt-tippecanoe supports other schemes
- [ ] Let MVT-proxy read this from a configuration parameter, as we are not sure what the proxy will have

**Comment by doublebyte1** [comment]
https://github.com/mapbox/tippecanoe/issues/770

**Comment by francbartoli** [comment]
thanks @doublebyte1, let's keep it optional if you don't mind

**Comment by doublebyte1** [comment]
TODOS:

- [ ] update demo config
- [ ] update docker examples
