### ISSUE TITLE
breadcrumb exception on TileMatrixSets

### ISSUE THREAD

**Issue by acikaz** [geopython/pygeoapi#1562]
**Description**
When clicking on Home / TileMatrixSets we get "Exception
could not find this tilematrixset"

**Screenshots/Tracebacks**
<img width="1767" alt="Screenshot 2024-02-28 at 13 07 51" src="https://github.com/geopython/pygeoapi/assets/52027726/76bdbd4b-743a-47dd-a4f9-03613949d42f">

**Environment**
 - OS:
 - Python version:
 - pygeoapi version:

**Additional context**

**Comment by PascalLike** [comment]
Fixed by https://github.com/geopython/pygeoapi/pull/1554
