### ISSUE TITLE
Graceful failure for xarray provider

### ISSUE THREAD

**Issue by sjordan29** [geopython/pygeoapi#1577]
**Is your feature request related to a problem? Please describe.**
I'm primarily working with the xarray provider. When I work with a pygeoapi config file contains many resources, but just a subset of them fail to properly generate the openapi, the entire process fails.

**Describe the solution you'd like**
 I think it would be useful to have the xarray provider (and possibly other providers as well) fail gracefully and issue/log a warning for a resource and then continue to the next one. This would make it easier to identify the data source(s) that need to be corrected, but also make it so that a single invalid dataset doesn't prevent the entire build process.

**Comment by tomkralidis** [comment]
@sjordan29 thanks for the report.  I've put forth #1585 to emit a warning on failing collections and carry on with the OpenAPI document generation.  Are you able to test the PR?  If it still fails, can you then provide an example configuration that would cause this issues you are running into?

**Comment by pvgenuchten** [comment]
What about a config flag to continue on failure, for some cases it may be critical all collections are valid

**Comment by tomkralidis** [comment]
Good idea as well @pvgenuchten.  Added to PR (default behaviour is to fail).

**Comment by sjordan29** [comment]
Great! Yes I will test

**Comment by sjordan29** [comment]
Hi @tomkralidis, this worked great for my use case.
