### ISSUE TITLE
apply to be an OSGeo community project

### ISSUE THREAD

**Issue by tomkralidis** [geopython/pygeoapi#159]
From https://wiki.osgeo.org/wiki/OSGeo_Community_Projects#Qualifying_As_An_OSGeo_Community_Project

> Your software project needs to meet the following criteria to be an OSGeo Community Project:
> 1. The technology in your software project should be geospatial (or directly support geospatial applications).
> 2. Your project should be open source and welcomes new contributions. If you don't have a license selected, we can help with that.

**Comment by kalxas** [comment]
https://lists.osgeo.org/pipermail/incubator/2019-June/003863.html

**Comment by kalxas** [comment]
I see we are missing a CONTRIBUTING.md file, which is recommended for OSGeo Community Projects.

**Comment by tomkralidis** [comment]
> I see we are missing a CONTRIBUTING.md file, which is recommended for OSGeo Community Projects.

Added in https://github.com/geopython/pygeoapi/pull/165 (thanks @kalxas)

**Comment by tomkralidis** [comment]
Done! https://lists.osgeo.org/pipermail/incubator/2019-June/003881.html
