### ISSUE TITLE
`get_collection_tile_items` not available in django mode, only `get_collection_tile_metadata` is being called

### ISSUE THREAD

**Issue by totycro** [geopython/pygeoapi#1595]
**Description**
The endpoint `collection_item_tiles` calls `get_collection_tiles_metadata` here, but it should be `get_collection_tiles_data`:
https://github.com/geopython/pygeoapi/blob/master/pygeoapi/django_/views.py#L348

This is fixed in the split-api-py branch since the code has to be touched there anyways, not sure if we need to fix it in master for now too.

**Environment**
 - OS:
 - Python version:
 - pygeoapi version: 0.16 / main

**Comment by doublebyte1** [comment]
@totycro thanks for spotting this! I addressed the issue on this PR: https://github.com/geopython/pygeoapi/pull/1601

In addition to the wrong method call, there is an issue with a parameter name on urls.py.
