### ISSUE TITLE
Adding `cftime` dependency for EDR

### ISSUE THREAD

**Issue by sjordan29** [geopython/pygeoapi#1609]
**Is your feature request related to a problem? Please describe.**
When I try to build for the EDR provider with xarray datasets with `cftime` times, they fail to build (or, using the graceful failure feature added recently, are excluded from the build). I'd like to add `cftime` as a dependency so I can included these datasets in our pygeoapi instance.

An example when I try to build with a dataset that has cftimes:

Failed to decode variable 'time': unable to decode time units 'days since 1961-01-01' with "calendar 'julian'". Try opening your dataset with decode_times=False or installing cftime if it is not installed.

**Describe the solution you'd like**
I believe all we'd need to do is add cftime to the provider requirements.

**Comment by tomkralidis** [comment]
Thanks @sjordan29.  I would support adding cftime to `requirements-provider.txt`.  Please feel free to issue a PR.
