### ISSUE TITLE
Add CONTRIBUTING.md file

### ISSUE THREAD

**Issue by kalxas** [geopython/pygeoapi#162]
I propose adding a CONTRIBUTING file to the git repository to show we are open to accepting contributions. Thougths?

**Comment by jodygarnett** [comment]
I have noted a few projects using pull request templates which can also help. They key thing is that a link to this file is provided when new contributors make a pull request. (So if they or their employer later complain you can say you provided some notice)

**Comment by kalxas** [comment]
Thanks @jodygarnett for the feedback
