### ISSUE TITLE
PostgreSQL provider does not support datetime

### ISSUE THREAD

**Issue by tomkralidis** [geopython/pygeoapi#1622]
**Description**
The PostgreSQL provider does not handle `datetime_` inputs as part of its [`query`](https://github.com/geopython/pygeoapi/blob/master/pygeoapi/provider/postgresql.py#L114) function (even though we advertise support for same in [docs](https://docs.pygeoapi.io/en/latest/data-publishing/ogcapi-features.html#providers)).

**Steps to Reproduce**
Assuming a PostgreSQL time enabled resource in pygeoapi config, execute an OGC API - Features items query with `.../items?datetime=t1`

**Expected behavior**
datetime support should be handled accordingly in the PostgreSQL provider.

**Screenshots/Tracebacks**

**Environment**
 - OS: all
 - Python version: all
 - pygeoapi version: all

**Additional context**
Thanks to @david-i-berry for reporting.

cc @KoalaGeo

**Comment by KoalaGeo** [comment]
We've been doing datetime filters using CQL like: 

1. https://ogcapi.bgs.ac.uk/collections/sensor-water-level-sta/items?f=json&limit=5&sortby=-resulttime&properties=resulttime,result,location_name
2. https://ogcapi.bgs.ac.uk/collections/sensor-water-level-sta/items?f=json&limit=5&filter=resulttime%20BEFORE%202024-04-06T22:30:00Z&sortby=-resulttime&properties=resulttime,result,location_name
3. https://ogcapi.bgs.ac.uk/collections/sensor-water-level-sta/items?f=json&limit=5&filter=resulttime%20AFTER%202024-04-07T22:30:00Z&sortby=-resulttime&properties=resulttime,result,location_name

**Comment by tomkralidis** [comment]
The equivalent queries using the `datetime` parameter would be:

1. https://ogcapi.bgs.ac.uk/collections/sensor-water-level-sta/items?f=json&limit=5&sortby=-resulttime&properties=resulttime,result,location_name (same)
2. https://ogcapi.bgs.ac.uk/collections/sensor-water-level-sta/items?f=json&limit=5&datetime=../2024-04-06T22:30:00Z&sortby=-resulttime&properties=resulttime,result,location_name
3. https://ogcapi.bgs.ac.uk/collections/sensor-water-level-sta/items?f=json&limit=5&datetime=2024-04-07T22:30:00Z/..&sortby=-resulttime&properties=resulttime,result,location_name

**Comment by KoalaGeo** [comment]
So it does work? We're using the postgres provider for this data...

**Comment by tomkralidis** [comment]
1. same request, so works
1. returns `The requested URL was rejected. Please consult with your administrator.`.  I am guessing there is something before pygeoapi that is returning this error (likely the `../` in the URL)
1. returns `Configured times should be RFC3339` error

**Comment by KoalaGeo** [comment]
2. Is allowed through now (pedantic F5....) now same error as 3.

**Comment by tomkralidis** [comment]
FYI @david-i-berry has a fix and will test/issue a PR in the next few days (thanks Dave).

**Comment by webb-ben** [comment]
Related to https://github.com/geopython/pygeoapi/discussions/1607
