### ISSUE TITLE
Are conformance class links supposed to resolve?

### ISSUE THREAD

**Issue by ShaneMill1** [geopython/pygeoapi#1637]
**Description**
It doesn't appear that all of the conformance class links resolve

**Steps to Reproduce**
Looking at conformance classes for Features: https://github.com/geopython/pygeoapi/blob/master/pygeoapi/api/itemtypes.py#L81, a url that does resolve is:
http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/core

A url that does not resolve is:
https://www.opengis.net/spec/ogcapi-features-3/1.0/conf/queryables, it just returns "Not Found"

**Expected Behavior**

I would expect all of the conformance links to resolve

**Comment by tomkralidis** [comment]
Thanks @ShaneMill1. pygeoapi implements both the approved/ratified standards as well as those in draft.  Conformance links are not created on infrastructure until a given standard is fully approved, so this is expected from a pygeoapi viewpoint (as simply implemementing a draft standard).

Let me know if that helps @ShaneMill1.  Closing this issue for now.
