### ISSUE TITLE
generate openapi, if not available during server start

### ISSUE THREAD

**Issue by pvgenuchten** [geopython/pygeoapi#1650]
**Is your feature request related to a problem? Please describe.**

if one runs `pygeoapi serve` without the open api document being generated, or env variable not set, the following error is thrown:

```
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Describe the solution you'd like**

- [x] Provide a better error to user: 'please initialise open api document first'
- [ ] Generate the actual document if detected it is not available (or out of date)

**Comment by tomkralidis** [comment]
@pvgenuchten PR in #1758 for your review.  Note that "automatic" OpenAPI generation is not implemented (IMHO would be safer to have this as an offline process overall).
