### ISSUE TITLE
Allow using sqlalchemy > 2

### ISSUE THREAD

**Issue by ricardogsilva** [geopython/pygeoapi#1661]
Now that [pygeofilter supports sqlalchemy v2](https://github.com/geopython/pygeofilter/issues/67), and with the changes merged in #1520, it seems pygeoapi can now lift the current restriction on using sqlalchemy<2, as seen in:

https://github.com/geopython/pygeoapi/blob/6c31a8e371d10750f265357bab62b45bfa9abc8f/requirements.txt#L17

This is related to #1123, but I am not able to re-open it - feel free to close this and re-open that if appropriate.

**Comment by tomkralidis** [comment]
cc @kalxas 

@ricardogsilva as discussed a couple of weeks ago, looks like SQLAlchemy is still at 1.x on [jammy](https://packages.ubuntu.com/jammy/python3-sqlalchemy).  We'll need to monitor accordingly and update once we have some updates from upstream.

**Comment by ricardogsilva** [comment]
@tomkralidis 

Just a small nitpick, current Ubuntu LTS is now 24.04 (Noble Numbat) - but your point is still valid, the `python3-sqlalchemy` package is still at version 1.4.50 as per:

https://packages.ubuntu.com/noble/python3-sqlalchemy

According to [sqlalchemy docs](https://docs.sqlalchemy.org/en/14/changelog/migration_20.html#overview), v1.4 is compatible with version 2 and in #1520 I had already fixed existing sqlalchemy transition to v2 warnings in the codebase.

This to say that I think we are now in a position whete it is possible to simply remove the `sqlalchemy<v2` pin in our requirements files and things should work OK both on Ubuntu LTS, as per RFC2 and would also allow other installs to move forward with using sqlalchemy v2+.

When I find some time I will check whether everything works OK with the pin removed, most likely by trying to run the test suite inside some ubuntu:24.04 container.

**Comment by kalxas** [comment]
keeping this one open
