### ISSUE TITLE
bbox does not work correctly

### ISSUE THREAD

**Issue by ksonda** [geopython/pygeoapi#1665]
**Description**
The bbox filter appears to intersect the provided bbox with the bboxes of features in the queries collection, rather than the actual geometries of the feature collection

**Steps to Reproduce**

1. Create a bbox a,b,c,d that is within the bbox of a test feature, but does not actually intersect the feature
2. Query the collection/{collectionId}/items?bbox=a,b,c,d

**Expected behavior**
The test feature should not be returned

**Screenshots/Tracebacks**
https://geoapi.geoplatform.gov/collections/62e48e3e_c8e9_4d48_990b_44dbb8265dd0/items?bbox=-111.020099,44.956318,-110.953495,44.971865

from this bbox

![image](https://github.com/DOI-USGS/nhdplusTools/assets/44071350/9573c35a-64fe-43a3-a145-e60118421109)

**Comment by webb-ben** [comment]
Same as https://github.com/geopython/pygeoapi/issues/1666
