### ISSUE TITLE
Pass extra parameters to requests to allow for custom behaviour down the line

### ISSUE THREAD

**Issue by Moritz-Langer** [geopython/pygeoapi#1667]
**Is your feature request related to a problem? Please describe.**
For some requests there might be a need custom behaviour. This can be implemented using extra parameters in the request which are evaluated later on in providers or plugins. If they're not passed to the request nothing happens. When for example &foo=bar is added to the request this should be available in a dictionary passed to the providers for additional functionality. 
  

**Describe the solution you'd like** 
Request can be in the form http://localhost:8080/collections/lakes/items?&foo=bar
and a dictionary containing 'foo':'bar' is avaialable in the providers. 

**Describe alternatives you've considered**

**Additional context**
@tomkralidis @totycro we talked about this at the vienna code sprint.

**Comment by francescoingv** [comment]
@Moritz-Langer
what about the possibility for the API to validate the input parameters against the metadata?

Could you please describe a more detailed use-case for such a need?
I don't see the reason for not advertising in the `metadata` about the ability for the process to accept the "extra parameters",
which in this case would be optional (not required).

**Comment by Moritz-Langer** [comment]
Do you mean the metadata of the table behind the collection? 
A Use-Case:
we have a filter for a maximum area for queries with bbox. This makes sense, since some layers might contain a lot of features and they should not be queried at every zoom level and it should not be allowed to, for example query all land properties for the entire USA. However there are certain cases where we want this to happen. Then there might be a parameter passed to the request that could be called `allow_big_bbox`. This can not be found in the Database Table but can be attached with functionality in a plugin.

There are certainly more use cases, but this one illustrates the problem.

**Comment by francescoingv** [comment]
@Moritz-Langer 
Sorry, I was focused on process only, and missed to view the bigger picture for the other specification.

I would better rephrase my question: what are the ogc-api specifications involved in your isssue?
