### ISSUE TITLE
Links in home of pygeoapi refer to "localhost"

### ISSUE THREAD

**Issue by francescoingv** [geopython/pygeoapi#1668]
**Description**
The links present in http://**my_server_ip**:5000/
start with http://**localhost**:5000/...

**Steps to Reproduce**
Follow directions in [pygeoapi.io](https://pygeoapi.io/) **Install in 5 minutes** on a PC with IP `my_server_ip`.
From a different PC open a browser and call `http://**my_server_ip**:5000/`
Follow any link in the page will have unexpected results as it point to **localhost** instead of **my_server_ip**.

**Expected behavior**
I expected all the links refer to `http://**my_server_ip**:5000/`.

**Context**
I wanted to make a demo from one PC pointing to my development PC (which could be any server).

**Comment by tomkralidis** [comment]
The 5 minute install instructions assume a light and easy install on one's local machine (localhost).  The configuration's `server.url` directive needs to be updated to match its deployment, which in the default configuration is `http://localhost:5000`), and can be changed accordingly.
