### ISSUE TITLE
Translate static texts

### ISSUE THREAD

**Issue by CeciliaPH** [geopython/pygeoapi#1681]
**Description**
This is not a bug, it is just a aesthetic detail. There are some texts in this page without the {trans} label.
Line 8
Line 35

(https://github.com/geopython/pygeoapi/blob/master/pygeoapi/templates/collections/index.html)

**Additional context**
I would have done a pull request adding them, but I am not sure if it would have any effect on the locale templates, if the string is not found.

**Comment by tomkralidis** [comment]
Thanks @CeciliaPH. PR in #1687
