### ISSUE TITLE
Error unable to find 'properties' key with ElasticSearch provider

### ISSUE THREAD

**Issue by ccancellieri** [geopython/pygeoapi#1684]
Hi I'm having problems with the from the ElasticSearch provider not finding the 'properties' key (nested two times, see link below) in the source data dict.

https://github.com/geopython/pygeoapi/blob/f978d0a1f6d9628da24348975747d9e0e21c4ef9/pygeoapi/provider/elasticsearch_.py#L124C17-L124C80

The source data from ElasticSearch has been loaded using Kibana and consists in the attached
[geojson.json](https://github.com/user-attachments/files/15839145/geojson.json)

**The code which is now working is below, but I'm wondering why if it was intentional and if I'm doing something wrong:**
```
try:
            if '*' not in self.index_name:
                p = ii[self.index_name]['mappings']
            else:
                LOGGER.debug('Wildcard index; setting from first match')
                index_name_ = list(ii.keys())[0]
                p = ii[index_name_]['mappings']
        except KeyError:
            LOGGER.warning('Trying for alias')
            alias_name = next(iter(ii))
            p = ii[alias_name]['mappings']
        except IndexError:
            LOGGER.warning('could not get fields; returning empty set')
            return {}
 
        for k, v in p['properties'].items():
            if 'type' in v:
                if v['type'] == 'text':
                    fields_[k] = {'type': 'string'}
                elif v['type'] == 'date':
                    fields_[k] = {'type': 'string', 'format': 'date'}
                elif v['type'] in ('float', 'long'):
                    fields_[k] = {'type': 'number', 'format': v['type']}
                else:
                    fields_[k] = {'type': v['type']}
 
        return fields_
```

**Comment by tomkralidis** [comment]
The code in https://github.com/geopython/pygeoapi/blob/f978d0a1f6d9628da24348975747d9e0e21c4ef9/pygeoapi/provider/elasticsearch_.py#L124 is "double nesting" properties of the mappings, not the actual GeoJSON data.

The test data attached in this is of a feature collection, not a feature.  From [the docs](https://docs.pygeoapi.io/en/latest/data-publishing/ogcapi-features.html#elasticsearch):

> To publish an Elasticsearch index, the following are required in your index:
> 
> indexes must be documents of valid GeoJSON Features
> 
> index mappings must define the GeoJSON geometry as a geo_shape
