### ISSUE TITLE
add support for item schema string format

### ISSUE THREAD

**Issue by tomkralidis** [geopython/pygeoapi#1691]
**Is your feature request related to a problem? Please describe.**
For itemtypes, add JSON schema string/format addition/support

**Describe the solution you'd like**
Add the JSON Schema string`format` property to `/queryables` and `schema` responses if defined by the provider.

**Describe alternatives you've considered**
None

**Additional context**
cc @KoalaGeo

**Comment by pvgenuchten** [comment]
is this somehow related to the open api description? Maybe the openapi description can point to this location to retrieve the schema of the item? (assuming this link is not available yet)

**Comment by tomkralidis** [comment]
@pvgenuchten the OpenAPI generation uses the same provider functionality, so outputs to `.../schema` and OpenAPI data schemas are then consistent.

**Comment by KoalaGeo** [comment]
Is there an underlying issue with some datatypes not supported including `timestamp`. See https://github.com/geopython/pygeoapi/issues/1695

**Comment by tomkralidis** [comment]
Will continue in #1695

**Comment by tomkralidis** [comment]
> Hi [@tomkralidis](https://github.com/tomkralidis),
> 
> We've be experimenting with including nested JSON objects in pygeoapi, eg responsible persons as a JSON.
> 
> However, it appears the data type JSON isn't supported.
> 
> `[2025-03-18T13:46:02Z] {/pygeoapi/pygeoapi/provider/postgresql.py:243} WARNING - Unsupported column type JSON `
> 
> Is this something that could be added?

@KoalaGeo see #1975 for PR/update.
