### ISSUE TITLE
Paging links for geojson lack bbox parameter (if requested)

### ISSUE THREAD

**Issue by thijsbrentjens** [geopython/pygeoapi#170]
When testing the ```bbox``` param I noticed that the paging links at the bottom of the geoJSON response don't contain the ```bbox``` param from the request. I would expect that this param is repeated there (maybe just as the ```limit``` parameter is, if explicitly provided). ```startindex``` seems to be accounted for.

Example request: 
[https://demo.pygeoapi.io/master/collections/ogr_addresses_gpkg/items?limit=10&bbox=5.692,52.091,5.854,52.112&f=json](https://demo.pygeoapi.io/master/collections/ogr_addresses_gpkg/items?limit=10&bbox=5.692,52.091,5.854,52.112&f=json)

**Comment by justb4** [comment]
Good find! Think this is a general problem with `links`: some parameters from the original request are not passed in `links` section. e.g. if we later support an attribute filter or `time` parameter, these won't be passed as well I suspect.

**Comment by tomkralidis** [comment]
Is this issue still valid?  I'm seeing the `bbox` parameter in the demo (perhaps since fixed?).

**Comment by thijsbrentjens** [comment]
Yes, they are there now. Can be closed now
