### ISSUE TITLE
Unconsistent return response object for delete_job() method in pygeoapi.api.processes

### ISSUE THREAD

**Issue by francescoingv** [geopython/pygeoapi#1721]
**Description**
While preparing a test for a new process manager
when the following methods were called succesfully and with query parameter `f=json`,
I found the method `pygeoapi.api.processes.delete_job()` returns as third item (`response`) an **object**,
while the other methods used by process, namely: `pygeoapi.api.processes.execute_process()`, `pygeoapi.api.processes.get_jobs()`, `pygeoapi.api.processes.get_job_result()`,
returns a **string representation of an object** in JSON format.

I believe **this is not consistent**.

**Steps to Reproduce**
Submit the following method calls and check the content of each `response` varaible:
- headers, http_status, response = processes_api.execute_process(api_, req, process_id)
- headers, http_status, response = processes_api.get_jobs(api_, req, job_id)
- headers, http_status, response = processes_api.get_job_result(api_, req, job_id)
- headers, http_status, response = processes_api.delete_job(api_, req, job_id)

**Expected behavior**
When the methods are called with the query parameter `f=json`,
I expected all methods to return as `response` a string in JSON format.

At least running `pygeoapi` using `Flask`,
the result is hidden by the framework converting by default the returned object to the corresponding JSON a string.
However this is not how I understand the API should work.

**Environment**
 - OS:
 - Python version: 11
 - pygeoapi version: 0.18

**Additional context**
While it would be simple to substitute the line 558 of `pygeoapi.api.processes.py`:
    `return {}, http_status, response`
with
    `return {}, http_status, json.dumps(response)`

I wonder if it could impact any actual code, and how to mitigate the impact.

**Comment by tomkralidis** [comment]
@francescoingv thanks for the report.  PR in #1726.
