### ISSUE TITLE
pygeoapi allows the registration of invalid EDR queries

### ISSUE THREAD

**Issue by webb-ben** [geopython/pygeoapi#1773]
**Description**
pygeoapi allows you to register any function to `@BaseEDRProvider.register()`, and will generate relative links for any edr provider that is registered. However when you try to navigate to the query itself, you receive an uninformative error - collection not found. This is because instead of finding the query, pygeoapi tries to find the collection that is named `COLLECTON_NAME/EDR_QUERY_TYPE`

**Steps to Reproduce**
1. Create plugin with an EDR query that doesnt exist:
```
    @BaseEDRProvider.register()
    def location(self, **kwargs):
         pass
```
2. Visit the collection page, and try to navigate to the offered EDR query

3. View the error, collection not found. That is because it is looking for the collection named `RISEEDR/location` instead of the locaation query of the RISEEDR provider

**Expected behavior**
pygeoapi does not allow the registration of invalid EDR query types, and throws an informative error when someone tries to register a query that is not valid.

**Screenshots/Tracebacks**
![image](https://github.com/user-attachments/assets/a365cdc7-71b6-4f65-941f-5cdad03d512f)
![image](https://github.com/user-attachments/assets/fb1578b2-9887-47da-8ce9-5e01857ef4b6)

**Environment**
 - OS: Mac
 - Python version: 3.10
 - pygeoapi version: 0.18.dev0

**Additional context**
cc @C-Loftus

**Comment by tomkralidis** [comment]
This is rooted in pygeoapi defining the EDR routes (in Flask/etc.) explicitly.  When a "foreign" query type is defined in an EDR provider (say `foo`) , Flask does not resolve the route, which causes Flask/pygeoapi to think the `collection/foo` is a hierarchical collection.  It makes sense to constrain EDR providers, then, to bind to query types defined exclusively in the standard.
