### ISSUE TITLE
Replace all references to access controlled map tiles

### ISSUE THREAD

**Issue by whatnick** [geopython/pygeoapi#1777]
**Description**
#697 Changes default background to OSM in one instance , there are still many references to wikimedia maps (11 from search of codebase). These should be bulk replaced to use OSM XYZ tile source.

**Steps to Reproduce**
Search code base for `https://tile.openstreetmap.org/{z}/{x}/{y}.png` - [result](https://github.com/search?q=repo%3Ageopython%2Fpygeoapi%20maps.wikimedia.org&type=code)

**Expected behavior**
Default map source is consistent.

**Screenshots/Tracebacks**
See previous issue #567 

**Environment**
 - OS: All
 - Python version: 3.10.12
 - pygeoapi version: 0.16.1

**Additional context**
The reference to old map source exists when config is generated via templating tool / docs.

**Comment by tomkralidis** [comment]
Thanks for reporting @whatnick.  PR in #1778.  Additional updates per below:
- https://github.com/geopython/demo.pygeoapi.io/commit/15d0dc79f9ecf02275f5188eb9473012db421a56
- https://github.com/geopython/pygeoapi-examples/commit/9547dd0a6edc34727042dfcc226794d9ff6730fe
- https://github.com/geopython/diving-into-pygeoapi/commit/37e99287f2e72da689b58bcc00b3f02f73f2b258
