### ISSUE TITLE
how are multiple ogc-api's combined in a single product?

### ISSUE THREAD

**Issue by pvgenuchten** [geopython/pygeoapi#179]
Current approach in pygeoapi seems:

pygeoapi
> - collections -> oapi features 
> - processes -> oapi processes
> - api
> - conformance

In that scenario /conformance and /api would need to list all supported conformance classes of all supported oapi's, with a high risk of name collision. This happens already for the suggested oapi-coverages, which also suggests to use /collections as a first level

The alternative approach to have a separate endpoint for each oapi is less efficient.

pygeoapi
>- features  
>> - api
>> - conformance
>> - collections
> - processes 
>> - api
>> - conformance
>> - processes
> - coverages
>> - api
>> - conformance
>> - collections
>>> - coverages
>>>> - bands

**Comment by pvgenuchten** [comment]
after some discussion at https://gitter.im/opengeospatial/WFS_FES I know understand that the first approach is intended behaviour of OGC, it means that /collections will contain both feature collections as well as coverage collections and /api and /conformance will contain methods and properties of all supported oapi's

**Comment by jorgejesus** [comment]
IMHO dont like the scenario of having `/conformance`  mixing `processes` and `coverages`. Separated endpoints for each oapi is also easier to implement in `Flask` using bluesprints

**Comment by pvgenuchten** [comment]
Please discuss this aspect at the London sprint @jorgejesus

**Comment by pvgenuchten** [comment]
Closing this, pygeoapi implements what is suggested by ogc api common: a single endpoint mixing various service types
