### ISSUE TITLE
using startindex gives an error: Can't convert 'int' object to str implicitly

### ISSUE THREAD

**Issue by jorgejesus** [geopython/pygeoapi#18]
Using the following link: (sqlite provider and countries)
[http://localhost:5000/collections/countries/items/?startindex=10](http://localhost:5000/collections/countries/items/?startindex=10)

Gives error
`
File "/home/jesus/tmp/pygeoapi/pygeoapi/pygeoapi/views.py", line 260, in get_features
    next_ = startindex + settings['server']['limit']
    TypeError: Can't convert 'int' object to str implicitly
`

**Comment by tomkralidis** [comment]
@jorgejesus fixed in master.  Can you validate?
