### ISSUE TITLE
PyGeoAPI WFS 3 Gazetteer

### ISSUE THREAD

**Issue by geekdenz** [geopython/pygeoapi#185]
If my information sources are correct, PyGeoAPI has a WFS 3 implementation and/or is working on it.
My employer is very keen on standards and joining efforts where possible. Would you consider incorporating a WFS 3 extension in PyGeoAPI that is a Gazetteer? Does that even make sense? Any constructive thought on this is much appreciated.

It could for example be an extension that is just a convenience service on top of Nominatim. I managed to get that working vs Pelias which I had problems configuring.

**Comment by justb4** [comment]
@geekdenz yes, that is right PyGeoAPI has a WFS 3 implementation, but in general aims to implement other upcoming OGC REST/OpenAPI standards as in https://github.com/opengeospatial/oapi_common.
The "old" WFS used to define a [Gazetteer API](http://www.opengeospatial.org/projects/groups/wfsgaz1.0swg) but I think this was never used. I don't know if something is planned for the upcoming OGC OAS APIs.

I know Nominatim, very powerful, with a specific API, first question is what you mean with "WFS 3 extension":

* mapping `pygeoapi` WFS 3 requests to a Nomintim backend (Provider)?
* extending the OGC WFS 3 API standard with Gazetteer endpoints?
* other

For the first: yes I can see that one could view addresses as a Feature Collection (or even map to OSM XAPI), but you would miss out on some of the powerful, wildcard freeform searches of Nominatim. Also for reverse geocoding: WFS 3 only has bbox query (for now), not yet point-query.

For the second: that could/would be an extension to the [WFS 3 Standard](https://github.com/opengeospatial/WFS_FES), or a complete new API.

You may also want to discuss this at the Gitter rooms: [pygeoapi](https://gitter.im/geopython/pygeoapi) or [OGC WFS 3 Standard](https://gitter.im/opengeospatial/WFS_FES).

**Comment by geekdenz** [comment]
@justb4 Sorry for not engaging in this sooner..

I found another gazetteer called Photon:
http://photon.komoot.de/

It actually seems easier to setup than Pelias and supports partial matches, which Nominatim does not. It uses a very similar API to Nominatim. It's backed by OSM and ElasticSearch, similar to Pelias. I found Pelias is quite heavy and I couldn't get it working properly for our use case.

I am generally interested in PyGeoAPI. I've actually been to the WFS 3 Hackathon in Fort Collins last year and met some very interesting people there. At the time I implemented a client. Later I implemented a WFS 3 prototype in TypeScript, NodeJS and ExpressJS:
https://bitbucket.org/heuert-landcare/wfs3/src/master/

It is merely an old WFS 3 implementation on top of WFS 2 which is probably not up-to-date.

However, I know Python well and would be happy to contribute to PyGeoAPI in ways that I can. If not with a gazetteer proxy, maybe something else makes more sense.

There is an upcoming FOSS4G Oceania in Wellington, 2 hours drive from where I live. I will most likely be there and am still wondering if I can present something useful. Maybe something to do with PyGeoAPI would be good. Any ideas welcome.

Sorry, I'm probably off-topic and violating the code of conduct.. But hopefully can be of help.

**Comment by justb4** [comment]
@geekdenz no sweat! You are very welcome for contributing in whatever way (from coding to documentation, testing, presenting) to pygeoapi. For discussion not directly issue-related the pygeoapi-team and -users use the pygeoapi Gitter room at: https://gitter.im/geopython/pygeoapi . If you want to present pygeoapi, we have a ready set of slides at: https://pygeoapi.io/presentation/ you can use.

Gazetteer in pygeoapi: you can propose what your aim is given the above discussion. `pygeoapi` is more than just WFS v3 (now rebranded as 'OGC API - Features') we plan to implement a number of OGC APIs. If it is an extension to the OGC OAS APIs standards, then the standards Gitter room is more suitable: https://gitter.im/opengeospatial/WFS_FES . If you've been in Ft Collins many names there may be familiar to you.

Gazetteer backends: indeed Photon is powerful and GeoJSON-based. In another project, [Wegue](https://github.com/meggsimum/wegue) (Vue.js with OpenLayers), I am using Photon as one of the backends (next to Nominatim and [OpenCage](https://opencagedata.com)) in a Vue.js/OpenLayers Geocoder widget [I am working on](https://github.com/meggsimum/wegue/issues/29) right now..

**Comment by francbartoli** [comment]
@geekdenz @justb4 does this have tight relations with the search/query feature of OGC API Features? It might be a possible backend for that imho

**Comment by justb4** [comment]
@francbartoli not yet familiar with *search/query feature of OGC API Features*, thought that was under standardization and subject for the [upcoming code sprint](https://forms.gle/NBsC5j4vaDv59jT4A).

**Comment by geekdenz** [comment]
Gazetteers are difficult and there are other projects that do this well and support GeoJSON formats such Nominatim and Photon. I think this is out of scope for PyGeoAPI and therefore I close this issue for now.
