### ISSUE TITLE
Conformance links for Processes are missing

### ISSUE THREAD

**Issue by francbartoli** [geopython/pygeoapi#198]
**Description**
At the `/conformance` endpoint there should be added more links for the OGC API - Processes (former WPS REST Binding) as below:

```
"http://www.opengis.net/spec/WPS/2.0/req/service/binding/rest-json/core",
"http://www.opengis.net/spec/WPS/2.0/req/service/binding/rest-json/oas30",
"http://www.opengis.net/spec/WPS/2.0/req/service/binding/rest-json/html"
```

**Steps to Reproduce**
curl -XGET https://demo.pygeoapi.io/master/conformance?f=json

**Expected behavior**

```json
{
    "conformsTo": [
        "http://www.opengis.net/spec/wfs-1/3.0/req/core",
        "http://www.opengis.net/spec/wfs-1/3.0/req/oas30",
        "http://www.opengis.net/spec/wfs-1/3.0/req/html",
        "http://www.opengis.net/spec/wfs-1/3.0/req/geojson",
        "http://www.opengis.net/spec/WPS/2.0/req/service/binding/rest-json/core",
        "http://www.opengis.net/spec/WPS/2.0/req/service/binding/rest-json/oas30",
        "http://www.opengis.net/spec/WPS/2.0/req/service/binding/rest-json/html"
    ]
}
```

**Screenshots/Tracebacks**

**Environment**
 - OS: Mac OS
 - Python version: 
 - pygeoapi version: master

**Additional context**
#179 is relevant, OGC API Hackathon has figured out that conformance classes should be combined for multiple specifications implemented by a single server

**Comment by jorgejesus** [comment]
@francbartoli  Is this ticket still valid have the idea that nothing was decided and that we have to wait for a WPS3.0 spec

**Comment by francbartoli** [comment]
The spec seems to be in progress with updates, also the name was aligned to the new name convention https://github.com/opengeospatial/wps-rest-binding/commit/d2b4105eefaa4d14c3359c88e55234ce52a8f8dc. 
I wouldn't say it's not valid even if the repo name is still the old one. Maybe we can change the tag of the issue?
