### ISSUE TITLE
normalize communications

### ISSUE THREAD

**Issue by tomkralidis** [geopython/pygeoapi#201]
We need consistent verbage (tagline, about pygeoapi, etc.), etc. to update various websites.

- [x] complete text
- [x] update various web presence
  - [x] [website](https://pygeoapi.io)
  - [x] [OSGeo page](https://www.osgeo.org/projects/pygeoapi)
  - [x] [presentation](https://pygeoapi.io/presentation)
  - [ ] other?

**Comment by tomkralidis** [comment]
pygeoapi - an OGC API to geospatial data

pygeoapi is a Python server implementation of the OGC API suite of standards.  The project emerged as part of the next generation OGC API efforts in 2018 and provides the capability for organizations to deploy an RESTful OGC API endpoint using OpenAPI, GeoJSON, and HTML.

- Easy to install: install a full implementation via pip, UbuntuGIS
- Easy to deploy: via UbuntuGIS or the official Docker image
- Flexible: built on a robust plugin framework
  - connect to custom data types
  - serve custom output formats
  - implement custom process and workflows
  - deploy via Flask, Django, or any Python framework
- Compliant: passes OGC Compliance testing

@kalxas / @justb4 / @jorgejesus / @pvgenuchten and others: comments/suggestions appreciated.

**Comment by justb4** [comment]
Good text, some suggestions:

* *pygeoapi - an OGC API to geospatial data* --> *pygeoapi - OGC APIs to geospatial data* ?
* add ref/link to "OGC API suite of standards"
* *connect to custom data types* --> *connect to custom data sources (files, services, DBs)*
* *implement custom process and workflows* --> *implement custom processes and workflows*
* Add "OSGeo Community Project" ?

(Did not know `pygeoapi` avail in UbuntuGIS, dood work @kalxas !)

**Comment by alexandreleroux** [comment]
Would it be pertinent to indicate which OGC API standards pygeoapi supports (such as OGC API Features)? 

Might not be pertinent though if pygeoapi's intention is to support all of them!

**Comment by tomkralidis** [comment]
@justb4 thanks.  Updated text below.  Note that for 'OGC API suite of standards', once more authoritative links surface we can update.  I put the foundational OGC blogpost link for now.

pygeoapi - an OGC API to geospatial data

pygeoapi is a Python server implementation of the [OGC API suite of standards](https://www.opengeospatial.org/blog/2996).  The project emerged as part of the next generation OGC API efforts in 2018 and provides the capability for organizations to deploy an RESTful OGC API endpoint using OpenAPI, GeoJSON, and HTML.

- Easy to install: install a full implementation via pip, UbuntuGIS
- Easy to deploy: via UbuntuGIS or the official Docker image
- Flexible: built on a robust plugin framework
  - connect to custom data sources (files, services, databases, etc.)
  - serve custom output formats
  - implement custom processes and workflows
  - deploy via Flask, Django, or any Python framework
- Compliant: passes OGC Compliance testing
- OSGeo Community Project

**Comment by tomkralidis** [comment]
@alexandreleroux thanks and good point. We're aiming to support all the APIs as a long term target.  Having said this, as part of documentation we will provide a feature matrix on standards supported.

**Comment by jorgejesus** [comment]
Fast comment: deploy via Flask, or any other Python webframeowork

**Comment by tomkralidis** [comment]
Thanks @jorgejesus ; updated.
