### ISSUE TITLE
Schema.org links should use HTTPS

### ISSUE THREAD

**Issue by jorgejesus** [geopython/pygeoapi#210]
**Description**
On template folder files we have schema.org annotations that use links with HTTP. If we run pygeoapi on HTTPS the browser will report mixed content. In case we run pygeopai as HTTP it will not be a problem to use links with HTTPS

**Steps to Reproduce**
For examples: Look at `templates/items.html` file an find:
 `itemtype="http://schema.org/Dataset`

**Expected behavior**
it should be: `itemtype="https://schema.org/Dataset`
**Screenshots/Tracebacks**

**Environment**
 - OS: All
 - Python version: 3.7.4 
 - pygeoapi version:  master - 0.6.0

**Additional context**

**Comment by pvgenuchten** [comment]
Most microdata examples use http, but https is also valid (at least in ggl validator), even this seems supported:

```
<li itemprop="distribution" itemscope itemtype="//schema.org/DataDownload">
```
