### ISSUE TITLE
collection detail page has wrong link in schema.org/includedInDataCatalog

### ISSUE THREAD

**Issue by pvgenuchten** [geopython/pygeoapi#213]
It should reference the pygeoapi main page (or collections page)

![image](https://user-images.githubusercontent.com/299829/63591729-e432e480-c5af-11e9-9ea7-aa08c6898597.png)

**Comment by jorgejesus** [comment]
Fixed #210  also looking at this
The collections page is considered a catalog:
 ```<section id="collections" itemscope itemtype="//schema.org/DataCatalog">```

now collection detail page points to the collection page (includedInDataCatalog)

@pvgenuchten Shouldnt the collection page also have a "includedInDataCatalog" to the pygeopai main page ??
