### ISSUE TITLE
add pygeoapi to OSGeoLive

### ISSUE THREAD

**Issue by tomkralidis** [geopython/pygeoapi#218]
[OSGeoLive](https://live.osgeo.org) provides an easy, isolated approach to spinning up a VM with numerous  FOSS4G tools.  We should add pygeoapi to OSGeoLive to make pygeoapi more available to wide user base.

**Comment by tomkralidis** [comment]
Application submitted to OSGeoLive mailing list: https://lists.osgeo.org/pipermail/osgeolive/2020-September/014746.html

**Comment by tomkralidis** [comment]
Application accepted: https://lists.osgeo.org/pipermail/osgeolive/2020-September/014753.html

Next steps are to provider an installer and overview/quickstart documentation.

**Comment by kalxas** [comment]
I have started working on an installer, while 0.8.0 is already in the OSGeoLive nightly ppa.
