### ISSUE TITLE
pygeoapi.io website is down

### ISSUE THREAD

**Issue by alexandreleroux** [geopython/pygeoapi#219]
In the project's GitHub description ( https://github.com/geopython/pygeoapi ), there's a link to https://pygeoapi.io , which doesn't answer at the moment (either in http or https) and has been down at least for several hours.

**Comment by justb4** [comment]
There appear to be DNS problems with our (domain/DNS) provider, seen for several domains, not just pygeoapi.io, also depends from where on the internet you access.

**Comment by justb4** [comment]
should be solved now, DNS problems not been seen last few days..closing, @alexandreleroux : re-open if still problem for you.

**Comment by alexandreleroux** [comment]
thanks @justb4 , I confirm https://pygeoapi.io/ now works for me
