### ISSUE TITLE
Error handling favicon.ico when SCRIPT_NAME is used

### ISSUE THREAD

**Issue by francbartoli** [geopython/pygeoapi#226]
**Description**
Deploy with Docker and SCRIPT_NAME variable set is causing a 500 error for /favicon.ico

**Steps to Reproduce**
Using my.config.yml from the documentation
`docker run -p 5000:80 -e SCRIPT_NAME='/mypygeoapi' -v $(pwd)/my.config.yml:/pygeoapi/local.config.yml -it geopython/pygeoapi`

**Expected behavior**
HTTP status 200 for favicon.ico

**Environment**
 - OS: Docker
 - Python version: 
 - pygeoapi version: 0.6.0

**Comment by pvgenuchten** [comment]
@francbartoli any idea why the favicon? are also other files in /static not available to you in that setup?
