### ISSUE TITLE
Improve the Docker strategy for deployments

### ISSUE THREAD

**Issue by francbartoli** [geopython/pygeoapi#227]
**Is your feature request related to a problem? Please describe.**
Support the deployment with Starlette through Docker

**Describe the solution you'd like**
`docker build -t geopython/pygeoapi-starlette -f starlette.dockerfile .`

**Describe alternatives you've considered**
Having Starlette/uvicorn in the same default image is dirty and it cannot be considered for production

**Additional context**

**Comment by justb4** [comment]
Thinking out loud: will require some thinking how to design/build/provide `pygeoapi` Docker images. Many of the well-known Docker Images have variants in their naming and tagging. From a user-perspective we need a tagging strategy first. Similar to e.g. Python OS variants (Alpine, Debian etc) we need to standardize tagging variants like:

* `geopython/pygeoapi:0.7.0-flask`, `geopython/pygeoapi:0.7.0-starlette` or
* `geopython/pygeoapi-flask:0.7.0`, `geopython/pygeoapi-starlette:0.7.0` or ?

(would prefer first).
Also multiple tags can be attached to the same image. As many users would not care, they must be able to use defaults like `geopython/pygeoapi` which implies `geopython/pygeoapi:latest` which e.g. implies `geopython/pygeoapi:latest-flask`.

Next is then a build strategy as to not duplicate Dockerfiles. 

(need to go, to be continued).

**Comment by francbartoli** [comment]
@justb4 I agree with the need for a strategy. Probably the first is more helpful but for the build, I don't think we can escape from having two different build path for Dockerfiles. For Starlette as an example, I would extend [those images](https://github.com/tiangolo/uvicorn-gunicorn-starlette-docker) rather than build our own from scratch.

**Comment by frafra** [comment]
I think we can have a single Dockerfile with a build argument, which is then passed to `pdm` to install one or more groups of additional packages: https://github.com/geopython/pygeoapi/issues/344#issuecomment-1377218503.
We could have 2~3 default images for covering most of the needs, and the users could build upon them.

I would suggest using `geopython/pygeoapi:$version-$flavour`, which seems rather common.
