### ISSUE TITLE
implement test framework based on unittests and not on current pytest

### ISSUE THREAD

**Issue by jorgejesus** [geopython/pygeoapi#229]
**Is your feature request related to a problem? Please describe.**
Current pygeoapi test framework is based on pytest, following a code structure based on generic and simple functions. Pytest is a good starting pointing but tests should be more structured and bundled into classes for easy maintenance.

**Describe the solution you'd like**
Code in `test` folder should be refactored into unittest framework, better structured with class methods like setUp() and tearDown() that prepare test implementation.

Aside from testing we should also focus on more integration testing, meaning running pygeoapi on cases that call multiple components and/or cases. 

Should look at the work being done in pywps project that has a good testing approach:
https://github.com/geopython/pywps/tree/master/tests

**Describe alternatives you've considered**
In python language, we have mainly 2 frameworks: pytest and unittest, maybe nose as alernative

**Additional context**
Work for porting pytest to unittest has in part been done in a ISRIC sponsored project (GLOSIS)

**Comment by francbartoli** [comment]
@jorgejesus +1 to expand tests to the integration pattern. However, I don't understand why we cannot still rely on `pytest` for unit testing. Anyway pytest would support [unittest](https://docs.pytest.org/en/latest/unittest.html) eventually `nose2` if at some point we need them. Regardless of tools I'm inclined to have both unit and integration tests mixed in the project. Maybe unit ones more focused on the `api` module and integration ones for the web modules.
Anyway -1 to replace `pytest`, sorry

**Comment by jorgejesus** [comment]
Comments from @jachym (record keeping):

I'm suggesting 2 things:
    prefer pytest module over standard unittests of python. pytest is much easier to be used and it has tons of plugins including html output
    I suggest not to focus on small unittests - just have them for some critical parts. it's much easier to write integration tests more simply more high-level tests to see, if the services are working well and producing corect output. testing against swagger spec is IMHO perfect fit. that is enough, to make suer that everything runs ok and that you did not break anything. having small unittests does not add big value imho

**Comment by jorgejesus** [comment]
Closing the tickets since is more or less agreed that we should continue with pytest
