### ISSUE TITLE
Extend html encoding to offer download of current feature(s) in various encodings to humans

### ISSUE THREAD

**Issue by pvgenuchten** [geopython/pygeoapi#231]
As suggested by @jorgejesus https://gitter.im/geopython/pygeoapi?at=5d72880254e7c649d49b814a, improve how download links are displayed for the current resultset in the various available formats

For example by introducing a dropdown in top left

![image](https://user-images.githubusercontent.com/299829/64511573-e94c9f00-d2e4-11e9-889b-c873e4282845.png)

But maybe we should make it more explicit in a link section in page content?

Does each backend provide to the frontend which output encodings it supports (or should this be a user configuration), this could be used to populate the links section, which would trigger the formats-dropdown.

**Comment by francbartoli** [comment]
I'd like to infer them from web api endpoints somehow and avoid any custom logic in templates as much as possible

**Comment by pvgenuchten** [comment]
This is the intended behaviour @francbartoli:

> each backend provides to the frontend which output encodings it supports, this could be used to populate the links section, which would trigger the formats-dropdown

It probably requires some development and/or configuration to make pygeoapi aware of the encodings supported for each collection

**Comment by jorgejesus** [comment]
I have gave a better look, and I forgot that:
https://demo.pygeoapi.io/master/collections/obs?f=json

Outputs a clear indication of the encoding available, and the templates should pick up from the code (or somewhere else) the encodings

**Comment by pvgenuchten** [comment]
if this was unintentional @jorgejesus, then thanks for reminding me, I think this is still a relevant user story.
