### ISSUE TITLE
update website setup

### ISSUE THREAD

**Issue by tomkralidis** [geopython/pygeoapi#233]
Currently the [pygeoapi.io](https://pygeoapi.io) website is a pure HTML implementation (in our `gh-pages` branch). To manage website content easier I'd like to move to Jekyll, MkDocs, Pelican, or Nikola (other options?).

What do folks think? I think this is a good time to port things given the website is very small. Note also that the website is different than the docs per se.

**Comment by francbartoli** [comment]
+1 to move on a more featured tool. Another option could be [gatsby.js](https://www.gatsbyjs.org/)

**Comment by jorgejesus** [comment]
Maybe related to this discussion. We have the jinja templates that generate the templates, but current JS  development  methodologies are more and more based on modules (nodejs et al) and JS code is build and deploy. Also it seems that module import in browser is still lacking. Could we over come  this ?? Using the proposed to the content managers suggested above

**Comment by jorgejesus** [comment]
Another option: https://gridsome.org/ ( to please the vue.js boys, me and @justb4 )

**Comment by pvgenuchten** [comment]
these tools look fantastic (was worried about seo, but seems covered), but doesn't it add too much complexity to things that should be simple... usefull aspects of any framework:

- sources should look good in cms as well as github (markdown)
- sources should be in github, so you can PR to it
- should have header/footer
- should degrade nicely/provide seo
...

Nice to have

- link checking
- search capabilities
...

**Comment by justb4** [comment]
No strong opinion, other then that it must be easy for anyone to update content while still allowing more dynamic stuff like a blog and possibly social media/gitter excerpts. There's I think a zillion solutions to maintain bare content in GitHub and render the result in one way or another. Easiest and most stable is to render the site on `gh-pages` (as now), a `Travis` build can do any rendering to flat HTML and push to `gh-pages` . The content does not have to be maintained in `gh-pages` then.

Another option is: we have already a VM running for `demo.pygeoapi.io` remember? This is maintained in a separate GH: https://github.com/geopython/demo.pygeoapi.io but could be easily extended to support the `pygeoapi.io` home, for example replacing the somewhat ugly/barren landing page: https://demo.pygeoapi.io. This is a [Flask Docker Image](https://github.com/geopython/demo.pygeoapi.io/tree/master/services/home) that is automatically rebuild and deployed on any content push but could be remolded to whatever solution in CMS-like we take (Flask is overkill here). I would rather have one website where this demo-homepage is a sub-page in `pygeoapi.io`. 

All in all I still think rendering on `gh-pages` is the most reliable.

**Comment by tomkralidis** [comment]
More notes/requirements:
- needs to be able to manage content in both Markdown and HTML
- setup is for website only.  Documentation remains in pygeoapi rep with workflow to RTD

**Comment by jorgejesus** [comment]
Also like no strong opinion as long it is easy to use and more or less on
the scope of our programming language (no JAVA or ruby)

**Comment by tomkralidis** [comment]
First pass implementation now available for review/comment:

- code: https://github.com/geopython/pygeoapi.io
- deployment: https://geopython.github.io/pygeoapi.io (via gh-pages branch)

Notes:
- implemented using Mkdocs
- initial website copied over and updated
- many concepts / content borrowed from https://pycsw.org setup
- added new pages of interest
    - community: https://geopython.github.io/pygeoapi.io/community
    - PSC: https://geopython.github.io/pygeoapi.io/community/psc
    - RFC list: https://geopython.github.io/pygeoapi.io/development/rfc
    - RFC1 (PSC): https://geopython.github.io/pygeoapi.io/development/rfc/1
- deployment will switch to point to https://pygeoapi.io once we are clear for a live update

**Comment by justb4** [comment]
Good to see this! Some suggestions:

Menu:

* combine Docs and Presentations into Documentation, with a page outlining/explaining various docs, presentations 
* many folks would look for a Download page with version-info
* possibly combine Code and Development into Development 
* Demo page: integrate into site, demo.pygeoapi.io could redirect to pygeoapi.io/demo so we have same design, one place for content
* Blog/news page?


Stale link in https://geopython.github.io/pygeoapi.io/community/psc/ for PSC list.

**Comment by tomkralidis** [comment]
Thanks @justb4.  Updates pushed. Notes:

- it is useful to have a dedicated "Code" link so (OSGeo reviews usually ask for this)
- we can put forth a blog/news setup once we have
- some broken links will resolve themselves once we deploy live to https://pygeoapi.io
- I will update look/feel based on a layout/template as per https://github.com/geopython/pygeoapi/blob/master/pygeoapi/templates/base.html which we can use in the demo.pygeoapi.io setup as well for a consistent look and feel across our web presence

**Comment by tomkralidis** [comment]
FYI update to theming for review and comment: https://geopython.github.io/pygeoapi.io/

**Comment by justb4** [comment]
* CSS: https://github.com/geopython/pygeoapi.io/blob/master/pygeoapi.io-theme/main.html#L13 refers to demo.pygeoapi.io , probably better to keep local, or maybe not needed?
* stale links in https://geopython.github.io/pygeoapi.io/ menu e.g. to /development, but will be solved when deployed it looks like (`site_url` Jinja2 var).
* logo not found: https://pygeoapi.io/img/pygeoapi-logo-notrans.png
* no  favicon.ico? we have one at: https://pygeoapi.io/favicon.ico

**Comment by tomkralidis** [comment]
@justb4 CSS localized.  The other issues should resolve once deployed live.
