### ISSUE TITLE
enhance HTML representations

### ISSUE THREAD

**Issue by tomkralidis** [geopython/pygeoapi#26]
The `f=html` responses need a better layout.  The goal here should be to enhance layout (especially the maps) without introducing too many external dependencies.

**Comment by jorgejesus** [comment]
Something every simple like: https://bulma.io/documentation/

**Comment by jorgejesus** [comment]
Suggestion from Paul van Genuchten

Make proposed page easy to customize using configuration options. and possibility of adding icons

**Comment by pvgenuchten** [comment]
The templating system seems a good option to change the layout according to user needs
https://github.com/geopython/pygeoapi/blob/master/pygeoapi/templates/base.html

Some comments to improve the generic base template:
- <head>title/keyword/abstract</head> should not be filled using generic config, in stead it should use properties from the collection or feature exposed on that page
- if the css were based on less, it would be nice to allow to define a color-scheme & font.
- add an organisation logo (upload logo.png from admin)
- add option to configure links in the header or footer (contact, disclaimer, help etc)

**Comment by thijsbrentjens** [comment]
@pvgenuchten this is a really good point: 

> head-title/keyword/abstract should not be filled using generic config, in stead it should use properties from the collection or feature exposed on that page (title will be displayed on google search result), so would be interesting to configure for each Collection which property of Feature can be used as title (aka schema.org/name)

I just tested the results in Google Search. Google indexes up to the individual item, which is really nice (and *could* be useful for some datasets). But the HTML representation could be improved. See for example [https://www.google.com/search?q=site:demo.pygeoapi.io&start=70](https://www.google.com/search?q=site:demo.pygeoapi.io&start=70)

Improvements like: add a specific H1 header (and title element) for an item (there is no H1 currently), preferably a human readable title, but that may require some more work (e.g. an optional ```title_field``` per provider for example). It may not be today, but I could maybe implement something for this

**Comment by tomkralidis** [comment]
Closing given we probably have enough given our current HTML representation.  Feel free to reopen if we missed anything.  Having said this, I will open a new ticket for being able to modify look and feel.

**Comment by pvgenuchten** [comment]
I agree with Thijs (sorry missed this discussion) we should make sure to list at least the id of the feature in the title, now google shows same title for each feature

![image](https://user-images.githubusercontent.com/299829/68399784-3929d400-0177-11ea-8999-d04ba112d478.png)

I'll work on a PR

**Comment by pvgenuchten** [comment]
or maybe better to move this to a new issue...

**Comment by tomkralidis** [comment]
FYI #296 opened for review/comment.

**Comment by justb4** [comment]
Think this also can be closed, the scope is also is rather broad but at the time of opening the HTML was rather barren. Better to have more specific/targeted issues like #361.
