### ISSUE TITLE
Flask has inconsistency with trailing slash in routes as compared to Starlette

### ISSUE THREAD

**Issue by francbartoli** [geopython/pygeoapi#260]
**Description**
Currently the routes in Flask are handling the trailing slash while the same routes from Starlette aren't.
**Steps to Reproduce**

1. `pygeoapi serve --starlette`
2. `curl -XGET http://localhost:5000/collections/`  --> `404`

3. `pygeoapi serve --flask`
4. `curl -XGET http://localhost:5000/collections/`  --> `200`

**Expected behavior**
The two frameworks should handle routes accordingly

**Screenshots/Tracebacks**

**Environment**
 - OS: Mac OS X
 - Python version: 3.7.4
 - pygeoapi version: master

**Additional context**

**Comment by tomkralidis** [comment]
So it looks like Flask honours trailing slashes while Starlette does not.  The following diff normalizes behaviour across both:


```diff
diff --git a/pygeoapi/starlette_app.py b/pygeoapi/starlette_app.py
index 4e4ee05..78e6b6e 100644
--- a/pygeoapi/starlette_app.py
+++ b/pygeoapi/starlette_app.py
@@ -80,7 +80,7 @@ async def root(request: Request):
     return response


-@app.route('/api')
+@app.route('/api/')
 async def api(request: Request):
     """
     OpenAPI access point
@@ -100,7 +100,7 @@ async def api(request: Request):
     return response


-@app.route('/conformance')
+@app.route('/conformance/')
 async def api_conformance(request: Request):
     """
     OGC open api conformance access point
@@ -118,8 +118,8 @@ async def api_conformance(request: Request):
     return response


-@app.route('/collections')
-@app.route('/collections/{name}')
+@app.route('/collections/')
+@app.route('/collections/{name}/')
 async def describe_collections(request: Request, name=None):
     """
     OGC open api collections  access point
@@ -140,8 +140,8 @@ async def describe_collections(request: Request, name=None):
     return response


-@app.route('/collections/{feature_collection}/items')
-@app.route('/collections/{feature_collection}/items/{feature}')
+@app.route('/collections/{feature_collection}/items/')
+@app.route('/collections/{feature_collection}/items/{feature}/')
 async def dataset(request: Request, feature_collection=None, feature=None):
     """
     OGC open api collections/{dataset}/items/{feature}  access point
@@ -169,8 +169,8 @@ async def dataset(request: Request, feature_collection=None, feature=None):
     return response


-@app.route('/processes')
-@app.route('/processes/{name}')
+@app.route('/processes/')
+@app.route('/processes/{name}/')
 async def describe_processes(request: Request, name=None):
     """
     OGC open api processes access point (experimental)
@@ -189,7 +189,7 @@ async def describe_processes(request: Request, name=None):
     return response


-@app.route('/processes/{name}/jobs', methods=['GET', 'POST'])
+@app.route('/processes/{name}/jobs/', methods=['GET', 'POST'])
 async def execute_process(request: Request, name=None):
     """
     OGC open api jobs from processes access point (experimental)
```

@francbartoli are you able to test the above?

**Comment by francbartoli** [comment]
@tomkralidis with those changes the behavior is exactly the same so do we want to support the trailing slashes even though the OAPIF doesn't require them mandatorily? I can send the PR with this patch if we decide

**Comment by tomkralidis** [comment]
I would keep the trailing slashes at the implementation (i.e. OpenAPI doc doesn't require them).  Thanks in advance for the PR!

**Comment by francbartoli** [comment]
@tomkralidis I was trying to implement your patch but I don't like what I'm facing from the command line:
1. `pygeoapi serve --starlette`

    `curl -XGET http://localhost:5000/api`

    `[2019-10-01T23:37:08Z] {/Users/geobart/.pyenv/versions/3.7.4/envs/pygeoapi/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py:443} INFO - ('127.0.0.1', 57094) - "GET /api HTTP/1.1" 307`

2. `pygeoapi serve --flask`

     `curl -XGET http://localhost:5000/api`

     `[2019-10-01T23:38:12Z] {/Users/geobart/.pyenv/versions/3.7.4/envs/pygeoapi/lib/python3.7/site-packages/werkzeug/_internal.py:122} INFO - 127.0.0.1 - - [01/Oct/2019 23:38:12] "GET /api HTTP/1.1" 200`

While the following:

```python
@app.route('/api')
@app.route('/api/')
async def api(request: Request):
    """
    OpenAPI access point
@ pygeoapi/starlette_app.py:104 @ async def api(request: Request):
    return response
```

serves the content

`[2019-10-01T23:40:24Z] {/Users/geobart/.pyenv/versions/3.7.4/envs/pygeoapi/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py:443} INFO - ('127.0.0.1', 57863) - "GET /api HTTP/1.1" 200`

**Comment by tomkralidis** [comment]
@francbartoli what happens if you duplicate the routes (with and without slashes) across the Starlette routes:

```python
@app.route('/collections/{feature_collection}/items')
@app.route('/collections/{feature_collection}/items/')
@app.route('/collections/{feature_collection}/items/{feature}')
@app.route('/collections/{feature_collection}/items/{feature}/')
```

Perhaps Starlette handles this better?

**Comment by tomkralidis** [comment]
Update: the 307 from Starlette is [by design](https://github.com/encode/starlette/pull/563)

**Comment by francbartoli** [comment]
> @francbartoli what happens if you duplicate the routes (with and without slashes) across the Starlette routes:
> 
> ```python
> @app.route('/collections/{feature_collection}/items')
> @app.route('/collections/{feature_collection}/items/')
> @app.route('/collections/{feature_collection}/items/{feature}')
> @app.route('/collections/{feature_collection}/items/{feature}/')
> ```
> 
> Perhaps Starlette handles this better?

Yes @tomkralidis duplicating them as I have already pushed in the PR align the behavior of responses. Can we merge?
