### ISSUE TITLE
Error when accessing /api in the HTML page of Swagger

### ISSUE THREAD

**Issue by francbartoli** [geopython/pygeoapi#262]
**Description**
The swagger page shows this error:

```
Resolver error at paths./api.get.responses.default.content.application/json.schema.$ref
Could not resolve reference: Could not resolve pointer: schemas/exception.yaml does not exist in document
```

**Steps to Reproduce**
Open the following link in the browser `http://localhost:5000/api#/server/get_api`

**Expected behavior**
No errors

**Screenshots/Tracebacks**
<img width="1678" alt="Senza nome" src="https://user-images.githubusercontent.com/560676/65987850-f2b1cd00-e486-11e9-9f08-2ef827498455.png">

**Environment**
 - OS: Mac OS X
 - Python version: 3.7.4
 - pygeoapi version: master

**Additional context**

**Comment by justb4** [comment]
Strange, cannot reproduce (using current `master` with `flask_app.py` as main):

![image](https://user-images.githubusercontent.com/582630/65993608-d9fae480-e491-11e9-979e-ec50c766a6f0.png)

Running `Starlette` maybe, slash issue?

**Comment by francbartoli** [comment]
@justb4 I'm aligned with master and getting that error both from flask and starlette. No slash involved, I'm following the link `OpenAPI` from the root page. Actually strange indeed

**Comment by tomkralidis** [comment]
@francbartoli is this still an issue via http (not https)?  Note that if you are testing with pygeoapi deployed via https, then you will likely run into issues (filed in #312 and https://github.com/opengeospatial/ogcapi-features/issues/276)

**Comment by francbartoli** [comment]
I tested again @tomkralidis and realized that `/api` is no longer available and it has been replaced by `/openapi`. This latter is working well with either flask/starlette so I'm going to close the issue
