### ISSUE TITLE
sanitize bbox content

### ISSUE THREAD

**Issue by jorgejesus** [geopython/pygeoapi#266]
**Is your feature request related to a problem? Please describe.**
Sanitize BBOX inputs, on BBOX validation: 
https://github.com/geopython/pygeoapi/blob/8709fbb43ca1a364ac13536b0ae2d638f6aa4135/pygeoapi/api.py#L461

It only checks that we have a list with 4 elements, independent of datatype,  we could have a bbox like this
`[hamster, cat, pigeon, dog]`

**Describe the solution you'd like**
Basic type checking (for future maybe use marshmallow lib to validate data structure)

**Describe alternatives you've considered**
Do validation at data provider level but that would require validation for all data providers and it is unfesable

**Additional context**
Since BBOX  values are passed to SQL queries on certain providers like sqlite3,  it could be a SQL injection vector

**Comment by tomkralidis** [comment]
@jorgejesus at the API level we could check that the values are ints/floats.  I would think that SQL-based providers would do the binding of values accordingly (example: http://initd.org/psycopg/docs/usage.html#passing-parameters-to-sql-queries)

**Comment by justb4** [comment]
Note that the [OGR Provider already supports bbox](https://github.com/geopython/pygeoapi/blob/master/pygeoapi/provider/ogr.py#L273) and does basic sanitation with exception handling. But indeed better to check at API-level, so all Providers can assume a sanitized `bbox`...

**Comment by tomkralidis** [comment]
Implemented in #267
