### ISSUE TITLE
update documentation

### ISSUE THREAD

**Issue by tomkralidis** [geopython/pygeoapi#277]
Given the awesome work by @jorgejesus to implement project documentation, it's a good time to update docs to provide further user support.

- [x] establish table of contents
- [x] develop first draft of updates for review and comment/refinement

**Comment by tomkralidis** [comment]
Suggest ToC for review/comment:

- project overview
  - features
- installation
   - pip
    - git
    - docker
- configuration
- administration/publishing
  - OpenAPI
- running
  - wsgi
  - asgi
- plugins
  - overview
  - formatters
  - providers
  - processes
- Python API documentation
- support
- contributing
- license

**Comment by jorgejesus** [comment]
The TOC content sounds good

**Comment by justb4** [comment]
ToC looks good, possibly need a config reference section/annex, in time with a formal config schema? Or fine in config chapter itself.
At least in configuration chapter we should point to more examples, e.g. from unit testing and demo.

**Comment by justb4** [comment]
* installation: also `conda`?
* chapter on https://demo.pygeoapi.io setup as example (Docker proxy-ing etc), instances and CITE?

**Comment by tomkralidis** [comment]
Thanks @justb4 I've added a deployment section to the above, as well as an OGC CITE compliance section, which should cover our CITE support/story/workflow (including how to test).

**Comment by justb4** [comment]
section suggestion: "Further Reading/Info": with links to presentations (slides, video) and..

**Comment by tomkralidis** [comment]
Implemented in #392.
