### ISSUE TITLE
Adding the ability to filter on properties in the postgres provider

### ISSUE THREAD

**Issue by mbucknell** [geopython/pygeoapi#279]
**Is your feature request related to a problem? Please describe.**
We are hoping to implement a OGC API service with a Postgres background and will need the ability to filter collections on property values in order to make it useful for our users. I saw the discussion in https://github.com/geopython/pygeoapi/issues/269 regarding this but wanted to call this out as a unique feature.

**Describe the solution you'd like**
At the very least, we should have the ability to query on all property values other than the id and the geom column. An additional features might be to specify the exact properties to use in the config file.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by mbucknell** [comment]
I plan on working on adding this feature and welcome any suggestions.

**Comment by justb4** [comment]
Quick scan: is this also related to https://github.com/geopython/pygeoapi/pull/220 ?
Implementation strategy: this feature will be generic, but not all Providers will be able to handle property filtering natively. Similar to a re-projection capability, see [this discussion on Gitter](https://gitter.im/geopython/pygeoapi?at=5da5fe2b8e2e9a7c6b0299da).  

Not sure if standard already provides API convention, but IMHO we should apply a common strategy here as well: Provider should indicate if it can handle property filtering, could be a simple `boolean`.

**Comment by mbucknell** [comment]
I believe it is related. There seems to be hooks in the providers for this but they aren't implemented at least in the case of postgres. I believe it is part of the standard: http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#_parameters_for_filtering_on_feature_properties

**Comment by mbucknell** [comment]
This PR contains an example implementation: https://github.com/geopython/pygeoapi/pull/283

**Comment by tomkralidis** [comment]
Should we close this issue given #283 has been merged?

**Comment by mbucknell** [comment]
https://github.com/geopython/pygeoapi/pull/283 implements this feature. Closing issue.
