### ISSUE TITLE
Add bbox parameter to postgres parameter

### ISSUE THREAD

**Issue by ayan-usgs** [geopython/pygeoapi#284]
**Is your feature request related to a problem? Please describe.**
We would like to implement an OGC API service with a Postgres/PostGIS backend and will need the ability to query for features within a specified bounding box. A bbox query feature was briefly mentioned in #269.

**Describe the solution you'd like**
I can pass in a bbox of four coordinates and all features within those coordinates are returned in a GeoJSON feature collection.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ayan-usgs** [comment]
I'm planning on implementing this. Suggestions are most welcome.

**Comment by jorgejesus** [comment]
closed by PR #287
