### ISSUE TITLE
Consider adopting pylint to make contributing easier

### ISSUE THREAD

**Issue by alpha-beta-soup** [geopython/pygeoapi#288]
**Is your feature request related to a problem? Please describe.**
As a contributor, it's easier to adopt the particular style of a given Python project when idioms that are a matter of developer preference are defined with a series of rules for a linter. Example: https://github.com/geopython/pygeoapi/pull/287#discussion_r338409963

**Describe the solution you'd like**
I want the project to adopt pylint, and define rules such as the f-string formatting within a `.pylintrc` configuration that is committed with git.

**Describe alternatives you've considered**
None; I think pylint is established as the most popular Python linter?

**Comment by jorgejesus** [comment]
Could we totally replace `flake8` for pylint and also in the process increase the number of characteres per line, as discussed in this feed ?
https://github.com/influxdata/influxdb-python/issues/474

**Comment by francbartoli** [comment]
@alpha-beta-soup @jorgejesus what about using black?

**Comment by jorgejesus** [comment]
> @alpha-beta-soup @jorgejesus what about using black?

It is another possibility,  @francbartoli  the project black seems to be beta, do you have a good experience with black ?

**Comment by francbartoli** [comment]
I've started using black in combination with [pre-commit](https://github.com/pre-commit/pre-commit) and it looks super cool.

**Comment by jkreft-usgs** [comment]
Another option would be to use codeclimate or codacy, both of which are free for open source and and super useful for both linting and other code quality issues.

**Comment by alpha-beta-soup** [comment]
OK so if I'm to implement this, I might need some direction from project owners/maintiners about their preference, since there are a few options on the table. My original intention was just to have auto-formatting and to avoid syntax debates/comments in PRs. My technological preference is anything that:

- is simple (i.e. not a SaaS or anything that resembles a SaaS; and *must* be FOSS)
- is established/popular
- CLI / allows easy integration with many IDEs to support e.g. lint on file save

Integration with a CI pipeline is optional in my opinion. I'd rather not use something that is hosted. My preference is still pylint, but I'm open to Black—although Black is new to me.

What say you, maintainers?

**Comment by alpha-beta-soup** [comment]
> @jorgejesus Could we totally replace flake8 for pylint and also in the process increase the number of characteres per line, as discussed in this feed ?
influxdata/influxdb-python#474

Black is "opinionated" and one of those opinions is an 88-character line (compared to the 79 of PEP 8). I've retained that 88-character default in my PR. It also needed the Flake8 configuration to agree.

**Comment by frafra** [comment]
I would suggest [ruff](https://github.com/charliermarsh/ruff) instead of flake and pylint. ruff replaces both, and it is way faster.

**Comment by francbartoli** [comment]
Thanks @frafra, I will look into that and give feedback asap
