### ISSUE TITLE
Query across multiple collections

### ISSUE THREAD

**Issue by jkreft-usgs** [geopython/pygeoapi#292]
**Is your feature request related to a problem? Please describe.**
I would like to be able to query across every feature that is cataloged in a given pygeoAPI endpoint, regardless of what collection a given feature is in.  This is something that is implemented in STAC, but not in pygeoAPI so far.

**Describe the solution you'd like**
The endpoint could potentially be `/search/` (like STAC) and the parameters could be the same as what you would use for the `/collections/` endpoint. The features returned would include an array of `collections` in the `properties` of each feature.

**Describe alternatives you've considered**
There are probably a few other ways to do this, but I haven't given them huge thought

**Additional context**

**Comment by matthewhanson** [comment]
There's a proposal being discussed to add an `/items` endpoint to OAF which will provide this capability.

**Comment by jkreft-usgs** [comment]
is there a link to that discussion?

**Comment by jkreft-usgs** [comment]
found the `items` discussion in [ogcapi-features issue 154](https://github.com/opengeospatial/ogcapi-features/issues/154)

**Comment by m-mohr** [comment]
Here's the PR for STAC to rename /stac/search as a first attempt to align with efforts of OAF: https://github.com/radiantearth/stac-spec/pull/632 
In discussions with OAF and STAC we agreed that /search makes most sense.

**Comment by pvgenuchten** [comment]
Yes I like this, one could even extend this idea to return items, but also collections or processes as the search result (sometimes users just want to query anything related to "forest", and don't care if it concerns actual features, sensor observations, collections or processes), the result can then later be filtered by selecting only the observations.
