### ISSUE TITLE
Many:many feature:collection relationship

### ISSUE THREAD

**Issue by jkreft-usgs** [geopython/pygeoapi#293]
**Is your feature request related to a problem? Please describe.**
Right now, each feature is tied to a single collection.  There are many use cases for a feature to be part of many different collections.  A feature could be in a number of different collections in an organization.

* climate response feature
* features that are in flood
* features that are important

**Describe the solution you'd like**
Each feature can be a member of one (possibly zero?) to many collections.  The collections that a given feature is enumerated in the properties of each feature, using something like `'collections' : ['<collection1URI>', '<collection2URI>' ]` 

**Additional context**
You can see many different collections (in this case they are called networks) of the same larger subset of features here: 
https://groundwaterwatch.usgs.gov/usgsgwnetworks.asp

**Comment by jkreft-usgs** [comment]
relevant discussion in [ogcapi-features](https://github.com/opengeospatial/ogcapi-features/issues/266)

**Comment by pvgenuchten** [comment]
@jkreft-usgs can you explain your use case of features being a part of many collections in your water network case. Are you referring to the wells, the observations in those wells or thematical information gathered from those observations? To me, all of these are individual items, where each of them would belong to a single collection. 

To me, the actual registration of an object with properties in a registry or table (its collection), identifies the object. Such an object can not be registered in another registry, without it being a copy/clone (in which case only 1 item in 1 collection will be the original). 

Looking forward to hear your thoughts

**Comment by jkreft-usgs** [comment]
Interesting.  I think we are coming at the idea of collection from pretty different viewpoints.  I see a collection of features as a group of features that are related to each other in a tangible way that matters to the people who care about those features.

The USGS has a million or so water monitoring locations, such as this one on the Colorado River at Lee's Ferry, which has the following URI: https://waterdata.usgs.gov/monitoring-location/09380000/.  This monitoring location, which is tied to a location on the earth's surface, could be put into a number of different collections:

- Locations operated in cooperation with The US Bureau of Reclamation `waterdata.usgs.gov/ogcAPI/collection/US_BOR`
- Locations on the Colorado River `waterdata.usgs.gov/ogcAPI/collections/colorado_r_1254`
- Locations that are within the Hydrologic Unit code 14070006 (Lower Lake Powell) `waterdata.usgs.gov/ogcAPI/collections/14070006`
- Locations that are in Coconino County, Arizona `waterdata.usgs.gov/ogcAPI/collections/US:05:04`
- (if it is over flood stage) Locations in the US that are over flood stage `waterdata.usgs.gov/ogcAPI/collections/flood`

If a collection is everything that is in a registry, then for all million USGS monitoring locations, there is only a single collection, and we need to figure out another way to represent groups of related features.  

I think that as part of a many-many implementation, there could also be at least a strong encouragement to include a `sameAs` property to make it possible for the user to know that `waterdata.usgs.gov/ogcAPI/collection/US_BOR/items/09380000` and `waterdata.usgs.gov/ogcAPI/collection/US:05:04/items/09380000` were both representations of `waterdata.usgs.gov/monitoring-location/09380000` . 

I'm certainly planning on doing that for the USGS implementation of pygeoAPI.

**Comment by jkreft-usgs** [comment]
With respect to this question:
> Are you referring to the wells, the observations in those wells or thematical information gathered from those observations? To me, all of these are individual items, where each of them would belong to a single collection.

I am currently referring to monitoring locations, each of which may have one or more sampling locations. The data being collected are a whole additional problem space that may be able to be addressed with datacubes (or data hyperspheres) in STAC. 

Monitoring Locations are also part of the SELFIE work that is also related to #246

**Comment by pvgenuchten** [comment]
Indeed, my understanding of collection is much more basic, the set comes to existence by how it is made available, in the case of https://waterdata.usgs.gov/monitoring-location/09380000/, i would say the collection is "monitoring-location". That these monitoring stations are used in a variety of contexts  is more an ontological challenge. I can see such a monitoring station being duplicated into another context (referencing the original with sameAs), but in that case a new registered item is created being part of an alternative collection.

But please go ahead with an implementation, I'm curious to see it in action. It will facilitate discussion.

**Comment by francbartoli** [comment]
@jkreft-usgs @pvgenuchten from my old knowledge of Simple Feature (Ref.  https://www.w3.org/TR/sdw-bp/#dfn-feature), that is 

> an abstraction of real-world phenomena. A digital representation of a real-world entity or an abstraction of the real world

I would consider a strict concept of feature as it is explained above.

Now it would be certainly of interest to have cross-referenced features in different groups but I have a strong opinion about:

1. groups or aggregations or subsets in a specific context can contain linked features even if they have different structures while a collection cannot (a WFS layer cannot have items with different schemas)
2. The reference of the same feature in different contexts doesn't need to duplicate that original feature itself even because it doesn't add any value IMHO, well actually it would break one the most important best practice in the SDW [Use globally unique persistent HTTP URIs for Spatial Things](https://www.w3.org/TR/sdw-bp/#globally-unique-ids) 

Also, I would say that your use case is tighter to different spatial filters (proximity or inclusion to something in general, it could be another feature, i.e. `waterdata.usgs.gov/ogcAPI/collections/14070006` or a buffer of a location
