### ISSUE TITLE
allow for custom HTML templating

### ISSUE THREAD

**Issue by tomkralidis** [geopython/pygeoapi#295]
**Is your feature request related to a problem? Please describe.**
It would be valuable for organizations to implement their own templates according to their requirements.

**Describe the solution you'd like**
Driven by configuration, implement the ability to point to a custom HTML template directory as well as static assets (icons, css, etc.).

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by isedwards** [comment]
Are you happy to assign this to me? It looks straightforward, but it may take me up to a couple of weeks to submit a PR if that is okay?

I see the interface has already be defined in [pygeoapi-config.yml](https://github.com/geopython/pygeoapi/blob/b61404d610060361e931e8abbd05b9ba34d9cc00/pygeoapi-config.yml#L41) as:
```
server:
    # templates: /path/to/templates
```

**Comment by tomkralidis** [comment]
Thanks @isedwards assigned over to yourself. Looking forward to this enhancement!

**Comment by pvgenuchten** [comment]
closed by #523
