### ISSUE TITLE
Postgres provider doesn't handle query parameters correctly when resulttype=hits

### ISSUE THREAD

**Issue by mbucknell** [geopython/pygeoapi#299]
**Description**
When the postgres provider is used and a query for items using the parameter resulttyepe=hits, it always returns the count of the total items in the collection. If other query parameters are provided, they are ignored and the result still contains the total number of items in the collection

**Steps to Reproduce**
For a postgres provider, use the propertyname=propertyvalue query parameter along with resulttype=hits. The returned count will be the total number if the collection rather than the number of items in the filtered collection.

**Expected behavior**
I expect the count to reflect the number of items returns when resulttype=hits is not included on the query.

**Screenshots/Tracebacks**

**Environment**
 - OS:
 - Python version: 
 - pygeoapi version: 

**Additional context**
This is for the postgres provider

**Comment by jorgejesus** [comment]
Just noticed on the postgresql provider, we have `self.conn_dic = provider_def['data']` which is already created by the parent class (BaseProvider) but called `self.data = provider_def['data']`

**Comment by jorgejesus** [comment]
``http://localhost:5000/collections/hotosm_bdi_waterways/items?name=Muha&resulttype=hits&f=json`` should return 2
