### ISSUE TITLE
Add the ability to generate collection dataset information from a database.

### ISSUE THREAD

**Issue by mbucknell** [geopython/pygeoapi#300]
**Is your feature request related to a problem? Please describe.**
Not really. The issue is that information on the set of collections is assumed to be static and we have a use case where would like this information generated from database tables.

**Describe the solution you'd like**
Not sure yet. I will have to give it more thought.

**Describe alternatives you've considered**
Alternatives would be writing scripts outside of pygeoapi to create the config data with the appropriate collection metadata.

**Additional context**

**Comment by pvgenuchten** [comment]
a while back i came up with an idea to [use pygeoapi to expose a folder structure of data files](#178), the idea is still relevant and could match with your idea here, pygeoapi would at intervals need to scan the folder (or a database) for changes and reflect them in its configuration
