### ISSUE TITLE
Previous and Next Links do not work

### ISSUE THREAD

**Issue by geekdenz** [geopython/pygeoapi#310]
**Description**
Previous and next links on the viewer of a single item do not work.

**Steps to Reproduce**

1. Go to a specific item.
2. Click on previous or next link.

**Expected behavior**
Previous or next item shows when link is clicked, but same item is displayed.

**Environment**
 - OS: Ubuntu 18.04
 - Python version: 3.7.3
 - pygeoapi version: b61404d

**Comment by alpha-beta-soup** [comment]
>  **Expected behavior**
> Previous or next item shows when link is clicked, but same item is displayed.

My expected behaviour would be either:
- There are no prev/next links when looking at a single feature
- They work but navigate to different features (e.g. prev/next with default sorting).

**Comment by tomkralidis** [comment]
This may or may not be trivial for a given provider backend to come up with.  Having said this, +1 for removing prev/next links from `pygeoapi/templates/item.html` in #311

**Comment by geekdenz** [comment]
@tomkralidis thanks for your feedback.

The previous/next links are broken before this fix for all providers. This fixes it for the pgsql provider and I think it's definitely possible to fix it, at least somewhat, for other providers. Also, I tested this with other providers and it didn't break anything further because the link then just does not work.

Maybe the previous/next links should be removed only for providers where it's not implemented. I'm happy to do this change.

Having said all that it might not be trivial to merge this fix in. If you like I can have a go at merging it into current master. Please let me know.

**Comment by tomkralidis** [comment]
Thanks @geekdenz.  I think it's safe to not assume all providers can implement this functionality and we can test for this in HTML mode, which you're implemented (thanks!).  Minor comments remaining in #311.
