### ISSUE TITLE
http://schemas.opengis.net/ is not running in HTTPs

### ISSUE THREAD

**Issue by jkreft-usgs** [geopython/pygeoapi#312]
**Description**
http uris are making swagger break due to mixed-content issues.  The TODO is indeed something that needs to be done

[Offending Line](https://github.com/geopython/pygeoapi/blob/61b1617d562c0a5573d21759fe6fdefb59cac2fe/pygeoapi/openapi.py#L44): 

```
# TODO: handle this better once schemas are public/final
# allow also for schema caching
OPENAPI_YAML = {
    'oapif': 'http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/ogcapi-features-1.yaml',  # noqa
    'oapip': 'https://raw.githubusercontent.com/opengeospatial/wps-rest-binding/master/core/openapi'  # noqa
}
```

**Steps to Reproduce**
load the swagger doc on a page that runs over https.  The browser will block the call to `http://schemas.opengis.net/` because of mixed content, and then the swagger will throw errors when you click on various endpoints, including the `collections/{collection-id}/items endpoint

If you force your browser to accept mixed content, the error goes away.

**Expected behavior**
Swagger works on https, including all of the collection query parameters

**Screenshots/Tracebacks**
![image](https://user-images.githubusercontent.com/8128936/69676603-b786e100-1066-11ea-9e46-2b01e38623dd.png)

**Environment**
 - OS: Docker (Alpine?)
 - Python version: 3.6 
 - pygeoapi version: Latest

**Additional context**
The easiest solution would probably be for schemas.opengis.net to just get a certificate and properly set HSTS and forwarding as well.

**Comment by jkreft-usgs** [comment]
You can see this issue on the demo site as well: https://demo.pygeoapi.io/master/openapi?f=html#/obs/get_collections_obs_items

**Comment by jkreft-usgs** [comment]
A path forward while OGC gets its ducks in a row would be to make the definition of  `OPENAPI_YAML` configurable so that I can easily point to a copy of the YAML file somewhere that does support `https`.

**Comment by tomkralidis** [comment]
Implemented in #347

**Comment by pvgenuchten** [comment]
Referencing duplicated schemas on a https location does indeed solve the case. 
Is the documentation updated to require this configuration step for https environments?
Has there been any contact with OGC to discuss if they can also host those schema's on https?

**Comment by tomkralidis** [comment]
@pvgenuchten 

- we're (slowly) working on docs in https://github.com/geopython/pygeoapi/tree/issue-277-documentation and will add this
- related item with OGC: https://github.com/opengeospatial/ogcapi-features/issues/276 .  Please feel free to add feedback there as well

**Comment by pvgenuchten** [comment]
also consider that referencing a local duplicate of the schema prevents the software running into problems if OGC updates the schema or schema-location
