### ISSUE TITLE
Align Accept header and f query parameter values

### ISSUE THREAD

**Issue by alpha-beta-soup** [geopython/pygeoapi#317]
**Is your feature request related to a problem? Please describe.**
At present, there are two ways to perform content negotiation ("conneg"): the `Accept` header and the `f` query parameter. `Accept` headers are standardised, `f` query parameters are not. Using the `f` query parameter is essentially a work-around since a bare URI/URL string by itself cannot express the desired conneg in an identical manner to the use of headers. Since the OCG API - Features specification is strong on the use of conneg for resources at the same URL—think `https://some.domain/api?f=html` and `https://some.domain/api?f=json`—and is designed to work as simple links embedded in HTML without JavaScript, then there is a lot of influence determined by this little `f` parameter.

The problem, as I see it, is that there *is* a clear association between `f` and `Accept` but *they don't accept the same values*. e.g. `Accept: application/json` but `f=json`. `Accept` is far more powerful and standardised (e.g. media ranges with wildcards, case-insensitivity, factor weighting, multiples, suffixes, etc.). There's even the HTTP response [406 Not Acceptable](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/406) that might be suitable to use in a response to a URL/query such as `https://demo.pygeoapi.io/stable?f=text/xml`. (Although, I don't know if the "range" of such a response includes query parameters as well as headers—would be a good idea to confirm.)

The mapping between a `f` value and an `Accept` header is not always clear, e.g. `f=jsonld` but `Accept: application/ld+json` or `Accept: application/ld+json,application/json`.

**Describe the solution you'd like**
Succinctly: https://demo.pygeoapi.io/stable?f=json should be https://demo.pygeoapi.io/stable?f=application/json.

The `f` value should be a simple, yet strict, substitute for the value of an `Accept` header.

**Describe alternatives you've considered**
The alternative is to make no change. I don't like changing API interfaces without a very good reason and I'm not *completely* convinced that this is a very good reason.

**Additional context**
I think if we standardise around this idea, then it also makes related decisions easier, e.g. support for `Accept-Language` in either headers or the URL query parameters.

It might also improve the codebase since it avoids the necessity of "branching" between how we parse the `Accept` header and the `f` parameter.

This proposal allows better future-proofing, e.g. for [`application/json-seq`](https://tools.ietf.org/html/rfc7464).

URLs might require encoding more often than before, if this is implemented.

The OGC API - Features specification has this to say:

> As clients simply need to dereference the URI of the link, the implementation details and the mechanism how the encoding is included in the URI of the link are not important. Developers interested in the approach of a particular implementation, for example, to manipulate ("hack") URIs in the browser address bar, can study the API definition.
>
> Two common approaches are:
> - an additional path for each encoding of each resource (this can be expressed, for example, using format specific suffixes like ".html");
> - an additional query parameter (for example, "accept" or "f") that overrides the Accept header of the HTTP request.

I disagree that it's "not important", but the key message there is that `f` is not a standard anywhere and we're free to use it in the way we judge most appropriate. They also mention that `f` commonly "overrides the Accept header of the HTTP request" - which is not strictly how pygeoapi uses it. Therefore my proposal is that the most appropriate use of `f` is as a strict substitute for the `Accept` header.

**Comment by pvgenuchten** [comment]
in gitter you mentioned: "But I'll admit that I haven't actually seen that pattern in an API before"
The typical use case for this is when you access the api with a browser, the browser will always send accept:text/html, however to explicitely request the json or xml, you need a way to override the browser-accept, the webapp could manage with ajax, but a url-param to override the accept header is far more intuitive. +1 to duplicate accept-header syntax in f=. However also the .html, .xml, .json postfix could be considered, this is also a common approach. But indeed we may then run into problems in more advanced types, such as [application/geopackage+sqlite3](https://www.iana.org/assignments/media-types/application/geopackage+sqlite3) vs [vnd.sqlite3](https://www.iana.org/assignments/media-types/application/vnd.sqlite3)

**Comment by jkreft-usgs** [comment]
probably the biggest challenge I have had with this issue is that the f parameter is a convenience function, and it is a whole lot easier to type `geopackage` than ` application/geopackage+sqlite3` in a script.  

I would be very much against dropping back to file extensions, because of the wide variety of different things that can come out of a single extension.  `.xml` gives you basically no information as to what is going to come out of the other end of the call.

**Comment by tomkralidis** [comment]
This was updated / refactored in the recent i18n updartes via `pygeoapi.api.APIRequest._get_format`.
