### ISSUE TITLE
add pygeoapi as early implementation for OGC API - Features

### ISSUE THREAD

**Issue by tomkralidis** [geopython/pygeoapi#325]
Steps (from OGC):

1. Register your implementation in the OGC database: https://www.opengeospatial.org/resource/products/registration
2. Then link your implementation to the test results in the beta website (once we have our tests fully passing CITE again, we will deploy as https://demo.pygeoapi.io/cite).
3. Your implementation will then appear in the OGC database as an official early implementation and we will waive the license fee for the first year.

Tracking of CITE beta conformance: https://github.com/opengeospatial/ets-ogcapi-features10/issues/85

Note we have passed previous versions of these tests before, so it appears some (hopefully) minor tweaks may be required.

**Comment by tomkralidis** [comment]
Update: almost there.

- fixes/updates in https://github.com/geopython/pygeoapi/tree/cite-beta-testing, which includes a build/setup of a pygeoapi instance for CITE compliance that we can deploy once we fully cover
- https://github.com/opengeospatial/ets-ogcapi-features10/issues/85 (fixed in https://github.com/geopython/pygeoapi/tree/cite-beta-testing)
- https://github.com/opengeospatial/ets-ogcapi-features10/issues/86 (possible CITE bug)

@kalxas thoughts on registering? Should we register under the OSGeo account?

**Comment by kalxas** [comment]
pygeoapi now registered under OSGeo in OGC site.
We need a cite test session id to add to certification list.

**Comment by tomkralidis** [comment]
Update: CITE fixes pushed to master.  Now working on https://github.com/geopython/demo.pygeoapi.io/issues/7

**Comment by justb4** [comment]
We need to fix the [Docker Compose ES example](https://github.com/geopython/pygeoapi/tree/master/docker/examples/elastic). i.e. make it inline with https://github.com/geopython/demo.pygeoapi.io/tree/master/services/pygeoapi_cite.

**Comment by tomkralidis** [comment]
Update:
- https://demo.pygeoapi.io/cite setup
- CITE beta testing results in 4 failures which appear to be [CITE related](https://github.com/opengeospatial/ets-ogcapi-features10/issues/86)

@kalxas can you submit to OGC against CITE beta?  Either run your own session or use username=tomkralidis, session=s0081)

**Comment by kalxas** [comment]
I have reproduced the test on my own session, getting the same errors.

**Comment by kalxas** [comment]
Certification request submitted, waiting for OGC feedback

**Comment by kalxas** [comment]
https://www.opengeospatial.org/resource/products/details/?pid=1606
