### ISSUE TITLE
GeoPackage from Filter for any Provider or at least PostGIS

### ISSUE THREAD

**Issue by geekdenz** [geopython/pygeoapi#329]
**Is your feature request related to a problem? Please describe.**
We want our clients to be able to download GeoPackage files based on a filter, at least for the PostGIS/greSQL provider and maybe for other providers or (at least?) the GeoPackage provider.

**Describe the solution you'd like**
When a user goes to the items page and applies a filter such as a limit or property filter, we would like her to be able to download a GeoPackage file for that subset. Additionally a complete GeoPackage should be downloadable.

**Describe alternatives you've considered**
Just a simple GeoPackage of everything might be enough (for now).

**Additional context**
I believe this topic was discussed on the Gitter channel and it might be possible to use OGR2OGR for this somehow, so as to not reinvent the wheel. Not sure how filtering will work with that though. More research is required.

I am happy to implement this feature.

**Comment by tomkralidis** [comment]
cc @jorgejesus 

@geekdenz some ideas:

can you simply provide the GeoPackage file as a link in the collection metadata for starters?  Further to this, we could implement a GeoPackage [formatter](https://github.com/geopython/pygeoapi/tree/master/pygeoapi/formatter).

**Comment by jorgejesus** [comment]
Adding my 2 cent: 
@geekdenz The best is to use the `?f=geopackage`  optinion suggested by @tomkralidis , this will require that sqlite3 becomes a dependency on the system.

Also @geekdenz  are you taking the lead on this otherwise I could give it a look

**Comment by geekdenz** [comment]
Thanks @tomkralidis and @jorgejesus for the quick answer.

I can do this, but if you want to do it rather, I have no objections. :smiley: 

I've put a bit of effort into finding out how the SWIG binding for GDAL/OGR work. See here:
https://github.com/geekdenz/pygeoapi/blob/gdal-docs/test_gdal_ogr2ogr.py

**Comment by geekdenz** [comment]
I will probably get to doing this next week if I don't get an itch before. :smile:

**Comment by tomkralidis** [comment]
I'm good with whoever work on this. Further comments:
- if we want something cross cutting, a GeoPackage formatter would have a GeoJSON collection as its input (as opposed to filtering a GeoPackage proper).  See https://github.com/geopython/pygeoapi/blob/master/pygeoapi/formatter/csv_.py as an example.  So the idea here is that any data would be filtered and then sent to the formatter

**Comment by geekdenz** [comment]
If there are no objections, I am taking ownership of implementation as my employer is sponsering me to do this and then you can get on with other issues. Also, I have done a day's worth of research on GDAL also in Python and think it would be good use of my time and for my professional development/aspirations.

To answer your comment @tomkralidis: If I understand correctly, it is desirable to also have this work with CSV and GeoJSON data sources. I believe all this can be done somewhat easily with GDAL.

**Comment by geekdenz** [comment]
FYI I managed to get quite far today with GDAL and putting arbitrarily filtered GeoJSON into a GPKG file and offering it for download with ?f=gpkg. The file gets generated, downloaded and is readable with valid features in QGIS. This means that the items endpoint just takes the already filtered GeoJSON and just puts it into a GPKG file that the client can download. Native filters and all providers should work although I have not tested that yet. But I am just reading the features that the API returns after filtering etc. So, there is no dependency on PostGIS or any provider really. Also it seems quite fast using native GDAL code with the GDAL Python API.

**Comment by geekdenz** [comment]
Downloading 10,000 features as GPKG took 13 seconds.

**Comment by bradh** [comment]
That seems quite slow. How long does download as geojson take?

**Comment by pvgenuchten** [comment]
Out of interest, is reading, writing and downloading implemented as a streaming process or is it an in memory process before downloading, sqlite3 may have limitations here...

Besides ?f=gpkg, i assume we also support Accept header application/geopackage+sqlite3

**Comment by geekdenz** [comment]
This is early days for this feature. I suggested we stream responses before but faced resistance because it makes things more complicated with the existing architecture. Currently I couldn't find out how to write the gdal code so that it generates the file in memory. At the moment it writes the file to disc, reads it into memory and sends out to the client. That was the simplest way. I believe it's probably a lot faster and simpler to use the current gdal code. If it becomes a vital feature we can always optimise later. There is no direct dependency on sqlite. Gdal that's used in the Docker container has all required dependencies.

Pre-mature optimisation is the root of all evil. 😉

I don't think the geojson download is much quicker but I'll check. Have to do some refactoring before I can commit because the flare of elif statements made the code too complex according to flake (the code formatter which runs on pre commit hook).

**Comment by geekdenz** [comment]
Accept header will come. Thanks for the reminder though. I haven't even had time to finish the first commit and already got so many comments on this issue. That means you're engaged which is great news! 😀

Thanks everyone!

**Comment by pvgenuchten** [comment]
Writing the file to disk in stead of creating it in memory could actually make sense, because it keeps memory use low, sure it may come with a performance cost, but people could use ssd for the temp folder....

**Comment by geekdenz** [comment]
Also, currently the geojson from the whole process that exists gets parsed into a string and then gets further processed. Of course it will be more optimal to stream everything and/or use the providers directly and implement all the details again. However, it will take valuable human time to do that and waiting a few seconds longer for a large result set of 10,000 features does not yet justify the expense, at least not for us. Remember, default is 100, which is 100 times less and takes less than half a second.

However, implementing it this way means the code is a lot simpler, smaller and reusable, because all filters and providers are guaranteed to work. Also, remember that an advanced user can always use the service directly. GeoPackage is a convenient endpoint if a user wants the data quickly and by quickly I mean little development time in a spatially indexed format.

**Comment by geekdenz** [comment]
The os actually writes files to memory that have the same data in a page lru cache. Also, a user can choose to have /tmp in memory. File systems are very sophisticated these days and do a lot of optimisation. Gdal is optimised as hell. I don't think replacing that bit will gain much in performance and it will definitely take time we can spend on higher priority things imho.

**Comment by geekdenz** [comment]
Btw, GeoJSON download takes much longer:
51 seconds.

**Comment by geekdenz** [comment]
![image](https://user-images.githubusercontent.com/479499/72148754-72e0ba80-3406-11ea-8b44-2121eb70e9ed.png)

is a screenshot of 10,000 polygons of our Land Use Capability dataset in QGIS. With GeoPackage it loaded in an instant.

**Comment by geekdenz** [comment]
@tomkralidis, @jorgejesus and others,

Note that this only works with newer versions of GDAL. I used the UbuntuGIS PPA. Would we consider upgrading it in the Travis and other builds?

**Comment by geekdenz** [comment]
It works and is merged into master. Closing.

**Comment by geekdenz** [comment]
Sorry saw this wrong. It's not merged into master.
