### ISSUE TITLE
add pygeoapi to conda-forge

### ISSUE THREAD

**Issue by tomkralidis** [geopython/pygeoapi#335]
@ocefpaf any advice on how to get pygeoapi onto conda-forge?

**Comment by ocefpaf** [comment]
The first step is to add a recipe in staged-recipes. [Our docs](https://conda-forge.org/docs/maintainer/infrastructure.html#staging-area-for-recipes) are not comprehensive enough but should help a little.

I started a submission in https://github.com/conda-forge/staged-recipes/pull/10592

**Comment by tomkralidis** [comment]
Thanks @ocefpaf

**Comment by tomkralidis** [comment]
Added in https://github.com/conda-forge/pygeoapi-feedstock thanks again @ocefpaf !
