### ISSUE TITLE
Reproducible build with docker

### ISSUE THREAD

**Issue by francbartoli** [geopython/pygeoapi#344]
**Is your feature request related to a problem? Please describe.**
Using tools like [poetry](https://python-poetry.org/) or [pipenv](https://pipenv.readthedocs.io/en/latest/) the docker build could reach the state of a deterministic artifact beyond the problem to have all requirements pinned (`<some package>==x.y.z`)at the current version. Also, this would allow us to publish and tag them only if they pass the build on travis. 

**Describe the solution you'd like**
I would go with [poetry](https://python-poetry.org/docs/cli/) because it is also a good replacement of `setup.py` and it can manage the lifecycle of publishing the package to the pypi repository.
With poetry everything happens in a `pyproject.toml`, even dependencies, so we should adopt it but this might have a high impact.

With poetry:
```Dockerfile
# Upgrade pip
RUN pip install pip --upgrade
# Install poetry:
RUN pip install poetry
# Copy only requirements to cache them in docker layer
# Install pygeoapi
COPY poetry.lock /pygeoapi/poetry.lock
COPY pyproject.toml /pygeoapi/pyproject.toml
# install dependencies from poetry.lock for reproducible builds
RUN POETRY_VIRTUALENVS_CREATE=false poetry install
```

or use tools like [dephells](https://dephell.readthedocs.io/) or [poetrify](https://github.com/kk6/poetrify) to convert from requirements.txt to pyproject.toml:
#### dephell
`dephell deps convert --from=requirements.txt --to=pyproject.toml`
#### poetrify
`poetrify generate -s requirements.txt`

With pipenv:
```shell
#generate Pipfiles from requirements.txt
pipenv install -r requirements.txt
```
In the Dockerfile:

```Dockerfile
# Upgrade pip
RUN pip install pip --upgrade
# Install pipenv
RUN pip install pipenv

# Install pygeoapi
COPY Pipfile /pygeoapi/Pipfile
COPY Pipfile.lock /pygeoapi/Pipfile.lock
# install dependencies from Pipfile.lock for reproducible builds
RUN pipenv install --system --deploy --ignore-pipfile
```

**Describe alternatives you've considered**

**Additional context**

**Comment by frafra** [comment]
I can work on that.
I would prefer pdm instead of Poetry. It still used `pyproject.toml`, but it is less buggy in my experience.

**Comment by francbartoli** [comment]
Hi @frafra, let's discuss that in-depth cause I've been using poetry for three years and haven't found so many issues. I see it is widely used now, but I'm happy to see what are the benefits of pdm as compared to poetry.
I'm very happy you are working with pygeoapi btw 👏

**Comment by frafra** [comment]
Hi @francbartoli :)
I am ok with both of them; I just use pdm since I hit various bugs in Poetry that required years to be fixed. pdm also supports multiple packages group (like prod, dev, test), take the Python version into account when solving the dependencies, and it follows the newer PEPs more closely.

There is something else we could take into account: creating wheels first, and then install them, using a multi-stage Docker image, so we do not have to keep build dependencies in the final image (I briefly mentioned that here: https://github.com/geopython/pygeoapi/pull/1093#issuecomment-1377201128).

**Comment by francbartoli** [comment]
@frafra I would start with the migration from `setup.py` and the different requirements to poetry since its adoption looks broader. If we find issues it's worth moving to something more robust like pdm.
In case you can work on it I'm happy to review it. Also, I believe it's worth creating a specific ticket for that task.

**Comment by frafra** [comment]
@francbartoli I will then use pdm to convert `setup.py` to `pyproject.toml` and then adapt it to Poetry, since Poetry has no import function :-D

**Comment by frafra** [comment]
I noticed that Poetry got better, but is still lagging behind with respect to PEPs, as it does not use [PEP 621](https://peps.python.org/pep-0621/). It uses its own sections, which are Poetry-specific. I wonder if it wouldn't be better to use a standard that can be understood by [setuptools as well](https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html).

**Comment by francbartoli** [comment]
what about [hatch](https://hatch.pypa.io/latest/) that looks pretty much similar to poetry and supports PEP 621?

**Comment by frafra** [comment]
I didn't know about hatch. Poetry is much similar to PDM than hatch. hatch doesn't do dependency pinning, nor it installs dependencies in a virtual env, like Poetry and PDM do.

**Comment by francbartoli** [comment]
you are right, it doesn't install packages and lock the dependencies indeed

**Comment by justb4** [comment]
@frafra Ok, see this now after my comment of #1093 
https://github.com/geopython/pygeoapi/pull/1093#issuecomment-1383901788

**Comment by justb4** [comment]
Question for group: should we proceed with #1093 or #1095. Or #1093 and then #1095? #1095 is quite involved. However we are quite backed by our unit tests (though many fail for unrelated reasons, like stale WFS URLs, .dockerignore etc), but others may be version-pin-related, like GDAL (for e.g. deegree WFS).

**Comment by francbartoli** [comment]
@justb4 I guess you meant [#1105](https://github.com/geopython/pygeoapi/pull/1105), in my opinion that should happen after https://github.com/geopython/pygeoapi/pull/1093. I believe @frafra may ask relevant changes in there before #1093 will be merged.

**Comment by frafra** [comment]
I can rebase mine based on the work that is already being done in PR #1093, which is far closer to being merged compared to #1105.

**Comment by francbartoli** [comment]
Just as a reference to the direction we are taking with #1105, [this](https://chriswarrick.com/blog/2023/01/15/how-to-improve-python-packaging/) is a good comparison to get an idea about the topic. To me, the only concern is about the adoption of a tool at an early stage. I'd like if other PSC's members might express their opinion

**Comment by frafra** [comment]
I agree, that is a major change.
I stumbled on this article yesterday about the state of Python packaging, which provides a great comparison of the existing tools: https://chriswarrick.com/blog/2023/01/15/how-to-improve-python-packaging/

**Comment by justb4** [comment]
Ha, both links refer to the same article. @frafra and @frafra are taking us to next-level Python and Docker! Never too old to learn.

**Comment by francbartoli** [comment]
Too many @fra something between us @justb4 :D

**Comment by justb4** [comment]
Pff I meant @francbartoli ; GH autosuggest :-).
