### ISSUE TITLE
cql filter extension

### ISSUE THREAD

**Issue by pvgenuchten** [geopython/pygeoapi#346]
Opening the discussion for ideas on filtering using cql extension
(https://github.com/opengeospatial/ogcapi-features/tree/master/extensions/cql)

I guess we have 2 options
- implement cql parsing into each data provider
- have a generic cql parser and convert to a set of filters applied in each data provider

From [gitter](https://gitter.im/geopython/pygeoapi?at=5e21b5e8c7647778a5dbf8e8):
IMHO we can use pycql to create an abstract syntax tree (AST) and then each provider handles the AST? https://github.com/geopython/pycql seems to support geometry

**Comment by tomkralidis** [comment]
Note CQL draft is now at http://docs.opengeospatial.org/DRAFTS/19-079.html

**Comment by tomkralidis** [comment]
FYI @francbartoli has implemented this in #670, which needs review.

**Comment by tomkralidis** [comment]
FYI this is now in master with support via the ES provider.  Other providers are open to implement as required.
