### ISSUE TITLE
Task: setup bridge from Gitter to IRC channel #pygeoapi

### ISSUE THREAD

**Issue by jmckenna** [geopython/pygeoapi#351]
- the IRC channel #pygeoapi has been registered on Freenode
- please setup a bridge from Gitter to that channel
- will give Tom ownership of the channel once his nick enters room

Benefits:
- users can join discussions without a Github account, or any account (in your browser at https://webchat.freenode.net/#pygeoapi )

**Comment by tomkralidis** [comment]
@kalxas any idea how we can setup Gitter/OSGeo Slack/IRC bridge?  I think this was also done for pycsw.

**Comment by tomkralidis** [comment]
@kalxas setup the bridge and we're now all connected!  Thanks all.
