### ISSUE TITLE
Display Collection properties on the Collection page

### ISSUE THREAD

**Issue by alexandreleroux** [geopython/pygeoapi#361]
**Is your feature request related to a problem? Please describe.**
Not really. 

**Describe the solution you'd like**
The Collection root page provides a link to browse the collection's items, but doesn't provide any info on the Collection itself. In this feature request I'm proposing to add the list of a Collection properties on the Collection html page.

Example: the Collection demo page https://demo.pygeoapi.io/master/collections/obs could include the list of properties for that collection. That list of properties is found on the table for items, such as https://demo.pygeoapi.io/master/collections/obs/items but not available in the Collection root page.

In addition to the list of properties, the total count of items in the Collection could also be useful.

More related to the current pygeoapi demo site: could the demo's Collection abstract be added to [the collection root page](https://demo.pygeoapi.io/master/collections/obs)? I think that's already supported by pygeoapi.

**Comment by alexandreleroux** [comment]
Related existing ticket: #142

**Comment by pvgenuchten** [comment]
Hi @alexandreleroux, your request makes sense from a web experience perspective. Some comments though (maybe others can share thoughts)
- the 'page' you are referring to is actually a webservice response to a getItems request encoded as html.
- the OGC API specification does indicate to expose only Items information in this webservice response.
- to improve web experience we'd need to grab and display the collection information separately

**Comment by alpha-beta-soup** [comment]
Is there any promise that the features of a feature collection always and everywhere have the same feature properties?

**Comment by justb4** [comment]
> Hi @alexandreleroux, your request makes sense from a web experience perspective. Some comments though (maybe others can share thoughts)
> 
> * the 'page' you are referring to is actually a webservice response to a getItems request encoded as html.
> * the OGC API specification does indicate to expose only Items information in this webservice response.
> * to improve web experience we'd need to grab and display the collection information separately
> 
> Alternatively, we could add a header: "This page lists Items from collection 'xxx', click here for details about 'xxx'."

Briefly looked into: yes the HTML of a single Collection root in pygeoapi basically encodes/formats the (JSON) info which in turn follows the OGC OAPI standard. But I can see the need for such an extension, also in the JSON response: the OAPIF equivalent of WFS `DescribeFeatureType`.
But then also should include type and optionality. "smart" client libs should be able to anticipate the presence of fields (think of pop-up datatables), which may not always be present in each feature (to partly answer @alpha-beta-soup).  As a start each Provider already has a `getFields()` function, though not all implement it.

**Comment by tomkralidis** [comment]
Thoughts:
- the outcome of https://github.com/opengeospatial/ogcapi-features/issues/56 will help guide our implementation
- we *could* implement this as part of the collection description (`/collections/{collectionId}`), but this would mean hitting the data source.  Then again we could also generate the data models and advertise in OpenAPI and then have `/collections/{collectionId}` use those (thus not hitting the data source)

**Comment by tomkralidis** [comment]
We've since implemented the `/collections/{collectionId}/queryables` endpoint which provides this functionality.  Downstream applications can integrate this on their `/collections/{collectionId}` HTML templates as desired.
