### ISSUE TITLE
sqlite driver doesn't handle query parameters correctly when resulttype=hits

### ISSUE THREAD

**Issue by jorgejesus** [geopython/pygeoapi#370]
**Description**

See #299  but for sqlite

**Comment by Moritz-Langer** [comment]
If this is still relevant I can look into it. 

Desired behaviour is when resulttype=hits then the result should be the count of features? And if there is additional query parameters for example id = 2 the result should be 1? Or if you filter for something else you expect the number of features where this filter applies to.
