### ISSUE TITLE
Provide feature response data model via OpenAPIDocument

### ISSUE THREAD

**Issue by pvgenuchten** [geopython/pygeoapi#375]
This is a placeholder to have some discussion around the ability to provide a datamodel of a set of features before actually querying the data itself. In WFS this functionality is available as the describefeaturetype request.

In the OAPI world this part is typically managed in the OpenAPIDocument. For service responses, response models are defined.

Seems OGC decided to leave this part out of the initial specification. [A generic response model](http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/schemas/featureGeoJSON.yaml) is defined for the fixed aspects of any featuretype encoded as geojson, such as identification, geometry and time. Other parts are left to the implementation (defined as "object"). In OpenAPI this aspect is very uncommon and challenging, because it means a developer has to go in and develop some custom code specific to the featuretype. Else generic code could have been used to manage retrieving, creating and updating of features. 

The OpenApiDocument is also a relevant location to specify additional details of attributes, such as field type, codelist to use, definition of the attribute, those aspects which are currently generally specified in feature catalog (ISO19110).

Some aspects of the specification of feature attributes can be automatically extracted from the source data (eg fieldname, fieldtype, fieldlength). Others may require a configuration (eg attribute definition, codelist).

Consider that some formats already contain a reference to their datamodel, such as xml (xsd/dtd) and json-ld. Maybe these formats can use parts of the functionality mentioned here to generate these datamodel specifications.

**Comment by pvgenuchten** [comment]
What would be interesting to research is if we can specify a response format for the specific parts only and let it inherit from the generic response model. 
Swagger seems to support that case via the allof keyword
https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism

**Comment by francbartoli** [comment]
This is relevant, I believe it is partially covered by queryables though. However, that would improve the consumption of the openapi document a lot
