### ISSUE TITLE
openApiDocument currently only lists geojson as a response encoding

### ISSUE THREAD

**Issue by pvgenuchten** [geopython/pygeoapi#376]
OpenApiDocument should be extended to indicate support for alternative encodings besides geojson (if enabled), such as application/json-ld, application/geopackage+sqlite3

Currently we link to definitions provided at OGC, which do not advertise these additional response encodings.

![image](https://user-images.githubusercontent.com/299829/76397006-98446300-637a-11ea-8ba5-3bc46197e81b.png)

references:

![image](https://user-images.githubusercontent.com/299829/76397182-eb1e1a80-637a-11ea-87b3-f4e44472a3e1.png)

We probably have to bring that file local and advertise whatever is configured on the server (maybe some users want to (de)activate certain response encodings with plugins).

Verify that it does not impact the validation result, may require a configuration "strict", which removes any mentions to non supported encodings by the specification.

**Comment by ajinkyajawale14** [comment]
Hi, I would like to work on this issue
Thanks

**Comment by pvgenuchten** [comment]
Thank you @ajinkyajawale14, that would be great.
