### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ajinkyajawale14** [geopython/pygeoapi#386]
**Description**

**Steps to Reproduce**

**Expected behavior**

**Screenshots/Tracebacks**

**Environment**
 - OS:
 - Python version: 
 - pygeoapi version: 

**Additional context**

**Comment by francbartoli** [comment]
@ajinkyajawale14 what does this mean?

**Comment by alpha-beta-soup** [comment]
This isn't the only blank error made by this user, e.g. https://github.com/BioGearsEngine/core/issues/32

I think this user is trying to surreptitiously inflate their Github presence, and this can be closed.
