### ISSUE TITLE
Property filtering for OGR Provider

### ISSUE THREAD

**Issue by justb4** [geopython/pygeoapi#398]
**Is your feature request related to a problem? Please describe.**
Property (attribute filtering) is not yet supported by OGR Provider.

**Describe the solution you'd like**
A Property (attribute filtering) should be supported by OGR Provider.

**Describe alternatives you've considered**
N.A.

**Additional context**
There is an existing PR: https://github.com/geopython/pygeoapi/pull/220 by @ynte , this should be taken as start of solution.

**Comment by francbartoli** [comment]
@justb4 Can we consider this closed?

**Comment by justb4** [comment]
Yes! Closing...
