### ISSUE TITLE
Errors in OpenAPI Document

### ISSUE THREAD

**Issue by justb4** [geopython/pygeoapi#399]
**Description**
The OpenAPI HTML service pages gives errors on page and in JS console

**Steps to Reproduce**
* go to https://demo.pygeoapi.io/master (latest master version)
* select OpenAPI doc as HTML: https://demo.pygeoapi.io/master/openapi?f=html
* select items from any collection, e.g. https://demo.pygeoapi.io/master/openapi?f=html#/obs/get_collections_obs_items
* observe error-emojis in page and errors in JS console (see screenshot below)
 
**Expected behavior**
No errors and texts for I think `properties` (attr filtering) and `bbox` filtering

**Screenshots/Tracebacks**
![image](https://user-images.githubusercontent.com/582630/79117695-1c2fa780-7d8c-11ea-8863-9721f069a4b1.png)

**Environment**
 - OS: any
 - Python version: 3.7
 - pygeoapi version: master as on april 13, 2020

**Additional context**
N.A.

**Comment by tomkralidis** [comment]
This appears to be the same problem as #312 (root cause https://github.com/opengeospatial/ogcapi-features/issues/276).  I have reached out again on the OGC ticket.

Until then, anyone running pygeoapi via HTTP will have a broken Swagger UI; options:

1. Use `server.ogc_schemas_location` as per https://docs.pygeoapi.io/en/latest/configuration.html#server and reference locally
2. copy YAML schemas tree into codebase and reference locally (we do this in pycsw, repo size obviously increases but stable/locked down)
3. other options?

**Comment by tomkralidis** [comment]
For option 1:

```bash
mkdir /tmp/schemas.opengis.net && cd $_
curl -O http://schemas.opengis.net/SCHEMAS_OPENGIS_NET.zip  && unzip SCHEMAS_OPENGIS_NET.zip
# edit pygeoapi config to point `server.ogc_schemas_location` to `/tmp/schemas.opengis.net`
# regenerate OpenAPI doc.
```

**Comment by justb4** [comment]
Q: for option 1, which (http) server actually serves the files? pygeoapi itself?  saw, think api.py,  that the config url is prepended to the unpacked file location..is an external apache server assumed?

Other option is a schemas.pygeoapi.io server with yaml files served from dedicated GitHub repo with that name using a CNAME. That includes https support. Or am I missing something completely?

**Comment by tomkralidis** [comment]
For Option 1, the actual pygeoapi deployment serves the files (see https://github.com/geopython/pygeoapi/blob/master/pygeoapi/flask_app.py#L63-L90).

Once OGC completes HTTPS support on schemas.opengis.net, we would change the default location to https://schemas.opengis.net (baked in [pygeoapi OpenAPI generation](https://github.com/geopython/pygeoapi/blob/master/pygeoapi/openapi.py#L42)), but having servers be able to host their own schemas would still be an option.

**Comment by justb4** [comment]
Ok, I see, my pref is hosting on GH. Not even a `gh-pages` branch is required these days, only some settings in repo, a `/docs` dir in repo, defining a CNAME in DNS (deployed a Hugo site for tv.osgeo.nl last week). But then probably CORS is required (?) so also for sake of progress happy with option 1.

**Comment by justb4** [comment]
Yes, can confirm: the errors are gone when serving schema files locally: see e.g. https://demo.pygeoapi.io/master/openapi?f=html#/lakes/get_collections_lakes_items
