### ISSUE TITLE
ArcGIS Javascript API Client Example

### ISSUE THREAD

**Issue by patgeocomm** [geopython/pygeoapi#401]
We've been researching using the ArcGIS Javascript API (4.14) as a client for pygeoapi feature services, but haven't had any success.  We've been looking for documentation with guidance or samples but haven't found any.  Is this possible at present?

An example that uses the ArcGIS Javascript API to display features served from a pygeoapi endpoint (if possible) would be very helpful indeed.

We've made attempts to use Esri's `FeatureLayer` class, as well as the `WFSLayer`.

(As an aside:  This is great project. Kudos to everyone involved!)

**Comment by tomkralidis** [comment]
@patgeocomm thanks for the report.  This is probably a good question for ArcGIS JavaScript API, and whether OGC API - Features is supported.

**Comment by patgeocomm** [comment]
Many thanks for your reply!  As we address it from that angle we'll report any findings (with examples if we get something working).

**Comment by tomkralidis** [comment]
OK, great.  Feel free to re-open this issue if required.
