### ISSUE TITLE
fix RTD autobuild

### ISSUE THREAD

**Issue by tomkralidis** [geopython/pygeoapi#402]
**Description**
I’m finding that RTD is not auto-building latest. I have force built the last two builds (last automated build was a 5 weeks ago)

**Steps to Reproduce**
See RTD pygeoapi admin builds

**Expected behavior**
pygeoapi docs on RTD should rebuild on each commit

**Screenshots/Tracebacks**

**Environment**
 - OS:
 - Python version: 
 - pygeoapi version: 

**Additional context**

**Comment by jorgejesus** [comment]
On RTD everything looks ok, the webhook seems to have been activated only 2 months ago. Conf looks OK just made a webhook resync.

Could be something on the side of github?? https://docs.readthedocs.io/en/stable/webhooks.html

I dont have permissions to see it?? @tomkralidis  ???

**Comment by jorgejesus** [comment]
The RTD webhook is now returning `200`. The webhooks/integrations had to be deleted on both systems and then first recreated on RTD and then on github.

The github diplaied a new page structure, seems that out projected needed some sort of internal update.

On github ticked the option for automatic rebuild upon milestone changes **(Milestone created, closed, opened, edited, or deleted.)**
