### ISSUE TITLE
clarify the status of each data provider 

### ISSUE THREAD

**Issue by jorgejesus** [geopython/pygeoapi#403]
Clarify reach data provider capabity for pagging, property filter, bbox, datetime, determine maintainer and status. Test status of each data provider

**Comment by tomkralidis** [comment]
also:
- add docs on contributing a data provider plugin
- ensure automated tests cover the requirements/policy to help regression testing over time

**Comment by jorgejesus** [comment]
Situation om  27 june 2020 and commit https://github.com/geopython/pygeoapi/commit/7766e2533ce487dc3cef158bc02ae56ccebf6b72


Data provider | properties | resulttype | bbox | datetime | sortby | maintainer
-- | -- | -- | -- | -- | -- | --
csv | YES | ALL | NO | NO | NO | Tom Kralidis
elasticsearch | YES | ALL | YES | YES | YES | Tom Kralidis
geojson | YES | ALL | NO | NO | NO | Matthew Perry
mongo | YES | RESULTS | YES | YES | YES | Timo Tuunanen
ogr | YES | ALL | YES | NO | NO | Just van den Broecke /Francesco Bartoli
postgresql | YES | ALL | YES | NO | NO | Jorge Samuel Mendes de Jesus, Tom Kralidis, Mary Bucknell
sqlite | YES | ALL | YES | NO | NO | Jorge Samuel Mendes de Jesus, Tom Kralidis, Mary Bucknell
