### ISSUE TITLE
 support OGC API - Records 

### ISSUE THREAD

**Issue by tomkralidis** [geopython/pygeoapi#404]
[Support the OGC API - Records](https://github.com/opengeospatial/ogcapi-records) specification.

**Comment by pvgenuchten** [comment]
Tom, there's a workplan for this?
- As a start, we could expose the current collections in the service described as records, using existing metadata provided in the config files (already interesting to see how that works, linking from the record to the endpoint and vice versa)
- Use various backends to store records
  - a relational database having a field containing the full record as a json/xml blob (gpkg, shape, postgis)
  - a folder(hierarchy) of json/xml files (probably requires to be indexed into something else)
  - An elastic search instance using a specific metadata model (stac/geonetwork/pycsw)
For blob and file stores, we need a machanism to ingest various metadata models into queryable parameters, we can start with one or two models (iso19139, stac), later extend to others like iso19115:2018, dcat, schema.org/Dataset, qgis, etc.

**Comment by tomkralidis** [comment]
@pvgenuchten thanks for the feedback.  I've started a branch in https://github.com/tomkralidis/pygeoapi/tree/oarec to follow the specification development (given our participation on the OGC API - Records SWG).  In terms of the various workflows:

- exposing current collections: I'm thinking this would be the pygeoapi 'local' catalogue.  How would we populate this in pygeoapi?  We would need an index of some sort that does spatial, for example.  Maybe the 'local' catalogue can be generate into an SQLite/Spatialite file and then be published by the SQLite backend in pygeoapi.  Has anyone considered [Whoosh](https://whoosh.readthedocs.io/en/latest/intro.html) as an option for a really lightweight search engine?  The only workaround would be storing bbox as numeric minx/miny/maxx/maxy columns and apply range queries.  I imagine SQLite/Spatialite with FTS would work too?
- @pvgenuchten do you have any sample of gpkg/shape of metadata?
- other backends can be implemented as provider plugins.  For example, the work in https://github.com/tomkralidis/pygeoapi/tree/oarec simply adds `q=` functionality to the pygeoapi ES provider and done.

**Comment by tomkralidis** [comment]
Implemented in #631 (collection of records).
