### ISSUE TITLE
on small devices long url in attribute expands table outside window

### ISSUE THREAD

**Issue by pvgenuchten** [geopython/pygeoapi#411]
attributes having a long non breakable string, like a url expand the screen outside the window, resulting in strange results

![F969BB19-3849-467D-99ED-C177CA882B25](https://user-images.githubusercontent.com/299829/79427907-b464a100-7fc5-11ea-85f2-3feb718c2fba.png)

colleague suggestion to add this css

```
display: block;
white-space: nowrap;
overflow: hidden;
text-overflow: ellipsis;
max-width: calc(100vw - 100px);
```

but we could also use a jinja filter to limit the string to a certain number of characters

**Comment by tomkralidis** [comment]
@pvgenuchten does this happen on the items page, the single item page, or both?
