### ISSUE TITLE
create documentation

### ISSUE THREAD

**Issue by tomkralidis** [geopython/pygeoapi#43]
Create documentation using [Sphinx](http://www.sphinx-doc.org) or [MkDocs](http://www.mkdocs.org/).

**Comment by tomkralidis** [comment]
Not sure why this was closed.  Reopening.

**Comment by justb4** [comment]
@jorgejesus thanks! Can you add @tomkralidis and me to the RTD project? at https://readthedocs.org/projects/pygeoapi/ . Think we need to change the repo location and default branch. Later we can link https://docs.pygeoapi.io and link from https://pygeoapi.io home.

**Comment by tomkralidis** [comment]
We have an initial implementation in http://docs.pygeoapi.io/en/latest and are in the process of updating via #277
