### ISSUE TITLE
create pygeoapi workshop

### ISSUE THREAD

**Issue by tomkralidis** [geopython/pygeoapi#434]
Given we now have [documentation](https://docs.pygeoapi.io), it would be a great to provide a pygeoapi workshop.  We scratch the surface of pygeoapi in the [geopython workshop](https://geopython.github.io/geopython-workshop), but an in depth workshop would be valuable for those wanting a deeper dive into pygeoapi beyond the docs.

Things to consider:
- maintenance: as pygeoapi matures, what commitments do/should we have to keep the workshop up to date?
- technical infrastructure:  Docker/Jupyter?  Other ideas?
- scope should be to deliver for in person workshop, virtual, or independent study
- areas to cover / table of contents?  We can use the docs outline as a starting point
- length?  Suggest we cover a 3 hour scenario (to cover for questions, etc. for live delivery)

**Comment by tomkralidis** [comment]
Summary, from @pvgenuchten via https://lists.osgeo.org/pipermail/pygeoapi/2020-September/000139.html

- installation and audience skill level.  We need to consider time to install/ramp up (faster=better). Options:
  - docker install on cloud
  - 5 minute install
- data theme?  Depending on time, location, we would want to setup a test data suite (raster, vector, process) depending

Potential items in the workshop:
- Set up a service (local/docker) using some prepared data (and/or existing WFS)
- Connect via GDAL or QGIS or OWSLib
- View data through a web interface, analyze in google structured data tools (advanced; set up a service with json-ld context; analyse in testing tool)
- STAC search/browse with some STAC client
- setup a process, use process via OpenAPI document

**Comment by justb4** [comment]
Closing, we have the created and even provided the Workshop Diving into pygeoapi, maintained at:
https://github.com/geopython/diving-into-pygeoapi

**Comment by tomkralidis** [comment]
For good measure, added a link in the main docs ToC page to https://dive.pygeoapi.io
