### ISSUE TITLE
GPKG: Extension loading not enabled

### ISSUE THREAD

**Issue by pvgenuchten** [geopython/pygeoapi#436]
Maybe this is a problem of qgis 3.12, but when i create a geopackage in qgis and load it as a source in pygeoapi, it gives me this error:

[2020-05-17T00:49:19Z] {/Users
/geopython/pygeoapi/provider/sqlite.py:185} ERROR - Extension loading not enabled: 'sqlite3.Connection' object has no attribute 'enable_load_extension'

I guess this is related to [extension loading](https://www.sqlite.org/c3ref/enable_load_extension.html) being disabled, but i have no clue how to enable that, a bug? or else can we write some documentation?

GPKG created from a shapefile downloaded from https://data.isric.org
[soil.gpkg.zip](https://github.com/geopython/pygeoapi/files/4639359/soil.gpkg.zip)

**Comment by tomkralidis** [comment]
cc @francbartoli / @jorgejesus 

Not sure if #349 is related or not.

**Comment by pvgenuchten** [comment]
Indeed, that seems related (I’m also running on macOS), or is it a SQLite version thing?

**Comment by francbartoli** [comment]
@pvgenuchten have you already tried to follow https://docs.pygeoapi.io/en/latest/development.html#working-with-spatialite-on-osx?

**Comment by pvgenuchten** [comment]
Closing this, because it's a known issue and documented (although i have not been able to solve it yet). I indeed use a combination of pyenv and brew...

**Comment by jorgejesus** [comment]
For the record, yes it is related to #349 and is also on stackoverflow https://stackoverflow.com/questions/58892028/sqlite3-connection-object-has-no-attribute-enable-load-extension/59963751#59963751

The solution proposed by @francbartoli  worked, it can be that you are pulling the python package from another place
