### ISSUE TITLE
geopackage as catalogue storage

### ISSUE THREAD

**Issue by pvgenuchten** [geopython/pygeoapi#438]
Geopackage has a [standardised mechanism to store metadata records](https://www.geopackage.org/spec121/#extension_metadata). pygeoapi could use that storage mechanism to store records which are published via the OGC API Records service. Records can easily be served, but also updated and created.

The metadata extension of geopackage is quite limited with regards to enabling queries on fields. A suggestion could be to [define an extension to the metadata table](https://github.com/opengeospatial/geopackage/issues/526) to store aspects such as spatial coverage, date issued, title, language. These fields would need to be filled from the metadata content at creation.

Alternative option would be to store these fields separately from the geopackage, for example in a full-text-search engine such as elastic/noise/whoosh.

**Comment by tomkralidis** [comment]
Relevant discussion in https://github.com/opengeospatial/geopackage/issues/526

**Comment by tomkralidis** [comment]
I think there may be room for a GPKG with:
- JSON data typing for metadata (thinking OARec model, or native MCF model), OR a text column called `metadata` that would be qualified by `metadata_schema` and `metadata_format` columns (i.e. `http://www.isotc211.org/2005/gmd`/`application/xml`, `http://www.opengis.net/spec/ogcapi-record-1/1.0/conf/record-model`/`application/json`, etc.)
- columns representing core queryables (some of which can be JSON types themselves depending on the content model of the queryable
- FTS5 index to facilitate full-text search

**Comment by tomkralidis** [comment]
FYI we have gone with TinyDB as a default backend storage mechanism for low barrier use cases.
