### ISSUE TITLE
implement CQL filter specifications in OpenAPI document

### ISSUE THREAD

**Issue by FarheenB** [geopython/pygeoapi#441]
Implement CQL filter specifications (https://github.com/opengeospatial/ogcapi-features/tree/master/extensions/cql) as OpenAPI Document

**Comment by francbartoli** [comment]
@jorgejesus @FarheenB I think the first decision to take would be how to handle the CQL extension versus the configuration file. Is this active by default along all the resources? Likely a fine-grained configuration it's easy to manage if not all providers are able to support the extended query model

**Comment by jorgejesus** [comment]
@francbartoli @FarheenB 
Here is more or less how I see it:

- CQL support defined at dataprovider level using config file (fine-grained)
- By default it should not be active unless defined on config file (idea that it is only implement if specifically asked for, avoid extra rest end point, secutiry problems etc etc)
-  Question: The `queriables` REST points should be avaiaible even  if not implemented ??? I think so, these REST points show complience to implementation of annex even if they are empty

**Comment by FarheenB** [comment]
- Doubt: As far as i understood Requirement36 of http://docs.opengeospatial.org/DRAFTS/19-079.html#cql-json is about creating predicate, expressions and operators' definitions. I looked into its implementation in openAPI but "definitions" paradigm was supported in swagger 2.0 and is no more supported in 3.0.

- Comment by @jorgejesus : https://swagger.io/specification/v2/#definitionsObject in V3 and things are different, the definition is more or less like components Object --> Schema Object and the schema object should be the CQL definitions.

Should i consider definitions as components for pygeoapi openAPI doc?

**Comment by francbartoli** [comment]
Are you saying that these two json files here https://github.com/opengeospatial/ogcapi-features/tree/master/extensions/cql/schema are not valid with the openapi v3 spec?

**Comment by FarheenB** [comment]
yes the references like this **{"$ref": "#/definitions/intersects"}** to a definition is not compatible with v3 spec https://swagger.io/docs/specification/basic-structure/ but was previously available in v2 as can be seen in https://swagger.io/docs/specification/2-0/basic-structure/ spec under "Input and Output Models" section.

**Comment by FarheenB** [comment]
if we follow https://swagger.io/docs/specification/basic-structure/ "Input and Output Models" section and replace reference a definition {"$ref": "#/definitions/intersects"}  to reference components/schemas like this {"$ref": "#/components/schemas/intersects"} then the problem of describing any operators or expressions (given here https://github.com/opengeospatial/ogcapi-features/tree/master/extensions/cql/schema ) will be solved.

**Comment by francbartoli** [comment]
Ok thanks, I understood now. Can we open an issue over there since accordingly with the core schema we are not interested in v2?

**Comment by FarheenB** [comment]
so should we open an issue something like #339?

**Comment by francbartoli** [comment]
We should open an issue for the two files below:

- [cql.json](https://github.com/opengeospatial/ogcapi-features/blob/master/extensions/cql/schema/cql.json)
- [filter-capabilities.json](https://github.com/opengeospatial/ogcapi-features/blob/master/extensions/cql/schema/filter-capabilities.json)

which are not aligned to OpenAPI v3 spec accordingly with your investigation

**Comment by FarheenB** [comment]
opened an issue [https://github.com/opengeospatial/ogcapi-features/issues/400 #400] regarding this problem

**Comment by FarheenB** [comment]
@francbartoli their reply https://github.com/opengeospatial/ogcapi-features/issues/400#issuecomment-643195598

**Comment by francbartoli** [comment]
Sorry @FarheenB, I didn't notice the first lines of the json schema. However, I think there is snippets of OpenAPI v3 fragment in each requirement of the CQL extension.

Look here https://github.com/opengeospatial/ogcapi-features/blob/master/extensions/cql/standard/requirements/filter/REQ_filter-lang-param.adoc for example. Grabbing them for each of the extension parameters we can build then the final yaml schema

**Comment by jorgejesus** [comment]
@francbartoli  I was just commenting with @FarheenB , would this be the implementation snippet for json-cql ?
```
 /collections/obs:
    post:
      description: cql-json request
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'https://github.com/opengeospatial/ogcapi-features/blob/master/extensions/cql/schema/cql.json'
      responses:
        200:
          $ref: http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/ogcapi-features-1.yaml#/components/responses/Features
```

- Basically we point to the  `cql.json` json schema

**Comment by FarheenB** [comment]
@francbartoli I used the very same snippets as this https://github.com/opengeospatial/ogcapi-features/blob/master/extensions/cql/standard/requirements/filter/REQ_filter-lang-param.adoc in my doc https://github.com/FarheenB/pygeoapi/blob/master/CQL_openapi_doc_proposal.yaml for requirements 6.1 6.2 and  6.3 of http://docs.opengeospatial.org/DRAFTS/19-079.html which follows OpenAPI 3.0 spec.

**Comment by FarheenB** [comment]
@francbartoli discussion is for requirement 36 of http://docs.opengeospatial.org/DRAFTS/19-079.html#cql-json

**Comment by francbartoli** [comment]
@jorgejesus I don't know actually if OpenAPI spec allows to reference a JSON schema rather than a fragment of a YAML one. Have you already checked?

**Comment by jorgejesus** [comment]
I have checked on the openapi docs:
https://swagger.io/docs/specification/using-ref/
```
URL Reference – $ref: 'http://path/to/your/resource' Uses the whole document located on the different server.
    The specific element of the document stored on the different server – $ref: 'http://path/to/your/resource.json#myElement'
```
I am assuming that that it is not a problem to link to a json-schema

I also see:

```
OpenAPI 3.0 uses an extended subset of JSON Schema Specification Wright Draft 00 (aka Draft 5) to describe the data formats
```
While: http://docs.opengeospatial.org/DRAFTS/19-079.html#cql-json
Indicates :

```
"$schema": "http://json-schema.org/draft-07/schema#",
```
A miss match between json-schema and openapi3 spec? ??

**Comment by FarheenB** [comment]
@jorgejesus I can try implementing this and will see if there are any discrepancies

**Comment by francbartoli** [comment]
@jorgejesus @FarheenB my understanding from the link above of the openapi docs is that:

- the link of an URI could be a json-schema resource per se but then the OpenAPI document would not be able to interpret the content and generate the swagger file properly
- we should translate that json-schema to something like:

```json
"components": {
  "schemas": {
    "user": {
      "properties": {
        "id": {
          "type": "integer"
        },
        "name": {
          "type": "string"
        }
      }
    }
  }
}
```

or exactly the same with the variant format

```yaml
components:
  schemas:
    User:
      properties:
        id:
          type: integer
        name:
          type: string
```

However, I will open a new ticket for the hack with the generation of the pygeoapi openapi document.

**Comment by FarheenB** [comment]
@francbartoli so as you said should i go with this approach https://github.com/geopython/pygeoapi/issues/441#issuecomment-642825579

**Comment by francbartoli** [comment]
@FarheenB yes, I would initially give a try with [this tool](https://gitlab.com/InstaffoOpenSource/DataScience/jsonschema-to-openapi). Then we can look at the result and see if some manual refinement is required or not. Finally, we can optionally propose the two schemas as a PR to the OGC repo.

**Comment by FarheenB** [comment]
Ok, I will check this.

**Comment by FarheenB** [comment]
@francbartoli @jorgejesus I used [this tool](https://gitlab.com/InstaffoOpenSource/DataScience/jsonschema-to-openapi) to convert [cql.json](https://github.com/opengeospatial/ogcapi-features/blob/master/extensions/cql/schema/cql.json) to yaml with some manual refinement as per https://github.com/geopython/pygeoapi/issues/441#issuecomment-643404501. 

Added the expressions and operators definitions as per https://github.com/geopython/pygeoapi/issues/441#issuecomment-642825579.

Please check whether this will work or not https://app.swaggerhub.com/apis/FarheenB/pygeoapi/3.0

**Comment by francbartoli** [comment]
Nice, well done

**Comment by FarheenB** [comment]
thank you @francbartoli 
@francbartoli @jorgejesus  In my OpenAPI doc https://app.swaggerhub.com/apis/FarheenB/pygeoapi/3.0 I have implemented both the json files:

- [cql.json](https://github.com/opengeospatial/ogcapi-features/blob/master/extensions/cql/schema/cql.json)
- [filter-capabilities.json](https://github.com/opengeospatial/ogcapi-features/blob/master/extensions/cql/schema/filter-capabilities.json)

**Comment by jorgejesus** [comment]
> @francbartoli I was just commenting with @FarheenB , would this be the implementation snippet for json-cql ?
> 
> ```
>  /collections/obs:
>     post:
>       description: cql-json request
>       requestBody:
>         required: true
>         content:
>           application/json:
>             schema:
>               $ref: 'https://github.com/opengeospatial/ogcapi-features/blob/master/extensions/cql/schema/cql.json'
>       responses:
>         200:
>           $ref: http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/ogcapi-features-1.yaml#/components/responses/Features
> ```
> 
>     * Basically we point to the  `cql.json` json schema



> thank you @francbartoli
> @francbartoli @jorgejesus In my OpenAPI doc https://app.swaggerhub.com/apis/FarheenB/pygeoapi/3.0 I have implemented both the json files:
> 
>     * [cql.json](https://github.com/opengeospatial/ogcapi-features/blob/master/extensions/cql/schema/cql.json)
> 
>     * [filter-capabilities.json](https://github.com/opengeospatial/ogcapi-features/blob/master/extensions/cql/schema/filter-capabilities.json)


The ecample  indicatedis miss leaading and is inccorect

**Comment by francbartoli** [comment]
Initial comments:

- https://github.com/FarheenB/pygeoapi/blob/7577ca8c24a9b143122a087e44a783f2d0a47cf6/cql_openapi_doc.yaml this file does make sense to me. What would be its rqationale?

- https://github.com/FarheenB/pygeoapi/blob/7577ca8c24a9b143122a087e44a783f2d0a47cf6/example-config.yml and https://github.com/FarheenB/pygeoapi/blob/7577ca8c24a9b143122a087e44a783f2d0a47cf6/example-config.yml don't have to be committed

- https://github.com/geopython/pygeoapi/compare/master...FarheenB:openapi-cql#diff-bef210239884d892a2f3a407f51a3518R69 has to load a custom yml file for the configuration of openapi tests, it can be a simple copy of the original `pygeoapi-test-config.yml` with the addition that you made here https://github.com/FarheenB/pygeoapi/blob/7577ca8c24a9b143122a087e44a783f2d0a47cf6/tests/pygeoapi-test-config.yml:

```shell
    with open(get_test_file_path('pygeoapi-test-openapi-config.yml')) as fh:
```

- overall I started from scratch with the repo and followed the configuration steps from docs but I cannot find anything related to CQL in the returned openapi document either html or json:

```shell
  cp pygeoapi-config.yml example-config.yml
   vi example-config.yml
   #####################
   # added the following under `obs`
   filters:
       - cql-text
       - cql-json
   #####################
   export PYGEOAPI_CONFIG=example-config.yml
   export PYGEOAPI_OPENAPI=example-openapi.yml
   pygeoapi generate-openapi-document -c $PYGEOAPI_CONFIG > $PYGEOAPI_OPENAPI
   pygeoapi serve
   curl http://localhost:5000
```

Also, giving a quick look at the test code it looks like that some assertions are not good since they should, at least, check for the presence of a schema for filter and filter-lang and then assert the elements within the schemas.

**Comment by FarheenB** [comment]
@francbartoli i have done all the changes that you asked for.

- Are you still not able to generate the openapi document? Because I am able to generate it on my local, following the same steps as you mentioned.

- I am in process on rewriting the test cases all over again. Will commit the changes once its done.

**Comment by francbartoli** [comment]
@FarheenB I have captured these attached errors in the browser. Did you open up it at [http://localhost:5000/openapi?f=html#/obs/get_collections_obs_items](http://localhost:5000/openapi?f=html#/obs/get_collections_obs_items) to check the openapi document?![console_errors_at_obs_items.png](https://app.gitkraken.com/api/glo/boards/5ed8f82c9ea51d001111b74b/attachments/5ef4eb7c42d43000111166c1)
![errors_swagger_page.png](https://app.gitkraken.com/api/glo/boards/5ed8f82c9ea51d001111b74b/attachments/5ef4eb7984d55700114ff475)

**Comment by francbartoli** [comment]
After a deeper look, some of the above errors are already present in the base code of pygeoapi, they need more investigation. However, the url parameters from the CQL extension doesn't appear in the swagger page cc @jorgejesus

**Comment by FarheenB** [comment]
- @francbartoli After you posted this issue I went back to master branch and deployed it to recreate the issue that you were facing. And I got the same error as yours in the base code.

I have attached the screenshots for your reference: CC @jorgejesus 

![image](https://user-images.githubusercontent.com/59408650/85905527-3f191600-b829-11ea-95cf-e4132c1a317a.png)

![image](https://user-images.githubusercontent.com/59408650/85905565-5b1cb780-b829-11ea-9891-29588dd1a924.png)


- With reference to the generation of openapi document with my changes either in html or json: 
Did you run **python setup.py install** could you please try running this command after the making changes in example_config.yml file. I am able to see the document with CQL generation.

For your reference: 
![image](https://user-images.githubusercontent.com/59408650/85906736-db90e780-b82c-11ea-8f09-dc92a87344e4.png)

![image](https://user-images.githubusercontent.com/59408650/85906751-e5b2e600-b82c-11ea-8f35-66d48a932ada.png)

Even the parameters are getting generated:
![image](https://user-images.githubusercontent.com/59408650/85906762-f2cfd500-b82c-11ea-8fae-96a6e79c37f5.png)

**Comment by FarheenB** [comment]
@francbartoli @jorgejesus 

- According to my understanding, I have restructured the code such that the swagger html or json document is generated with respect to CQL extension. If the config file has filters extension then the CQL OpenAPI document is generated as the screenshot attached above or else the document remains as the original one with query parameters or filter schemas. 
Please find my new commit on openapi.py here https://github.com/FarheenB/pygeoapi/commit/e3a67e632145453f2f05b2e8d912bd1f66b0cadb

- I have also added a new test case which now performs tests on cql extensions only if the config file of the provider supports it. In case of NO CQL config all the assertions in test_cql_filters() fails.
Please review it once https://github.com/FarheenB/pygeoapi/commit/6d69b2269dc8dc3d772a0d050d4551cb8d3a528c

Need your suggestion to proceed further. Also would like to know whether am understanding is right or wrong.

**Comment by francbartoli** [comment]
Overall tests are failing with me:

```python
pytest tests/test_openapi.py
============================================================================================= test session starts ==============================================================================================
platform darwin -- Python 3.7.6, pytest-5.3.4, py-1.8.1, pluggy-0.13.1
rootdir: /Users/geobart/code/test/pygeoapi, inifile: pytest.ini
plugins: env-0.6.2, subtests-0.2.1, hypothesis-5.10.4, schemathesis-1.3.1, cov-2.8.1
collected 2 items

tests/test_openapi.py .F                                                                                                                                                                                 [100%]

=================================================================================================== FAILURES ===================================================================================================
_______________________________________________________________________________________________ test_cql_filters _______________________________________________________________________________________________

get_oas_30_ = {'components': {'parameters': {'f': {'description': 'The optional f parameter indicates the output format which the se...api/ogcapi-features-1.yaml#/components/responses/ServerError'}}, 'summary': 'Get Observations items', ...}}, ...}, ...}
config = {'logging': {'level': 'ERROR'}, 'metadata': {'contact': {'address': 'Mailing Address', 'city': 'City', 'country': 'Cou...}}, 'server': {'bind': {'host': '0.0.0.0', 'port': 5000}, 'cors': True, 'encoding': 'utf-8', 'language': 'en-US', ...}}

    def test_cql_filters(get_oas_30_, config):
        """added assertions here for every piece of the openapi document related to CQL extension"""

        assert isinstance(config, dict)

        #assertion for checking for support of filters
        assert 'filters' in config['resources']['obs']

        filters=['cql-text', 'cql-json']
        for filter_lang in filters:
            assert filter_lang in config['resources']['obs']['filters']


        assert isinstance(get_oas_30_, dict)

        #assertion for get paths
        openapi_paths=get_oas_30_.get('paths', None)
        assert openapi_paths is not None

        #assertion for components
        openapi_components=get_oas_30_.get('components', None)
        assert openapi_components is not None


        #assertion for responses
        openapi_responses=openapi_components.get('responses', None)
        assert openapi_responses is not None

        #assertion for parameters
        openapi_parameters=openapi_components.get('parameters', None)
        assert openapi_parameters is not None

        #assertion for cql schemas
        cql_schemas=openapi_components.get('schemas')
>       assert cql_schemas is not None
E       assert None is not None

tests/test_openapi.py:113: AssertionError
========================================================================================= 1 failed, 1 passed in 0.19s ==========================================================================================
```

**Comment by francbartoli** [comment]
the result of the openapi command still doesn't work for me

```shell
   cp pygeoapi-config.yml example-config.yml
   vi example-config.yml
   #####################
   # added the following under `obs`
   filters:
       - cql-text
       - cql-json
   #####################
   export PYGEOAPI_CONFIG=example-config.yml
   export PYGEOAPI_OPENAPI=example-openapi.yml
   pygeoapi generate-openapi-document -c $PYGEOAPI_CONFIG > $PYGEOAPI_OPENAPI
```

looking for the parameter filter and filter-lang still fails:

```
grep filter example-openapi.yml
grep filter-lang example-openapi.yml
```

This means also that the tests were not asserting the cql expectations. I think they should be updated to accomplish them

**Comment by jorgejesus** [comment]
@FarheenB  and @francbartoli  Cool work and explanations :+1:  there is lot of issues going on at the same time, will make a localized comment, mainly around the  `cql-text` and `cql-json`

If you look here (@FarheenB )
https://github.com/FarheenB/pygeoapi/blob/4adbd666e4f07f7d455da41ac52e14ddb65a3dcf/tests/test_openapi.py#L89
the code is testing if the `cql-text` and `cql-json` are present on the config file, this is not the objective of  the test. What your code needs to (around line 89):
-  From `config['resources']`  get a resource that implements filters and and another that does not implement filters (A and B).
-  Further on the code using  `get_oas_30_` you need to check if the return document (open api doc: https://gist.github.com/jorgejesus/641f349e9fd559c763e2b8fcf6f71ee0) has the filter implemented for A and not for B.
- Your current `get_oas_30_`  doesnt give indication that you have filter support for resource A you need to have in the parameters an indication a bit like in this example   `https://gist.github.com/jorgejesus/b8246b4b53a270e9ac098f2a45371dab#file-gistfile1-txt-L288`

**Comment by jorgejesus** [comment]
@FarheenB  Based on https://github.com/FarheenB/pygeoapi/commit/03b5b929b444febc9945329c7b00ec462b88c061
For what I see/understand:
-  `openapi.get_oas_30`  is not outputting the filter/filter-lang content (around here: https://github.com/FarheenB/pygeoapi/blob/0a2dc5e44e38eea82f36f0b269f97f0f5224054f/pygeoapi/openapi.py#L342). You need the check the code and logic seems that there is something wrong.
- Unitil you have a proper get_oas_30 return object, you pytest will not pass, and for me it crashes here: https://github.com/FarheenB/pygeoapi/blob/0a2dc5e44e38eea82f36f0b269f97f0f5224054f/tests/test_openapi.py#L96  (this is the point of TDD)

**Comment by jorgejesus** [comment]
Seem there was alot of issues due to the back that `pip install -e .` was not run on my directory and the `openapi.py` being used had a different source

**Comment by jorgejesus** [comment]
@FarheenB  
Could you refactor the  `def test_cql_filters(get_oas_30_, config):` is it a bit long, for example  alex split things into [subfuctions](https://github.com/alex-mathew/pygeoapi/blob/data-transaction/tests/test_openapi.py )

**Comment by FarheenB** [comment]
@jorgesus I have already restructured my code and split it into multiple function. Please check my new branch for which I have requested a pull request https://github.com/FarheenB/pygeoapi/tree/openapi-cql-extension

**Comment by francbartoli** [comment]
Farheen you should update the same PR with additional commits otherwise things will go messy

**Comment by FarheenB** [comment]
open-cql-extension is my same branch for which I have requested PR. My additional commits are on this PR only https://github.com/geopython/pygeoapi/pull/478
