### ISSUE TITLE
use default slides in inspire conference

### ISSUE THREAD

**Issue by pvgenuchten** [geopython/pygeoapi#447]
The setting of the [ogc api features track](https://indico.unidu.hr/event/2/contributions/55/contribution.pdf)
 at inspire may be a bit different then the normal setting of the slide set, we don't need many of the ogc/api intro slides because those are covered by Gobe and Thorsten. On the other hand we may add some slides related to schema-org and json-ld.

We could skip/add the topics in the presentation or create a dedicated copy.

schema-org is relevant because there is a general feel that inspire data is hard to locate, facilitating data search via google dataset search is one of the potential improvements people expect, pygeoapi will facilitate that

json-ld is relevant because inspire has many app-schema xml models which are quite challenging to consume. GeoJson on the other hand is quite limited in hierarchical capabilities.
An option would be the adoption of json-ld as a app-schema alternative. Experiments and findings from the pygeoapi project are interesting

what i like of the approach chosen in pygeoapi (rather then requiring to fit a dataset into a model) publish the data more or less as-is and reference a ld-context file to make the data (inspire) model aware. see also [open data principles](https://opengovdata.org/)

rdf vocabularies of some inspire models are published [here](https://github.com/inspire-eu-rdf/inspire-rdf-vocabularies)

**Comment by tomkralidis** [comment]
Default presentation updated for review and comment.

**Comment by pvgenuchten** [comment]
changes look good Tom, closing this
