### ISSUE TITLE
add project sponsorship capabilities

### ISSUE THREAD

**Issue by tomkralidis** [geopython/pygeoapi#449]
## Overview
Provide opportunity for project sponsorship.

## Mechanism
- via OSGeo (PayPal, GitHub Sponsors, etc.)
- others?

## Communications
- via [GitHub](https://help.github.com/en/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository) `.github/FUNDING.yml` (will automatically show up here on GitHub repo)
- via https://pygeoapi.io or wiki

## Other
- see [GeoServer](https://github.com/geoserver/geoserver/wiki/Sponsor) for example and inspiration.

**Comment by kalxas** [comment]
I think it is a good idea to use existing mechanisms (OSGeo Paypal and recent Github Sponsors)

**Comment by tomkralidis** [comment]
- we now have OSGeo PayPal capability (thanks @msmitherdc)
- sponsorship [wiki page](https://github.com/geopython/pygeoapi/wiki/Sponsorship) created (thanks @jodygarnett for the [GeoServer](https://github.com/geoserver/geoserver/wiki/Sponsor) example)
- Donate button/link added to:
  - website homepage
  - wiki sidebar
