### ISSUE TITLE
implement data transaction document on code base

### ISSUE THREAD

**Issue by jorgejesus** [geopython/pygeoapi#450]
Following the generic creation of a data transaction document 

https://github.com/alex-mathew/pygeoapi/blob/openapidoc/data_transaction_openapidoc_proposal.yml

It is necessary to start its implementation:

- Write  pytests that check the mockup implementation (next bullets)
- Test the code for compliance
- Take into consideration the geojson providers
- Modify `openapi.py` file so that it generates the proposed openapi document for data transactions
- Mockup implementation based on "dummy" information gathered from  config file that describes data providers (example: `pygeoapi-config.yaml`)
- Implement mockup REST generation on base code (`api.py`)
(this was updated base on the feedback on https://github.com/geopython/pygeoapi/issues/450#issuecomment-643575199)

**Comment by francbartoli** [comment]
@jorgejesus seems to be a good plan. Just a couple of comments:
- I would start with the tests following TDD
- the simplest case for providers is geojson IMHO

**Comment by jorgejesus** [comment]
@alex-mathew : Based on the previous commits, could you now focus on 

- Modify openapi.py file so that it generates the proposed openapi document for data transactions
- Mockup implementation based on "dummy" information gathered from config file that describes data providers (example: pygeoapi-config.yaml)

The REST end points are now this issue: https://github.com/geopython/pygeoapi/issues/461
