### ISSUE TITLE
Apply filter while zooming in items page

### ISSUE THREAD

**Issue by pvgenuchten** [geopython/pygeoapi#455]
In the html encoding of items operation a map is displayed highlighting the current items on the page. It could be interesting to allow users to zoom in that map to a smaller extent and apply that extent as a spatial filter to the result-set.

![image](https://user-images.githubusercontent.com/299829/84325271-ad4bb080-ab7a-11ea-8db3-af5efdc6d833.png)

Requesting a filtered set from the server could be an ajax request. With every ajax request, it would be good to update the url with the latest bounds, so if users at some point copy the url and share it with others, it would zoom to the same area. Or if they click the json representation for that page, they would get the same records. Combining ajax with a change of the url can be managed with [window.history.pushState](https://stackoverflow.com/questions/824349/how-do-i-modify-the-url-without-reloading-the-page).

**Comment by geekdenz** [comment]
Yes, @alpha-beta-soup this is related. Our version is not as advanced as @pvgenuchten is suggesting, but was quick to implement and achieves a similar result.
The suggestion above is an evolution so could be better in the long run.
