### ISSUE TITLE
sitemap.xml

### ISSUE THREAD

**Issue by dblodgett-usgs** [geopython/pygeoapi#456]
There is no sitemap.xml generated for a pygeoapi. 

**Describe the solution you'd like**
A `sitemap` parameter at the collection level with options: `items`, `collections`, or `none`. For items, include all items. For collections, include only collection level path. For none, do not include that collection in the sitemap.xml

**Describe alternatives you've considered**
I could crawl and generate the sitemap out of band, but the information required is available to the server at startup and it could be generated easily.

**Additional context**
We are building a pretty significant reference data server over here: https://info.geoconnex.us/ and could really use a sitemap as we build it out.

**Comment by pvgenuchten** [comment]
Sitemap.xml and robots.txt are considered suggestions for exclusion only, use a [noindex header](https://support.google.com/webmasters/answer/93710?hl=en) to indicate no-crawling. Adding the noindex tag could be trigger by the same proposed configuration change.

**Comment by ksonda** [comment]
@dblodgett-usgs just to be clear, were you thinking something like /collections/sitemap?type={collections,items,none}?

or more like /collections?f=sitemap, collections/{collection}/items?f=sitemap

**Comment by dblodgett-usgs** [comment]
Not sure I'd gotten that far. Seems like it would be a root sitemap.xml that would "just work"? Perhaps the root sitemap would orchestrate paged sitemap calls using OAFeatures as you've illustrated above?

**Comment by webb-ben** [comment]
Note: a sitemap OGC API - Process has been implemented in https://github.com/cgs-eath/pygeoapi-plugins.

**Comment by webb-ben** [comment]
> Note: a sitemap OGC API - Process has been implemented in https://github.com/cgs-earth/pygeoapi-plugins.
