### ISSUE TITLE
Remove duplicated schema.org

### ISSUE THREAD

**Issue by pvgenuchten** [geopython/pygeoapi#459]
Current master contains 2 approaches for adding schema.org, via an embedded json-ld, and as microdata. Somehow the two are not conflicting, maybe because the embedded json-ld throws an error?

![image](https://user-images.githubusercontent.com/299829/84551197-25e27680-ad0d-11ea-9a98-536ea04c81cf.png)

On the microdata part (maybe not relevant anymore) I noticed some validation warnings on schema.org/dataset

![image](https://user-images.githubusercontent.com/299829/84550563-46113600-ad0b-11ea-9528-a039e7ff0f74.png)

contentUrl is not provided in the proper way here...

and a warning: license information is missing

also tried a collection record on the yandex validator

![image](https://user-images.githubusercontent.com/299829/84551820-0f3d1f00-ad0f-11ea-80a7-4e5c005646a8.png)

which translates to "ERROR: The content property of the meta tag cannot contain a link"

this is an interesting one

![image](https://user-images.githubusercontent.com/299829/84551960-8a063a00-ad0f-11ea-89bb-e218603d1548.png)

translates to "ERROR: the contentURL field is not defined in the https://schema.org/DataDownload specification. Perhaps you meant contentUrl"

**Comment by alpha-beta-soup** [comment]
Ah cool, didn't even know there was a Yandex validator too.
