### ISSUE TITLE
implement flake8 and travis on data-transacion branch

### ISSUE THREAD

**Issue by jorgejesus** [geopython/pygeoapi#466]
Code in branches before a pull request (PR) has to be checked for coding style using flake8,  and integrated into travis.

Todo:

- [x]  Check  code before commit with flake8 for problems (find . -type f -name "*.py" | xargs flake8)
- [x]  Rename current work branch from `openapidoc` to `data-transaction`
- [x]  Integrate branch into travis so that for each push, travis is run and all code content is validated

Documentation to consider:
- https://docs.travis-ci.com/user/tutorial/
- https://www.baeldung.com/travis-ci-build-pipeline

**Comment by alex-mathew** [comment]
Travis build is failing

**Comment by jorgejesus** [comment]
There are some issues on the ogr unittest but your pytest is passing. You have to wait until the other developers fix it (they are looking into it)
