### ISSUE TITLE
implement documentation for data-transaction branch with read the docs 

### ISSUE THREAD

**Issue by jorgejesus** [geopython/pygeoapi#467]
pygeoapi uses read the docs (RTD) for documentation. The code for documentation is in folder `docs`

Todo:

- [x]  Check if committed code has proper docstring and text description 
- [x]  Link the data-transaction branch to you personal account of read the docs, so that documentation is automatically build.
- [x]  Write a subsection  under configuration with indication of what is the purpose of data transaction (small text from proposal).
- [x]  Extend configuration description to the proposed data configuration yml configuration  
 

     

Documentation to consider:

- docstrings  https://sphinx-rtd-tutorial.readthedocs.io/en/latest/docstrings.html

**Comment by alex-mathew** [comment]
linked data-transaction brach to read the docs
https://pygeoapi-data-transaction.readthedocs.io/en/data-transaction/

**Comment by jorgejesus** [comment]
The table of content of your read the docs (https://pygeoapi-data-transaction.readthedocs.io) has the configuration section and you should a subsection concerning `data-transaction` and you need to include a small text indicating:

- What is the purpose of data transaction
- What and how to configure support for data transactions. (Look how it was done for the linked data section)

**Comment by jorgejesus** [comment]
Change:

> Data transaction support is optional and can be enabled for a collection resource by adding transactions: true to extents under the resource in the pygeoapi config file.


To:

> Data transaction support is optional and can be enabled for a collection resource by adding `transactions: true` to extents under the resource in the pygeoapi config file. If transactions parameter is not set it will be considered as   `transactions: false`

**Comment by jorgejesus** [comment]
This seems updated
