### ISSUE TITLE
implement flake8 and travis on openapi-cql branch

### ISSUE THREAD

**Issue by jorgejesus** [geopython/pygeoapi#471]
Code in branches, before a pull request (PR) has to be checked for coding style using flake8,  and integrated into travis.

Todo:

- [x]  Check  code before commit with flake8 for problems (find . -type f -name "*.py" | xargs flake8)
- [x]  Integrate branch into travis so that for each push, travis is run and all code content is validated

Documentation to consider:
- https://docs.travis-ci.com/user/tutorial/
- https://www.baeldung.com/travis-ci-build-pipeline

**Comment by FarheenB** [comment]
@jorgejesus @francbartoli 
The build failed due to following reasons:
https://travis-ci.com/github/FarheenB/pygeoapi/jobs/355061206
https://travis-ci.com/github/FarheenB/pygeoapi/jobs/355061207

test cases of test_openapi.py is passed.

**Comment by francbartoli** [comment]
One error about wfs is known to fail sometime so you can ignore for now. On the other hand, is `test_api.py` failing locally?

**Comment by FarheenB** [comment]
yes test_api.py is failing locally
![image](https://user-images.githubusercontent.com/59408650/85958848-5fc2a680-b9b6-11ea-9599-0334d1305dc2.png)

**Comment by francbartoli** [comment]
I think you are missing some dependency because it is not failing with me locally from master

**Comment by FarheenB** [comment]
I reinstalled requirements.txt still no luck

![image](https://user-images.githubusercontent.com/59408650/85959193-808bfb80-b9b8-11ea-98ef-46a2d339c9de.png)

**Comment by alpha-beta-soup** [comment]
You'll need to install `requirements-dev.txt` as well, to get `pyld` so you can run tests.

**Comment by FarheenB** [comment]
@alpha-beta-soup thanks for the info. Now the issue on local is same as the build.

![image](https://user-images.githubusercontent.com/59408650/85981488-e51f7880-ba01-11ea-909a-78b195e6a79e.png)

**Comment by francbartoli** [comment]
@FarheenB I run the same test on master and it succeeds

**Comment by FarheenB** [comment]
Travis build successful for openapi-cql branch
https://travis-ci.com/github/FarheenB/pygeoapi/jobs/356448280
https://travis-ci.com/github/FarheenB/pygeoapi/jobs/356448281

**Comment by francbartoli** [comment]
I know, it was expected ;)
