### ISSUE TITLE
implement documentation for cql branch with read the docs

### ISSUE THREAD

**Issue by jorgejesus** [geopython/pygeoapi#472]
pygeoapi uses read the docs (RTD) for documentation. The code for documentation is in folder `docs`

Todo:

- [x]  Check if committed code has proper docstring and text description 
- [x]  Link the cql branch  (working branch) to you personal account of read the docs, so that documentation is automatically build.
- [x]  Write a subsection  under configuration with indication of what is the purpose of CQL and usage (small text from proposal).
- [x]  Extend configuration description (on RTD) to the proposed cql configuration  (Subsection has to contain a snipped of configuration `yml` indicating how implementation should be configured)

Documentation to consider:

- docstrings  https://sphinx-rtd-tutorial.readthedocs.io/en/latest/docstrings.html

**Comment by FarheenB** [comment]
give it a look
https://pygeoapi-cql-filters.readthedocs.io/en/latest/configuration.html#cql-filter
