### ISSUE TITLE
Create a clean PR for data-transaction branch

### ISSUE THREAD

**Issue by jorgejesus** [geopython/pygeoapi#481]
When all review is done and all issues are from the first GSoC milestone are solved:

- [x] Rename data-transaction branch to data-transaction-GSoC-1
- [x] Check that travis passes
- [x] Submit a PR to the pygeoapi project

**Note:** This PR is only for review by the community, only the final data-transaction implementation will be accepted into  the master code of pygeoapi

**Comment by alex-mathew** [comment]
Travis build for pygeoapi master again started failing.
I think the demo geoserver in test_ogr_wfs_provider.py is down.

https://travis-ci.org/github/geopython/pygeoapi/jobs/704471838
