### ISSUE TITLE
Research on how to implement generic routes

### ISSUE THREAD

**Issue by jorgejesus** [geopython/pygeoapi#482]
**Is your feature request related to a problem? Please describe.**

Taking `flask_api.py` as reference: 

We have the following route code structures:
https://github.com/geopython/pygeoapi/blob/d2cbf48cd3f7663caf7520b69451723cfadf47f7/pygeoapi/flask_app.py#L192-L194

For the data-transactions this needs to be extended for extra HTTP verbs

Based on  the pygeoapi config files we will have datasets supporting transitions and other no. The description by openapi indicates which ones allow it or not

**Describe the solution you'd like**

Research how routes could be implemented in a more generic way so that there is of non-data-transactions providers have not recollection/awareness of other HTTP verbs 

For example FastAPI has  a `RouteAPI` object https://fastapi.tiangolo.com/advanced/custom-request-and-route/

**Describe alternatives you've considered**

None

**Additional context**

- Discussion to follow on this ticket

**Comment by alex-mathew** [comment]
@jorgejesus @francbartoli 
I think the most direct approch is creating a function each to handle each verb in `flask_app.py` and checking whether the particular collection supports transactions or not inside the functon:
```
@APP.route('/collections/<collection_id>/items',
           methods=['POST'])
def post_collection(collection_id):
    if not supports_transactions(collection_id):
        pass
    else:
        pass
```
Are there any issues with this approach?

**Comment by jorgejesus** [comment]
Please check the Flask views:
-  https://pythonise.com/series/learning-flask/flask-api-methodview
-  https://flask.palletsprojects.com/en/1.1.x/views/
