### ISSUE TITLE
One OGR WFS test fails and one stalls test process

### ISSUE THREAD

**Issue by justb4** [geopython/pygeoapi#495]
**Description**
`test_gs_force_getting_gml_id fails` and `test_get_gs_with_geojson_output_too_complex_raise_exception` stalls process.
Both are OGR WFS tests in `tests/test_ogr_wfs_provider.py `

**Steps to Reproduce**

* run `pytest -v tests/test_ogr_wfs_provider.py `
* seeing test 6 fail and 7 stalling

**Expected behavior**
* expect all tests succeed

**Screenshots/Tracebacks**
```
pytest -v tests/test_ogr_wfs_provider.py 
============================================================== test session starts ===============================================================
platform linux -- Python 3.8.4, pytest-5.4.3, py-1.9.0, pluggy-0.13.1 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /pygeoapi, inifile: pytest.ini
plugins: env-0.6.2, cov-2.10.0
collected 21 items                                                                                                                               

tests/test_ogr_wfs_provider.py::test_get_fields_gs PASSED                                                                                  [  4%]
tests/test_ogr_wfs_provider.py::test_get_ms PASSED                                                                                         [  9%]
tests/test_ogr_wfs_provider.py::test_get_geosol_gs PASSED                                                                                  [ 14%]
tests/test_ogr_wfs_provider.py::test_get_gs PASSED                                                                                         [ 19%]
tests/test_ogr_wfs_provider.py::test_gs_not_getting_gml_id PASSED                                                                          [ 23%]
tests/test_ogr_wfs_provider.py::test_gs_force_getting_gml_id FAILED                                                                        [ 28%]
tests/test_ogr_wfs_provider.py::test_get_gs_with_geojson_output_too_complex_raise_exception ^C
```

**Environment**
 - OS: any
 - Python version: 3.8 (used the Docker image)
 - pygeoapi version: master on demo  (used the Docker image to reproduce)

**Additional context**
N.A.

**Comment by francbartoli** [comment]
It is not a bug per se. This call https://geonode.wfp.org/geoserver/wfs?service=WFS&request=DescribeFeatureType&typeName=geonode:wld_bnd_adm0 gives an error server side. So the gml_id is not available and the other stalls

**Comment by justb4** [comment]
True, it is not a `pygeoapi`-bug. Any chance to fix this on the GeoServer-side?

**Comment by tomkralidis** [comment]
Note that current master [is failing Travis](https://travis-ci.org/github/geopython/pygeoapi/jobs/734561245#L4327). I guess we cannot mock deep enough into the GDAL/OGR Python bindings?  Another option is doing more flexible testing for this provider, which is hitting remote resources that we have no control over.

**Comment by pvgenuchten** [comment]
can we set up a mapserver under pygeoapi control, so we make sure to provide a valid service

**Comment by tomkralidis** [comment]
>> can we set up a mapserver under pygeoapi-team control, so we make sure to provide a valid service

We can also use https://demo.mapserver.org/cgi-bin/wfs, @justb4 thoughts?  In general, it would be better to find a stable demo instance vs. a live deployment.

**Comment by francbartoli** [comment]
I think mapserver wouldn’t mimic any type of the different WFS implementations like GeoServer, GeoNode (that has different auth system, etc). We should experiment a little bit with http mocking tools or VCR cassettes IMHO

**Comment by tomkralidis** [comment]
FYI I have opened a PR at #552 for consideration.
