### ISSUE TITLE
Implementation of PATCH request in data transactions

### ISSUE THREAD

**Issue by alex-mathew** [geopython/pygeoapi#503]
**Is your feature request related to a problem? Please describe.**
While implementing data transactions, I am facing some issues in the implementation of the PATCH request. My initial plan was to implement ``add``, ``modify``, ``remove`` via a JSON-Patch payload. But ``add`` and ``remove`` cant be supported in data providers with fixed schemas (like RDBMS providers). 

**Describe the solution you'd like**
Implement ``add`` and ``remove`` only for flexible schema providers (like GeoJSON and CSV). The schema will be a union of attributes of all features in the provider. The schema will have to be generated dynamically during each GET, POST, PUT, and PATCH requests. This will be a bit costly.

**Describe alternatives you've considered**
Support only ``modify`` in PATCH requests for all providers.

**Additional context**
This is a discussion ticket, based on [OGC Data transaction doc](http://docs.opengeospatial.org/DRAFTS/20-002.html)

**Comment by jorgejesus** [comment]
Me and @alex-mathew  had a bit of discussion on the topic 
 - I am concern about implement `add` and `remove` on schemaless data providers. Mainly for the fact that it would be easy to inject 100000  property in a `CSV/Geojson`  provider and cause problems on the system 
- IMHO we should only implement `modify` in the PATCH requests  (json-merge)
