### ISSUE TITLE
improve openapi docs  with extra examples and description

### ISSUE THREAD

**Issue by jorgejesus** [geopython/pygeoapi#507]
On the branch: `data-transaction-GSoC-2`

- [x]  Improve openapi with better working examples with examples of obs/items id, geojson
- [x] Better text descriptions for CRUD operations
- [x] fix error from pygeoapi, see image bellow, need to have a better geosjon example

![image](https://user-images.githubusercontent.com/1275400/89728246-2f960b00-da2c-11ea-8665-e353f59e55bd.png)

**Comment by alex-mathew** [comment]
To assign examples, do we have to read values from each data provider or is there an easy solution?

**Comment by jorgejesus** [comment]
Dont think there is an easier solution, you need to implement something like the [examples](https://swagger.io/specification/), and likely to pick up some values from the provider.

![image](https://user-images.githubusercontent.com/1275400/89862028-617fac80-dba7-11ea-836a-b37955fc3556.png)
