### ISSUE TITLE
implement data transactions on database providers

### ISSUE THREAD

**Issue by jorgejesus** [geopython/pygeoapi#508]
Since data transactions have been implemented on csv and geojson:

Implement data transaction on the following providers:

- [x] sqlite/gpkg
- [x] postgresql

**Comment by alex-mathew** [comment]
SQLite INSERT query runs fine but ``GeomFromGeoJSON`` function seem to convert the geojson geometry to ``None``.

**Comment by fredmorin** [comment]
Hello,

This ticket is marked closed as completed, but the implementation is not integrated in pygeoapi.

It lays in a fork by @alex-mathew :
https://github.com/alex-mathew/pygeoapi/commit/ff78bad2f590f4a377c2e044cc21024bc8415d82
