### ISSUE TITLE
SQLiteGPKG plugin doesn't support gpkg with multiple tables

### ISSUE THREAD

**Issue by mvaaltola** [geopython/pygeoapi#519]
**Description**
Method __load in pygeoapi/provider/sqlite.py raises an unnecessary InvalidPluginError ([line 221](https://github.com/geopython/pygeoapi/blob/85939109b1946f2bc951f7e2ebce603561318ee6/pygeoapi/provider/sqlite.py#L221)) if query `SELECT AutoGPKGStart();` returns >1. AutoGPKGStart returns an integer of how many VirtualGPKG tables have been created. According to the log message this exception should only be raised if the value is 0. In my case the gpkg has 2 tables, AutoGPKGStart returns 2, and pygeoapi raises an exception and fails to start.

**Steps to Reproduce**
- Create a .gpkg file with two or more spatial tables
- Try to publish a table from the geopackage as a resource with pygeoapi using the SQLiteGPKG provider

**Expected behavior**
The exception should only be raised if `SELECT AutoGPKGStart();` returns 0.

**Environment**
- Docker image: geopython/pygeoapi:latest

**Comment by tomkralidis** [comment]
@mvaaltola thanks for the report. Can you provide a test GPKG dataset (or steps to create one)?
