### ISSUE TITLE
Improving reusability with Flask Blueprints

### ISSUE THREAD

**Issue by constantinius** [geopython/pygeoapi#530]
**Is your feature request related to a problem? Please describe.**

We are trying to combine pygeoapi with an existing Flask App. There is the way to do so using [werkzeug middlewares](https://flask.palletsprojects.com/en/1.1.x/patterns/appdispatch/#combining-applications), but this is really low level and hard to do correctly.

**Describe the solution you'd like**
I think the best solution would be to use the Flask Blueprint to set up the routes to the internal functions, which then can be mounted in the Flask App under the root URL.

With this way, it is easy to just mount the pygeoapi URLs in any other Flask based App.

This would be the change in the `flask_app.py`

```python

# imports and such ...
from flask import Flask, Blueprint, make_response, request, send_from_directory
# ...

URLS = Blueprint('pygeoapi', __name__)
APP = Flask(__name__)
APP.url_map.strict_slashes = False

# ...

@URLS.route('/')
def landing_page():
    # ...

# other routes
# ...

# finally mount the Blueprint
APP.register_blueprint(URLS, url_prefix='/')

# ... everything else
```

**Describe alternatives you've considered**

Mentioned in the description above using werkzeug middlewares.

**Additional context**

none

**Comment by tomkralidis** [comment]
@constantinius thanks for the report.  Does something like this work, then?

```diff
diff --git a/pygeoapi/flask_app.py b/pygeoapi/flask_app.py
index c766db2..91941f2 100644
--- a/pygeoapi/flask_app.py
+++ b/pygeoapi/flask_app.py
@@ -34,11 +34,12 @@ import os
 
 import click
 
-from flask import Flask, make_response, request, send_from_directory
+from flask import Blueprint, Flask, make_response, request, send_from_directory
 
 from pygeoapi.api import API
 from pygeoapi.util import get_mimetype, yaml_load
 
+BLUEPRINT = Blueprint('pygeoapi', __name__)
 APP = Flask(__name__)
 APP.url_map.strict_slashes = False
 
@@ -365,6 +366,10 @@ def stac_catalog_path(path):
     return response
 
 
+# mount the Blueprint
+APP.register_blueprint(BLUEPRINT, url_prefix='/')
+
+
 @click.command()
 @click.pass_context
 @click.option('--debug', '-d', default=False, is_flag=True, help='debug')
```

I would suppose, then, that downstream Flask applications would register the pygeoapi blueprint thereafter?  Would have an example of a downstream app example code snippet (will help adding an example to the documentation).  Also, @francbartoli  is there an equivalent approach in Starlette?

**Comment by constantinius** [comment]
Hi @tomkralidis 

Thanks for the response. We actually got it to work with our eurodatacube OGC API. This is the Blueprint (same approach as described): https://github.com/eurodatacube/ogc-edc/blob/oapi/edc_ogc/oapi.py and this is how I mount it: https://github.com/eurodatacube/ogc-edc/blob/oapi/edc_ogc/app.py#L177. I had to do some shenanigans to get the static files to work, but I think this is unrelated.

Unfortunately I don't have experience with Starlette.
