### ISSUE TITLE
gunicorn doesn't work with greenlet 0.4.17

### ISSUE THREAD

**Issue by totycro** [geopython/pygeoapi#545]
**Description**
When running with greenlet 0.4.17 (released 2 days ago), gunicorn doesn't actually respond to requests. I'm not sure what's going on here, but I wanted to inform you that it does not happen with 0.4.16.
```
$ curl localhost:5000/foo
curl: (52) Empty reply from server
```
The log contains this (apparently workers are restarted after every request):
```
[2020-09-24 08:28:11 +0000] [23] [INFO] Booting worker with pid: 23
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
```

**Steps to Reproduce**
Rebuild docker image with cache and run, or force install of greenlet==0.4.17. Run in docker and try any request.

**Additional context**

**Expected behavior**
Gunicorn should serve some kind of http response.

**Environment**
 - OS: Ubuntu
 - Python version: 3.8.5 (as installed in docker)
 - pygeoapi version: master (2ea8a5f6cb76fdfbec2e78fda416d443df449458)

**Comment by tomkralidis** [comment]
Thanks @totycro.  Is this worth mentioning to [greenlet](https://github.com/python-greenlet/greenlet) ?

**Comment by totycro** [comment]
Possibly. I'm not sure what's happening here exactly, and you can find similar error messages online. They recently did some work on supporting different python versions.

It might also be possible that this greenlet version is just incompatible with other pip packages where the version is frozen in the Dockerfile.

**Comment by jvanulde** [comment]
Is there a workaround?

**Comment by jvanulde** [comment]
I found a workaround. In the Dockerfile I set the following:

    PIP_PACKAGES="greenlet==0.4.16 gunicorn==20.0.4 gevent==1.5.0 wheel==0.33.4 ${ADD_PIP_PACKAGES}"

**Comment by justb4** [comment]
@jvanulde thanks should be the trick: pinning greenlet to 0.4.16.
