### ISSUE TITLE
more/better validation of yaml content 

### ISSUE THREAD

**Issue by jorgejesus** [geopython/pygeoapi#553]
**Is your feature request related to a problem? Please describe.**
Currrent `yaml` config file is big and with data, that requires validity checks in multiple points. This makes the code confusing and time consuming to implement fixes 

**Describe the solution you'd like**
- Check possibility of implementing [Yamale](https://github.com/23andMe/Yamale), this tool could even create the validation schema from a pre-existing yml (bootstrap).
-  Strict validation possibility inside code or as an extra support tool

**Describe alternatives you've considered**
None

**Additional context**
This came out looking at #316  that requires datetime validation (not only the simple  `datetime` object when parsing the yml). The yml parser on `utils` could copy/paste some code from [piny](https://github.com/pilosus/piny)

**Comment by jorgejesus** [comment]
After discussion, better to implement `jsonschema` for validation.

**Comment by AelMalinka** [comment]
We are currently working on a system that generates a pygeoapi config (along with other configs and does various data manipulations) and ran into an issue where it generated an array for `resources -> providers -> geom_fields`; obviously, that's wrong but it would be very beneficial to have some mechanism by which to validate the generated config

**Comment by tomkralidis** [comment]
FYI implemented in master via #719
