### ISSUE TITLE
Default map provider (maps.wikimedia.org) tile requests are returning HTTP 403 response codes.

### ISSUE THREAD

**Issue by Dukestep** [geopython/pygeoapi#567]
**Description**
The default map provider (https://maps.wikimedia.org/osm-intl/{z}/{x}/{y}.png) is returning a 403 forbidden status code when displaying items via the HTML UI.

**Steps to Reproduce**
https://demo.pygeoapi.io/master/collections/lakes/items

Behaviour is also reproduced on a completely different private instance.

**Expected behavior**
Tiles requests should be returning 200 OK code.

**Environment**
 - OS: Not applicable
 - Python version: Not applicable
 - pygeoapi version: master

According to their [Terms of Use](https://foundation.wikimedia.org/wiki/Maps_Terms_of_Use):
```
Using maps in third-party services

If you use the Wikimedia Maps service for your third-party project (that is, outside of the Wikimedia projects), 
please respect our limited services and resources. We reserve the right to discontinue or change our service, 
block or limit certain users or applications, or take other measures in cases at our sole discretion 
at any time without notice. If you use the service too heavily, it could affect the service's stability for 
others or degrade our quality of service.

If you are developing an application that uses the Wikimedia Maps service, you must provide a valid HTTP 
User-Agent that includes your application, version, and sufficient information to easily contact you 
(e.g., your email address).

The following are prohibited on the Wikimedia Maps service:

    - Excessive downloading (such as downloading significant areas of tiles for later offline usage)
    - Accessing the service without a proper HTTP User-Agent or HTTP referer
    - Using the service without compliance with any license or copyright terms
```

It seems like we access the service with a valid HTTP referer but may fall in the "use the service too heavily" category?

**Comment by jasonwhitedev** [comment]
Gives out this error for the missing tiles/pngs: 
`Error: 403, Forbidden: Map tiles are restricted to Wikimedia & affiliated sites only. Please post on https://phabricator.wikimedia.org/T261694 if you believe your usage supports the Movement. at Tue, 10 Nov 2020 11:48:34 GMT`

As mentioned, someone probably needs to go & do this: 
```
If you are developing an application that uses the Wikimedia Maps service, you must provide a valid HTTP 
User-Agent that includes your application, version, and sufficient information to easily contact you 
(e.g., your email address).
```

**Comment by justb4** [comment]
@jasonwhitedev good to bring up! `pygeoapi` (HTML view) already migrated from using OSM tiles from `tile.openstreetmap.org` (which half of the world still is using) to Wikimedia OSM Tiles, not aware of these (recent?) restrictions.

The `pygeoapi` HTML view mainly uses a Leaflet-map with a tile-url. Not sure how/where we can configure an HTTP `User-Agent` as a custom HTTP-header in Leaflet. May be possible with some interception. See e.g. for auth: 
https://stackoverflow.com/questions/43946257/how-can-we-add-a-request-header-in-leaflet-tile-layer-wms-request

Another option is to use a tile-proxy/caching component like MapProxy which allows to configure custom HTTP-headers including referrers.

**Comment by doublebyte1** [comment]
I addressed this on this PR:
https://github.com/geopython/pygeoapi/pull/697
