### ISSUE TITLE
Improve developer experience when using Docker

### ISSUE THREAD

**Issue by jasonwhitedev** [geopython/pygeoapi#568]
This could just be me missing the obvious but when developing with Docker and docker-compose I really struggled to get the flask app to hot-reload on code changes.

I have worked out how to do this now but my solution seems very hacky. Also I get the impression that there is already a way to do this. If this is the case then can someone please enlighten me.

**Comment by justb4** [comment]
Hmm yes, by chance answered a similar question the other day: https://twitter.com/pvangenuchten/status/1315313826317971458 .
But this is not really hot-reloading, mainly sending a Signal to reload `gunicorn` (or `uwsgi`) on config-changes.

Thinking out loud: possibly we could extend the [Docker entrypoint](https://github.com/geopython/pygeoapi/blob/master/docker/entrypoint.sh) to run the Flask app using the standard Flask server, "dev-mode" via a Docker arg `entry-cmd` (default `run`) like `dev`. At the same time the `pygeoapi` code should be Docker Volume-mounted. Possibly that setup could work. For me the holy grail would be to also connect from within an IDE like IntelliJ IDEA to allow for breakpoints and step-wise debug. In my Java-time there was a way to connect to e.g. a running Tomcat instance for remote debugging. For development I now run `pygeoapi` with Flask directly within the IDE using a virtualenv, but this requires all dependencies like e.g. GDAL to be present on your local system.

**Comment by jasonwhitedev** [comment]
I have a branch where I have added development/flask dirs under the docker folder. Here I have set up a docker-compose.yml etc. that will serve the flask app running in development mode. Once I've tidied it up a bit I will submit a PR.
