### ISSUE TITLE
add functionality for writing OpenAPI document in full or brief mode

### ISSUE THREAD

**Issue by tomkralidis** [geopython/pygeoapi#571]
**Is your feature request related to a problem? Please describe.**
pygeoapi's OpenAPI generation utility (`pygeoapi generate-openapi-document`) works such that all layers in a pygoeapi configuration, as well as their (in the OAFeat case) properties as query parameters are explicitly provided.  Pseudo example:

```
/collections/roads
/collections/roads/items  # shows all queryable properties
```

This doesn't scale very well, leading to an enormous OpenAPI YAML, as well as clunky Swagger/ReDoc/other HTML UI rendering.

OpenAPI allows for collection paths to be parameterized as per below:

```
/collections/{collectionId}
/collections/{collectionId}/items
```

**Describe the solution you'd like**
Update `pygeoapi generate-openapi-document` to allow a `--mode=full|brief` flag.  `--mode=full` would provide current functionality.  `--mode=brief` would provide parameterized functionality, which would NOT include displaying queryable properties given the brief output applies to all collections.

**Describe alternatives you've considered**
NA

**Additional context**

cc @ricardogsilva

**Comment by pvgenuchten** [comment]
Tom, I noticed some discussion that a single openapi endpoint should only have a limited number of related resources. The reason behind this is probably to prevent the api-document to become very big.

Which brings back an initial discussion, should pygeoapi be able to host a number of api-endpoints each serving a subset of resources

In such a scenario, this feature could still make sense, because it's always nice to be able to limit the response size

**Comment by tomkralidis** [comment]
Good points Paul.  How would we envision pygeoapi doing multi-tenancy in this manner?  One option is to have the user setup 1..n pygeoapi configurations and [hang each of them as blueprints](https://docs.pygeoapi.io/en/latest/running.html#flask-wsgi).  Another option is spinning up 1..n pygeoapi containers each with its own subset of configuration and OpenAPI documents (which can be passed as environment variables).  What other options/ideas could we consider?

**Comment by ricardogsilva** [comment]
> I noticed some discussion that a single openapi endpoint should only have a limited number of related resources

Could you please provide some reference to this discussion (in case it is recorded online)? I'd be interested in reading the arguments for it.

IMHO, if the main problem is the generation of a huge openapi document when there is a large number of collections (brings back painful memories of the WMS GetCapabilities operation, which suffers from this same problem), the sensible approach is just to put parametrize the collections endpoint, similarly to what @tomkralidis described above. This will keep the openapi document's size manageable.

Even if the queryables may not be immediately described in the openapi document, we can surely provide this description elsewhere, as that seems to be direction the [OGC API - Features - Part 3: Filtering and the Common Query Language (CQL)] is going:

- there is a provision for a `/queryables` endpoint
- there is also a provision for a `collections/{collectionId}/queryables` endpoint

(I'm not familiar with the whole pygeoapi codebase yet, so I don't know if this is already implemented, but I guess it will be, at some point).

I think a multi-tenant pygeoapi is definitely a good idea, and something to think about, but I would not use the potential for huge number of existing collections to justify it. I can imagine the problem arising again for tenants that would want to expose a large number of collections :smile: 

[OGC API - Features - Part 3: Filtering and the Common Query Language (CQL)]: http://docs.ogc.org/DRAFTS/19-079.html#filter-queryables
