### ISSUE TITLE
duplicated schema-org annotation & parsing failure

### ISSUE THREAD

**Issue by pvgenuchten** [geopython/pygeoapi#574]
Some observations when validating https://demo.pygeoapi.io/master/collections/lakes in https://search.google.com/structured-data/testing-tool

**Duplicated annotation**
The pygeoapi templates still have microdata 'itemscope' attributes, combined with the embedded json-ld, it leads to duplicated parsing in validation tools. validator extracts the same dataset information twice

![image](https://user-images.githubusercontent.com/299829/99598639-21c42e80-29fa-11eb-8825-ac89deb30958.png)

**Parse error**

The embedded json-ld throws a parse error on
```
 "@context": "https://schema.org/docs/jsonldcontext.jsonld",
```
error:
```
There was an invalid type in your JSON-LD.
```
This results in the object described being a:
![image](https://user-images.githubusercontent.com/299829/99598259-9185e980-29f9-11eb-95a6-cd4a92eec168.png)

In other implementations I notice this string seems to work fine:
``` 
"@context": "http://schema.org/",
```
In that case the type is recognized as:
![image](https://user-images.githubusercontent.com/299829/99598410-c42fe200-29f9-11eb-9da1-9bef2b79165d.png)

**Comment by alpha-beta-soup** [comment]
See #444

**Comment by pvgenuchten** [comment]
#575 had negative side-effect, so we should keep this open

**Comment by pvgenuchten** [comment]
confirming here that the merge made datasets crawlable again through google tooling

![image](https://user-images.githubusercontent.com/299829/100926789-43d2ac00-34e4-11eb-9091-1b5ddac7b313.png)
