### ISSUE TITLE
content negotiation should check first matching

### ISSUE THREAD

**Issue by pvgenuchten** [geopython/pygeoapi#577]
**Description**
if you send a combined accept header of ``plain/text, application/ld+json`` a json response is returned (i guess json is the catch all format returned for unknown encodings). Expected is to return a json-ld encoding as it is the first match with any of the encodings available in pygeoapi

**Steps to Reproduce**
I used poster in chrome to send various accept headers
I arrived at this issue when testing microdata using http://linter.structured-data.org, they send a long accept header with various ld types and html, but json is returned, leading to a parse error

**Expected behavior**
pygeoapi returns the encoding for which it finds the first match in the list of requested and available encodings

**Screenshots/Tracebacks**

![image](https://user-images.githubusercontent.com/299829/99693220-6a77f800-2a8b-11eb-97d2-9acce2e3db40.png)

![image](https://user-images.githubusercontent.com/299829/99693280-795eaa80-2a8b-11eb-9c64-b9ef635933c3.png)

**Environment**
 - pygeoapi version: .8

**Comment by pvgenuchten** [comment]
> I think pygeoapi isn't really doing content negotiation via accept header order. It defaults to json if there's no accept header, and has a hard-coded priority of text/html, json+ld, then json if there is.

i got same impression, the behaviour must have been changed a while ago, we have structured data results at least up to march 2020, but currently structured data parsing, at least on google is broken, in my impression it is related to above statement, not providing a accept encoding causes pygeoapi to return json

**Comment by ksonda** [comment]
Since the changes above Our own crawler harvests our pygeoapi urls ok. We haven't gotten any results from Google since the introduction of Rich Results test tool and retirement of the structured data test tool. It seems like google is not indexing structured content based on @type
