### ISSUE TITLE
Allow the server to return only responses with JSON encoding as a configuration option 

### ISSUE THREAD

**Issue by francbartoli** [geopython/pygeoapi#592]
**Is your feature request related to a problem? Please describe.**
At the moment pygeoapi is compliant with the OGC API specifications which require to return the responses with at least two different formats, `json` and `html`. This is addressed using the `f` query string parameter from the user request. However, there isn't any mandatory encoding as per the specification [i.e.: OAFeat](http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#_encodings) despite the `HTML` is recommended. The conformance could be still maintained and updated accordingly at the server bootstrap. Moreover, this would be an option disabled by default.
Also, this would make the integration with GeoNode smoother, as per https://github.com/geopython/pygeoapi/issues/586 we should be able then to leave any Django app to use their own templates.

**Describe the solution you'd like**
A new configuration might address this, something like `server.disable_html: false|true` with default of `false`

**Describe alternatives you've considered**

**Additional context**

**Comment by justb4** [comment]
Bit puzzled, but may be missing something: `pygeoapi` supports Content Negotiation. This is enforced within the browser as it adds an `Accept` HTTP header for HTML.. but  if I do e.g.
`curl https://demo.pygeoapi.io/master` I get JSON as it is the default. But if (Geo)JSON needs to be enforced at all times, regardless of client `Accept` header, then this option can be ok.

**Comment by pvgenuchten** [comment]
I'm not in favour of this, users might be tempted to switch it off, without understanding the full impact. Usability of the service significantly decreases if switched off and should always be combined with proper request forwarding to relevant content. With that being said, if users want to turn off html output, they could also manage on the firewall/webserver level by introducing a rewrite rule rewriting the accept=text/html requests to relevant content elsewhere

**Comment by francbartoli** [comment]
That would be a weak option @pvgenuchten to integrate pygeoapi with GeoNode. It’s just a workaround at the infrastructure level. We’d like to provide a robust solution to use pygeoapi as a library in GeoNode.
In this sense, I don’t think the python API of pygeoapi has necessarily to handle the content negotiation with both JSON and HTML. If I understand well the various specifications none of them requires such specific encodings as mandatory.
Moreover, this wouldn't affect the overall developer experience for the content negotiation since the default configuration would be as it is now.
