### ISSUE TITLE
Write provider for Google Big Query

### ISSUE THREAD

**Issue by jorgejesus** [geopython/pygeoapi#60]
BigQuery from google now supports SQL/MM Spatial standard:

https://cloud.google.com/blog/big-data/2018/07/bridging-the-gap-between-data-and-insights

Using data from BigQuery should be more or less like the PostGIS provider

**Comment by tomkralidis** [comment]
cc @cholmes

**Comment by tomkralidis** [comment]
Some approaches/ideas:
- OAPIP could wrap queries/processes via BigQuery
- OAPIF could provide the results

**Comment by bkanuka** [comment]
hey @tomkralidis - bumping an old ticket, but I'm looking to take this on.  Short of using PostGIS provider as a starting point, any further thoughts on this?

**Comment by tomkralidis** [comment]
Thanks @bkanuka, sounds good! Also consider practical and isolated (enough) ways to run tests, as well as adding docs (following the patterns of how the other feature providers are implemented/tested/documented).
