### ISSUE TITLE
Express in json-ld that items are part of a collection

### ISSUE THREAD

**Issue by pvgenuchten** [geopython/pygeoapi#629]
I noticed the current json-ld output of items does not reflect the fact that these items belong to a collection. It is therefore impossible for a sparql engine to navigate to the parent (collection) and back to siblings (items) of the item. Can we extend the default json-ld context to use the links object to reference the collection an item belongs to also as rdf?

The [hydra ontology](http://www.hydra-cg.com/spec/latest/core/#classes) seems set up for the typical 'browse through a list of items in a paginated way', and also has quite some adoption.

An interesting topic more at core rdf level is about [collections and containers](https://stackoverflow.com/questions/17588804/difference-between-rdf-containers-and-collections/17589666)

**Comment by charlesvardeman** [comment]
An example of using the Hydra ontology to facilitate paging of collections is the [Triple Pattern Fragment](https://linkeddatafragments.org/specification/triple-pattern-fragments/) specification. There are client libraries such as [comunica](https://github.com/comunica/comunica/) that can use TPF for client side SPARQL queries.
