### ISSUE TITLE
Minor fixes for serverless/aws lambda instructions

### ISSUE THREAD

**Issue by bo-lu** [geopython/pygeoapi#660]
**Description**

Typos in aws-lambda/Readme.md

1.
> To test the application as a lambda locally:
> 
> serverless wsgi server

Should be:
> serverless wsgi serve

2.
> Once deployed, if you only need to update the code and not anything in the serverless configuration, you can update the function using:
> 
> serverless deploy --function app

Should be:
> serverless deploy function -f app

Self-assigning these typos and I will provide additional instructions and minor fixes for the serverless.yml file to get it working out of the box via a PR.

**Comment by tomkralidis** [comment]
@bo-lu any updates on your side?  Feel free to send a diff of changes if you don't have time for a PR.

**Comment by tomkralidis** [comment]
Fixed in master.
