### ISSUE TITLE
support OGC API - Maps

### ISSUE THREAD

**Issue by landryb** [geopython/pygeoapi#668]
Cf https://github.com/opengeospatial/ogcapi-maps for the spec, was partly discussed in #123 that added support for OGC API Tiles.

**Comment by tomkralidis** [comment]
This was asked at FOSS4G 2019 during the [pygeoapi presentation](https://media.ccc.de/v/bucharest-32-next-generation-ogc-web-services-with-pygeoapi).  Some initial thoughts/possibilities:

- we do not want to reinvent the wheel with rendering maps/tiles (MapServer, Mapnik, MapProxy, etc.), so investigation is needed on options and use cases
- we need to support a Python based mapping backend.  Examples include MapServer ([Python mapscript](https://pypi.org/project/mapscript/)), [Mapnik](https://github.com/mapnik/python-mapnik/blob/master/demo/python/rundemo.py). Others?
- the idea of pygeoapi acting as an OGC API proxy to existing WMS/WMTS instances should also be considered
- consideration is needed on how much independent configuration is needed (outside of pygeoapi) as part of implementation.  We want to minimize this if possible.  For example, if we go with Python mapscript as an option, then do we need mapfiles alongside pygeoapi configuration?  Or can we use the pygeoapi config to define inline in mapscript on the fly?  Can we use [mappyfile](https://mappyfile.readthedocs.io/en/latest/)? Performance?

**Comment by tomkralidis** [comment]
OAMaps is now implemented in master branch (via #1048 and #1052).
