### ISSUE TITLE
support more OGC API - Tiles providers

### ISSUE THREAD

**Issue by landryb** [geopython/pygeoapi#669]
support for MVT for vector tiles was added in #419, but as mentioned in https://github.com/geopython/pygeoapi/issues/123#issuecomment-612511971 support for more providers would be welcome:

for raster data:
- mbtiles
- various x/y/z layouts as served/generated by mapproxy or s3/minio (think 3dtiles for example)

for vector data:
- MVT from postgis

**Comment by KoalaGeo** [comment]
@landryb I believe 3D Tiles are going to come under the proposed OGCAPI - GeoVolumes but @ghobona could clarify.

**Comment by doublebyte1** [comment]
@KoalaGeo there is a [3D tiles candidate standard](https://portal.ogc.org/files/102132).

**Comment by doublebyte1** [comment]
@landryb pygeoapi does support now generic tiles providers in the formats /{z}/{x}/{y} or /{z}/{y}/{x}. 

[Tiles rendered using Pg_tileserv or Elastisearch, can be published as OGC API Tiles](https://docs.pygeoapi.io/en/latest/data-publishing/ogcapi-tiles.html#connection-examples).

**Comment by KoalaGeo** [comment]
A question - would there be appetite to cut out the middleman (pg_featureserv) and offer direct PostGres provider? Ideally tables and functions (same as pg_featureserv). 

Support for tiles in .mbtiles or .gpkg would be good in principle although I don't know how widely those are adopted in the community

**Comment by ShaneMill1** [comment]
I am interested in more OGC API - Tiles providers as well. We have data we disseminate via the OGC API - EDR in the form of Zarr. I am trying to figure out how to offer the same day within OGC API - Coverages and OGC API - Tiles. 

I am thinking that the multidimensional Zarr can be converted to GeoTIFF by band, and then converted to MBTiles. That may end up being too compute intensive however.

Then, once I have data in MBTiles, a Pygeoapi provider would be needed to create the OGC API - Tiles endpoints.

**Comment by doublebyte1** [comment]
It is possible to serve vector tiles now, using  elasticsearch, tippecanoe (from folder or url) and also a generic proxy that supports marvin and pg_tileserv (and possible others). Raster tiles are supported using the WMTS facade.

https://docs.pygeoapi.io/en/latest/data-publishing/ogcapi-tiles.html

I will close this issue for now, but feel free to open other issues for discussions about specific providers.
