### ISSUE TITLE
Clarification on Features Core Part 1 1.0 Conformance

### ISSUE THREAD

**Issue by captaincoordinates** [geopython/pygeoapi#672]
As documented on the pygeoapi website and [here](https://www.ogc.org/resource/products/details/?pid=1606), pygeoapi is considered compliant with OGC API - Features - Part 1: Core 1.0, however I'm confused about how this certification was acheived.

Looking through the source I see that `bbox` filtering in the `/collections/{collectionId}/items` endpoint is not implemented across all data providers, and I haven't been able to find any providers that implement `datetime` filtering. These are part of the spec and are required [here](http://docs.ogc.org/is/17-069r3/17-069r3.html#_parameter_bbox) and [here](http://docs.ogc.org/is/17-069r3/17-069r3.html#_parameter_datetime).

For example this block is in the [current GeoJSON provider on master](https://github.com/geopython/pygeoapi/blob/3f248a5c42aa0a453129572798b43c03dbcd891a/pygeoapi/provider/geojson.py). It is not filtering data on either `bbox` or `datetime`. How does pygeoapi comply with the spec when it does not appear to implement features mandated by the spec's "SHALL" qualifier? Am I misinterpreting the spec?

 ```
    def query(self, startindex=0, limit=10, resulttype='results',
              bbox=[], datetime_=None, properties=[], sortby=[],
              select_properties=[], skip_geometry=False, q=None):
        
        [... comments omitted for brevity]
        
        # TODO filter by bbox without resorting to third-party libs
        data = self._load(skip_geometry=skip_geometry,
                          select_properties=select_properties)

        data['numberMatched'] = len(data['features'])

        if resulttype == 'hits':
            data['features'] = []
        else:
            data['features'] = data['features'][startindex:startindex+limit]
            data['numberReturned'] = len(data['features'])

        return data
```

**Comment by tomkralidis** [comment]
pygeoapi's plugins have varying levels of support (check the docs for what providers support which aspects of a given endpoint/specification; for example for vector providers: https://docs.pygeoapi.io/en/latest/data-publishing/ogcapi-features.html).  This allows providers to be implemented independently.

Our CITE setup is documented at https://github.com/geopython/pygeoapi/wiki/OGCCompliance.

**Comment by captaincoordinates** [comment]
@tomkralidis thanks for the info. Are you able to tell me how or where the OGC spec permits different levels of conformance based on source data type? From my reading of the documentation I did not think that this was an option.

**Comment by tomkralidis** [comment]
@captaincoordinates this is irrelevant from the OGC viewpoint.

**Comment by tomkralidis** [comment]
Please post questions to the pygeoapi mailing list or Gitter channel. pygeoapi's GitHub issues are for **software bugs/enhancements** and related tasks.
