### ISSUE TITLE
sensorthings provider plugin

### ISSUE THREAD

**Issue by ksonda** [geopython/pygeoapi#685]
I'm interested in having a SensorThings API endpoint be a provider for pygeoapi, so that pygeoapi can serve as a quick landing page and linked data generator for low capacity sensorweb data producers. I have a start with @webb-ben [here](https://github.com/webb-ben/pygeoapi-sensorthings/) that templates in a `sta/Things?$expand=Locations` call. Demo deployment, using the [BRGM water quality endpoint](https://sensorthings-wq.brgm-rec.fr/FROST-Server/v1.0) as the provider: `docker run --rm -p 5000:80 ksonda/sta-pygeoapi`

I know there has been some background noise at OGC over eventually bringing SensorThings into alignment with OGC API. This issue is not meant to dig deep into data model alignment or anything like that. 

If there is interest in this idea, we're open to suggestions on configuration options.

**Comment by justb4** [comment]
@ksonda I applaud this development! Though did not think that far as you folks: to have SensorThings API (STA) endpoint be a provider for pygeoapi. My line of thought was to investigate if pygeoapi (actually OAFeat) could provide a JSON-LD model that mimics the STA Entity Model, still with each STA Entity type being Collection. I am no expert on JSON-LD...Foreign keys could work as well. Challenge is to map the STA Entity model to OAFeat Collection(s).

STA has a navigational highly normalized data model: from `Things` you get to `DataStreams` and then to `Observations`. `Location` is a separate entity, one or more tied to `Thing`. Wonder how to map those references and location data to OAFeat. First approach indeed (looked into [code](https://github.com/webb-ben/pygeoapi-sensorthings/)) map for each `Thing` `Location`[0] to Feature geometry. Well, you folks know your way in STA! For others, here is the UML Model actually reflected in the STA endpoint:

![image](https://user-images.githubusercontent.com/582630/117127862-f1e8c780-ad9c-11eb-954b-3fb75b087f23.png)


Thinking out loud/my $0.02: Maybe one can bundle, 'join', the unique combination Thing+Location[0]+Sensor+Datastream+ObservedProperty as a single identified Feature 'SensorThingPropertyStream', in a OAFeat Collection. There are usually not so many of these objects. Then each Observation could point to its parent 'SensorThingPropertyStream'. The STA Query language allows to fetch all 'SensorThingPropertyStream' related entities in a single get IMHO. This would be easy to work with, just 2 Collections: `SensorThingPropertyStream` and `Observations`.

**Comment by ksonda** [comment]
I agree that the `SensorThingPropertyStream` is a common enough construction in applications downstream of STA that this could be useful.  `Observations` might be `Observations_FeaturesOfInterest` as well. 

I think the trick is trying to not be prescriptive with the behavior and allow some degree of configuration. Some user may prefer to provide OAF access to STA by using each STA entity as a separate OAF collection. Some user may prefer this `SensorThingPropertyStream`, and there may be other custom joins they want to represent as collections.

**Comment by jkreft-usgs** [comment]
A wrinkle that would need to be either addressed or explicitly left out of an initial implementation is the concept of moving features/things, which sensorthings addresses but OGCAPI-Features doesn't address directly.

**Comment by ksonda** [comment]
very good point. some options

1) Ignore/disallow this use case for now
1.5) Focus on Feature Of Interest as the primary location provider 
2) Explore [OGC MF-JSON](http://docs.opengeospatial.org/is/19-045r3/19-045r3.html) types as acceptable OAF "features" 
3) Every Thing/Sensor/Datastream object is a collection, with items being observations with locations. This might be feasible to make some kind of OAF endpoint on but not really the way pygeoapi is designed to be configured

**Comment by jkreft-usgs** [comment]
I would be a fan of starting with `1` and building to 2 eventually.

**Comment by ksonda** [comment]
Working through this some more, particularly with reference to the JSON-LD aspect...the logical thing to do (I think) is to use sosa/ssn. Summarizing @justb4 proposal each STA endpoint can be represented in OAF as 2 collections: 

1. `SensorThingLocationPropertyStream` (hereafter I'll call it "STAF" for "STA Features")
2. `Observations`. Potentially `Observations` includes each STA Observation's STA FeatureOfInterest for their geometry.

The issue is that a STAF is basically a `Datastream` with some links. And a Datastream, if it is anything in `sosa`, is a `sosa:ObservationCollection` with mandatory `observedProperty` and `madeBySensor` links. However I think in this context we want the STAF to be more more like `sosa:FeatureOfInterest`, that each `Observation` item can declare links of `sosa:hasFeatureOfInterest` to. The issue with the STAF is that it introduces duplicate Thing/Locations with no good way to indicate which ones are the same other than with STA absolute @iot.id navigationLinks, which are a) not semantic and b) not necessarily there due to most STA implementations using relative navigationLinks by default.

I think to do this correctly, we actually need three Collections, and can only do it assuming non-moving sensors and that a STA Thing + Location corresponds to an O+M FeatureOfInterest. 

1. Thing + Location Serving as `sosa:FeatureOfInterest` (this being an extra-ontological, use-case based assumption)
2. Datastreams serving as `sosa:ObservationCollection`, linked to (1) by `sosa:hasFeatureOfInterest`
3. Observations, related to (2) by `sosa:isMemberOf`  (although as far as I know there is only `sosa:hasMember`. the inverse was in a proposed draft but isn't in ssn-ext)

Thoughts?

**Comment by ksonda** [comment]
we have another iteration if people want to peruse.

`docker run -p 5000:80 --rm webbben/pygeoapi-sensorthings:1.2`

Now im worried this actually is an OAF/STA alignment conversation more than a pygeoapi one...

**Comment by tomkralidis** [comment]
Excellent work here!  Agree, pending the STA/OAFeat alignment that from a pygeoapi standpoint this looks great!

**Comment by ksonda** [comment]
We'd be happy to convert this to a PR, although I'm not sure if you want it as a core plugin or if we should just maintain elsewhere.

**Comment by tomkralidis** [comment]
IMO this would be valuable as a core plugin.  If you're willing to provide tests, documentation and maintenance around the plugin itself in pygeoapi core (we're willing to help guide you if needed), this would be great.

**Comment by ksonda** [comment]
It's certainly in our own org's interests for this to be a core plugin so we can work towards that. @webb-ben may indeed need some guidance around tests and places in the docs that would need to be updated.

**Comment by webb-ben** [comment]
Hello Tom! Nice to e-meet you. I certainly would appreciate any guidance you are willing to offer. 

I am still working to optimize the performance and configuration requirements. With that in mind, this section of code has been driving me crazy.

[Code](https://github.com/webb-ben/pygeoapi/blob/837ba981d651a268b45ad37e39b18a87a8bdebed/pygeoapi/provider/sensorthings.py#L262-L273)-
```
# Create relative links            
if k in ['Thing', 'Datastream']:
    _ = 'collections/{}/items/{}'.format(
        k + 's', v['@iot.id']
    )
    entity[k] = urljoin(self.rel_link, _)
```
[Config](https://github.com/webb-ben/pygeoapi/blob/837ba981d651a268b45ad37e39b18a87a8bdebed/docker/examples/sensorthings/sta.pygeoapi.config.yml#L129)-
```
 - type: feature
    name: Sensorthings 
    entity: Observations 
    data: https://sensorthings-wq.brgm-rec.fr/FROST-Server/v1.0/
    id_field: '@iot.id'
    relative_link: http://localhost:5000
```
None of the server config makes it to any of the providers, the configuration has to take in the relative link from the provider definition. Even more generally, STA is one entity that is split into three (or more) collections, and thus uses very similar configurations for each. Can you think of a way to make this less verbose?

Gonna work on the documentation and pytest next. Any advice would be much appreciated!

**Comment by tomkralidis** [comment]
Likewise @webb-ben!

- you might want consider setting some configuration as environment variables and simply use those in your plugin
- can you provide example of the relationships you're looking for? Not sure whether you can generate these from your backend per se
- for tests, see the provider test in `tests/test_*_provider.py`
- for docs, you would want to update https://docs.pygeoapi.io/en/latest/data-publishing/ogcapi-features.html accordingly, adding SensorThings to the provider matrix as well as adding example provider configurations

Hope this helps.

**Comment by webb-ben** [comment]
To your first and last point: We haven't been sure how configurable the STA provider should be. Would be interested to hear your thoughts as well as @ksonda (and anyone else) as to what you think makes the most sense to be configured vs. configurable.

The relationship is that [Datastreams(2516486)](https://sensorthings-wq.brgm-rec.fr/FROST-Server/v1.0/Datastreams(2516486)?$expand=Thing,Observations) has a relationship to Thing and Observations that can be represented in pygeoapi. For instance: http://localhost:5000/collections/Datastreams/items?Thing=2995 points to all of the Datastreams related to Thing 2995. In this way, every STA entity represented in pygeoapi has a relationship to other items that _could_ be represented in pygeoapi. However, to make that relationship an attribute of the item's property table. Instead of making `http://localhost:5000/` (or whatever is in `config['server']['url']`). Just trying to think of the most parsimonious way to implement this relationship.

Working on the tests for jsonld/geosparql is giving me a good start into the tests in general but I will take a look.

Thanks!

**Comment by ksonda** [comment]
The properties filter is good to enable no matter what.

However, we do want there to the relationships directly encoded in the item property table too. eg. Thing(2995) should still have a Datastream attribute listing all the /collections/Datastreams/items/xxxxx items directly, mostly for the JSON-LD part, because part of the whole point is that we want HTTP URIs for these compounded entities that dont include querystrings.

agree environmental variables is probably the most parsimonious way to do it

Regarding configurability, I think we can start with this recommended 3-collection configuration and iterate in the medium term to either a more fully flexible model or to whatever comes out of OAF/STA alignment in ~2 years.

**Comment by tomkralidis** [comment]
@webb-ben +1 to leave the `sortby` handling separate/isolated to another PR given it has deeper implications on other standards.

**Comment by tomkralidis** [comment]
Implemented in #721 (great work!) .  @webb-ben / @ksonda if there are no objections I propose to close this issue given the initial implementation

**Comment by ksonda** [comment]
That's fine, the discussion here is probably better moved to the OGC OAF and/or STA repos.

**Comment by KoalaGeo** [comment]
Follow on feature request - https://github.com/geopython/pygeoapi/issues/817
