### ISSUE TITLE
Enable datetime / sortby / properties queries for Postgres provider

### ISSUE THREAD

**Issue by KoalaGeo** [geopython/pygeoapi#687]
**Is your feature request related to a problem? Please describe.**
We have a lot of data in Postgres, it'd be great to connect this to pygeoapi with the full query functionality the same as an elastic search or mongodb provides

**Describe the solution you'd like**
When using Postgres as a provider for OA-Features be able to query datetime, sortby and properties

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by ksonda** [comment]
@webb-ben @dblodgett-usgs we are probably going to need to do this for the global river runner anyway.

**Comment by webb-ben** [comment]
I've added to the select_properties, skip_geometry, and sortby to the postgres provider when tinkering around for river runner. I don't know if this is still relevant @ksonda but figured I would loop back to this.
