### ISSUE TITLE
Question re: OpenAPI document generation

### ISSUE THREAD

**Issue by captaincoordinates** [geopython/pygeoapi#688]
OpenAPI documentation appears to be generated exclusively by [openapi.py](https://github.com/geopython/pygeoapi/blob/a4bf35d310f66aa03889e086de4a0d3d4090f394/pygeoapi/openapi.py). This is a large file with a significant number of string literals in which human error could occur. Are there any guarantees, i.e automated tests, that the OpenAPI documentation accurately reflects the behaviour of the API's endpoint interfaces?

Looking through the tests directory I see [test_openapi.py](https://github.com/geopython/pygeoapi/blob/a4bf35d310f66aa03889e086de4a0d3d4090f394/tests/test_openapi.py) but it appears limited in scope. Are there other tests elsewhere that guarantee agreement between the API and its documentation?

**Comment by tomkralidis** [comment]
There are no deep automated tests at the moment.  Can you describe the human errors?

We do linting of test OpenAPI output [in Travis](https://github.com/geopython/pygeoapi/blob/master/.travis.yml#L96), but not as part of the main test harness (the reason being that the OGC API schemas we are using are in flux given the pre-1.0 state of OGC APIs and pygeoapi for that matter).

Contributions to help update the tests are welcome.

**Comment by francbartoli** [comment]
Thanks @captaincoordinates, I believe that's a great point and definitively something to improve. Can you elaborate more in-depth on the automation that you are looking for?

**Comment by captaincoordinates** [comment]
For errors I'm anticipating a scenario where API implementation code changes but openapi.py is not updated by the develeper(s) for some reason. For example, let's say the format parameter name changes from `f` to `format`. Based on my (limited) understanding of openapi.py I believe that would require updates in all 12 locations in openapi.py featuring the following array member

```
    {'$ref': '#/components/parameters/f'}
```
and changes within the `oas['components']` dictionary value.

If human error resulted in some or all of these updates being missed then the OpenAPI documentation would be incorrect, and it would disagree with the API's observed behaviour. However without automated tests this issue will be hidden until a user or developer raises it.

I'm not familiar enough with the domain to know what a suitable test strategy would look like. Perhaps a test that iterates over all endpoints defined in /openapi?f=json and attempts to issue requests against those endpoints?

**Comment by tomkralidis** [comment]
@francbartoli isn't this what spectral was for? i.e., from our Travis setup:

`docker run --rm -it -v $(pwd):/tmp stoplight/spectral lint "/tmp/pygeoapi-openapi.yml"`

Spectral would verify that the OpenAPI document is valid and resolves accordingly.  Does this help (once the OGC API specifications we support are ratified)?

**Comment by tomkralidis** [comment]
@captaincoordinates please post questions to the pygeoapi mailing list or [GitHub discussions](https://github.com/geopython/pygeoapi/discussions). pygeoapi GitHub issues are for **software bugs/enhancements** and related tasks.
