### ISSUE TITLE
fix MVT tiles provider broken tile references

### ISSUE THREAD

**Issue by tomkralidis** [geopython/pygeoapi#695]
**Description**
The MVT provider plugin has an issue referencing tiles. This may be bound to environments where pygeoapi is deployed to a subpath.  We found this during the [May 2021 OGC API Virtual Code Sprint](https://github.com/opengeospatial/ogcapi-code-sprint-2021-05).

**Steps to Reproduce**

- Go to https://demo.pygeoapi.io/stable/collections/lakes/tiles?f=html

This page looks for tiles at

https://demo.pygeoapi.io/collections/lakes/tiles/WorldCRS84Quad/0/0/0?f=mvt

But should be looking for tiles instead at:

https://demo.pygeoapi.io/stable/collections/lakes/tiles/WorldCRS84Quad/0/0/0?f=mvt

(i.e. “stable” is missing).

**Expected behavior**
Tile link relations should resolve correctly.

**Screenshots/Tracebacks**
None

**Environment**
 - OS: OSX
 - Python version: 3.7
 - pygeoapi version: master

**Additional context**

**Comment by tomkralidis** [comment]
The issue seems to be the use of `urllib.parse.urljoin` in `pygeoapi/provider/mvt.py` when the baseurl contains a subpath.

To isolate / demonstrate:
```python
>>> urljoin('http://demo.pygeoapi.io', 'collections')
'http://demo.pygeoapi.io/collections'
>>> urljoin('http://demo.pygeoapi.io/stable', 'collections')
'http://demo.pygeoapi.io/collections' 
```

**Comment by justb4** [comment]
Yes, *"urljoin does not join URLs"* :-) as in [this StackOverflow discussion](
https://stackoverflow.com/questions/1793261/how-to-join-components-of-a-path-when-you-are-constructing-a-url-in-python). Long discussion, I tried this snippet (at bottom of discussion), working ok, maybe a `util.py` thing:

```
Python 3.7.1 (default, Nov 17 2020, 13:42:41) 
[Clang 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> def UrlJoin(*parts):
    return '/'.join([p.strip().strip('/') for p in parts])
... 
>>> UrlJoin('https://example.com/', '/TestURL_1')
'https://example.com/TestURL_1'
>>> UrlJoin('https://example.com/baspath', '/TestURL_1')
'https://example.com/baspath/TestURL_1'
>>> UrlJoin('https://example.com/baspath//', '/TestURL_1')
'https://example.com/baspath/TestURL_1'
```
