### ISSUE TITLE
Update OATiles to the latest specification changes

### ISSUE THREAD

**Issue by francbartoli** [geopython/pygeoapi#699]
**Description**
As reported at the OGC OATiles code sprint our demo implementation of the [specification](https://github.com/opengeospatial/ogcapi-tiles) is outdated:

- [ ] `tilesets` should replace `tileMatrixSetLinks`
- [ ] there should also be a link to a TileSet resource, where the actual `item` link to tiles will be (`/tiles` is only the "list of tilesets")
- [ ] The TileJSON should also be changed to be an alternate representation of a particular tileset, as opposed to a `describedby` / separate metadata resource
- [ ] Also the `tileMatrixSetURI` should use the TMS register , e.g. http://www.opengis.net/def/tilematrixset/OGC/1.0/WebMercatorQuad
- [ ] the `tileMatrixSet` key is for a full TMS description, the id should use `id`

See also [this diagram](https://files.gitter.im/60634f5b6da0373984789488/UyKK/TileSet.png)

**Steps to Reproduce**

Open the tiles about the lake collection in the [demo instance](https://demo.pygeoapi.io/master/collections/lakes/tiles)

**Expected behavior**
The closest implementation might be found [here](https://maps.ecere.com/ogcapi/collections/Daraa/tiles?f=json)

**Screenshots/Tracebacks**

**Environment**
 - OS:
 - Python version:
 - pygeoapi version:

**Additional context**

**Comment by PascalLike** [comment]
For the tileMatrixSetURI that should use the TMS register part, I got an interesting suggestion: we could use [this registry](https://github.com/opengeospatial/2D-Tile-Matrix-Set/tree/master/registry/json), linking directly raw files [like this](https://raw.githubusercontent.com/opengeospatial/2D-Tile-Matrix-Set/master/registry/json/CanadianNAD83_LCC.json)
