### ISSUE TITLE
OA-Tiles not available in HTML or API

### ISSUE THREAD

**Issue by KoalaGeo** [geopython/pygeoapi#714]
**Description**
Vector tiles aren't displayed on the HTML pages, logs indicate pygeoapi is requesting tiles which are aren't present. 

`Jun 14 16:54:45.637 | pygeoapi-1430-staging-dmz-579ffb74b6-lqxxj | [2021-06-14T16:54:45Z] {/pygeoapi/pygeoapi/api.py:2827} ERROR - Tile not found (check logs)`
`Jun 14 16:54:45.637 | pygeoapi-1430-staging-dmz-579ffb74b6-lqxxj | [2021-06-14T16:54:45Z] {/pygeoapi/pygeoapi/api.py:2010} ERROR - [Errno 2] No such file or directory: '/pygeoapi/bgsdata/tiles/bedrock-geology/8/76/92.pbf'`
`Jun 14 16:54:45.637 | pygeoapi-1430-staging-dmz-579ffb74b6-lqxxj | [2021-06-14T16:54:45Z] {/pygeoapi/pygeoapi/api.py:2827} ERROR - Tile not found (check logs)`

**Steps to Reproduce**
Create tiles using tippecanoe
`tippecanoe -zg -e bedrock-geology --drop-densest-as-needed bedrock_geology.geojson`
Source dataset - https://github.com/BritishGeologicalSurvey/bgs-pygeoapi/blob/master/content/bedrock_geology.geojson 
`COPY` data to container - https://github.com/BritishGeologicalSurvey/bgs-pygeoapi/blob/master/Dockerfile 
Config - https://github.com/BritishGeologicalSurvey/bgs-pygeoapi/blob/master/content/local.config.yml 

**Expected behavior**
Vector tiles should be visible on leaflet map at https://osgeodev.bgs.ac.uk/pygeoapi/collections/BGSGeology625kBedrock/tiles 

**Screenshots/Tracebacks**
https://osgeodev.bgs.ac.uk/pygeoapi/collections/BGSGeology625kBedrock/tiles

**Environment**
 - OS: Ubuntu
 - Python version: pygeoapi from DockerHub
 - pygeoapi version: 0.11

**Additional context**
Requests to known tile locations work - https://osgeodev.bgs.ac.uk/pygeoapi/collections/BGSGeology625kBedrock/tiles/WorldCRS84Quad/8/123/77

**Comment by KoalaGeo** [comment]
Linked to https://osgeodev.bgs.ac.uk/pygeoapi/collections/BGSGeology625kBedrock/tiles/WorldCRS84Quad/8/123/77 ?

**Comment by KoalaGeo** [comment]
Closing this, as believe it's a tippecanoe issue. No major issues when using pg_tileserv to serve the tiles

**Comment by nagyrobir** [comment]
Hei!
I don't know if this got fixed eventually but i am running into the same issue, I cannot manage to publish vector tiles from local folder. I don't get anything even though i tried to generate the tiles with GDA. If i type in the browser http://localhost:5000/collections/demo_mvt/tiles/WorldCRS84Quad/0/0/0 then the pbf file gets downloaded as a gz file, even though gzip is set to false in the config.
