### ISSUE TITLE
response to non-existent collection returns 400 instead of 404

### ISSUE THREAD

**Issue by philvarner** [geopython/pygeoapi#722]
https://github.com/geopython/pygeoapi/blob/48efbdec531d13e8d6bc41e9a20f6e419b2ad1c0/pygeoapi/api.py#L702

Per http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#_error_situations_5 , a request for a collection that does not exist should return status code 404, rather than 400 as pygeoapi does now.

**Comment by tomkralidis** [comment]
Thanks for reporting @philvarner.  Fixed in f01dfd3
