### ISSUE TITLE
Support cloud object storage for STAC

### ISSUE THREAD

**Issue by aripollak** [geopython/pygeoapi#724]
**Is your feature request related to a problem? Please describe.**
Currently, STAC support requires files to be accessible via regular filesystem operations, but I'm working on a project where it would make more sense for the files to live in AWS S3.

**Describe the solution you'd like**
Add the ability to retrieve files for STAC via cloud storage, perhaps via something like https://libcloud.apache.org/ or using pystac?

**Describe alternatives you've considered**
* It might be possible to emulate a real filesystem by using something like https://github.com/kahing/goofys, but that requires FUSE support, which isn't currently possible on AWS ECS Fargate.

**Comment by aripollak** [comment]
Note that libcloud storage doesn't currently seem to have the ability to walk just a single directory level at a time, so I'd probably go with boto3 for efficiency reasons based on the way the existing FileSystem provider works. Many non-AWS providers already have an S3-compatible API, so supporting those should just be a matter of configuring the hostname.

**Comment by tomkralidis** [comment]
Thanks @aripollak, sounds good.  Might want to consider abstracting the boto3 support within the provider, so that we can extend at some point if needed (for example, for Azure blob storage, etc.).
