### ISSUE TITLE
fix SensorThings API provider tests

### ISSUE THREAD

**Issue by tomkralidis** [geopython/pygeoapi#733]
We're seeing regression errors in this provider: https://github.com/geopython/pygeoapi/runs/3125739931?check_suite_focus=true#step:14:166

@ksonda @webb-ben can you take a look?  I have commented out the unit test for now in master until we can integrate a fix.

**Comment by ksonda** [comment]
working on it. think it's a configuration issue with FROST sta server.

**Comment by webb-ben** [comment]
@tomkralidis this can probably be closed
