### ISSUE TITLE
Executing Hello World process in async mode returns an empty json object

### ISSUE THREAD

**Issue by PhilippePinheiroLIST** [geopython/pygeoapi#734]
**Description**
Executing the Hello World process in async mode directly returns {}   (empty JSON object) instead of returning a object with  processID  or an error message due to a problem related to tinyDB

**Steps to Reproduce**
execute curl command as defined in doc https://docs.pygeoapi.io/en/latest/data-publishing/ogcapi-processes.html : 

```bash
curl -X POST "http://localhost:5000/processes/hello-world/jobs" -H "Content-Type: application/json" -d "{\"mode\": \"async\", \"inputs\":[{\"id\":\"name\",\"type\":\"text/plain\",\"value\":\"hi there2\"}]}"
```
**Expected behavior**
Return non empty JSON object containing a processID or an error message

**Environment**
 - OS:  Ubuntu 20
 - Python version: 3.8.10
 - pygeoapi version:  version 0.11.dev0

**Comment by tomkralidis** [comment]
@PhilippePinheiroLIST thanks for the report. There have been some updates to pygeoapi's OAProc support as part of the OGC July 2021 Virtual Sprint.  Can you try as follows and report back?

```bash
# note the updated endpoint and change of request JSON payload format

curl -X POST "http://localhost:5000/processes/hello-world/execution" -H  "accept: application/json" -H  "Content-Type: application/json" d "{\"mode\": \"async\",\"inputs\":{\"message\":\"An optional message.\",\"name\":\"World\"}}"
```
