### ISSUE TITLE
flowtrace and split-catchment not working

### ISSUE THREAD

**Issue by cheginit** [geopython/pygeoapi#778]
**Description**
It seems that there's an issue with `flowtrace` and `split-catchment` processes. Even, the default examples on the [Swagger](https://labs.waterdata.usgs.gov/api/nldi/pygeoapi/openapi) are not working and return the following error:

```python
{
  "code": "InvalidParameterValue",
  "description": "Error updating job"
}
``` 

**Steps to Reproduce**

Run this in a terminal (the default example for the `flowtrace` service):
```bash
curl -X POST "https://labs.waterdata.usgs.gov/api/nldi/pygeoapi/processes/nldi-flowtrace/jobs?response=document" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{\"inputs\":[{\"id\":\"lat\",\"type\":\"text/plain\",\"value\":\"43.29139\"},{\"id\":\"lon\",\"type\":\"text/plain\",\"value\":\"-73.82705\"},{\"id\":\"raindroptrace\",\"type\":\"text/plain\",\"value\":\"False\"},{\"id\":\"direction\",\"type\":\"text/plain\",\"value\":\"none\"}]}"
```

**Expected behavior**
It should return the correct response.

**Screenshots/Tracebacks**
N/A

**Environment**
The PyGeoAPI [Swagger UI](https://labs.waterdata.usgs.gov/api/nldi/pygeoapi/openapi).

**Additional context**
N/A

**Comment by tomkralidis** [comment]
Looks like this is for another project. Closing.
