### ISSUE TITLE
Subsetting a coverage using a bounding box with the xarray provider creates a query using the wrong parameters

### ISSUE THREAD

**Issue by metmikel** [geopython/pygeoapi#782]
**Description**
From inspection of the xarray code (I'm borrowing heavily from it as I want to do something similar), I noticed that when building the list of query parameters from a bounding box definition the literal values 'x_axis_label' and 'y_axis_label' are added to the query parameters dictionary rather looking up the values of these keys using `self._coverage_properties['x_axis_label']` (for instance).  This is different from what will happen if subsetting using the axis labels.
[See lines 234-235 xarray_py](https://github.com/geopython/pygeoapi/blob/2cb68277f96d7bcbae97af6fe1e83a30bd0741ea/pygeoapi/provider/xarray_.py#L234)

**Steps to Reproduce**
I haven't actually reproduced this bug, but presumably you could by:
1. Setting up a resource with a provider of type 'coverage' and name 'xarray'
2. Requesting a spatial subset of the coverage using the bbox query parameter.

**Expected behavior**
The requested spatial subset of the coverage would be returned.

**Comment by tomkralidis** [comment]
Fixed by #783 -- thanks @metmikel !
