### ISSUE TITLE
STA Provider breaks if STA @iot.id is not integer

### ISSUE THREAD

**Issue by ksonda** [geopython/pygeoapi#787]
This is mostly for @webb-ben, who is out until Wednesday

**Description**
The USGS demonstrator (https://pygeoapi-test.info.geoconnex.us/collections/Things/items) successfully produces a feature collection, but any particular item errors out.

**Steps to Reproduce**
https://pygeoapi-test.info.geoconnex.us/collections/Things/items/USGS-14152000

**Expected behavior**
If STA @iot.id is non-integer, the item is successfully rendered

**Screenshots/Tracebacks**
I believe this is the issue: https://github.com/geopython/pygeoapi/blob/master/pygeoapi/provider/sensorthings.py#L244 Basically, if the identifier (from id_field/ @iot.id) is not integer, the request needs to be wrapped in single quotes

**Comment by webb-ben** [comment]
I have the patch for this bug (as well as a correct implementation of the `hits` query parameter) located at [pygeoapi/sta-patch](https://github.com/webb-ben/pygeoapi/tree/sta-patch), but can't get the [github workflow](https://github.com/webb-ben/pygeoapi/actions/runs/1295704058) to pass. @tomkralidis if you have any idea what is going on with the config validation, your thoughts would be greatly appreciated. In looking through `pygeoapi-config-0.x.yml`, I saw that I forgot to add `uri_field` to the schema file when I implemented that field, but it doesn't seem to be the source of the issue.

**Comment by tomkralidis** [comment]
Good catch @webb-ben.  There was an issue in the config schema (now fixed in https://github.com/geopython/pygeoapi/commit/f091d971b16c59f36ef3371eb434b02c4c7492e1), which I'm guessing materialized via a newer jsonschema release.  Can you rebase/try again (without adding the `uri_field` definition given it's STA provider specific)?  Thanks

**Comment by webb-ben** [comment]
@tomkralidis The most recent commit fixed it. I might be misunderstanding your second request but I will remove `uri_field` schema from this PR because it is not STA specific. It should be an optional field for all feature providers whereas this is just a STA patch. Cheers!
