### ISSUE TITLE
apply for OSGeo project status

### ISSUE THREAD

**Issue by tomkralidis** [geopython/pygeoapi#790]
As per https://lists.osgeo.org/pipermail/pygeoapi/2021-October/000203.html, it's a good time to move pygeoapi through the OSGeo incubation process.  Becoming an OSGeo project will give the project a stamp of approval, help with long term health and
sustainability, as well as provide the project some access to OSGeo budget.

pygeoapi is already an OSGeo Community project so our next step is entering incubation.

Steps (per https://wiki.osgeo.org/wiki/Incubation_Committee):
- Initial Application
  - [x] Application request
  - [x] Mentor volunteer (@msmitherdc)
- Incubator
  - [x] Project Status: project details, and a few resourcing questions for the system admin committee (see [Project Status Template](https://wiki.osgeo.org/wiki/Project_Status_Template))
  - [x] Provenance Review: project team check to ensure the project is open source and has permission to distribute its source code.
  - [x] Project team and mentor work on [graduation checklist](https://github.com/OSGeo/osgeo/blob/master/incubation/documents/graduation_checklist.pdf) priorities
- Graduation
  - [x] Mentor recommends project for graduation with motion to the incubation committee
  - [x] Committee chair informs the OSGeo board, who appoints the project team as a newly formed OSGeo committee

The [pycsw](https://github.com/geopython/pycsw/wiki/OSGeo-Incubation) and [PyWPS](https://github.com/geopython/pywps/wiki/OSGeoIncubation) projects provide examples from similar projects in our Geopython family.

Documentation is on Wiki at https://github.com/geopython/pygeoapi/wiki/OSGeoIncubation

**Comment by tomkralidis** [comment]
- application submitted: https://trac.osgeo.org/osgeo/ticket/2651
- request sent to Incubation Committee: https://lists.osgeo.org/pipermail/incubator/2021-October/004422.html

**Comment by kalxas** [comment]
welcome @msmitherdc !

**Comment by tomkralidis** [comment]
Hi all: update: our next step in the process is the provenance review.  I've done a first pass in https://github.com/geopython/pygeoapi/wiki/ProjectProvenanceReview for review and comment.

@msmitherdc please let us know if this is suitable and what we should update.

**Comment by msmitherdc** [comment]
@tomkralidis this looks like a very good start for the Provenance Review. Have you started contacting Copyright holders? That and fixing the few code headers and attribution and you look quite far along. Do you have a target release for getting these changes in?

**Comment by tomkralidis** [comment]
Thanks @msmitherdc.  Updates/questions:

- contribution agreements issue now filed in #928
- I've also added a [Pull Request Template](https://github.com/geopython/pygeoapi/blob/master/.github/PULL_REQUEST_TEMPLATE.md) for contributions moving forward
- as far as other issues:
  - https://github.com/geopython/pygeoapi/issues/929
  - https://github.com/geopython/pygeoapi/issues/930
  - we have one file with magazine code: https://github.com/geopython/pygeoapi/blob/master/pygeoapi/util.py#L118.  Not sure if/how this one needs to be resolved per se?
  
We are targetting 0.13 as our next release in the coming weeks.

**Comment by tomkralidis** [comment]
Updates:
- OSGeo project officer selected (https://lists.osgeo.org/pipermail/pygeoapi/2022-August/000259.html)
- PSC approved to motion to graduate (https://lists.osgeo.org/pipermail/pygeoapi/2022-August/000267.html)
- @msmitherdc has made the motion to the OSGeo Incubation committee (https://lists.osgeo.org/pipermail/incubator/2022-August/004507.html)

**Comment by tomkralidis** [comment]
Additional references:
- https://wiki.osgeo.org/wiki/Incubation_Committee#pygeoapi
- https://www.osgeo.org/projects/pygeoapi

**Comment by tomkralidis** [comment]
Motion passed: https://lists.osgeo.org/pipermail/incubator/2022-August/004535.html

Next step:
- seek OSGeo Board of Directors approval, which has been cast by @msmitherdc at https://www.loomio.org/p/XjpcFNvf?stance_token=942siJBuhnMpw5NgrGDsNWnY
  -  also added to agenda for next Board meeting: https://wiki.osgeo.org/wiki/Board_Meeting_2022-08-27#Current_items

**Comment by tomkralidis** [comment]
Board vote complete; motion passed.

- https://www.osgeo.org/foundation-news/pygeoapi-graduates-osgeo-incubation
- https://twitter.com/OSGeo/status/1561434042007945216
- sent as news item to OSGeo announce as per https://wiki.osgeo.org/wiki/News_Queue#Submitting_News

**Comment by justb4** [comment]
So we can close, right?

**Comment by tomkralidis** [comment]
Yes, we are now an official OSGeo project.  Thanks everyone!
