### ISSUE TITLE
expand support options

### ISSUE THREAD

**Issue by tomkralidis** [geopython/pygeoapi#791]
We should add more information to our support documentation:

- https://docs.pygeoapi.io/en/latest/support.html
- https://pygeoapi.io/community

...by adding support from commercial providers.

**Comment by GeoSander** [comment]
Hi @tomkralidis, good idea! On behalf of [GeoCat](https://www.geocat.net/) I can report that we would be happy to be listed as a service provider (and/or core contributor).

**Comment by tomkralidis** [comment]
Inspired by the GeoServer and GDAL examples, an initial page has now been published to https://pygeoapi.io/community/service-providers for review/comments.  Please feel free to improve (repo at https://github.com/geopython/pygeoapi.io

@kalxas @francbartoli @justb4 @GeoSander / @jodygarnett : I've added `TODO` placeholders for your organizations as per those listed in https://pygeoapi.io/presentations/foss4g2021/#/7 .  Please update accordingly for your respective organizations.

The page is not linked yet to the main website (will do so once we have the service providers updated)

cc @totycro @webb-ben @jmckenna please feel free to add/update if you wish.

We can do a wider announcement and invite others/potentially more providers thereafter.

**Comment by tomkralidis** [comment]
Initial page now updated at https://pygeoapi.io/community/service-providers/
