### ISSUE TITLE
URL links drop ending parentheses in HTML

### ISSUE THREAD

**Issue by KoalaGeo** [geopython/pygeoapi#796]
**Description**
When connecting to SensorThingAPI the @iot.selfLink is dropping the final ) from the Frost Server URL - in this case = http://sensors-internal.bgs.ac.uk/FROST-Server/v1.1/Things(4)

In `?f=json` view the URL is correct

**Steps to Reproduce**
Run pygeoapi in docker connecting to a SensorThingsAPI provider

**Expected behavior**
URL link function in html view 

**Screenshots/Tracebacks**
![image](https://user-images.githubusercontent.com/33657876/136968878-3b157738-9cba-4800-866f-2ede4fed6fd5.png)

![image](https://user-images.githubusercontent.com/33657876/136968804-18859aa6-42e9-4da8-a20d-a7cc732d0b6f.png)

**Environment**
 - OS: Docker image
 - Python version: ^
 - pygeoapi version: :latest

**Additional context**
N/A

**Comment by tomkralidis** [comment]
Iis this now fixed, given #876?
