### ISSUE TITLE
add providers for generic open data portals like CKAN and Socrata

### ISSUE THREAD

**Issue by ksonda** [geopython/pygeoapi#810]
**Is your feature request related to a problem? Please describe.**
I would like to use pygeoapi to generate an OAF endpoint based on tabular data made available via the CKAN Data API and the Socrata SODA API. These two platforms are extremely common (along with ArcGIS Hub) among government agencies to publish their open data, including environmental monitoring data with point geometry.

Examples:

CKAN:
https://data.cnra.ca.gov/dataset/periodic-groundwater-level-measurements/resource/af157380-fb42-4abf-b72a-6f9f98868077
(see "data API")

Socrata:
https://data.waterpointdata.org/dataset/Water-Point-Data-Exchange-WPDx-Basic-/jfkt-jmqa/data
(see "Export" -> "SODA API")

**Describe the solution you'd like**
pygeoapi providers similar in configuration to the CSV provider. Specification of an x and y field is about as general as I think it could get with these tabular data APIs. 

**Describe alternatives you've considered**
My existing workflows to do this involve bulk downloading the tabular data in csv format and serving the pygeoapi based on the local copy.

**Additional context**
@webb-ben I'd appreciate it if you could take a start but all contributions welcome.

**Comment by webb-ben** [comment]
Socrata provider in main. CKAN provider in [cgs-earth/pygeoapi-plugins](https://github.com/cgs-earth/pygeoapi-plugins)
