### ISSUE TITLE
SensorThingsAPI Provider Plugin for OGCAPI-EDR

### ISSUE THREAD

**Issue by KoalaGeo** [geopython/pygeoapi#817]
**Is your feature request related to a problem? Please describe.**
Interopability between the STA standard and the OGCAPI-EDR standard 

**Describe the solution you'd like**
Be able to add a STA endpioint to the pygeoapi config to generate endpoints for:
+ [x] - OGCAPI-Features (https://github.com/geopython/pygeoapi/issues/685 )
+ [ ] - OGCAPI-EDR 

**Describe alternatives you've considered**
Postgres provider for EDR?

**Comment by ksonda** [comment]
Can probably start contributing to something like this in March.

**Comment by KoalaGeo** [comment]
@ksonda @jkreft-usgs @hylkevds kicked of a feature request to consolidate discussion on concept mapping

**Comment by tomkralidis** [comment]
Note the discussion #817 which has resulted in an EDR base plugin, so recommend to inherit from `pygeoapi.provider.base_edr` and auto-register query types with decorators.

**Comment by ksonda** [comment]
There are 2 issues embedded here. 

1. Concept mapping STA -> EDR
2. Implementing said mapping in pygeoapi, inheriting from base_edr provider

I'm wondering if (1) should be taken up at https://github.com/opengeospatial/sensorthings

**Comment by webb-ben** [comment]
Implemented with https://github.com/geopython/pygeoapi/pull/1928
