### ISSUE TITLE
PDF output of documentation is missing emojis

### ISSUE THREAD

**Issue by maaattes** [geopython/pygeoapi#844]
**Description**
This is probably just a minor issue of [readthedocs](https://github.com/readthedocs/readthedocs.org), but emojis used in the HTML documentation don't show up in the PDF so some parts lose their information.

**Steps to Reproduce**
1. Download the documentation in PDF via [https://docs.pygeoapi.io/_/downloads/en/latest/pdf/](https://docs.pygeoapi.io/_/downloads/en/latest/pdf/)
2. Scroll to page 39
3. Compare the matrix with the matrix at [https://docs.pygeoapi.io/en/latest/data-publishing/ogcapi-features.html#providers](https://docs.pygeoapi.io/en/latest/data-publishing/ogcapi-features.html#providers)

**Expected behavior**
The PDF output should match the HTML.

**Screenshots/Tracebacks**
![Emoji in HTML](https://user-images.githubusercontent.com/52661914/150842097-541e8fef-a984-439b-9150-2845be7bf8e0.png)
![Emoji in PDF](https://user-images.githubusercontent.com/52661914/150841989-e4a869ac-f52f-4d8d-86a0-d6f0a90f4ab4.png)

**Comment by tomkralidis** [comment]
Reported to RTD at https://github.com/readthedocs/readthedocs.org/issues/8841

**Comment by tomkralidis** [comment]
Moved to Sphinx at https://github.com/sphinx-doc/sphinx/issues/10171

**Comment by tomkralidis** [comment]
FYI fixed in master (see https://github.com/sphinx-doc/sphinx/issues/10171#issuecomment-1036494391)
