### ISSUE TITLE
Missing / non-conforming OGC API - Processes links/relations

### ISSUE THREAD

**Issue by jerstlouis** [geopython/pygeoapi#845]
**Description**
Issues conforming with [OGC API - Processes 1.0](https://docs.ogc.org/is/18-062r2/18-062r2.html) discovered in extended T-17 TIEs:
- Each process description (`/processes/{processId}`) needs to include a link to the execution end-point with relation type `http://www.opengis.net/def/rel/ogc/1.0/execute`
- The list of processes (`/processes`) needs to include a link with relation type `self` in each array item pointing to the process description (`/processes/{processId}`)
- Note also that the links currently in process description using _collection_ relation type end-point linking to jobs is not correct -- the specification specifies `http://www.opengis.net/def/rel/ogc/1.0/job-list` to link to the list of jobs. (also applies to the content at `/processes`)
- The use of rel: _canonical_ is probably also wrong, IANA says canonical _"Designates the preferred version of a resource (the IRI and its contents)."_, and I would take this to mean the canonical resource for the same resource, not some other resource (also applies to the content at `/processes`)

**Steps to Reproduce**
Inspect the resources for an _OGC API - Processes_ deployment of pygeoapi.

**Expected behavior**
Following the specifications as explained above.

**Environment**
 - pygeoapi version: 0.12.dev0

**Additional context**
Testbed 17 / 52 North pygeoapi deployment - Ecere client TIEs

cc @MartinPontius @tomkralidis

**Comment by tomkralidis** [comment]
Thanks @jerstlouis for the detailed report.  PR in #846

**Comment by tomkralidis** [comment]
Merged in #846.  Please reopen if there are outstanding issues.
