### ISSUE TITLE
OGC API - Records Provider - Local or Web Accessible Folder of metadata XML

### ISSUE THREAD

**Issue by KoalaGeo** [geopython/pygeoapi#865]
**Is your feature request related to a problem? Please describe.**
Similar to pyCSW it'd be nice to be able to load XML metadata records to serve OA-Records

**Describe the solution you'd like**
In the config be able to point pygeoapi at a local folder or web accessible folder (https://www.ordnancesurvey.co.uk/xml/products/)

**Describe alternatives you've considered**
Deploy pyCSW separately

**Additional context**

**Comment by tomkralidis** [comment]
cc @kalxas @pvgenuchten @francbartoli 

@KoalaGeo thanks for the info.  Sounds like we are looking for an OARec record loader of sorts that will write metadata (XML) to a given backend.  Given the complexity of various metadata XML representations and management workflow, I'm not sure we should have this capability in pygeoapi proper.

pygeoapi's current OARec design (like other provider types in the project) is that the metadata backend already exists and is ready for binding.  We have some [rudimentary utilities](https://github.com/geopython/pygeoapi/blob/master/tests/load_tinydb_records.py) to load ISO metadata into TinyDB databases, but this is scoped to bootstrapping test environments.

So, while we are here:
Q: "What's the difference between pycsw and pygeoapi" (coming to an FAQ soon)
A: pycsw has deeper metadata **content** support (administration/management/transactions and format translation).  pygeoapi assumes your backend is already in place

Having said this, I think there is a great opportunity for developing a pycsw record backend for pygeoapi.  In this way, one can use pycsw to manage the repo and pygeoapi to simply serve it out (note that pycsw also supports OARec).

Another option is to build something out in @pvgenuchten's up and coming [PyGeoDataCrawler](https://github.com/pvgenuchten/pyGeoDataCrawler), but I will let Paul speak to feasibility/options.

Looking forward to folks comments here.
