### ISSUE TITLE
datetime parameter not queryable

### ISSUE THREAD

**Issue by ThibautAr** [geopython/pygeoapi#869]
**Description**
Its seems like the datetime parameter is not queryable.

**Steps to Reproduce**
I tried the following query https://demo.pygeoapi.io/master/collections/obs/items?datetime=2001-10-30T14:24:55Z&f=json 

**Expected behavior**
Instead of having only one feature, the query returns all the features of the collections obs.

Did I miss somthing when writing the query?

**Comment by tomkralidis** [comment]
Correct, as @maaattes mentions.  This is a welcomed enhancement for our default CSV provider.
