### ISSUE TITLE
support  text/html encoding request in headers

### ISSUE THREAD

**Issue by jorgejesus** [geopython/pygeoapi#87]
Currently the default output of pygeoapi is a json format encoding with html only being supported when using `f=html` on the requests

Sofwares that are not geospatial aware e.g browser should automatically display the html formating. This could be achieved by by reading text/hml encoding on the HTTP header request

https://github.com/opengeospatial/WFS_FES/blob/75d7c7839aca8c27ad9f8590727b37e110cfa0e7/placeholder-additional-conformance-class/parameters/f.yaml

discussion:
https://github.com/opengeospatial/WFS_FES/issues/179

possibilities:
- a visitor opening a feature in a browser (browser will send html header)
- a search engine crawling the service (crawler will send html header)
- leaflet/openlayers requesting a set of features (it will send the json header)
- a desktop gis following a link from a feature to another feature (does it expect a webpage or a feature?)

**Comment by tomkralidis** [comment]
Implemented in #88
