### ISSUE TITLE
google does not index datasets anymore

### ISSUE THREAD

**Issue by pvgenuchten** [geopython/pygeoapi#877]
i noticed google dataset search does not list any datasets from demo.pygeoapi.io anymore

i wonder if it is related to the fact that rich snippets test finds the json representation

I assume, in case no accept header is given, the json representation is returned by pygeoapi, in my opinion we should return the html representation if no accept header is given (to support this case)

![image](https://user-images.githubusercontent.com/299829/160828469-6c8b0741-52a6-40ba-aa61-391126068bce.png)

**Comment by pvgenuchten** [comment]
The json-ld for search engine is embedded in the html response. No need to request json-ld specifically

**Comment by ksonda** [comment]
I tested using this config https://github.com/ksonda/global-river-runner/blob/main/deploy/cloud/latest/pygeoapi.config.yml

(server mimetype set to text/html) and google does indeed retrieve the json response by default still.

**Comment by pvgenuchten** [comment]
see #902
