### ISSUE TITLE
Clip data using a polygon

### ISSUE THREAD

**Issue by ThibautAr** [geopython/pygeoapi#879]
Hello all,

Is it possible to write a query for feature or Coverage collection that clip data inside a polygon?

Rigth now, this is doable only with a rectangular bounding box and I would like to use instead a geometryWKT.

**Comment by ksonda** [comment]
This would need to be implemented via cql filter probably. https://github.com/geopython/pygeoapi/blob/master/docs/source/cql.rst 

@webb-ben and I can add this to our road map, if adding more than the basic CQL filters implemented for ES provider is ok. What do you think @tomkralidis ? If we took this on, it would probably be for geopackage and postgis providers to begin with

**Comment by tomkralidis** [comment]
Makes sense. I would recommend [pygeofilter](https://github.com/geopython/pygeofilter/) as the CQL handler here, which has bindings for SQL.

**Comment by ThibautAr** [comment]
According to the documentation (see https://pygeoapi-cql-filters.readthedocs.io/en/latest/cql-filter.html#steps-to-generate-and-execute-cql-endpoints), the following query https://demo.pygeoapi.io/master/collections/lakes/items?f=json&filter-lang=cql-text& filter=WITHIN(geometry, POLYGON((-80.0 -80.0,-80.0 50,80.0 50,-80.0 -80.0))) should return some results. However, I only got an error {"code": "InvalidParameterValue", "description": "unknown query parameter: filter-lang"}.

**Comment by ksonda** [comment]
That documentation refers to this fork I believe which never merged into the main pygeoapi branch. https://github.com/FarheenB/pygeoapi
