### ISSUE TITLE
Some coverage endpoints report an error when running under the starlette framework

### ISSUE THREAD

**Issue by metmikel** [geopython/pygeoapi#882]
**Description**
Some of the coverage endpoints return an error when pygeoapi is served using the starlette framework.  For example, requesting coverage data results in the error message:
`TypeError: collection_coverage() missing 1 required positional argument: 'collection_id'`
Similar errors exist for the collection_coverage_domainset and collection_coverage_rangetype endpoints as well.

**Steps to Reproduce**
Launch pygeoapi using the starlette application version.  For example:
`gunicorn pygeoapi.starlette_app:app -w 4 -k uvicorn.workers.UvicornWorker`

**Expected behavior**
A coverage request (or coverage domainset or rangetype request) should succeed and return the data requested.

**Environment**
 - OS: Amazon Linux 2
 - Python version: 3.8
 - pygeoapi version: 0.12.0

**Comment by metmikel** [comment]
Addressed in https://github.com/geopython/pygeoapi/pull/883

**Comment by francbartoli** [comment]
@metmikel merged into master!

**Comment by why-not-try-calmer** [comment]
I seem to run into the same issue; using the same running method as OP, doing

    curl -X POST "http://localhost:5000/processes/hello-world/execution" -H "Content-Type: application/json" -d "{\"mode\": \"async\", \"inputs\":{\"name\": \"hi there2\"}}"

yields

    Internal Server Error (response)
    TypeError: execute_process_jobs() missing 1 required positional argument: 'process_id' (sdout)
