### ISSUE TITLE
Support the new OGC encoding format FG-JSON

### ISSUE THREAD

**Issue by francbartoli** [geopython/pygeoapi#884]
**Is your feature request related to a problem? Please describe.**
It would be great to add the support to this new encoding format https://github.com/opengeospatial/ogc-feat-geo-json that overcomes the GeoJSON limitation to have only the standard CRS WGS84

**Describe the solution you'd like**
Add a utility that translates the output from `geojson` to `feat-geo-json`

**Describe alternatives you've considered**
Remaining with just GeoJSON

**Additional context**
NA

**Comment by francbartoli** [comment]
During the code sprint, I heard about this instance `https://fgjson.skymantics.com/`.  @skyNacho do you know if this extension is publicly available and/or if they want to contribute back?

**Comment by skyNacho** [comment]
Sure! I implemented the extension for the TB17 and I was waiting to get to a stable version (0.2) before updating it and contributing to the community, much in the same way as I am doing with the routing plugin. It should not be long before the new draft spec is ready.

**Comment by doublebyte1** [comment]
@skyNacho @francbartoli what is the status of this plugin? I recogn this could be important enough to be in the core?

**Comment by francbartoli** [comment]
Sorry @doublebyte1, I didn't have any update after then. I hope @skyNacho can share something for a community module
