### ISSUE TITLE
skipGeometry not implemented for geopackage provider

### ISSUE THREAD

**Issue by ksonda** [geopython/pygeoapi#886]
skipGeometry query parameter is not implemented for geopackage provider

This is a port from https://github.com/internetofwater/geoconnex.us/issues/156 

Compare:

https://demo.pygeoapi.io/master/collections/ogr_gpkg_poi/items?f=json&skipGeometry=true 
https://demo.pygeoapi.io/master/collections/lakes/items?f=json&skipGeometry=true

**Comment by tomkralidis** [comment]
Addressed in #887

**Comment by tomkralidis** [comment]
Now fixed/merged in #887.  @webb-ben can you validate?

**Comment by ksonda** [comment]
It seems to work correctly on /items?f=json&skipGeometry=true

although it does not work on /items/id?f=json&skipGeometry=true

This is fine for our purposes but not sure if skipGeometry is supposed to also work on /items/id endpoint

**Comment by tomkralidis** [comment]
I would leave to `/items` for now, given at the `.../{itemId}` level we are at much smaller payload size (always a single feature).

**Comment by tomkralidis** [comment]
P.S. to add, note that pygeoapi's `skipGeometry` support is at the `.../items` level.  Does this work for you @ksonda ?

**Comment by ksonda** [comment]
Yeah that's fine. Don't need it at /item/id level.
