### ISSUE TITLE
Hateoas issue serving collections

### ISSUE THREAD

**Issue by gnosys-ccoupal** [geopython/pygeoapi#896]
When serving collections, the provider does integrate the links from the .json file, but the stac_extensions, license, and extent keys are not included in the response. The result is the collection cannot be consumed by pystac-client. 

**Steps to Reproduce**
serve a stac collection using hateoas

**Expected behavior**
The resulted json would include the stac_extensions, license, and extent keys

**Environment**
 - OS:
 - Python version: 
 - pygeoapi version: latest

work around, in provider/hateoas.py, insert the following lines at line 135 as a hack to resolve

```
        if resource_type == 'Collection':
                content['extent'] = jsondata['extent']
                content['license'] = jsondata['license']
                content['stac_extensions'] = jsondata['stac_extensions']
```

**Comment by allixender** [comment]
also relevant maybe: https://github.com/geopython/pygeoapi/issues/1434

**Comment by allixender** [comment]
https://github.com/geopython/pygeoapi/issues/221 and https://github.com/geopython/pygeoapi/issues/1434
