### ISSUE TITLE
return html if no accept encoding is requested

### ISSUE THREAD

**Issue by pvgenuchten** [geopython/pygeoapi#901]
Somehow i missed the aspect that google these days does not fetch any structured content from demo.pygeoapi.io since mid 2020, it seems related to the fact that google crawler does not send an accept header when fetching content in combination with pygeoapi returning json, if no accept header is send.

The yandex structured data validator has the same 'challenge'.

Suggestion would be to return html when no accept-header or ?f={encoding} is provided.

**Comment by ksonda** [comment]
I agree

**Comment by pvgenuchten** [comment]
a potential workaround if people are not enthousiastic on this:
- add a sitemap.xml which references each of the enpoints with explicit ?f=html (or better xxx.html)
- the html would indicate xxx.html as canonical url
