### ISSUE TITLE
pygeoapi as a codelist registry

### ISSUE THREAD

**Issue by pvgenuchten** [geopython/pygeoapi#906]
In the European Soil Community we're in the process of setting up a tool chain of tools to support our data workflows. For one aspect we're still looking for a good technical option. It is the publication of Codelists. In many cases common codelists are imported and extended to support a local use case, these extended codelists would need to be published in a simple method.

There are common tools for this task, such as: 
- Skosmos (requires a sparql endpoint)
- Re3gistry (requires SOLR) 
- GeoNetwork

Each of them a bit too hard to setup and manage

Some codelists actually have a geometry (consider a list of countries/regions/nature area's, etc), many do not. Still it would be interesting to publish every concept in a list as a feature in an OGC-API Features endpoint (do features need to have a geometry?).

I guess I would need to define a postgres/sqlite structure for codelists, to be consumed by one of the pygeoapi data providers.

A `nice to have` would be to have the json-ld be encoded using the SKOS ontology, which i think is possible with the current ld tooling.

An aspect of codelists is that they are usually nested (World-Africa-Nigeria-Lagos-Makoko). I wonder if pygeoapi has a mechanism for this. Concepts typically have sameAs, narrower, wider links to other concepts, I guess this can be managed in the link section.

**Comment by ksonda** [comment]
We have an open PR to allow for arbitrary JSON-LD templating that may be useful for this use case as well. https://github.com/geopython/pygeoapi/pull/868

**Comment by pvgenuchten** [comment]
@ksonda, i tried your pr branch, but it was not clear how i could populate those json-ld templates, do you have some examples?

**Comment by ksonda** [comment]
You can see an example json-ld document here: https://reference.geoconnex.us/collections/gages/items/1185577?f=jsonld 

This is generated by this template https://github.com/internetofwater/geoconnex.us/blob/master/pygeoapi/pygeoapi-skin-dashboard/templates/jsonld/ref-gages.jsonld 

Which is placed in a folder called `jsonld` within the `templates` directory (as set in the server config yaml)

Then, the template can be set at the collection level:
![image](https://user-images.githubusercontent.com/44071350/170031865-4c2add0f-8b2b-406f-b5c2-99921b847c52.png)

**Comment by pvgenuchten** [comment]
I'm going to give it a try, we should add such an example to docs
