### ISSUE TITLE
Openapi function expects utf-8 encoding but the generate command outputs utf-16 on Windows

### ISSUE THREAD

**Issue by msouff** [geopython/pygeoapi#919]
**Description**
The openapi generate command example given in the documentation uses `click.echo` and redirection to save the output to a file:

`pygeoapi openapi generate /path/to/my-pygeoapi-config.yml > /path/to/my-pygeoapi-openapi.yml`

The openapi function expects utf-8:

```
@BLUEPRINT.route('/openapi')
def openapi():
    """
    OpenAPI endpoint

    :returns: HTTP response
    """
    with open(os.environ.get('PYGEOAPI_OPENAPI'), encoding='utf8') as ff:
        ...
```

The problem is that `click.echo` will output utf-16 if it detects a Windows console:

> If no Windows console is present then the text output stream is returned as such and the encoding for that stream is set to utf-8 like on all platforms. However if a console is connected the stream will instead be emulated and use the cmd.exe unicode APIs to output text information. **In this case the stream will also use utf-16-le as internal encoding**.

From: https://click.palletsprojects.com/en/7.x/wincmd/#unicode-output-and-input

**Steps to Reproduce**
Run the openapi generate from powershell on Windows.

**Expected behavior**
Instead of relying on redirection, it'd be nice to add an output option to the generate command that creates the file ensuring that the encoding is utf-8 (If the user passes the --output option with a path then you create the file instead of using `click.echo` to spit the output). This can easily be done with click by adding like 3 lines of code. I could submit a PR if you are interested.

**Environment**
 - OS: Windows
 - Python version: 3.10.4
 - pygeoapi version: latest

**Comment by tomkralidis** [comment]
@msouff fixed via #925.  Let us know if this fixes the issue.
