### ISSUE TITLE
 update contributor and license agreements

### ISSUE THREAD

**Issue by tomkralidis** [geopython/pygeoapi#928]
cc @msmitherdc 

## Overview

As part of OSGeo incubation, our Graduation Checklist (https://github.com/geopython/pygeoapi/wiki/ProjectGraduationChecklist) requires the project to firm up contribution agreements.

This applies to the pygeoapi software code files.

This is outlined in https://github.com/geopython/pygeoapi/blob/master/CONTRIBUTING.md#contributions-and-licensing.  Template for completing the agreement (per https://github.com/geopython/pygeoapi/blob/master/CONTRIBUTING.md#contributions-and-licensing).

## Template

`Hi all, I'd like to contribute <feature X|bugfix Y|docs|code|something else> to pygeoapi. I confirm that my contributions to pygeoapi will be compatible with the pygeoapi license guidelines at the time of contribution.`

Committers and contributors can either agree either via the pygeoapi mailing list, or here in this ticket.

All committers and contributors are listed at https://github.com/geopython/pygeoapi/graphs/contributors

### Committers
- [x] @tomkralidis
- [x] @kalxas
- [x] @francbartoli 
- [x] @justb4 
- [ ] @jorgejesus 
- [x] @gpetrochenkov-usgs 
- [x] @GeoSander (GeoCat BV)
- [x] @pvgenuchten
- [ ] @alpha-beta-soup 

### Contributors
- [x] @webb-ben 
- [x] @Youngestdev 
- [x] @perrygeo 
- [x] @ychoquet 
- [ ] @timtuun  
- [x] @totycro 
- [x] @doublebyte1 
- [ ] @ayan-usgs 
- [x] @alexandreleroux 
- [x] @rouault 
- [x] @alex-mathew 
- [x] @mbucknell 
- [x] @jmckenna 
- [x] @aripollak 
- [x] @geekdenz 
- [x] @kngai 
- [x] @jemrobinson 
- [x] @bitner 
- [x] @bradh 
- [x] @acapparelli 
- [x] @KoalaGeo 
- [x] @metmikel 
- [x] @constantinius 
- [ ] @giphahne 
- [x] @isedwards 
- [x] @ShaneMill1 
- [ ] @fzeiser 
- [x] @geographika 
- [ ] @normanb 
- [ ] @saltaverde 
- [x] @mvaaltola 
- [x] @astroidex 
- [x] @ynte 
- [x] @jodygarnett (GeoCat BV)
- [x] @MartinPontius (52°North Spatial Information Research GmbH)
- [x] @sbrunato

**Comment by tomkralidis** [comment]
Hi all, I'd like to contribute code to pygeoapi. I confirm that my contributions to pygeoapi will be compatible with the pygeoapi license guidelines at the time of contribution.

Tom Kralidis

**Comment by bradh** [comment]
Hi all, I'd like to contribute docs and code to pygeoapi. I confirm that my contributions to pygeoapi will be compatible with the pygeoapi license guidelines at the time of contribution.

Brad Hards

**Comment by metmikel** [comment]
Hi all, I'd like to contribute docs & code to pygeoapi. I confirm that my contributions to pygeoapi will be compatible with the pygeoapi license guidelines at the time of contribution.
Mike Lane

**Comment by pvgenuchten** [comment]
Hi all, I'd like to contribute docs & code to pygeoapi. I confirm that my contributions to pygeoapi will be compatible with the pygeoapi license guidelines at the time of contribution.

**Comment by jemrobinson** [comment]
Hi all, I'd like to contribute docs and code to pygeoapi. I confirm that my contributions to pygeoapi will be compatible with the pygeoapi license guidelines at the time of contribution.

James Robinson

**Comment by francbartoli** [comment]
Hi all, I'd like to contribute docs and code to pygeoapi. I confirm that my contributions to pygeoapi will be compatible with the pygeoapi license guidelines at the time of contribution.
Francesco Bartoli

**Comment by MartinPontius** [comment]
Hi all, I'd like to contribute docs and code to pygeoapi. I confirm that my contributions to pygeoapi will be compatible with the pygeoapi license guidelines at the time of contribution.

Martin Pontius

**Comment by kalxas** [comment]
Hi all, I'd like to contribute code to pygeoapi. I confirm that my contributions to pygeoapi will be compatible with the pygeoapi license guidelines at the time of contribution.

Angelos Tzotsos

**Comment by bitner** [comment]
Hi all, I'd like to contribute docs and code to pygeoapi. I confirm that my
contributions to pygeoapi will be compatible with the pygeoapi license
guidelines at the time of contribution.

David Bitner

**Comment by mbucknell** [comment]
Hi all, I'd like to contribute code to pygeoapi. I confirm that my contributions to pygeoapi will be compatible with the pygeoapi license guidelines at the time of contribution.

Mary Bucknell

**Comment by KoalaGeo** [comment]
Hi all, I'd like to contribute code to pygeoapi. I confirm that my contributions to pygeoapi will be compatible with the pygeoapi license guidelines at the time of contribution.

Edward Lewis

**Comment by geographika** [comment]
Hi all, I'd like to contribute docs and code to pygeoapi. I confirm that my contributions to pygeoapi will be compatible with the pygeoapi license guidelines at the time of contribution.

Seth Girvin

**Comment by isedwards** [comment]
Hi all, I'd like to contribute docs and code to pygeoapi. I confirm that my contributions to pygeoapi will be compatible with the pygeoapi license guidelines at the time of contribution

Ian Edwards

**Comment by webb-ben** [comment]
Hi all, I'd like to contribute docs and code to pygeoapi. I confirm that my contributions to pygeoapi will be compatible with the pygeoapi license guidelines at the time of contribution.

Ben Webb

**Comment by acapparelli** [comment]
Hi all, I'd like to contribute code to pygeoapi. I confirm that my contributions to pygeoapi will be compatible with the pygeoapi license guidelines at the time of contribution.

Adam Capparelli

**Comment by kngai** [comment]
Hi all, I'd like to contribute docs and code to pygeoapi. I confirm that my contributions to pygeoapi will be compatible with the pygeoapi license guidelines at the time of contribution.

Kevin Ngai

**Comment by ychoquet** [comment]
Hi all, I'd like to contribute docs and code to pygeoapi. I confirm that my contributions to pygeoapi will be compatible with the pygeoapi license guidelines at the time of contribution.

Yves Choquette

**Comment by doublebyte1** [comment]
Hi all, I'd like to contribute docs and code to pygeoapi. I confirm that my contributions to pygeoapi will be compatible with the pygeoapi license guidelines at the time of contribution.

Joana Simoes

**Comment by geekdenz** [comment]
Hi all, I'd like to contribute code to pygeoapi. I confirm that my
contributions to pygeoapi will be compatible with the pygeoapi license
guidelines at the time of contribution.

Tim-Hinnerk Heuer

**Comment by constantinius** [comment]
Hi all, I'd like to contribute code to pygeoapi. I confirm that my contributions to pygeoapi will be compatible with the pygeoapi license guidelines at the time of contribution.

Fabian Schindler

**Comment by aripollak** [comment]
Hi all, I'd like to contribute docs and code to pygeoapi. I confirm that my contributions to pygeoapi will be compatible with the pygeoapi license guidelines at the time of contribution.

Ari Pollak

**Comment by perrygeo** [comment]
Hi all, I'd like to contribute docs and code to pygeoapi. I confirm that my contributions to pygeoapi will be compatible with the pygeoapi license guidelines at the time of contribution.

**Comment by totycro** [comment]
Hi all, I'd like to contribute code to pygeoapi. I confirm that my contributions to pygeoapi will be compatible with the pygeoapi license guidelines at the time of contribution.

Bernhard Mallinger

**Comment by mvaaltola** [comment]
Hi all, I'd like to contribute code to pygeoapi. I confirm that my contributions to pygeoapi will be compatible with the pygeoapi license guidelines at the time of contribution.

Mikael Vaaltola

**Comment by justb4** [comment]
Hi all, I'd like to contribute code to pygeoapi. I confirm that my contributions to pygeoapi will be compatible with the pygeoapi license guidelines at the time of contribution.

Just van den Broecke

**Comment by jodygarnett** [comment]
I confirm that my contributions to pygeoapi will be compatible with the pygeoapi license guidelines at the time of contribution.

**Comment by astroidex** [comment]
Hi all, I'd like to contribute docs code translations to pygeoapi. I confirm that my contributions to pygeoapi will be compatible with the pygeoapi license guidelines at the time of contribution.

Astrid Emde

**Comment by ShaneMill1** [comment]
Hi all, I'd like to contribute code to pygeoapi. I confirm that my contributions to pygeoapi will be compatible with the pygeoapi license guidelines at the time of contribution.
Shane Mill

**Comment by alex-mathew** [comment]
Hi all, I'd like to contribute code to pygeoapi. I confirm that my contributions to pygeoapi will be compatible with the pygeoapi license guidelines at the time of contribution.

Alex Mathew

**Comment by ynte** [comment]
Hi all, I'd like to contribute code to pygeoapi. I confirm that my contributions to pygeoapi will be compatible with the pygeoapi license guidelines at the time of contribution.

Ynte de Wolff

**Comment by alexandreleroux** [comment]
Hi all, I'd like to contribute code to pygeoapi. I confirm that my contributions to pygeoapi will be compatible with the pygeoapi license guidelines at the time of contribution.

Alexandre Leroux

**Comment by doublebyte1** [comment]
Hi all, I'd like to contribute code to pygeoapi. I confirm that my contributions to pygeoapi will be compatible with the pygeoapi license guidelines at the time of contribution.

                 Joana Simoes
