### ISSUE TITLE
ES docker-composition is not starting correctly

### ISSUE THREAD

**Issue by doublebyte1** [geopython/pygeoapi#931]
**Description**
The example [ES docker-composition](https://github.com/geopython/pygeoapi/blob/master/docker/examples/elastic/docker-compose.yml) starts with errors.

**Steps to Reproduce**
Start the [docker composition](https://github.com/geopython/pygeoapi/blob/master/docker/examples/elastic/docker-compose.yml) with `docker-compose up`

**Expected behavior**
All containers should start and pygeoapi should be available at http://localhost:5000

**Screenshots/Tracebacks**
the pygeoapi entry script shows the following error:

> pygeoapi_es       | /wait-for-elasticsearch.sh: 40: curl: not found

As it is not able to run curl, it never detects if ES is up and therefore hangs on waiting forever/ never starts the pygeoapi container.

![wait-for-elastic](https://user-images.githubusercontent.com/1038897/177588509-c75cfdbb-10b4-4a30-8be3-9fb0d4db6261.png)

**Environment**
 - OS: Ubuntu 20.04.4 LTS
 - Python version: 3.8.10
 - pygeoapi version:  0.11.0

**Comment by doublebyte1** [comment]
Hopefully addressed in this PR: https://github.com/geopython/pygeoapi/pull/932

**Comment by tomkralidis** [comment]
Merged - thank you!
