### ISSUE TITLE
Support up-to-date version of CQL

### ISSUE THREAD

**Issue by francbartoli** [geopython/pygeoapi#937]
**Is your feature request related to a problem? Please describe.**
It was reported that the Elasticsearch provider support CQL with an older version of the specification

**Describe the solution you'd like**
Support CQL2 via [pygeofilter](https://github.com/geopython/pygeoafilter)

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by KoalaGeo** [comment]
In progress for PostGres provider - https://github.com/geopython/pygeoapi/pull/964
