### ISSUE TITLE
add the leaflet markercluster for point features

### ISSUE THREAD

**Issue by pvgenuchten** [geopython/pygeoapi#951]
the leaflet marker-cluster plugin improves visualization of large point datasets

![image](https://user-images.githubusercontent.com/299829/182874236-532f45a7-95d0-4ee1-9d57-b0296caa9b0a.png)

![image](https://user-images.githubusercontent.com/299829/182874359-4b89ace0-9c53-4627-a08a-dd424b140b85.png)

**Comment by justb4** [comment]
Yes, good approach. Using `resulttype=hits`. Contemplating this for generic OAPIF clients for Leaflet and OL. But to our surprise `resulttype=hits` is no longer in the core OGC standard, so now a proprietary pygeoapi facility. See also Gitter WFS-FES for discussion. May return as Extension...

**Comment by justb4** [comment]
Was thinking of a minzoom-maxzoom or maxhits-minhits where clustering is active. Not just for Point features.

**Comment by tomkralidis** [comment]
Added via #1025
