### ISSUE TITLE
Build/push pygeoapi Docker Images within a GH Workflow

### ISSUE THREAD

**Issue by justb4** [geopython/pygeoapi#973]
**Is your feature request related to a problem? Please describe.**
DockerHub has stopped automated builds (though "geopython" org had an Open Source waiver).

**Describe the solution you'd like**
It is better to build/push Docker Images within a GH Workflow. One can then first build, run unit tests, and then push. Often this is also quicker.

**Describe alternatives you've considered**
Try to get the Open Source waiver back, but I prefer the  GH Workflow solution.

**Additional context**
See for example GeoHealthCheck: https://github.com/geopython/GeoHealthCheck/blob/master/.github/workflows/docker.yml
We can use it as a starter.

**Comment by KoalaGeo** [comment]
I started - https://github.com/geopython/pygeoapi/pull/801

**Comment by justb4** [comment]
Yes, and completely forgot, sorry. We have a head start thus.

**Comment by tomkralidis** [comment]
Implemented/fixed.  CI workflow publishes to Docker and GHCR.
