### ISSUE TITLE
Error while publishing Hierarchical collections

### ISSUE THREAD

**Issue by maxcollombin** [geopython/pygeoapi#978]
**Description**
I tried to follow [this procedure](https://docs.pygeoapi.io/en/latest/configuration.html#hierarchical-collections) to publish hierarchical collections but I get the following error when I try to access the following url via my browser: http://localhost:5000/collections/naturalearth/lakes?f=html

```
Not Found

The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
```
and at the log level:

`[2022-09-02T15:09:19Z] {/pygeoapi/pygeoapi/api.py:3202} ERROR - Collection not found`

**Steps to Reproduce**
1. `svn export https://github.com/geopython/pygeoapi/trunk/docker/examples/simple pygeoapi-simple`
2. `cd pygeoapi-simple`
3. update the line 87 in `my.config.yml` to `naturalearth/lakes` instead of `lakes`

**Expected behavior**
I expected to see the lakes collection.

**Screenshots/Tracebacks**

![image](https://user-images.githubusercontent.com/93529214/188181746-a68e266b-bed5-4b01-9991-a53776bcbaff.png)

**Environment**
 - OS: Windows 10
 - Python version: 3.9.13
 - pygeoapi version: 0.12.0

**Additional context**
- None

**Comment by tomkralidis** [comment]
Cannot reproduce/worksforme.  What is the result of `http://localhost:5000/collections`?

**Comment by maxcollombin** [comment]
Hi @tomkralidis ,

Thanks for your feedback!

The result is the following:

![image](https://user-images.githubusercontent.com/93529214/188580446-95371064-f32f-40a9-93e6-e19fce17f9d3.png)

**Comment by tomkralidis** [comment]
Can you turn on debugging and provide logging output?

**Comment by maxcollombin** [comment]
Sure,

[Here](https://gist.github.com/maxcollombin/1d8d496f46b447374c7b46e1d19020cf) it is.

**Comment by tomkralidis** [comment]
Thanks. You need to set `logging.level` to `DEBUG`, restart the server, run the request http://localhost:5000/collections/naturalearth/lakes?f=html, and provide the logging output.

**Comment by maxcollombin** [comment]
I am however not able to get the logs correctly
I've tried to update the my.config.yml as follow:

```
logging:
    level: DEBUG
    logfile: pygeoapi.log
```
but a folder is created instead without any logs.

I used the command 'docker-compose logs -f -t >> pygeoapi.log' instead which fills in the information given in the previous message.

Sorry for any misunderstandings.😑

**Comment by tomkralidis** [comment]
Do not set / comment out the logfile directive, then logs will be sent to the console.

**Comment by maxcollombin** [comment]
Ok, 

I've updated the associated [gist](https://gist.github.com/maxcollombin/1d8d496f46b447374c7b46e1d19020cf).

**Comment by tomkralidis** [comment]
@maxcollombin if you are using pygeoapi via Docker, please see #989, as I think this may be related.

**Comment by maxcollombin** [comment]
Indeed. The issue can then be closed. Thanks for your feedback!
