### ISSUE TITLE
Mixed Content Warnings 

### ISSUE THREAD

**Issue by KoalaGeo** [geopython/pygeoapi#980]
**Description**
Mixed Content Warnings in the console 

```
Mixed Content: The page at 'https://ogcapi.bgs.ac.uk/openapi?f=html#/recentearthquakes/describeRecentearthquakesCollection' was loaded over HTTPS, but requested an insecure resource 'http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/ogcapi-features-1.yaml'. This request has been blocked; the content must be served over HTTPS.
```
```
index.js:952
```

**Steps to Reproduce**
Go to https://ogcapi.bgs.ac.uk/openapi?f=html#/recentearthquakes/describeRecentearthquakesCollection open devtools

Click one of the "GET" buttons

**Expected behavior**
No error

**Screenshots/Tracebacks**
![image](https://user-images.githubusercontent.com/33657876/188675060-f84442a1-72db-4489-955a-25d3498f4af5.png)

**Environment**
 - OS: Official Docker Image
 - Python version:
 - pygeoapi version: 0.12

**Additional context**

**Comment by KoalaGeo** [comment]
Also impacts redoc - https://ogcapi.bgs.ac.uk/openapi?f=html&ui=redoc 

![image](https://user-images.githubusercontent.com/33657876/188675353-78521f35-b498-4c83-a545-5559fccedbba.png)

**Comment by KoalaGeo** [comment]
https://github.com/geopython/pygeoapi/blob/master/pygeoapi/api.py#L101-L143 needs ammending to 

```
CONFORMANCE = {
    'common': [
        '//www.opengis.net/spec/ogcapi-common-1/1.0/conf/core',
        '//www.opengis.net/spec/ogcapi-common-2/1.0/conf/collections'
    ],
    'feature': [
        '//www.opengis.net/spec/ogcapi-features-1/1.0/conf/core',
        '//www.opengis.net/spec/ogcapi-features-1/1.0/conf/oas30',
        '//www.opengis.net/spec/ogcapi-features-1/1.0/conf/html',
        '//www.opengis.net/spec/ogcapi-features-1/1.0/conf/geojson'
    ],
    'coverage': [
        '//www.opengis.net/spec/ogcapi-coverages-1/1.0/conf/core',
        '//www.opengis.net/spec/ogcapi-coverages-1/1.0/conf/oas30',
        '//www.opengis.net/spec/ogcapi-coverages-1/1.0/conf/html',
        '//www.opengis.net/spec/ogcapi-coverages-1/1.0/conf/geodata-coverage',  # noqa
        '//www.opengis.net/spec/ogcapi-coverages-1/1.0/conf/coverage-subset',  # noqa
        '//www.opengis.net/spec/ogcapi-coverages-1/1.0/conf/coverage-rangesubset',  # noqa
        '//www.opengis.net/spec/ogcapi-coverages-1/1.0/conf/coverage-bbox',  # noqa
        '//www.opengis.net/spec/ogcapi-coverages-1/1.0/conf/coverage-datetime'  # noqa
    ],
    'tile': [
        '//www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/core'
    ],
    'record': [
        '//www.opengis.net/spec/ogcapi-records-1/1.0/conf/core',
        '//www.opengis.net/spec/ogcapi-records-1/1.0/conf/sorting',
        '//www.opengis.net/spec/ogcapi-records-1/1.0/conf/opensearch',
        '//www.opengis.net/spec/ogcapi-records-1/1.0/conf/json',
        '//www.opengis.net/spec/ogcapi-records-1/1.0/conf/html'
    ],
    'process': [
        '//www.opengis.net/spec/ogcapi-processes-1/1.0/conf/ogc-process-description', # noqa
        '//www.opengis.net/spec/ogcapi-processes-1/1.0/conf/core',
        '//www.opengis.net/spec/ogcapi-processes-1/1.0/conf/json',
        '//www.opengis.net/spec/ogcapi-processes-1/1.0/conf/oas30'
    ],
    'edr': [
        '//www.opengis.net/spec/ogcapi-edr-1/1.0/conf/core'
    ]
}
```

**Comment by KoalaGeo** [comment]
And here https://github.com/geopython/pygeoapi/blob/master/pygeoapi/flask_app.py#L73

**Comment by francbartoli** [comment]
@KoalaGeo I think some of the OGC links are not available under the secured protocol. For example:

- [https://www.opengis.net/spec/ogcapi-common-1/1.0/conf/core](https://www.opengis.net/spec/ogcapi-common-1/1.0/conf/core)
- [https://www.opengis.net/spec/ogcapi-common-1/1.0/conf/collections](https://www.opengis.net/spec/ogcapi-common-1/1.0/conf/collections)

**Comment by tomkralidis** [comment]
@KoalaGeo can you try against master?  OGC API schema references (which are used when generating the OpenAPI document) have all been [updated to HTTPS](https://github.com/geopython/pygeoapi/blob/master/pygeoapi/openapi.py#L48-L57).

**Comment by francbartoli** [comment]
Sorry folks, please ignore my previous message. I do believe @tomkralidis' comment would close the issue imho

**Comment by KoalaGeo** [comment]
@tomkralidis using latest still gettign the issue - see https://ogcapi-staging.bgs.ac.uk/openapi?f=html#/server/getCollections

```
Mixed Content: The page at 'https://ogcapi-staging.bgs.ac.uk/openapi?f=html#/server/getCollections' was loaded over HTTPS, but requested an insecure resource 'http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/ogcapi-features-1.yaml'. This request has been blocked; the content must be served over HTTPS.
(anonymous) @ index.js:952
```

**Comment by francbartoli** [comment]
@KoalaGeo can you share your pygeoapi yml config file?

**Comment by KoalaGeo** [comment]
Sure - https://gist.github.com/KoalaGeo/56795751d660689b45234b406ddf174d

**Comment by tomkralidis** [comment]
@KoalaGeo can you share the OpenAPI document? The links should be HTTPS if you are using master branch.

**Comment by KoalaGeo** [comment]
Looks to all be http - https://ogcapi-staging.bgs.ac.uk/openapi?f=json

**Comment by tomkralidis** [comment]
@KoalaGeo I still cannot reproduce.  Also works as expected in our public demo (https://demo.pygeoapi.io/master/openapi?f=json).

**Comment by KoalaGeo** [comment]
I'll have a go not using  url: https://${HOSTNAME}/ and actually hardcoding the url as thats the standout difference from the doc examples

**Comment by KoalaGeo** [comment]
I've hardcoded the hostname & tried disabling cors still having the same error 
![image](https://user-images.githubusercontent.com/33657876/191533838-d7127722-4d30-4f4b-900e-45d0d0d3bf64.png)

http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/ogcapi-features-1.yaml

There does exist a https version see https://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/ogcapi-features-1.yaml

I am getting the same error on the demo service - https://demo.pygeoapi.io/master/openapi?f=html&ui=redoc
![image](https://user-images.githubusercontent.com/33657876/191536482-f3ea0500-95ce-4e00-94c3-2c4f5eb9d3a4.png)

We've now fixed the using our F5, setting up a streaming site policy to rewrite links from http to https but the underlying issue remains.

**Comment by KoalaGeo** [comment]
From OGC
"https://schemas.opengis.net/ and http://schemas.opengis.net/ serve the same content.

http://schemas.opengis.net/ does not use HSTS as that might break existing clients by forcing HTTPS.  Instead the schema site uses HTTP Content-Security-Policy (CSP) upgrade-insecure-requests.  This HTTP header directive instructs the user agents (client) to treat all of the site's insecure URLs as though they have been replaced with secure URLs (served over HTTPS).  We do not force clients to HTTPS but allow each to match their own requirements."

**Comment by tomkralidis** [comment]
Still cannot reproduce.  The demo is working off an old version pygeoapi master.  I think our Docker images need updating.  Opening a new issue on this one.

Having said this, if you test with a local (non-Docker [!]) install, you will see that the URLs to OGC schemas are all HTTPS.

**Comment by tomkralidis** [comment]
Ref #989 (outdated Docker images)

**Comment by tomkralidis** [comment]
@KoalaGeo can you validate again now that our Docker and GHCR images are current?

**Comment by KoalaGeo** [comment]
All working at my end now, cheers!
