### ISSUE TITLE
Docker images outdated

### ISSUE THREAD

**Issue by tomkralidis** [geopython/pygeoapi#989]
**Description**
Docker images for master builds appear to be out of date.

**Steps to Reproduce**
Steps to reproduce the behavior: `docker pull geopython/pygeoapi:latest`

**Expected behavior**
Docker images for the master build should represent same.

**Screenshots/Tracebacks**
From Docker Hub
![Screen Shot 2022-09-25 at 16 23 10](https://user-images.githubusercontent.com/910430/192163647-804c0703-8b46-4a4f-80a2-1c464dd07f37.png)

**Environment**
 - OS: Docker based
 - Python version: NA
 - pygeoapi version: master

**Additional context**
cc @KoalaGeo

**Comment by justb4** [comment]
So at least now the images are not outdated. So we may close this.
