### ISSUE TITLE
Version 0.12.0 (tagged as such here and available from PyPI) features bugs that have been squashed for a long time

### ISSUE THREAD

**Issue by why-not-try-calmer** [geopython/pygeoapi#991]
One such bug is the missing `process_id=None` default to the second argument of this [function](https://github.com/geopython/pygeoapi/blob/faa00e7c9232a773d4d701a90855ae06c4068eae/pygeoapi/starlette_app.py#L353), making the application not very usable in production. Code from `master` (including the official Docker image) is up-to-date, though, but lacks the simplicity and flexibility afforded by deploying from the PyPI package.

**Comment by tomkralidis** [comment]
Please post questions to the pygeoapi mailing list. pygeoapi GitHub issues are for **software bugs/enhancements** and related tasks.
